### ISSUE TITLE
Claims too big for header

### ISSUE THREAD

**Issue by ferronsw** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#103]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [x] regression (a behavior that used to work and stopped in a new release)
```

## The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. [ ] Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users 
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../5-WebApp-AuthZ/5-1-Roles)
   1. [x] by Groups: [5-WebApp-AuthZ/5-2-Groups](../5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Minimal steps to reproduce
Add security groups claim to an app registration

`"groupMembershipClaims": "SecurityGroup"`

Login with a user with many groups (in my case 120 including nested groups)
(Cookie 6 chunks #toomany)

### Any log messages given by the failure
Connection is not secure after logging in and being redirect to the site.

### Expected/desired behavior
When the groups claims are to large for the header they should be removed.
I don't know if this should be done in AzureAD or in the Microsoft.Idenitity.Client or Microsoft.Identity.Web.

In previous situations there was a claim with the value `getMemberObjects` when the user had too many groups. In this situation you should get the groups trough the Graph API.

### OS and Version?
Windows 10 & Azure Web App

### Versions
>

**Comment by jmprieur** [comment]
@ferronsw ; I'm assuming you've read the README in [5-WebApp-AuthZ/5-2-Groups](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/5-WebApp-AuthZ/5-2-Groups)

Do I understand that the overflow does not work?

**Comment by ferronsw** [comment]
@jmprieur I've read it now, but the so called overage/overflow isn't working for me.
The document says it's only kicking in at `(**150 for SAML tokens, 200 for JWT tokens**)`.
My user has about 120 groups, but the cookie size was 6 chunks and to large to process.

**Comment by kalyankrishna1** [comment]
@ferronsw , what is the exact error . 200 objectIds are actually within limits of cookies/header and such. Please help us with details on what were you trying and what error you ran into? The claims should travel over Http without any issues.

**Comment by ferronsw** [comment]
@kalyankrishna1 there is no error in the application, because the browser displays "Secure connection failed" after logging in (I'm using https). When I delete some group claim within the Microsoft.Identity.Web.StartupHelper.AddMsal() `OnAuthorizationCodeReceived` I don't get this error anymore. The browser says that the header it tries to submit to the server is 22,0006 KB.

**Comment by kalyankrishna1** [comment]
So you delete the claims from the claimsPrincipal object ? if that's the case then the token traveled from AAD to your browser and was successfully hydrated in the ClaimsPrincipal collection. I think this claimsprincipal, along with other attributes is being written to a header and that breaks the limits.
This is always an issue that developers should be careful about when requesting group claims in the token. There is nothing on Azure AD that maps groups to app really, that will enable AAD to pick and choose groups  to send across. 
I suggest two approaches
1. Do not accept group claims, your cookies are large enough and a groups claims just breaks them. Consider defining Approles if its possible
2. If App roles is too much work then, call MS Graph to obtain user's group memberships after the user has signed in.

**Comment by ferronsw** [comment]
I understand. It would be nice if you could set the overage number on an Azure AD app registration.
That would limit the number of Graph request.
