### ISSUE TITLE
[Request] Account controller scaffold

### ISSUE THREAD

**Issue by pablitofernandez** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#11]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 10

### Versions
>

### Mention any other details that might be useful
> ---------------------------------------------------------------
> So I would like to scaffold the AccountController to be able to check if the logged user through Azure AD exists in my local database and create it if not. I woulk like to integrate my local user database with Azure AD. Thanks!

**Comment by jmprieur** [comment]
@pablitofernandez : what is your scenario? 
Azure AD is about delegating authentication to the cloud … are you concerned about something? is it about performance?
