### ISSUE TITLE
Tutorial Phase - 1.5. WebApp signs-in users with local or social identities (B2C)

### ISSUE THREAD

**Issue by jmprieur** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#112]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

It's about adding a **phase 1.5** to the tutorial to show how to sign-in users with social identities or local identities with Azure AD B2C

### Repro-ing the issue
Go to [1-WebApp-OIDC/1-5-B2C](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-5-B2C)

**Expected behavior**
A sample is available to explain how to sign-in users to the Web App using Azure AD B2C.

**Actual behavior**
The directory is empty

**Possible Solution**

It would be good to:
- clone the [1-WebApp-OIDC/1-1-MyOrg](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-1-MyOrg) sample
- then re-incorporate the B2C specific elements from the following sample https://github.com/Azure-Samples/active-directory-b2c-dotnetcore-webapp. (See below)

Note that that sample is a bit old (ASP.NET Core 2.1), and since then, classes such as Azure AD B2C Options, etc ... are available part of ASP.NET Core. (https://github.com/aspnet/AspNetCore/tree/master/src/Azure/AzureAD/Authentication.AzureADB2C.UI/src)

It might be good to:
- leverage Microsoft.Identity.Web as much as possible (hence the idea of cloning 1-WebApp-OIDC/1-1-MyOrg](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-1-MyOrg)
- In the library, add a `StartupB2Helper.cs` file containing a `StartupB2CHelpers` class similar to `StartupHelpers` providing the method `public static IServiceCollection AddAzureAdB2CAuthentication(this IServiceCollection services, IConfiguration configuration)` which would:

```CSharp
services.AddAuthentication(AzureADDefaults.AuthenticationScheme)
                ..AddAzureAdB2C(options => Configuration.Bind("Authentication:AzureAdB2C", options))
```

Maybe have a new method for the OpenIdConnect code which is the same for AzureAD B2C and Azure AD v2.0 (a lot)

**Additional context/ Error codes / Screenshots**

Good ideas in the B2C sample should be brought back as well in the AAD tutorial (for instance logging ?)

**Comment by jmprieur** [comment]
@TiagoBrenck 
assigning this issue to you. Ping me if this is not clear. The work (given that most of the code is now in ASP.NET core directly) should be minimal.

cc: @kalyankrishna1

**Comment by TiagoBrenck** [comment]
PR opened: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/pull/116

**Comment by TiagoBrenck** [comment]
This is has been merged already @jmprieur.
