### ISSUE TITLE
Wrong redirect URI behind a proxy

### ISSUE THREAD

**Issue by Elanis** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#118]
### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. [X] Web app that signs in users
   1. [X] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users 
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### OS and Version?
> Windows Server

### Versions
> ASP.NET Core 2.1.1

### The issue
Hello, i'm here to seek help about a problem I Have with an [1-WebApp-OIDC/1-1-MyOrg](../1-WebApp-OIDC/1-1-MyOrg) derivated application. I try to execute it on a server behind a reverse proxy. 

The reverse proxy listen HTTPS request but forward the request to the app as HTTP, so when the app try to call azure API it have **http://example.com** in request_uri parameter instead of **https://example.com**, so I have the error message "AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application".

As you know, we can't set an HTTP domain in AzureAD reply URLs.

I tried to force https by writing request.scheme or editing *Microsoft.Identity.Web/Client/TokenAcquisition.cs* line 269 by forcing https; but neither works.

Did you have an idea how to fix this ?

Thanks

**Comment by kalyankrishna1** [comment]
Could you advise the proxy admins to whitelist Azure AD endpoint "https://login.microsoftonline.com" and allow traffic to pass as is ?

**Comment by Elanis** [comment]
I already made it whitelisted because at first I couldn't couldn't call the AzureAD endpoint, but now, after being connected as my professional account, i got redirected to:
**https://login.microsoftonline.com/......?redirect_uri=http://example.com........** instead of **https://login.microsoftonline.com/......?redirect_uri=https://example.com........**.

Isn't the library (or the web app itself) giving to the AzureAD endpoint the request URI ?

**Comment by jmprieur** [comment]
@Elanis : would this article help you? http://josephwoodward.co.uk/2016/07/proxying-http-requests-asp-net-core-using-kestrel ?

**Comment by Elanis** [comment]
Hello, I don't think so. I don't have any control on the reverse proxy, and it isn't a .NET app.

Is there a way to force redirect_uri on the application side ?

Notes:
- What happening:
![image](https://user-images.githubusercontent.com/7013446/60005621-2488eb80-966f-11e9-97ef-cf09ef10f863.png)

- The url i'm redirected to: https://login.microsoftonline.com/MYTENANTID/oauth2/v2.0/authorize?client_id=MYAPPLICATIONID&redirect_uri=http%3A%2F%2Fexample.com%2Fsignin-oidc&response_type=id_token&scope=openid%20profile&response_mode=form_post&nonce=NUMBERS.VERYLONGCHAIN&state=VERYLONGSTRING&x-client-SKU=ID_NETSTANDARD1_4&x-client-ver=5.2.0.0

Thanks for your help :)

**Comment by jmprieur** [comment]
Thanks for the clear explanation, @Elanis 

I'm not sure this is the right fix, but to make progress towards the issue resolution, I would try to insert a line here: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/47f1fc57b3574c011cd52d2bcc45b240f29fcc03/Microsoft.Identity.Web/StartupHelpers.cs#L94
 
something like:

```CSharp
context.ProtocolMessage.RedirectUri = "https://example.com";
```

Please tell me if that worked.

**Comment by Elanis** [comment]
Yeah, thanks, It was fixed.

I got another error with Signature validation but I'll try to fix it by myself first. If I got another stuck or when I find out how to make it work, I'll update this issue to explain how to fix it (if another person have the problem).

**Comment by Elanis** [comment]
Hello !

The problem fix was indeed:

> Thanks for the clear explanation, @Elanis
> 
> I'm not sure this is the right fix, but to make progress towards the issue resolution, I would try to insert a line here:
> 
> https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/47f1fc57b3574c011cd52d2bcc45b240f29fcc03/Microsoft.Identity.Web/StartupHelpers.cs#L94
> 
> something like:
> 
> ```cs
> context.ProtocolMessage.RedirectUri = "https://example.com";
> ```
> 
> Please tell me if that worked.

------

The problem I got after this fix was:

> SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed.

The fix was to add privileges to the service account running the website.

------

Thanks @jmprieur, you saved me some hours ! 😃 

**Problem Solved**

**Comment by tylerforaie** [comment]
Hey @jmprieur or anyone else that may be monitoring this closed issue. I am encountering basically the same issue as above however now that `Microsoft.Identity.Web` is a nuget package things behave a little bit differently. The recommend practice is to use the `.AddSignIn()` extension and I am unable to see a way to set the redirect url as mentioned above. Any help would be appreciated.

I also made a [stackoverflow](https://stackoverflow.com/questions/61465140/how-do-you-set-the-redirect-url-when-using-microsoft-identity-web) post and would be receptive to any feedback there as well.

Thanks!

**Comment by jmprieur** [comment]
@tylerforaie : I think that this should be addressed by https://github.com/AzureAD/microsoft-identity-web/issues/115, which is next on line to be implemented in Microsoft.identity.Web
cc: @jennyf19 as it's assigned to her.
