### ISSUE TITLE
Build/Deploy with dev.azure.com: Build fails.

### ISSUE THREAD

**Issue by multco-malan** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#122]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. [X] Web app that signs in users
   1. [X] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users 
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../5-WebApp-AuthZ/5-2-Groups)
1. [X] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

I'm following along in the 1-1-MyOrg project.
When I deploy to dev.azure.com the Build solution **\*.sln step fails with 

 Error MSB3202: The project file "D:\a\1\s\aspnetcoretutorial\webapp\Microsoft.Identity.Web\Microsoft.Identity.Web.csproj" was not found.

My solution contains the two projects Microsoft.Identity.Web which is referenced by the WebApp-OpenIDConnect-DotNet project.

Here is the sln file:
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 16
VisualStudioVersion = 16.0.29020.237
MinimumVisualStudioVersion = 10.0.40219.1
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "WebApp-OpenIDConnect-DotNet", "aspnetcoretutorial\webapp\1-WebApp-OIDC\1-1-MyOrg\WebApp-OpenIDConnect-DotNet.csproj", "{016D21EC-DDAA-4C32-8C48-5BA3A6155D84}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Microsoft.Identity.Web", "aspnetcoretutorial\webapp\Microsoft.Identity.Web\Microsoft.Identity.Web.csproj", "{7427E143-B78C-4E4C-B94F-D78B12FD0598}"
EndProject
...

Here is the azure-pipelines.yml:
# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

And finally here is the Visual Stuido build step:

#Your build pipeline references an undefined variable named ‘Parameters.solution’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references the ‘BuildPlatform’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971

steps:
- task: VSBuild@1
  displayName: 'Build solution **\*.sln'
  inputs:
    solution: '$(Parameters.solution)'
    vsVersion: 15.0
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    clean: true

**Comment by jmprieur** [comment]
@multco-malan : I'm confused. Is this a bug (of Azure DevOps?) or a feature request?
As far as I'm concerned, the sample uses continuous integration with Azure DevOps legacy builds (not yaml), and they don't fail?
[![Build status](https://identitydivision.visualstudio.com/IDDP/_apis/build/status/AAD%20Samples/.NET%20client%20samples/ASP.NET%20Core%20Web%20App%20tutorial)](https://identitydivision.visualstudio.com/IDDP/_build/latest?definitionId=819)

**Comment by multco-malan** [comment]
Hi Jean-Marc,

Nevermind.
I had some issues with how my VS sln was configured as well as some self inflicted issues in my DevOps build/release steps.

**Comment by jmprieur** [comment]
Thanks for the clarification, @multco-malan
