### ISSUE TITLE
Account selection dialog displaying on logout

### ISSUE THREAD

**Issue by logankp** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#126]
## The issue was found for the following scenario:

1. [x] Web app that signs in users
   1. [x] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../1-WebApp-OIDC/1-1-MyOrg)

When logging out of the web app, I'm still getting the account selection screen even though the login_hint parameter is in the URL with the correct value. How do I skip the account selection screen and log out right away?

I apologize for asking this here, but I've been struggling with this for quite a while and have asked on StackOverflow and have gotten nowhere :(

**Comment by TiagoBrenck** [comment]
Hi @logankp, we are aware of this behavior and we have opened an internal thread about this topic since some are saying that this is a feature introduced lately on OIDC v2 for security purpose. 
We will let you know soon.

Thanks

**Comment by jmprieur** [comment]
In my opinion, there is a regression/change on the service. I'm pretty sure this was working when I wrote the code.
@logankp : do you see at least the right account selected in the list of accounts?

**Comment by logankp** [comment]
@jmprieur The correct account is selected. I can also confirm that the v1 endpoint works correctly.

**Comment by TiagoBrenck** [comment]
v1 endpoint still accepts login_hint for the sign-out flow. As confirmed, v2 doesn't accept it anymore so the behavior of displaying the account selection dialog is by design.

**Comment by logankp** [comment]
Thanks for confirming this. My use case is implementing auto-logout: after a certain period of time, the app will log the user out by initiating the logout flow. With the current implementation of v2, this is useless because the user has to physically click logout.

**Comment by TiagoBrenck** [comment]
I understand. I don't know about the whole business need behind your use case, but maybe the conditional access policies could be an option for you. If you go to Azure Portal, then navigate to "Enterprise applications" > "Your app" > "Conditional Access", you can create a **Sign-in frequency** policy and set it to every X hour/days.

**Comment by selvarajendran** [comment]
Is it recommended to use the v1 endpoint? Any idea when the v1 endpoint would be deprecated? 

Thanks in advance.

**Comment by jmprieur** [comment]
No, we don't recommend you use the v1.0 endpoint. 
@hpsin could you please help if there is a workaround?

**Comment by hpsin** [comment]
We're improving this flow and will have updated guidance on "single sign out" shortly (end of April ETA)

**Comment by selvarajendran** [comment]
Thank you both @jmprieur @hpsin

**Comment by plaa** [comment]
@hpsin How can I follow the progress of "single sign out"?  Will you post about it here (even though it's closed), or is there another issue that I can subscribe to?

We're implementing an internal app that embeds various web services in WebViews.  In order for SSO to work inside the WebView, we're performing AD authentication in a WebView using MSAL.js.  Currently, we've implemented logout by simply clearing cookies and all storage from the WebView, but it would be good to be able to perform back-channel logout as well.  The account selection prompt is preventing us from doing that.

**Comment by hpsin** [comment]
It won't be marked on this Github issue, but you can follow along with our product announcements here: https://techcommunity.microsoft.com/t5/azure-active-directory-identity/bg-p/Identity

**Comment by s-t-e-v-e-c** [comment]
Has this been implemented yet for the v2 endpoint?  It seems that the logout_hint parameter is not being honored still at sign-out, and I don't see mention of this in the blog linked above by hpsin.
