### ISSUE TITLE
Scope as part of the cache key?

### ISSUE THREAD

**Issue by HenningRoigaard** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#129]
I have a question related to the cacheprovider implementations and scopes.

The sample library includes a number of XXXTokenCacheProvider implementations, e.g., MSALAppSqlTokenCacheProvider. None of these consider scopes when defining a cache key, and I have been wondering if that is the intended "MSAL-way" of doing it.

Consider this case: 
I would like for my Web App to access two different APIs using the on-behalf-of flow. 

To this end, I acquire an access token for the first API using scope "A" via **ITokenAcquisition.GetAccessTokenOnBehalfOfUser**, caching it in the process. Then, I acquire an access token for the second API using scope "B", again using **ITokenAcquisition.GetAccessTokenOnBehalfOfUser** but with the new scope. This results in a cache-hit returning the old token for scope "A" ... which I expect would result in an error if sent to the second API.

I realize that we pass the scope along when invoking GetAccessTokenOnBehalfOfUser , which means it would be possible to compare scopes in the request and the cached token, and get a new token in case the existing token lack some of them. However, I cannot find such a comparison anywhere in **Microsoft.Identity.Web** nor in **Microsoft.Identity.Client**.

The question then is this: How is the situation above resolved, such that the second token contains the second scope? It will accept "somewhere in **Microsoft.Identity.Client**" as an answer :)

I also realize that I could request both scopes initially, but the use case detailed above should be supported, right?

**Comment by TiagoBrenck** [comment]
There is no need for the scope to be part of the token cache key, because the token saved for that user will be the same but it will contain both scopes. Basically, by the point that the user requested an access token for "scope B", their token will be one containing "scope A" and "scope B". 

Does it answer your question?

**Comment by HenningRoigaard** [comment]
Well, I expected that "scope B" would be part of the token, i.e., the scope should not be part of the cache key. The question was more along the line of how it gets to be part of the token? Since we cannot simply edit a token issued by the AD, someone somewhere must request a new token from the AD containing the new scope. 

I guess I just wanted to get confirmation, that adding scopes to tokens was indeed taken care of elsewhere (and probably in **Microsoft.Identity.Client**), and thus was not relevant for the cache key.

**Comment by jmprieur** [comment]
@HenningRoigaard . Indeed it's taken care by Azure AD, called by MSAL.NET.
