### ISSUE TITLE
TodoListService missing configuration?

### ISSUE THREAD

**Issue by HenningRoigaard** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#133]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. [ ] Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [x] Web app calling your own Web API
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

First the documentation part

1.	At “Creating the client web app (TodoListClient)”: The list starts with “option 2”, without any other options presented. Seems like it could be deleted.
2.	At “Add a model (TodoListItem) and add the controller and views”: Item 7 seems like a duplicate of item 5 in the previous list.
3.	At “Creating the Web API project (TodoListService) > Modify the startup.cs … > Step 2” we add the line “.AddProtectedApiCallsWebApis(Configuration, new string[] { Configuration["TodoList:TodoListScope"] }). But nowhere is "TodoList:TodoListScope" configured for the TodoListService.
4.	I think a description of the purpose of “AddProtectedApiCallsWebApis” would be beneficial, much like it is for AddProtectWebApiWithMicrosoftIdentityPlatformV2. When I first read the guide, I believed that the purpose of AddProtectedApiCallsWebApis was to assert that callers had access to the given scope. 

Then the (possible) bug part

Even if the "TodoList:TodoListScope" is added to the service, I get and [exception](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/files/3416378/exception.txt) when navigating to the todolist in the client, which seems to indicate that the TodoListService should have a clientSecret configuration, or that AddProtectedApiCallsWebApis is doing something it should not.

Lastly, the TodoListService is configured with both AddProtectWebApiWithMicrosoftIdentityPlatformV2 and AddProtectedApiCallsWebApis. Both of these set JwtBearerOptions.Events.OnTokenValidated, of which the last overrides the first. Is this intended?

**Comment by kalyankrishna1** [comment]
Thanks for taking the time to provide a detailed feedback, we've addressed most of your comments and observations
1. fixed
2. It actually needs to be done twice, I understand in actual prod scenarios you'd optimize, but this is a sample.
3. & 4. That was wrong and old code that we'd deprecate soon

Let us know if there are any more pending issues
