### ISSUE TITLE
GetAccountsAsync() returns null on second debug when using chrome

### ISSUE THREAD

**Issue by liroforum** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#137]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. [ ] Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [x] Web app calling your own Web API
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

1) Open Visual studio and launch the solution.
2) Run the aspnetcore UI project which references Microsoft.Identity.Web library.
3) Start debugging after selecting Google chrome as the Web Browser.
4) UI Project logs you in (using OIDC) which call the downstream API and gets the result.
5) Now stop debugging and start it again.
6) In the  Microsoft.Identity.Web library> TokenAcquisition.cs line 368 and line 373 returns empty results.
7) AcquireTokenSilent() on the line 381 fails as a result of the above.
8) Gets Internal Server error as a result.
9) Clear cookie in Chrome, and start debugging. Then the GetAccounts() has a non empty value on the first trial of debugging on the following debugs steps 6 is repeated.

**Expected behavior**
GetAccounts() should return non empty value on second or third or forth debugging(only in Chrome). Tested in Edge and IE and they both work as expected.

**Actual behavior**
GetAccounts() returns null after the first debugging, unless the cookie is cleared

**Possible Solution**

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
ASPNETCore 2.1( so had to downgrade nuget packages in microsoft.identity.web library)

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue?
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)
  
### Mention any other details that might be useful
Tried reinstalling Chrome to rule out personal settings, but issue persists.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by liroforum** [comment]
on further investigation, I can see the OnAuthorizationCodeRecieved event is not fired in the second and following debugs.

**Comment by jmprieur** [comment]
@liroforum it's not because the app thinks the user is signed-in, whereas the cache is not
1. Which cache adapter did you use? maybe an adapter like the memory adapter that clears the process when you stop debugging? I'm thinking it's only a dev issue, not a prod issue?
2. I'm confused why a challenged is not triggered by the attribute on the controller. Wouldn't you have removed the `[MsalUiRequiredExceptionFilter(Scopes = new[] { ... })]` attribute?

**Comment by liroforum** [comment]
1)Yes, I was using InMemory caching mechanism.
2)I was following 4-WebApp-your-API sample. I could not find [MsalUiRequiredExceptionFilter(Scopes = new[] { ... })] in the controller code(but found it in readme).

But yes, now I have added [MsalUiRequiredExceptionFilter(Scopes = new[] { ... })] to my controller action, so when the account is empty it goes for the MSAL exception and relogin.

Just wanted to confirm, should the MsalUiRequiredExceptionFilter parameter be the APIScope when calling a down stream api?

**Comment by jmprieur** [comment]
yes, the parameter shoud be the scopes you need to call downstream APIs, @liroforum

**Comment by liroforum** [comment]
I used the below code without the Apiscope and it worked. Not sure why.

[MsalUiRequiredExceptionFilter(Scopes = new[] { Constants.ScopeUserRead })]

Thanks for your help.

**Comment by jmprieur** [comment]
"user.read" is automatically added as an API permission when you create an app, and you consent for it when you log-in. That's why it worked without the attribute.
