### ISSUE TITLE
Request for example to assign existing roles to existing groups

### ISSUE THREAD

**Issue by jcox86** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#144]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

> N/A

### Repro-ing the issue

> N/A

### Any log messages given by the failure
> N/A

### OS and Version?
Windows 10.

### Versions
.NET Core - 2.2.0
Microsoft.AspNetCore.Authentication.AzureAD.UI - 2.2.0
  
### Mention any other details that might be useful
You have a number of Powershell examples to create roles and create users.  I would like to assign existing roles to existing users/groups.  I can run `Get-AzureADGroup` to find the object ID of the group I want to assign, but the same does not happen for Roles.  

The objectIds returned from `Get-AzureADServiceAppRoleAssignment -ObjectId <my-service-account>` seem to encoded somehow, and are not the unique guids used in the manifest where they were created. 

Also, should we be upgrading from `Microsoft.AspNetCore.Authentication.AzureAD.UI` to `Microsoft.Identity.Client`?

**Comment by DhivyaG19** [comment]
To find the objectId of existing roles in your tenant you can use [Get-AzureADMSRoleDefinition](https://docs.microsoft.com/en-us/powershell/module/azuread/get-azureadmsroledefinition?view=azureadps-2.0-preview) powershell commandlet and you can use [New-AzureADMSRoleAssignment](https://docs.microsoft.com/en-us/powershell/module/azuread/New-AzureADMSRoleAssignment?view=azureadps-2.0-preview) command let to assign users/groups to that roles.

**Comment by kalyankrishna1** [comment]
Closing this as the PS command needed is provided and Microsoft.AspNetCore.Authentication.AzureAD.UI has been superseded by Microsoft.Identity.Web
