### ISSUE TITLE
Set AccountController as ApiVersionNeutral

### ISSUE THREAD

**Issue by paolorr** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#155]
I configured a webapp to use API versioning and if I try to access /AzureAD/Account/SignIn or /AzureAD/Account/SignOut I get ```{"error":{"code":"ApiVersionUnspecified","message":"An API version is required, but was not specified.","innerError":null}}``` because the API versioning is set to AssumeDefaultVersionWhenUnspecified = false.

On Asp.Net Core 2.2 to force this error it's necessary to add EnableEndpointRouting = false as described below.

A workaround is setting AssumeDefaultVersionWhenUnspecified = true. Is it possible to set AccountController as ApiVersionNeutral to avoid assuming default version when unspecified?

### Repro-ing the issue

**Repro steps**

1. Open solution 1-WebApp-OIDC\1-1-MyOrg
2. Add following lines to ConfigureServices
```
services.AddApiVersioning(opt =>
{
	opt.ApiVersionReader = new UrlSegmentApiVersionReader();
});
```
3. If running Asp.Net Core 2.2 also add following line to ConfigureServices (on 2.1 this is not necessary)
```
services.AddMvc(options =>
{
	//add following line to force api version error
	options.EnableEndpointRouting = false;

	var policy = new AuthorizationPolicyBuilder()
		.RequireAuthenticatedUser()
		.Build();
	options.Filters.Add(new AuthorizeFilter(policy));
})
```
4. Access /AzureAD/Account/SignIn or /AzureAD/Account/SignOut

**Expected behavior**
After setting AccountController to ApiVersionNeutral, executos sign in or sign out

**Actual behavior**
```{"error":{"code":"ApiVersionUnspecified","message":"An API version is required, but was not specified.","innerError":null}}```

**Possible Solution**
A workaround is setting AssumeDefaultVersionWhenUnspecified = true (this would impact all the API), but the ideal solution is setting AccountController as ApiVersionNeutral 

### Any log messages given by the failure
Web Server output
```
WebApp-OpenIDConnect-DotNet> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
WebApp-OpenIDConnect-DotNet>       Request starting HTTP/1.1 GET http://localhost:44321/AzureAD/Account/SignOut  
WebApp-OpenIDConnect-DotNet> info: Microsoft.AspNetCore.Mvc.Routing.DefaultApiVersionRoutePolicy[3]
WebApp-OpenIDConnect-DotNet>       Request did not specify a service API version, but multiple candidate actions were found. Candidate actions: Microsoft.AspNetCore.Authentication.AzureAD.UI.AzureAD.Controllers.Internal.AccountController.SignOut (Microsoft.AspNetCore.Authentication.AzureAD.UI)
WebApp-OpenIDConnect-DotNet> info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
WebApp-OpenIDConnect-DotNet>       Executing ObjectResult, writing value of type '<>f__AnonymousType0`1[[<>f__AnonymousType1`3[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[<>f__AnonymousType2`1[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Microsoft.AspNetCore.Mvc.Versioning, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]], Microsoft.AspNetCore.Mvc.Versioning, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]]'.
WebApp-OpenIDConnect-DotNet> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
WebApp-OpenIDConnect-DotNet>       Request finished in 28.0076ms 400 application/json; charset=utf-8
```

### Versions
Asp.Net Core 2.1 + MSAL 2.1.1
Asp.Net Core 2.2 + MSAL 2.2.0

**Comment by jmprieur** [comment]
@paolorr : you don't want us to change things in the sample?

**Comment by paolorr** [comment]
I found it easier to update my project to 2.2 as it has no conflicts with API versioning (by default) and moving from 2.1 to 2.2 had no impact in the project
