### ISSUE TITLE
Using ClaimsPrincipal with GetAccessTokenOnBehalfOfUser

### ISSUE THREAD

**Issue by robertjf** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#159]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

I'm using the Microsoft.Identity.Web project with IdentityServer4 and MSAL to allow retrieval of additional user details via MS Graph when a user logs in with an Organisational account - the problem is, in order for the authentication to work, I need to pass in a `ClaimsPrincipal` to `GetAccessTokenOnBehalfOfUser` as HttpContext.User doesn't contain the necessary information when I need it.

In order to do this, I've made the following changes to the project:

1. Change to the signature for `GetAccessTokenOnBehalfOfUser` from

```csharp
        Task<string> GetAccessTokenOnBehalfOfUser(HttpContext context, IEnumerable<string> scopes, string tenantId=null);
```
to
```csharp
        Task<string> GetAccessTokenOnBehalfOfUser(HttpContext context, IEnumerable<string> scopes, string tenantId=null, ClaimsPrincipal claimsPrincipal = null);
```
2. Replace `context.User` with `claimsPrincipal ?? context.User` in the implemented method.

This is used via a callback url from Azure Authentication:

```csharp
            // read external identity from the temporary cookie
            var isAzure = true;

            // Support for AzureAD's default cookie...
            var cookie = AzureADDefaults.CookieScheme;
            var result = await HttpContext.AuthenticateAsync(cookie);

            // Set ClaimsPrincipal to read MS Graph later on - we can't use the HttpContext as it doesn't have the details.
            _azureGraphService.SetClaimsPrincipal(result.Principal);

            var details = await _azureGraphService.GetMyDetailsAsync(populatePicture: true);
```

_azureGraphService has the following relevant methods:

```csharp
        /// <summary>
        /// Sets the ClaimPrincipal for AccessToken retrieval.
        /// </summary>
        /// <param name="claimsPrincipal"></param>
        public void SetClaimsPrincipal(ClaimsPrincipal claimsPrincipal)
        {
            ClaimsPrincipal = claimsPrincipal;
        }

        private GraphServiceClient GetGraphServiceClient(string[] scopes)
        {
            return GraphServiceClientFactory.GetAuthenticatedGraphClient(async () =>
            {
                try
                {
                    string result = await _tokenAcquisition.GetAccessTokenOnBehalfOfUser(_httpContext, scopes, claimsPrincipal: ClaimsPrincipal);
                    return result;
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, $"Error attempting to retrieve Access Token: {ex.Message}");
                }
                return null;
            }, _options.GraphApiUrl);
        }

        /// <summary>
        /// Get additional details about the current user to help in investigating the alert
        /// </summary>
        /// <param name="populatePicture"></param>
        /// <returns>Graph User Model</returns>
        public async Task<UserAccountDevice> GetMyDetailsAsync(bool populatePicture = false)
        {
            var taskList = new List<Task>();
            var userModel = new UserAccountDevice();
            Task<Stream> populatePictureTask = null;

            var client = GetGraphServiceClient(new[] { Constants.AzureGraphApi.ScopeUserRead });
            var userTask = client.Me.Request().GetAsync();

            // do stuff.
        }


```

This is working beautifully, however I'm wondering if there's another way to do this?

---

Please add an 'x' for the scenario(s) where you found an issue

1. [x] Web app that signs in users
   1. [x] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
1. Web app that calls Microsoft Graph
   1. [x] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
1. [x] Other (please describe) - Integrating with IdentityServer4

**Comment by TiagoBrenck** [comment]
@jmprieur could you take a look at this one?
Thanks

**Comment by jmprieur** [comment]
@robertjf do you know why the HttpContext.User does not have the user principal? wasn't the identity extracted from the ID Token?
How do you get the value to pass to `SetClaimsPrincipal` ?

**Comment by robertjf** [comment]
Hi @jmprieur sorry about the delay, finally got a chance to investigate a little further.

The code currently does this:

1. Receives a callback from Azure AD login.
2. runs `var result = await HttpContext.AuthenticateAsync(AzureADDefaults.CookieScheme);`

At this point, the HttpContext.User doesn't contain any information about the authenticated user, but the `result.Principal` does.  This is basically a variation on the [IdentityServer4 External Providers flow](http://docs.identityserver.io/en/latest/topics/signin_external_providers.html)

I'm probably missing something, but I've not yet found another way to get the authenticated Principal into the AzureGraphService.

**Comment by Mrcl1450** [comment]
I don't know if it's related but I'm having a similar issue with claims in AuthorizationRequirement.
If a user keeps writing a report for too long (30 mins - 1 hour?) `context.User.Claims.FirstOrDefault(c => c.Type == "preferred_username").Value;` throws a null exception on submit the form and they need to go back to main page in order to make it work again, losing what they wrote.

**Comment by robertjf** [comment]
@jmprieur just checking in to see if you have enough information or require more from me?

**Comment by jmprieur** [comment]
@robertjf : We've done this in Microsoft.Identity.Web 0.2.1-preview which released on Saturday.
Thanks for your suggestion
