### ISSUE TITLE
Azure B2C with core 2.1 

### ISSUE THREAD

**Issue by skorpionet100** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#16]
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release

### Expected/desired behavior
> Sample, in a Razor project, to login to Azure B2C with asp.net core 2.1 and latest identity client to read the token.

### OS and Version?
> Windows 10

**Comment by jmprieur** [comment]
Closing as duplicate of #112
