### ISSUE TITLE
Using Redis Cache

### ISSUE THREAD

**Issue by ferronsw** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#163]
The following is stated in '2-WebApp-graph-user/2-1-Call-MSGraph/README.md'

> Decide which token cache implementation to use. In this part of the phase, we'll use a simple in memory token cache, but next steps will show you other implementations you can benefit from, including distributed token caches based on a SQL database, or a Redis cache.

But when I look at the next step ('/2-WebApp-graph-user/2-2-TokenCache') there is only spoken about caching the token in sql. So is Redis cache not  supported, not documented or both?

**Comment by jmprieur** [comment]
@ferronsw : It is supported, and you could definitively implement a Redis cache based on the token cache serialization examples provided in this sample in the [Microsoft.Identity.Web/Client/TokenCacheProviders](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/Microsoft.Identity.Web/Client/TokenCacheProviders) sub-folder.

This is on our backlog to provide a sample implementation, but if you do it first, don't hesitate to contribute.

**Comment by ferronsw** [comment]
@jmprieur  So if I understand correctly I have to write my own logic for the redis token serialization part?

**Comment by jmprieur** [comment]
@ferronsw : yes, or otherwise wait until someone (who could be us) writes the serializer. This is on our backlog, but not the highest priority. If there are many votes, though, we could bump it up.

**Comment by jmprieur** [comment]
PR from @ferronsw is https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/pull/165

**Comment by udlose** [comment]
> @ferronsw : It is supported, and you could definitively implement a Redis cache based on the token cache serialization examples provided in this sample in the [Microsoft.Identity.Web/Client/TokenCacheProviders](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/Microsoft.Identity.Web/Client/TokenCacheProviders) sub-folder.
> 
> This is on our backlog to provide a sample implementation, but if you do it first, don't hesitate to contribute.

@jmprieur the link you provided gives a 404.  Can you please provide the correct link?

Also, the same link on this page is broken - https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/2-WebApp-graph-user/2-2-TokenCache#next-steps

**Comment by kalyankrishna1** [comment]
target is this sample -> https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/2-WebApp-graph-user/2-2-TokenCache

**Comment by v-michaelmi** [comment]
PR up here:

https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/pull/646

Need to add in documentation but the code should be straight-forward enough for anyone to explore to see how to setup Redis if they want to ahead of time.

**Comment by v-michaelmi** [comment]
Resolved with [commit dfff7](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/commit/dfff728ce03b5cd6e0d41cc4940ed974c12b88ca)
