### ISSUE TITLE
azureAdOptionsAccessor.CurrentValue.ClientId is null but exception is not thrown

### ISSUE THREAD

**Issue by ferronsw** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#164]
Each token cache provider uses the clientId to set the AppId for the AppCacheId. 
Currently this check is executed:

```
  if (azureAdOptionsAccessor.CurrentValue == null && string.IsNullOrWhiteSpace(azureAdOptionsAccessor.CurrentValue.ClientId))
            {
                throw new ArgumentNullException(nameof(AzureADOptions), $"The app token cache needs {nameof(AzureADOptions)}, populated with clientId to initialize.");
            }
```

Writing the Redis Serialization I discovered this is useless. In my case `CurrentValue` isn't null, but `CurrentValue.ClientId` is.  Because of the `&&` operator the exeception is not thrown. The AzureADOptions are mapped in the Microsoft.Identity.Web.StartupHelpers like this:

```
services.AddAuthentication(AzureADDefaults.AuthenticationScheme)
                .AddAzureAD(options => configuration.Bind("AzureAd", options));
```

The token cache providers uses  `IOptionsMonitor<AzureADOptions> azureAdOptionsAccessor)` to get the mapped values. But they are all empty and because of the incorrect null check the exception is not thrown.

**Comment by TiagoBrenck** [comment]
Is your options under `AzureAd` section on your config? Are your using `services.AddOptions();` on the `Startup.cs`? 
The configuration expects them to be like this in your `appsettings.json`:

```
"AzureAd": {
    "Instance": "value",
    "Domain": "value",
    "TenantId": "value",
    "ClientId": "value"  
    ...
}
```

If you don't want to use the appId as part of your token key, it is fine, but the `AzureADOptions` is a must on other parts of your application, like the `Startup.cs`.

**Comment by ferronsw** [comment]
@TiagoBrenck The `AzureAd` settings are specified like this.

> "AzureAd": {
>     "Instance": "value",
>     "Domain": "value",
>     "TenantId": "value",
>     "ClientId": "value"  
>     ...
> }

This line fixes it:

`services.Configure<AzureADOptions>(Configuration.GetSection("AzureAd"));`

I just find it weird that this is not configured in the existing Token Serialization provider methods, because they all use the clientId.
