### ISSUE TITLE
User.Identity.Name is null but should be preferred_username from claims

### ISSUE THREAD

**Issue by bmmathe** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#169]
### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. [ ] Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ x] Web app calling your own Web API
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

In an Authorized controller User.Identity.Name is null however the User.Claims has a preferred_username. 

User.GetDisplayName() will return the preferred_username however the sample is using User.Identity.Name.

**Expected behavior**
User.Identity.Name should be set to preferred_username.

**Actual behavior**
User.Identity.Name is null.

**Possible Solution**
Maybe this is an issue in Microsoft.AspNetCore.Authentication.AzureAD.UI?

### Versions
> of ASP.NET Core, of MSAL.NET
2.2 and 4.2.1

**Comment by jmprieur** [comment]
This should work (and used to work), given this line: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/7a67374ddcc2216d84f05583ef6dcbbafcde86c9/Microsoft.Identity.Web/StartupHelpers.cs#L76

Can you please share detailed repro steps? which solution of the sample did you use ? @bmmathe

**Comment by jmprieur** [comment]
Thanks for these explanations @bmmathe 
Just out of curiosity, do you use the same clientId for the msal.js app and the Web API? (which is a valid scenario)

**Comment by jmprieur** [comment]
Closing this issue as it was fixed
