### ISSUE TITLE
Explain how to sign-in users with ADFS

### ISSUE THREAD

**Issue by jmprieur** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#171]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. [x ] Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

**Comment by Welteam** [comment]
Is there any news on this topic? I'm currently trying to do just that and [the only doc I found](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/enabling-openId-connect-with-ad-fs) still uses the old project structure with web.config and reference the previous version of this repo.

**Comment by jmprieur** [comment]
@kalyankrishna1 would you know?

**Comment by kalyankrishna1** [comment]
@Welteam, The OIDC/OAuth support on ADFS is somewhat different for the libraries involved as there is no concept of a tenantId (tid) in ADFS and that breaks the libraries that depend on this being available, like the ones in use here.
I suggest you look at [this](https://github.com/Azure-Samples/ms-identity-dotnet-adfs-to-aad/blob/master/README.md) guide and choose what works best for you.

**Comment by kalyankrishna1** [comment]
closing as we already have an ADFS sample
