### ISSUE TITLE
Microsoft Graph responses cached and shared across subsequent user logins

### ISSUE THREAD

**Issue by gavinharriss** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#180]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. [ ] Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [x] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

1) Setup 2 different users belonging to different security groups.
2) Login with user 1 and click on their user name to view their current groups.
3) Log off user 1.
4) Login with user 2 and view their security groups. Notice that the groups displayed belong to user 1 and have not been refreshed for user 2.

**Expected behavior**

Groups should be unique per user.

**Actual behavior**

Groups for the first user are shown for all subsequent users.

**Possible Solution**

Maybe there is a problem with the memory cache setup?

**Additional context/ Error codes / Screenshots**

The home page does show different details for the different users, but the profile page shows exactly the same details for both users, which are all the details from the first logged in user.

### Any log messages given by the failure
None.

### OS and Version?
Windows Server 2012 R2 Standard
Also seen same behavior when deployed to Windows Server 2016

### Versions
ASP.NET Core 2.2.6
MSAL.NET 4.3.1

### Attempting to troubleshooting yourself:

Watched http calls using Fiddler. Not seeing subsequent calls to https://graph.microsoft.com/v1.0 after initial call suggesting cache is being hit instead and re-used across different users.
  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@kalyankrishna1 : do you have cycles to look at it?

**Comment by kalyankrishna1** [comment]
@gavinharriss , I've tested  this a few times now and not able to replicate this behavior at all.

The code in HomeController.cs is very simple, it picks the CurrentUser and prints their claims
            ViewData["User"] = HttpContext.User;

Please debug this line of code and check if the HttpContext is getting mixed up for you somehow?

**Comment by gavinharriss** [comment]
@kalyankrishna1 ViewData["User"] = HttpContext.User is behaving as expected.

The home page https://localhost:44321/ always shows the correct information.

It's when Microsoft Graph is used that the issue manifests. If you hit the user profile page https://localhost:44321/UserProfile it always presents the details associated with the first user that logged in. My investigations seems to suggest it's re-displaying the cached info from the first user for all subsequent users.

**Comment by kalyankrishna1** [comment]
This bug has been fixed. Please take a the latest code and try again.

**Comment by gavinharriss** [comment]
@kalyankrishna1 thanks for the super fast bug fix - very much appreciated :)

**Comment by jmprieur** [comment]
@kalyankrishna1 : can you please add the link to the PR that fixed it?

**Comment by kalyankrishna1** [comment]
Link to [PR](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/pull/147)
