### ISSUE TITLE
Client App calls Service App which then calls another Service App Example

### ISSUE THREAD

**Issue by Alfetta159** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#181]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. [ ] Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [X] Web app calling your own Web API
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

**Expected behavior**
I would like to be able to set up an API (service) to call another API service using the same user impersonation that a client app called the first service, it that's possible.

**Actual behavior**
I've been trying a number of things but can't get it to work. I could use client credential flow, but I was hoping that I could maintain the user identity throughout the SOA.

**Possible Solution**

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
> of ASP.NET Core, of MSAL.NET

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue?
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)
  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by TiagoBrenck** [comment]
Hello @Alfetta159 your scenario seems to fit the on behalf of flow (OBO) case. Would you mind reading this documentation, https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow, and check if you are following its requirements?

Let us know if it didnt help.

**Comment by jmprieur** [comment]
@Alfetta159 : indeed, this is OBO. See https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph

**Comment by Alfetta159** [comment]
Thank you, @TiagoBrenck . That did help. I wasn't using an on-behalf-of flow, but now I have it working.

**Comment by Alfetta159** [comment]
Thank you, @jmprieur .That sample was very helpful. The version of the Microsoft.Identity.Web library is a little behind the other, but I was able to make it work with a number of changes. I don't have to tell you that troubleshooting those issues can really force you to look and see what is happening behind the scenes.

**Comment by jmprieur** [comment]
@Alfetta159 : yes, it's one of our goal to re-sync the version of Microsoft.Identity.Web in the Web API sample (and the daemon one). We also hope to have it as a NuGet package at some point.

**Comment by Alfetta159** [comment]
One last thing, and I'm not sure if it should be a new issue or if falls under re-syncing the version of MS Identity Web:

When using `BuildConfidentialClientApplication`, [TokenAquisition.cs](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/4dbe43cab617796384df63b8a368fb56aa5c6c81/Microsoft.Identity.Web/TokenAcquisition.cs#L320) as eventually called from `AddAccountToCacheFromJwtAsync`, the Authority value is generated from members of `azureAdOptions`, but it is the `Instance` and `TenantId` members of `applicationOptions` which are populated, so I'm concatenating the authority value from basically which ever object has its `Instance` and `TenantId` members populated.
