### ISSUE TITLE
When using this sample I get Signature validation failed.

### ISSUE THREAD

**Issue by andrenpt** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#183]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. [ ] Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ x] Web app calling your own Web API
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

When I add my credentials to your sample and I use Scope: "User.Read"
I get an Exception of Signature validation failed

**Expected behavior**

**Actual behavior**

**Possible Solution**

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
> of ASP.NET Core, of MSAL.NET

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue?
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)
  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by TiagoBrenck** [comment]
Hello @andrenpt, I tried to reproduce the bug and didn't get the error.
Could you please provide more details, like:
- Did you customize the code?
- Are you using single tenant? Multi? Personal Account?
- What are the steps to reproduce it?

Thanks

**Comment by andrenpt** [comment]
Hello @TiagoBrenck 
Thank you very much for your quick answer. Really appreciate that
I am using a single TenantId

My Scope Config looks like this:

>  "TodoList": {
    /*
      TodoListScope is the scope of the Web API you want to call. This can be: "api://90b0be48-155d-4ba5-ba7a-0fddd1b68795/user_impersonation",
      - a scope for a V2 application (for instance api://b3682cc7-8b30-4bd2-aaba-080c6bf0fd31/access_as_user)
      - a scope corresponding to a V1 application (for instance <GUID>/user_impersonation, where  <GUID> is the
        clientId of a V1 application, created in the https://portal.azure.com portal.
    */
    "TodoListScope": "user.read",
    "TodoListBaseAddress": "https://localhost:44351"

Exception details

`IDX10511: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.X509SecurityKey, KeyId: 'KEYWASHERE', InternalId: 'INTRNALIDWASHERE'. , KeyId: KEYWASHERE
'.
kid: 'KEYWASHERE'.
...`

Token Details
`{"alg":"RS256","typ":"JWT","nonce":"XXXXXXXXXXXXXXXX","x5t":"XXXXXXXXXX","kid":"XXXXXXXXX"}.{"aud":"00000003-0000-0000-c000-000000000000","iss":"https://sts.windows.net/XXXXXXXXXX/","iat":1568037599,"nbf":1568037599,"exp":1568041499,"acct":0,"acr":"1","aio":"XXXXXXXXXXXXXXX","amr":["pwd","mfa"],"app_displayname":"XXXXXXX","appid":"XXXXXX","appidacr":"1","family_name":"XXXXX","given_name":"XXXXXX","ipaddr":"XXXXXXXX","name":"XXXXX XXXXXX","oid":"XXXXXXXXXX","onprem_sid":"XXXXXXXXXXXX","platf":"3","puid":"XXXXXXXX","scp":"Directory.AccessAsUser.All Directory.Read.All Directory.ReadWrite.All email IdentityProvider.Read.All IdentityProvider.ReadWrite.All IdentityUserFlow.Read.All IdentityUserFlow.ReadWrite.All openid profile User.Read User.Read.All User.ReadBasic.All User.ReadWrite User.ReadWrite.All","signin_state":["inknownntwk"],"sub":"XXXXXXXXX","tid":"XXXXXXXXXXXXX","unique_name":"XXXXXX.XXXX@XXXXX","upn":"XXXXXX@XXXXXXX","uti":"XXXXXX","ver":"1.0","xms_st":{"sub":"XXXXXXXXX"},"xms_tcdt":XXXXX}`

I believe this signature validation issue is happening because the token is for a Microsoft Graph Api and I just want to secure my own personal API. Maybe ?

**Comment by kalyankrishna1** [comment]
You should not be looking at or trying to validate access tokens for Apis that are not "yours", like those issued for MS Graph. See [this thread](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/609) for a detailed discussion,

**Comment by jmprieur** [comment]
Closing this issue as we answered.

**Comment by JoelPagliuca** [comment]
Hello @jmprieur @kalyankrishna1 , this document I believe contradicts your response https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow

To me this description of the implicit flow (particularly the protocol diagram) says a protected API should trust the token given by Microsoft Graph.

I'm having the same problem and I'll raise a new Issue to continue this discussion

**Comment by JoelPagliuca** [comment]
#209

**Comment by TiagoBrenck** [comment]
@JoelPagliuca the doc actually says:

 "Now that you've signed the user into your single-page app, you can silently **get** access tokens for calling web APIs secured by Microsoft identity platform, **such as the Microsoft Graph**."

I will explain it on your [opened issue](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/209)
