### ISSUE TITLE
BuildConfidentialClientApplication uses AzureAdOptions

### ISSUE THREAD

**Issue by dotnetprofessional** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#187]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. [ ] Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [X] Web app calling your own Web API
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

* Define AzureAD config
* Do not define AzureADOptions config

```
  "AzureAd": {
    "Authority": "xxx",
    "Instance": "xxx",
    "TenantId": "xxx",
    "ClientSecret": "xx",
    "ClientId": "xxx",
    "Audience": "xxx"
  },
```
**Expected behavior**
BuildConfidentialClientApplication picks up the Instance and TennantID from AzureAD config rather than AzureADOptions config.

existing code fails without defining yet another config that has the same info as AzureAD
```
IOptions<AzureADOptions> azureAdOptions
...
string authority = $"{azureAdOptions.Instance}{azureAdOptions.TenantId}/";
```

**Actual behavior**
Failure due to Instance and TenantId not being populated

**Possible Solution**
Change line to use `applicationOptions` instead as this is populated and has the same properties.

```
string authority = $"{applicationOptions.Instance}{applicationOptions.TenantId}/";
```

**Additional context/ Error codes / Screenshots**
I tried to work out what this additional AzureADOptions is used for and it seems it shares a lot of the same properties as the AzureAD. I don't understand why there's a need to have yet another config when the 'standard' one would handle most of what's needed. I dont want to have to duplicate config values. I think this additional config should be dropped because at best its confusing.

It is possible I've just misread what this is doing...

**Comment by TiagoBrenck** [comment]
Hi @dotnetprofessional,

I didn't understand the bug. If you check all the samples in this tutorial, you wont find any duplicated config. The `appsettings.json` has just one section called "AzureAd", which contains the configurations needed. `AzureADOptions` is just the class name. 

Note that we are using "AzureAd" as the default section name, on `AddMicrosoftIdentityPlatformAuthentication()`, but you can pass another name If you want. 

Does that answer your question?

**Comment by jmprieur** [comment]
@dotnetprofessional did you get the latest version of the code? I cannot repro your issue?

**Comment by dotnetprofessional** [comment]
So I'll admit I'm not using the sample directly, but from my code base and there maybe an issue there. Here's what I"m seeing:

![image](https://user-images.githubusercontent.com/5588330/65063697-a23d5a00-d933-11e9-9239-32421c7a69c6.png)

vs
![image](https://user-images.githubusercontent.com/5588330/65063762-bed99200-d933-11e9-9107-87af7eb31a25.png)

With regards to: `AzureADOptions` I see you're providing a custom binding, not letting .Net do it for you. However I only see this in the `AddMicrosoftIdentityPlatformAuthentication` method which wasn't part of my call path. Adding it in does resolve that issue.

The reason it wasn't in my call path was because I was following docs for [Web APIs](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/Microsoft.Identity.Web/README.md#protected-web-apis-that-call-downstream-apis-on-behalf-of-a-user---startupcs) which doesn't include a call to this method.

```
   services.AddProtectedWebApi(Configuration)
           .AddProtectedApiCallsWebApis()
           .AddInMemoryTokenCaches();
   ...
```
So I've now changed my code to be:

```
services.AddMicrosoftIdentityPlatformAuthentication(Configuration)
        .AddProtectedWebApi(Configuration)
        .AddProtectedApiCallsWebApis(Configuration, new[] { Constants.ScopeImpersonate }) 
        .AddInMemoryTokenCaches();
```
So not sure if this is a documentation bug or a code one, depending on if this call is required for my scenario, which is to call downstream services onBehalf of the caller. I don't want them to 'sign in' as that's already happened and I receive a bearer token. I still can't get this to work due to a `AADSTS65001` error but that's a separate issue.

* Yes I'm using the latest code from yesterday

**Comment by TiagoBrenck** [comment]
Oh, do you mean that instead of having this code,
```
string authority = $"{azureAdOptions.Instance}{azureAdOptions.TenantId}/";
```

we could have:
```
string authority = $"{applicationOptions.Instance}{applicationOptions.TenantId}/";
```

Removing the need of `var azureAdOptions = _azureAdOptions;` on `BuildConfidentialClientApplication()`?

**Comment by dotnetprofessional** [comment]
Yes - that was my original proposed fix.

**Comment by TiagoBrenck** [comment]
Sorry for taking some time to understand your point. I have opened a PR(https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/pull/188) with your suggestion.

Thank you.

**Comment by jmprieur** [comment]
Thanks @dotnetprofessional : I think you make a good point
Thanks  @TiagoBrenck for proposing the PR

**Comment by dotnetprofessional** [comment]
Thanks for the quick turnaround...

**Comment by karllarssonusawest** [comment]
I have the opposite problem. My code has this line:

`string authority = $"{applicationOptions.Instance}{applicationOptions.TenantId}/";`

But the instance and tenant ID are null, so it fails.

The original versions seems to work:

`string authority = $"{azureAdOptions.Instance}{azureAdOptions.TenantId}/";`

**Comment by TiagoBrenck** [comment]
@karllarssonusawest  We had some changes in the couple of months, so I believe your code might not have the latest changes. To solve your case, please check if you have this line in `AddMsal()` method (it is inside WebAppServiceCollectionExtensions.cs):
```c#
services.Configure<ConfidentialClientApplicationOptions>(options => configuration.Bind(configSectionName, options));
```

**Comment by karllarssonusawest** [comment]
I do, yes, but you helped me solve the problem. Whatever sample I'd been following had specified a custom config section in this line:

`.AddProtectedApiCallsWebApis(Configuration)`

I removed that, and it picked up the default AzureAD one, and all was well.

Thanks for your prompt and helpful response.
