### ISSUE TITLE
Cookie being used as the Cache for Everyone

### ISSUE THREAD

**Issue by jasonkenneth** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#19]
### This issue is for a:
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1. checkout the aspnetcore2-2-signInAndCallGraph branch
2. perform necessary app registration steps
3. deploy to an IIS host
4. login with >= 2 people AzureAD users, the app stops working and/or we get a "400 error: Headers too large" on the client.
 
### Any log messages given by the failure
>

### Expected/desired behavior

* app works no matter how many people login
* the cookie size does not increase based on the number of people logged in

### OS and Version?

Windows 10 / Azure App Service (as of 11/12/2018)
.NET Core 2.1.403

### Versions

aspnetcore2-2-signInAndCallGraph (as of 11/12/2018)

### Mention any other details that might be useful
Decoding the cookie and printing it on the web browser console, it looks like the server is accidentally using the cookie as the store for the TokenCache. For example, when the second person logs in, and I decode their cookie, I find both users' latest tokens in the JSON graph in the cookie.

Furthermore, when this happens, and the cookies in the header are not too large, IIS seems to see that something is amiss and will not serve the page and not give an error. (Are the cookies being encrypted or tracked with infor from the current user?)

Kestrel, however, will serve the page.

**Comment by jmprieur** [comment]
@jasonkenneth : When you say everyone, you mean every identity using the **same browser**, not several users using the app with a different browser / machine.
But you make a good point that the cookie can become big with several identities (still same user). 

Would providing a cache implementation with the session storage or local storage be better? what would you prefer to have?

**Comment by jmprieur** [comment]
@jasonkenneth 
we've replaced the cookie cache by a session cache. Please confirm this works for you now.
