### ISSUE TITLE
The AutoProvisioning scripts seem to only update Enterprise Applications, not App Registrations

### ISSUE THREAD

**Issue by RedBlue1776** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#193]
Are the scripts using the 1.0 endpoint?

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. [ ] Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

The issue is with Step 4 (which doesn't seem to be listed in this issues template)

**Expected behavior**
Running the auto provision script should create a 2.0 endpoint that should also appear in App Registrations.  

**Actual behavior**
The app registrations tab in AD is blank, however the application is registered in Enterprise Applications

**Possible Solution**
Upgrade the script to use MSAL/2.0 endpoints?

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 
   
### OS and Version?
Windows 10

**Comment by TiagoBrenck** [comment]
Hi,
The scripts doesn't register only Enterprise Applications (which technically is called Service Principle). It actually has to create the application first to then create the Service Principle. 

Are you signing-in on Azure Portal with the same user (from the same tenant) that you signed in when you executed the scripts?

Have you checked on App Registration page, under "All applications" tab?

**Comment by jmprieur** [comment]
Also an app is an app (there is no v1.0 and v2.0 applications)
but the scripts create applications with the audience "My Org" or "Any Org" because Azure AD PowerShell cannot create apps with the "AAD + MSA" audience. But this is coming soon.

**Comment by jmprieur** [comment]
@RedBlue1776 : if you still have the issue, can you provide detailed repro steps?
