### ISSUE TITLE
Microsoft.Identity.Web - WebApiServiceCollectionExtensions - AddProtectedWebApi

### ISSUE THREAD

**Issue by conkman** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#196]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. [ ] Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [x ] Other (please describe)
- I need to augment the current ClaimsPrincipal by adding claims to it using data from a call to the Microsoft Graph Api.  Currently it does not look like the Microsoft.Identity.Web project provides any sort of hooks into the JwtBearerEvents.  I am creating this to get help in either finding how this can be done with the current library already or to help me with a path forward.

Currently in the start up of my WebApi project I am using the extension method:
`Microsoft.Identity.Web.WebApiServiceCollectionExtensions.AddProtectedWebApi`
### Repro-ing the issue
NA
**Repro steps**
NA

**Expected behavior**
I would like a way to have the JwtBearerEvents exposed to allow for custom code to be executed in these different events.

**Actual behavior**
NA
**Possible Solution**
NA

**Comment by TiagoBrenck** [comment]
@conkman You might want to use this logic on your `Startup.cs`:

```csharp
services.Configure<JwtBearerOptions>(AzureADDefaults.JwtBearerAuthenticationScheme, options => 
{
  var existingEventHandler = options.Events.<EventThatYouNeedToIncrement>;
  options.Events.<EventThatYouNeedToIncrement>= async context =>
  {
       await existingEventHandler (context);

       //custom code
      
  }    
}
```

Let me know if this does not attend your needs.

**Comment by conkman** [comment]
Won't this overwrite whats currently being done in the Library at WebApiServiceCollectionExtensions.AddProtectedWebApi?  I am calling this extension in the startup already.

**Comment by conkman** [comment]
> @conkman You might want to use this logic on your `Startup.cs`:
> 
> ```cs
> services.Configure<JwtBearerOptions>(AzureADDefaults.JwtBearerAuthenticationScheme, options => 
> {
>   var existingEventHandler = options.Events.<EventThatYouNeedToIncrement>;
>   options.Events.<EventThatYouNeedToIncrement>= async context =>
>   {
>        await existingEventHandler (context);
> 
>        //custom code
>       
>   }    
> }
> ```
> 
> Let me know if this does not attend your needs.

@TiagoBrenck won't this overwrite whats currently being done in the Microsoft.Identity.Web Library at WebApiServiceCollectionExtensions.AddProtectedWebApi? I am calling this extension in the startup already.

**Comment by TiagoBrenck** [comment]
No, it wont overwrite. Lets take for example the method `AddProtectedWebApi`. If you check the code inside it, you have this event setup:

```
options.Events.OnTokenValidated = async context =>
{
    // This check is required to ensure that the Web API only accepts tokens from tenants where it has been consented and provisioned.
    if (!context.Principal.Claims.Any(x => x.Type == ClaimConstants.Scope)
    && !context.Principal.Claims.Any(y => y.Type == ClaimConstants.Scp)
    && !context.Principal.Claims.Any(y => y.Type == ClaimConstants.Roles))
    {
         throw new UnauthorizedAccessException("Neither scope or roles claim was found in the bearer token.");
    }

    await Task.FromResult(0);
};
```

Lets say you want to augment the current `ClaimsPrincipal` by adding claims to it, and you have to do it on `OnTokenValidated `, however you don't want to lose this `UnauthorizedAccessException` check existing in the event. To do so, on your `Startup.cs` you would have:

```
services.AddProtectedWebApi(Configuration);
services.Configure<JwtBearerOptions>(AzureADDefaults.JwtBearerAuthenticationScheme, options => 
{
  var existingOnTokenValidatedHandler = options.Events.OnTokenValidated ;
  options.Events.OnTokenValidated = async context =>
  {
       await existingOnTokenValidatedHandler(context);
      // your code to add extra claims that will be executed after the current event implementation.
  }    
}

```

**Comment by conkman** [comment]
@TiagoBrenck your the man!  Sorry I didn't read your code closer.  I see now what you are referring too.  This works and will accomplish what I am looking for.  Thanks again!

**Comment by jmprieur** [comment]
Thanks @TiagoBrenck 
@TiagoBrenck @kalyankrishna1 @conkman @jennyf19 @bgavrilMS I've documented this use case in the README.md for Microsoft.Identity.Web (as this is the second time we have the question)

https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/Microsoft.Identity.Web/README.md#more-customizations

**Comment by BeenaCelin** [comment]
How to validate audience and scope in startup.cs file. I know the validation is happening inside AppProtectedWebApi - Microsoft.Identity.Web.WebApiServiceCollectionExtensions.AddProtectedWebApi
But i want to explicitly validate Audience and scope before this.

**Comment by jmprieur** [comment]
@BeenaCelin : to validate the audience, just set it in the appsettings.json file (there is an option named Audience).

Alternatively you might want to hard code it (I would not)

```CSharp
services.AddProtectedWebApi(Configuration);
services.Configure<JwtBearerOptions>(AzureADDefaults.JwtBearerAuthenticationScheme, options =>
            {
                // The valid audiences are both the Client ID (options.Audience) and api://{ClientID}
                options.TokenValidationParameters.ValidAudiences = new string[]
                {
                   "the hardcoded audience you want"
                };
```

For the scope, we recommend you validate it on the controller (as it can be different for different controller actions), 

See https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/1e97054a90249c3ae4f5a3174b1ed41b48d9b80f/2.%20Web%20API%20now%20calls%20Microsoft%20Graph/TodoListService/Controllers/TodoListController.cs#L51: 

```CSharp
            HttpContext.VerifyUserHasAnyAcceptedScope(scopeRequiredByApi);
```

You** should not validate it before you know the token is validated** (as it might be wrong)

**Comment by BeenaCelin** [comment]
@jmprieur Agree. Thanks for the details.

**Comment by udlose** [comment]
> No, it wont overwrite. Lets take for example the method `AddProtectedWebApi`. If you check the code inside it, you have this event setup:
> 
> ```
> options.Events.OnTokenValidated = async context =>
> {
>     // This check is required to ensure that the Web API only accepts tokens from tenants where it has been consented and provisioned.
>     if (!context.Principal.Claims.Any(x => x.Type == ClaimConstants.Scope)
>     && !context.Principal.Claims.Any(y => y.Type == ClaimConstants.Scp)
>     && !context.Principal.Claims.Any(y => y.Type == ClaimConstants.Roles))
>     {
>          throw new UnauthorizedAccessException("Neither scope or roles claim was found in the bearer token.");
>     }
> 
>     await Task.FromResult(0);
> };
> ```

@jmprieur , @TiagoBrenck 
I have tried using this check but I'm not getting success - it fails and throws the `UnauthorizedAccessException`.  Here are the Claims I'm getting back.  What am I missing?

1. aud
2. iss
3. iat
4. nbf
5. exp
6. aio
7. http://schemas.microsoft.com/claims/authnmethodsreferences
8. http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname:
9. http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname
10. ipaddr
11. name
12. nonce
13. http://schemas.microsoft.com/identity/claims/objectidentifier
14: onprem_sid
15. http://schemas.microsoft.com/ws/2008/06/identity/claims/role
16: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier
17. http://schemas.microsoft.com/identity/claims/tenantid
18. http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name
19. http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn
20. uti
21. ver: 1.0

**Comment by udlose** [comment]
@jmprieur , @TiagoBrenck  bump

**Comment by TiagoBrenck** [comment]
@udlose sorry I was on vacation. It looks like your app uses an older JWT claims mapping, so the correspondent claim for role is `http://schemas.microsoft.com/ws/2008/06/identity/claims/role`.

So in your case, the role check should be:

```
 && !context.Principal.Claims.Any(y => y.Type == "http://schemas.microsoft.com/ws/2008/06/identity/claims/role"))
```

If you want to change the claims mapping, place this line in your `ConfigureServices(IServiceCollection services)` at `Startup.cs`:

```
JwtSecurityTokenHandler.DefaultMapInboundClaims = false;
```

**Comment by udlose** [comment]
@TiagoBrenck  thank you for your prompt reply :)

> It looks like your app uses an older JWT claims mapping
I'm using the sample from Microsoft.Identity.Web for Auth via AzureAD (unfortunately, this code is not available as a Nuget yet).  Where is this configured?

> If you want to change the claims mapping, place this line in your ConfigureServices(IServiceCollection services) at Startup.cs
What are the ramifications of doing this?

Also, I assume that I have 2 options:
1. to either change the role check as you mention OR
2. change the claims mapping as you mention

Is that correct? TIA

How do I use the newest JWT claims mapping?

**Comment by TiagoBrenck** [comment]
Answering your questions by its numbers:

1. If you check the `ver` claims of your token, it says v.1. I believe these claims names are the default for v1 tokens. 
1. What do you mean about "ramifications"?
1. You could also change token version to v2 on AzurePortal. This can be done by editing the app manifest: `"accessTokenAcceptedVersion": 2,`. The other solution is from our side to include the older role claim name in the check (as we do for scope). For this one I will discuss with the engineers.
1. @jmprieur @kalyankrishna1 could you help me answering this one?
1. We have these three checks because we wanted the code to be quite generic and work for samples that use scope and roles. What we are basically doing is a security check that validates that the client app is known to the web api app (when the api is a multi-tenant). In the current stage, what I would do is add a new `ClaimConstants` for the older role name and have this block of code:

```
if (!context.Principal.Claims.Any(x => x.Type == ClaimConstants.Scope)
                        && !context.Principal.Claims.Any(y => y.Type == ClaimConstants.Scp)
                        && !context.Principal.Claims.Any(y => y.Type == ClaimConstants.Roles)
                        && !context.Principal.Claims.Any(y => y.Type == ClaimConstants.SamlRoles))
```

**Comment by jmprieur** [comment]
@TiagoBrenck : I think that the code should be more robust and accept both set of claims. Also the claims mapping could be partial. 

Also this code will change in the future as we introduce more hierarchical ways of defining scopes / roles for the application, the controller and the controller action.

**Comment by udlose** [comment]
@jmprieur , @TiagoBrenck  

> Also this code will change in the future as we introduce more hierarchical ways of defining scopes / roles for the application, the controller and the controller action.

This is one of the most important reasons that we need to have this kind of implementation provided as a Nuget package.  This *should* be nothing more than a black-box to application developers that we plugin to to get this functionality.  Crafting it ourselves and having to maintain this just doesn't make sense as a long-term strategy.  I'm aware of the efforts to have this exposed as a nuget via Microsoft.Identity.Web package but I just want to highlight the reason and need from our side of the table - i.e. being the consumer of this functionality.  If you concentrate on making this as *easy and effortless* as possible to consume, it will be most greatly appreciated.

**Comment by jmprieur** [comment]
@udlose : thanks for the feedback. We do really understand the need for the NuGet package and are working on providing a solution to make your life easy
cc: @henrik-me @jennyf19 @bgavrilMS

**Comment by dancundy** [comment]
This thread saved me from a lot of headache. I also agree this needs to be wrapped up into a Nuget package. Thanks to the @jmprieur for his help though.

**Comment by CodeguruEdison** [comment]
I have the same issue, It is not working asp.net core 3.1, I would like to additional check if a user exists on application database. here is sample code i am using, but it is not working, can anyone help us on this.

` services.AddProtectedWebApi(Configuration);
            services.Configure<JwtBearerOptions>(AzureADDefaults.JwtBearerAuthenticationScheme, options =>
            {
                var existingOnTokenValidatedHandler = options.Events.OnTokenValidated;
                options.Events.OnTokenValidated = async context =>
                {
                    await existingOnTokenValidatedHandler(context);
                    context.Fail("user not avilable in database");
                    // your code to add extra claims that will be executed after the current event implementation.
                };
            });`

**Comment by TiagoBrenck** [comment]
@CodeguruEdison `Microsoft.Identity.Web` has become a nuget package and your code is not in sync with its version. Could you please update your code to use the nuget package?

Then your custom code would probably look like:

```c#
...
// Microsoft.Identity.Web methods
...
// Your customization
service.Configure<JwtBearerOptions>(options => 
{
    options.Events.OnTokenValidated = async context => //your code
});
```

**Comment by TiagoBrenck** [comment]
What error are you getting?

**Comment by TiagoBrenck** [comment]
Ops my bad. I missed one item:

```c#
            services.AddProtectedWebApi(options => 
            {
                Configuration.Bind("AzureAd", options);
                options.Events.OnTokenValidated = // your code;
            }, options => 
            {
                Configuration.Bind("AzureAd", options);
            });
```

**Comment by CodeguruEdison** [comment]
@TiagoBrenck 
options. Events are coming null now.

**Comment by TiagoBrenck** [comment]
Sorry @CodeguruEdison I dont have a fully testing scenario for your case. I edited my code snippet again. Hopefully it works.

Thanks

**Comment by CodeguruEdison** [comment]
![SSO_ERROR](https://user-images.githubusercontent.com/10437792/83670416-20fd2480-a5a1-11ea-8294-76ffec5fa3c7.PNG)

@TiagoBrenck  you can see the image, is anything we need to do in appsetting.json

**Comment by TiagoBrenck** [comment]
@CodeguruEdison I updated my code snippet.

Your solution should be like this sample: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-1-MyOrg but adding the code snippet in the web api startup.

Please follow the sample configuration so you can learn what should go in the appsettings.json (you can bind any property from JwtBearerOptions, or OpenIdConnectOptions for web apps).

**Comment by CodeguruEdison** [comment]
@TiagoBrenck 
it worked. Thank you :). Looks like samples are not updated yet.

**Comment by TiagoBrenck** [comment]
@CodeguruEdison  I am glad it worked. The samples are updated, as far as I know.

Do you have the latest master branch?
What updates are you missing?

**Comment by CodeguruEdison** [comment]
@TiagoBrenck 

if you see line#34 on https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/4-WebApp-your-API/4-1-MyOrg/TodoListService/Startup.cs . We should put a comment for custom validation.

**Comment by jwahr** [comment]
Hi!

I am having issues with `VerifyUserHasAnyAcceptedScope` validating my accessToken with the scopes.

When I use the default `HttpContext.VerifyUserHasAnyAcceptedScope(scopeRequiredByApi)`, it gives me an error of `System.Net.Http.HttpRequestException: The 'scope' claim does not contain scopes 'access_as_user' or was not found
   at Microsoft.Identity.Web.Resource.ScopesRequiredHttpContextExtensions.VerifyUserHasAnyAcceptedScope(HttpContext context, String[] acceptedScopes)`.

But my scopes are there, verified with https://jwt.ms.

But when I take that method from here - https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-verification-scope-app-roles#verify-scopes-in-apis-called-on-behalf-of-users and put it into my own code and replace `.FindFirst("http://schemas.microsoft.com/identity/claims/scope")` with `.FindFirst("scp")` and it works.

Am I doing this wrong? I wish there was another parameter in that function to define the claim type so I don't have to create my own function.

Thanks!

**Comment by TiagoBrenck** [comment]
@jwahr Could you update your Microsoft.Identity.Web version please? They have just fixed this issue.

**Comment by jwahr** [comment]
@TiagoBrenck thanks a bunch! Great this is fixed 😃 

https://github.com/AzureAD/microsoft-identity-web/compare/0.1.4-preview...0.1.5-preview#diff-7d8f6a372000d8d43a1e5d473acbf323

**Comment by ahmedsza** [comment]
Has a similar issue and thanks for the pointer to update Microsoft.Identity.Web.. Thanks @TiagoBrenck

**Comment by tbrophy** [comment]
@TiagoBrenck, 

_Is there a way to disable scope and roles claims decoratively in appsettings.json?_  

The Use Case involves a client that does not provide either scope or role claims in a Bearer token.

If there is **_not_** a way to turn off scope and claims via appsettings.json, can you please suggest a programmatic alternative?

Thanks in Advance!
mr.T


Here is what I have **tried so far** (BTW; total .NET newbie here)...

Replacing (master branch) https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/d52951f3006c51a1470690b2a716d10c0f24705a/4-WebApp-your-API/4-1-MyOrg/TodoListService/Startup.cs#L34 with...

```
            services.AddProtectedWebApi(options =>
            {
                Configuration.Bind("AzureAd", options);
                options.Events = new JwtBearerEvents();
                options.Events.OnTokenValidated = context =>
                {
                    return Task.CompletedTask;
                };
            }, options =>
            {
                Configuration.Bind("AzureAd", options);
            });
```

...shows the same error output in the console as the version of Startup.cs without the modification...

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:44351/  
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[2]
      Successfully validated the token.
fail: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[3]
      Exception occurred while processing message.
System.UnauthorizedAccessException: Neither scope or roles claim was found in the bearer token.
   at Microsoft.Identity.Web.WebApiAuthenticationBuilderExtensions.<>c__DisplayClass1_1.<<AddProtectedWebApi>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.UnauthorizedAccessException: Neither scope or roles claim was found in the bearer token.
   at Microsoft.Identity.Web.WebApiAuthenticationBuilderExtensions.<>c__DisplayClass1_1.<<AddProtectedWebApi>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 1006.9329ms 500 text/plain
```

**Comment by udlose** [comment]
@tbrophy this question should be in a separate Issue

**Comment by super-jb** [comment]
Has this ever been solved? Running into the same problem
Microsoft.Identity.Web v1.8.2
.NET 5.0

**Comment by tbrophy** [comment]
Here is what I did in the Startup class inside of Program.cs.

There might be better ways to do this now.

```
        // This is called from  public virtual void ConfigureServices(IServiceCollection services)
        // Configuration is injected in the Startup class constructor public Startup(IConfiguration configuration)
        protected virtual void ConfigureAuth(IServiceCollection services)
        {
            // https://github.com/AzureAD/microsoft-identity-web/wiki/Migrating-from-0.1.x-to-0.2.x
            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddMicrosoftWebApi(Configuration);    

            services.Configure<JwtBearerOptions>(JwtBearerDefaults.AuthenticationScheme, options =>
            {
                options.Events.OnTokenValidated = async context =>
                {
                     // whatever you want here, if anything
                };
            });
        }
```
