### ISSUE TITLE
Microsoft.Identity.Web - OnTokenValidated - TokenAcquisition

### ISSUE THREAD

**Issue by conkman** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#197]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. [ ] Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [X ] Other (please describe)
I am trying to call the Microsoft Graph API in the OnTokenValidated event using the TokenAcquistion class to obtain an Access Token on behalf of the user.  But I am realizing this has a dependency on the IHttpContextAccessor.  Unfortunately the user has not been set on the HttpContext at this point in the life cycle.  Is there a recommendation on what to do in this scenario?

### Repro-ing the issue

**Repro steps**

**Expected behavior**

**Actual behavior**

**Possible Solution**

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
> of ASP.NET Core, of MSAL.NET

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue?
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)
  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@conkman ; a controller action will be hit first? would it make sense to call the Microsoft Graph API in the controller action?

Otherwise, let me have a look.

**Comment by TiagoBrenck** [comment]
@conkman would you prefer to have this claim already mapped on the JWT token instead? If so, you can read about it here: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-claims-mapping. For your case, you are looking into the onpremisessamaccountname value.

You will need to change your app manifest file, and set `acceptMappedClaims: true`. Then you will create the custom policy mapping (can only be done via powershell) with this:

```
# First uninstall existing Azure AD PS module using
# UnInstall-Module AzureAD #-Force

# then install the AzureADPreview module
# Install-Module AzureADPreview

# sign -in
Connect-AzureAD -Confirm

# get existing policies and test if you have the correct AzureADPreview module
Get-AzureADPolicy

# create a new claims mapping policy for onpremisessamaccountname
New-AzureADPolicy -Definition @('{"ClaimsMappingPolicy":{"Version":1,"IncludeBasicClaimSet":"true", "ClaimsSchema": [{"Source":"user","ID":"onpremisessamaccountname","SamlClaimType":"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/onpremisessamaccountname","JwtClaimType":"onpremisessamaccountname"}]}}') -DisplayName "SamAccountNameExtraClaims" -Type "ClaimsMappingPolicy"

# verify it got created and save its ID
Get-AzureADPolicy

#apply policy to the service principal
Add-AzureADServicePrincipalPolicy -Id <yourServicePrincipleId> -RefObjectId <createdPolicyId>
```

Now, your token will have this claim filled if the user has it set.

**Comment by conkman** [comment]
@TiagoBrenck what do we set for the service principle id?  Is that an Id I can find on our App Registration?

**Comment by TiagoBrenck** [comment]
No. You grab the ServicePrincipleId by clicking on the highlighted link below. You can find this screen at your AppRegistration Overview tab.
![print](https://user-images.githubusercontent.com/16087102/67528225-cb0ce980-f66d-11e9-9c6b-9e6e5e47a5b8.png)

Once you click it, copy the ObjectId from that screen.

**Comment by conkman** [comment]
@TiagoBrenck we applied this to the App Registration and now I am getting this error back from the swagger page of the API while attempting to Authenticate.  Any idea why this would be happening now?

`Auth Error{"error":"invalid_request","error_description":"AADSTS50146:+This+application+is+required+to+be+configured+with+an+application-specific+signing+key.\r\nTrace+ID:+49a7b471-b45b-4ff5-9b0c-507e8450a300\r\nCorrelation+ID:+e5fb1dbc-728a-47d7-95d2-de281c0a3042\r\nTimestamp:+2019-10-25+14:30:12Z","error_uri":"https://login.microsoftonline.com/error?code=50146","state":"RnJpIE9jdCAyNSAyMDE5IDEwOjMwOjEyIEdNVC0wNDAwIChFYXN0ZXJuIERheWxpZ2h0IFRpbWUp"}`

![image](https://user-images.githubusercontent.com/5832004/67579700-fdbced80-f712-11e9-8dad-5ddab4118643.png)

**Comment by conkman** [comment]
> @TiagoBrenck we applied this to the App Registration and now I am getting this error back from the swagger page of the API while attempting to Authenticate. Any idea why this would be happening now?
> 
> `Auth Error{"error":"invalid_request","error_description":"AADSTS50146:+This+application+is+required+to+be+configured+with+an+application-specific+signing+key.\r\nTrace+ID:+49a7b471-b45b-4ff5-9b0c-507e8450a300\r\nCorrelation+ID:+e5fb1dbc-728a-47d7-95d2-de281c0a3042\r\nTimestamp:+2019-10-25+14:30:12Z","error_uri":"https://login.microsoftonline.com/error?code=50146","state":"RnJpIE9jdCAyNSAyMDE5IDEwOjMwOjEyIEdNVC0wNDAwIChFYXN0ZXJuIERheWxpZ2h0IFRpbWUp"}`
> 
> ![image](https://user-images.githubusercontent.com/5832004/67579700-fdbced80-f712-11e9-8dad-5ddab4118643.png)

Alright this is fixed now we did not update the acceptMappedClaims in the manifest for the App Registration to the value of:

`true`

**Comment by conkman** [comment]
This is confirmed to be working!  Thanks again for your help @TiagoBrenck and @jmprieur

**Comment by TiagoBrenck** [comment]
Awesome! I am glad I could help. For any extra claim that you need, check [this table](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-claims-mapping#table-3-valid-id-values-per-source) to get the corresponding ID and Source.
