### ISSUE TITLE
AADSTS50011: The reply url specified in the request does not match the reply urls

### ISSUE THREAD

**Issue by AaronNesbitt** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#20]
### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Following steps in 
https://azure.microsoft.com/en-gb/resources/samples/active-directory-dotnet-webapp-openidconnect-aspnetcore/

Download active-directory-dotnet-webapp-openidconnect-aspnetcore
Change Domain,TenantId & ClientId in appsettings.json
Run application = Works

Download active-directory-aspnetcore-webapp-openidconnect-v2-aspnetcore2-2 
Change Domain,TenantId & ClientId in appsettings.json
Run application = Fails

### Any log messages given by the failure
>
Sign in
Sorry, but we’re having trouble signing you in.

AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: '9999999-9999-9999-9999-999999999999'.

**Comment by jmprieur** [comment]
Sorry, I don't understand your question. you want to follow the steps for a v1 sample (which home URL is http://localhost:5000/) and expect, with the same app registration that the v2.0 sample works? 

Did you see in https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#register-your-app that you need to add the following in the app registration:
- In the **Redirect URIs**, add a redirect URL of type Web and valued https://localhost:44321/signin-oidc
- In the Advanced settings section set **Logout URL** to https://localhost:44321/signout-oidc

**Comment by AaronNesbitt** [comment]
Thank you 
(Never underestimate the value of scrolling down on GitHub)

Working now as intended
