### ISSUE TITLE
Need simple sample to login and show name and photo in top bar

### ISSUE THREAD

**Issue by pmeems** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#204]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [X] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**
I'm new to Core and Identity Platform and have tried all samples included in this repo.
They all do part of what I need but I can't get them to work together.

**Expected behavior**

A simple sample doing:
1. Login using MyOrg
2.  Not only show login name in top bar but show full name and profile photo (using MS Graph)
3. Show how to get groups/claims of the user to for example know if he is part of the 'AppAdmin'-group
4. Show how to make sure users that get deleted or are no longer allowed to login can't use the app anymore. The current behavior of all sample is that when a user is logged in never is checked if he is still allowed. Not even after closing browser window and stop+start IIS Express.

**Actual behavior**
Login is no problem. When deleting a user the user can keep logging in on the same laptop: https://stackoverflow.com/questions/58833240/user-stays-logged-in-after-deleting-from-azure-ad
Unclear how to get the groups/claims or show the profile photo in the top bar.

**Possible Solution**

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
> of ASP.NET Core, of MSAL.NET

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue? Yes
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview) Yes
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview) Yes
  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by TiagoBrenck** [comment]
Hi @pmeems,

First of all, thanks for using this tutorial as a learning tool. About your questions:

1. _Login using MyOrg_ (you said that this part is ok, so lets check-it)
2. _Not only show login name in top bar but show full name and profile photo (using MS Graph)_ ([Please check this sample and go to Profile action on HomeController](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/2-WebApp-graph-user/2-1-Call-MSGraph))
3. _Show how to get groups/claims of the user to for example know if he is part of the 'AppAdmin'-group_([This sample](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/5-WebApp-AuthZ/5-2-Groups) is about groups. Please read the Readme carefully since it has mandatory steps that enables groups on your tokens)
4. _Show how to make sure users that get deleted or are no longer allowed to login can't use the app anymore. The current behavior of all sample is that when a user is logged in never is checked if he is still allowed. Not even after closing browser window and stop+start IIS Express._ (The [StackOverflow answer](https://stackoverflow.com/questions/58833240/user-stays-logged-in-after-deleting-from-azure-ad) explains what you are experiencing. It is about token, caching and session lifetime. But AAD will never issue a new token for a deleted user.)

Please, let us know with more details what steps are blocking you, or error messages or code examples.

**Comment by pmeems** [comment]
Thanks @TiagoBrenck for your quick reply. I managed to get the profile picture in my top bar using a View Component (see my question at [SO](https://stackoverflow.com/questions/58855518/upgrading-netv4-7-application-to-net-core-v3-and-identity-platform) ). Not sure if that is the best approach.

I still have problems with the cookie lifetime. It is still never refreshed. I've updated my [SO Question](https://stackoverflow.com/questions/58833240/user-stays-logged-in-after-deleting-from-azure-ad/)

And I still think new users like me would benefit most with a real-live example. For example a simple forum, where users log in using MS Identity Platform. After log-in, the name and profile photo of the user is shown in the top bar. A user can post, edit and delete its own post, but a user from the 'Admin' group can edit and delete all users. Of course every hour/day the user is re-authenticated to check if he is still allowed and to check if he's added or removed from groups.
This example would combine all workflows and examples found here and on other places and would be a could starting point.

**Comment by jmprieur** [comment]
@pmeems : thanks for your interest in this sample.
There are a lot of directions in which we could make the tutorial evolve. We'll definitively think of your requirements but there is a trade-off between the simplicity of the incremental chapters (as a learning tool), and a complete sample that would do all what you want, but that might not be that someone else want to have.
If you want to share your code, we'd be happy to provide  a link to it, though.
