### ISSUE TITLE
Cannot get user IP when using AAD

### ISSUE THREAD

**Issue by KirteeM** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#207]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [x] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [x] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [x] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [x] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**
I have followed the documentation at https://docs.microsoft.com/en-gb/azure/active-directory/develop/tutorial-v2-asp-webapp#add-a-controller-to-handle-sign-in-and-sign-out-requests to create a web app and deployed successfully to Azure.
My web app needs to track logged in users' IP addresses for auditing purposes.
I have used the following code to get the IP:
```
        private string GetIp()
        {
            string ip = System.Web.HttpContext.Current.Request.ServerVariables["HTTP_X_FORWARDED_FOR"];
            if (string.IsNullOrEmpty(ip))
            {
                ip = System.Web.HttpContext.Current.Request.ServerVariables["REMOTE_ADDR"];
            }
            return ip;
        }
```
This works on my local machine **but when deployed to Azure, the app cannot sign me in**.

I have also tried to call external apis like https://ip-api.io/json/ and http://checkip.dyndns.org/ using the code below:
 ```
 WebClient client = new WebClient();
        string jsonstring = client.DownloadString(url);
        return jsonstring;

```

These code get called in the Index method of the HomeController.

**Expected behavior**
The web app when deployed to Azure should be able to sign me in and get the my ip address.

**Actual behavior**
When running the web app, I get the Microsoft screen to enter my email address and password but then get the error message "We couldn't sign you in. Please try again." 

**Possible Solution**

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
> of ASP.NET MVC 4.5

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue?
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)
  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by TiagoBrenck** [comment]
Hi @KirteeM, would [fwd optional claims](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims) works better for you? The `fwd` claims holds the client IP.

**Comment by KirteeM** [comment]
Hello @TiagoBrenck ,

We will try that and let you know of the outcome. 

Thanks and Regards
Kirtee

**Comment by KirteeM** [comment]
Hello @TiagoBrenck ,

I have added the following in the manifest and I still don't get the Ip address:
	"optionalClaims": {
		"idToken": [],
		"accessToken": [
			{
				"name": "fwd",
				"source": null,
				"essential": false,
				"additionalProperties": []
			}
		],
		"saml2Token": []
	},

Am I missing something?

Thanks and Regards
Kirtee

**Comment by jmprieur** [comment]
@KirteeM if you add claims to an accessToken, you need to edit the manifest of the protected Web API for which this token is mean to be used (if you are its owner).
Did you edit the manifest of the Web app (therefore a client?). In that case you can only have an action on claims for the IDToken

**Comment by KirteeM** [comment]
Thanks @jmprieur ,
that did the trick!

Regards
Kirtee
