### ISSUE TITLE
What cache dictionary key to use for authorization code flow

### ISSUE THREAD

**Issue by MonkeyTennis** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#212]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [x] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

Disclaimer - I am fairly new to MSAL and so some of my repro steps below may be wrong.

This sample app uses the implicit flow (context.ProtocolMessage.ResponseType = OpenIdConnectResponseType.CodeIdToken) and so it is possible to get the signed-in user id on line 109 of AzureAdB2CAuthenticationBuilderExtensions:

string signedInUserID = context.Principal.FindFirst(ClaimTypes.NameIdentifier).Value;

This means MsalStaticCache can be set up before the call to AcquireTokenByAuthorizationCode (i.e. - the BeforeAccessNotification and AfterAccessNotification event handlers are already wired up).

However, we are trying to modify the sample to retrieve the id token using an authorization code (context.ProtocolMessage.ResponseType = OpenIdConnectResponseType.Code). Therefore, the signed-in user is not known before the call to AcquireTokenByAuthorizationCode and so the BeforeAccessNotification and AfterAccessNotification event handlers are not wired up. This means no token cache is stored as a result of the call to AcquireTokenByAuthorizationCode.

It seems therefore that I need to set up MsalStaticCache before the call to AcquireTokenByAuthorizationCode. However, in the absence of a signed-in user at that point, what dictionary key should I use?

Also, the BeforeAccessNotification and AfterAccessNotification event handlers are wired up off the back of a ITokenCacheSerializer instance contained within TokenCacheNotificationArgs. How do I get this to happen before the call to AcquireTokenByAuthorizationCode?

### Any log messages given by the failure

The result of the above is that when I attempt to call a downstream web API, MsalStaticCache contains no entries.

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> Windows 10.

### Versions
> ASP.NET Core v2.2. MSAL.NET v4.7.0

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue?
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)
  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@MonkeyTennis 
the Web apps are not using the implicit flow but the hybrid flow (`OpenIdConnectResponseType.CodeIdToken`). You should not remove IdToken. BTW there is no security concern here. It's more the portal which calls out the IDToken as part of the implicit flow section, but we are going to change this because it's confusing.

You will never get the ID token from the access token acquired with the code. This access token is for the API that your Web app will call, it's not for your Web App. The Web App should by no means try to crack open it. And in some cases (users signing-in with a personal account), you'll find that this token is encrypted

What is your concern with using `OpenIdConnectResponseType.CodeIdToken`. Can you please elaborate?
