### ISSUE TITLE
Client assertion audience does not match Realm issuer with JWT assertion.

### ISSUE THREAD

**Issue by robgarrett** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#213]
Is it possible to use client assertion (JWT payload) instead of a client secret in the authorization code grant, with a Microsoft Personal Account?

I've tried the flow manually (outside of MSAL framework) using the COMMON endpoint as the JWT audience and get an error "client assertion audience does not match Realm issuer".

Curious if anyone has this working.

**Comment by sujayvsarma** [comment]
How are you constructing / acquiring the client assertion JWT?

**Comment by jennyf19** [comment]
issue tracked in microsoft identity web repo: https://github.com/AzureAD/microsoft-identity-web/issues/16
