### ISSUE TITLE
Enable AuthorizeForScopes to be applied to a controller (was Exception thrown: 'Microsoft.Identity.Client.MsalUiRequiredException')

### ISSUE THREAD

**Issue by jasonshave** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#216]
### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [X ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [X ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

1. Start the website in debug mode using VS2019 and observe the execution work correctly when pulling the user's photo from MS Graph.
2. Stop the website.
3. Start the debug session again and observe the call to MS Graph fail.

**Expected behavior**
I would expect the website to retrieve a previously obtained, and stored, token to be used to authenticate to the MS Graph. 

**Actual behavior**
An exception is thrown in Microsoft.Identity.Web when trying to obtain a token:

Message="No account or login hint was passed to the AcquireTokenSilent call."

While executing: 

```
private async Task<string> GetAccessTokenOnBehalfOfUserAsync(
            IConfidentialClientApplication application,
            string accountIdentifier,
            IEnumerable<string> scopes,
            string loginHint,
            string tenant)
```

The code falls into: `IAccount account = await application.GetAccountAsync(accountIdentifier).ConfigureAwait(false);`

Which returns `null`. LoginHint is observed with the user's UPN just fine (from line 383). 

Next, it executes: `var accounts = await application.GetAccountsAsync().ConfigureAwait(false);`

...and falls into `private async Task OnBeforeAccessAsync(TokenCacheNotificationArgs args)`

This appears to try and read a cache of some sort. The `cacheKey` from line 88 in MsalAbstractTokenCacheProvider is populated, but then the following line returns null:
`byte[] tokenCacheBytes = await ReadCacheBytesAsync(cacheKey).ConfigureAwait(false);`

Next, line 399 executes and the `authority` variable is populated with the "login.microsoftonline.com/{tenantID}" value. 

The application throws at line 400 which is: 

```
result = await application
                    .AcquireTokenSilent(scopes.Except(_scopesRequestedByMsalNet), account)
                    .WithAuthority(authority)
                    .ExecuteAsync()
                    .ConfigureAwait(false);
```

**Possible Solution**
I used a previous version which had an attribute class for `[MsalUiRequiredExceptionFilter(Scopes = new[] { ScopeConstants.ScopeUserRead })]` which helped this issue I had previously. With the latest version things have changed quite a bit so I'm not sure if that old attribute extension class is even valid anymore. I did try adding it back to the project and decorated one of my controllers with it but it doesn't seem to help.

If I clear out the browser cache/cookies, I can get authenticated just fine. It's only on the subsequent attempts is when it fails.

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
Windows 10

### Versions
ASP.NET Core 2.2

**Comment by TiagoBrenck** [comment]
Hi @jasonshave, we have renamed `MsalUiRequiredExceptionFilter` to `AuthorizeForScopes`. 

Are you experiencing this bug with the sample's latest version?

**Comment by jasonshave** [comment]
Hey @TiagoBrenck I changed the attribute to what the sample uses and I still get the same error.

**Comment by TiagoBrenck** [comment]
I ve tried to reproduce the error with the current version on `master` branch, and the samples worked fine. Is your local branch updated?

**Comment by jasonshave** [comment]
The demo code appears to work okay as I can stop/restart/run the code over and over without issue. 

In my reported case I've essentially copied the same code into my own project and have been using the previous version without issue until the latest update of this sample to fit my code. The issue appears to be with the following line:

`IAccount account = await application.GetAccountAsync(accountIdentifier).ConfigureAwait(false);`

The first time I start the application/website, that line returns an object. If I stop debugging and start it again, that call returns `null` which causes the error I posted about. 

So is there any guidance on resolving the `GetAccountAsync` method?

**Comment by TiagoBrenck** [comment]
So, the behavior of returning `null` after restarting the app is expected when storing MSAL cache in memory. That is why we added the `MsalUiRequiredExceptionFilter/AuthorizeForScopes` attribute.

In a web scenario OAuth authentication flow, the entry point happens in the openId event `OnAuthorizationCodeReceived`. Here is where MSAL will create the first cache record, after calling `AcquireTokenByAuthorizationCode`. Then, methods like `AcquireTokenSilent` or `application.GetAccountsAsync()` would come to action. 

Having this entry point in mind, when you restart your app, dotnet manages to authenticate you "automatically" due to cookies. For the dotnet perspective, the user is authenticated so it doesn't challenge the authentication flow, thus the event `OnAuthorizationCodeReceived` is not triggered. But since you stored the cache in memory, MSAL at this point is empty so you basically need to trigger authentication flow so it can set MSAL caches.

Does that help?

**Comment by jasonshave** [comment]
That helps explain what's happening.

First, is there a way to prevent .NET Core from saving the credential (i.e. a cookie policy)? I'm curious as this came up in a previous discussion I had with a customer as well. There may be cases where certain sites need to prompt the user for authentication each time they visit the site.

Second, given what I have presently, if we just let dotnet authenticate the user automatically, what would be a practical way of triggering the authentication flow?

**Comment by TiagoBrenck** [comment]
@jmprieur could you help in this one?

**Comment by jasonshave** [comment]
@TiagoBrenck how does the sample app deal with this scenario of a cached token?

**Comment by TiagoBrenck** [comment]
For simplicity, most of our samples use in memory cache, so the `AuthorizeForScopes` attribute solves the restart problem for us.

**Comment by jasonshave** [comment]
@TiagoBrenck thanks for this. Mine is using the same though. 

```
            services.AddMicrosoftIdentityPlatformAuthentication(Configuration)
                .AddMsal(Configuration, new string[] { ScopeConstants.ScopeUserRead })
                .AddInMemoryTokenCaches();
```

Unless I'm missing something?

I'm using the same attribute declaration on my Index page:

`[AuthorizeForScopes(Scopes = new[] { ScopeConstants.ScopeUserRead })]` 

The only difference is that I had to rename my `Constants` static to `ScopeConstants` due to a naming conflict but it resolves no problem.

**Comment by TiagoBrenck** [comment]
The attribute must be on top of the Profile page as well.

**Comment by jmprieur** [comment]
@TiagoBrenck : you mean the `[Authorize]` attribute?

**Comment by TiagoBrenck** [comment]
This: `[AuthorizeForScopes(Scopes = new[] { ScopeConstants.ScopeUserRead })]`

**Comment by jasonshave** [comment]
Is there a way to apply this attribute globally? I'm using ASP.NET Razor pages and there is no 'controller' per se. I noticed you're using the `[Authorize]` attribute on the controller, then using the `[AuthorizeForScopes(Scopes = new[] { ScopeConstants.ScopeUserRead })]` attribute on the method corresponding to the Profile() method for that page.

I cannot apply the `[AuthorizeForScopes(Scopes = new[] { ScopeConstants.ScopeUserRead })]` on a method used in a Razor page.

All my pages require authorization and I'm applying the attribute on the class containing the view code as follows:

```
    [AuthorizeForScopes(Scopes = new[] { ScopeConstants.ScopeUserRead })]
    public class IndexModel : PageModel
    {
       public async Task OnGet()
       {
              ...my call to the graph is in here
       }
    }
```

**Comment by jmprieur** [comment]
@jasonshave : that sounds like a good enhancement.

**Comment by jasonshave** [comment]
@jmprieur, I set up a new class and an event handler to capture the exception in my `GetGraphServiceClient` method call. I can get the event handler to trigger no problem, however I'm wondering what I could call to 'kickstart/boostrap' the re-authentication process?

**Comment by jmprieur** [comment]
@jasonshave : you would need to do like the following: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/c62791909de85fa3342ed564b3427703cf5f3fb5/Microsoft.Identity.Web/AuthorizeForScopesAttribute.cs#L50-L81

the key is to let ASP.NET Core trigger the re-auth by sending a challenge to the user:

```CSharp
context.Result = new ChallengeResult(properties);
```

https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/Microsoft.Identity.Web/AuthorizeForScopesAttribute.cs#L81

**Comment by jasonshave** [comment]
Thanks @jmprieur. I've tried implementing this in several different ways including setting up a custom middleware handler using `IExceptionFilter` and adding it to `Startup.cs` but it simply never triggers when `MsaluiRequiredException` is raised. I could easily be missing something as I've never implemented this type of filter in asp.net core before. If you have any advice I'd be happy to continue working on a solution.

**Comment by jasonshave** [comment]
@jmprieur and @TiagoBrenck I spent a bit more time working through this and have found a solution!

First, the changes involve using an `IExceptionFilter` in ASP.NET Core instead of a `ExceptionFilterAttribute`. This is a key factor in the implementation as you don't need to decorate the methods with the attribute declaration. Instead, the global exception handler will pick up the `MsalUiRequiredException`.

Second, I created a constructor in `AuthorizeForScopesAttribute` so we can pass in the scope array from `Startup.cs` where the filter is established.

Third, the `override` keyword is removed from the `OnException` method as the class now derives from `IExceptionFilter` interface versus an abstract class. In addition to this, since there is no `base` class, the following recursive statement was removed:

`base.OnException(context);`

Last, the filter is implemented in `Startup.cs` as follows:

```
            services.AddMvc(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
                options.Filters.Add(new AuthorizeFilter(policy));
                options.Filters.Add(new AuthorizeForScopesAttribute(new string[] { ScopeConstants.ScopeUserRead }));
            })
            .SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
```

I'm happy to submit a PR with my changes but there should be some more discussion about this implementation in ASP.NET overall, along with the naming of the filter.

Personally, the name of the class (`AuthorizeForScopesAttribute`) simply doesn't apply anymore. The class is a filter, not an attribute. Second, the filter is applicable only to the `MsalUiRequiredException` and as such, it should be named accordingly. Perhaps something like `MsalUiRequiredFilter` is better?

As I touched on this above, the idea of asking people to decorate their methods with the attribute could lead to a missed entry followed by significant frustration. Using one style (i.e. the filter) versus the attribute will ensure it's set globally and will prevent someone from missing decorating a method.

**Comment by jmprieur** [comment]
Thanks @jasonshave 
I get your point for wanting a global filter and that would be great for Web apps which have actions which only require one scope, but as you'll notice in this sample (multiple APIs) there can be controllers with actions which require different scopes. 

https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/3-WebApp-multi-APIs/Controllers/HomeController.cs

So I still think that the attribute added on methods is interesting. The filter would not enable the same scenarios.

Now, I also see the point of having a default filter, which would share some code with the attribute. We could name it DefaultAuthorizeForScopeFilter, as it would be st on the statup.cs as a default. But in any case the attribute should have precedence (as they would be more fine grained)

does it make sense?

**Comment by jasonshave** [comment]
@jmprieur yes it makes sense and I did forget about those samples as well. I wonder if there is another way we can implement the global exception filter while maintaining flexibility between the Razor page syntax and the MVC style web API's with controllers. In my research I found that we support a [hierarchy of filtering in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-3.0#filter-scopes-and-order-of-execution) which may allow us to set multiple levels of filters (global-to-method).

I agree on your naming suggestion as well.

**Comment by jennyf19** [comment]
tracked in microsoft identity web repo: https://github.com/AzureAD/microsoft-identity-web/issues/11

**Comment by VictorioBerra** [comment]
This conversation helped me quite a bit. Like @jasonshave said, the name `[AuthorizeForScopes]` caused me significant confusion as I see `[Authorize...` and immediately think of a controller or action `IAuthorizeData` attribute. Something that inspects the User Principal for claims, roles, policies, permissions.

As someone coming from IS4 when you configure your client, you generally ask for the scopes you need up-front. https://github.com/IdentityServer/IdentityServer4/blob/main/samples/Clients/src/MvcCode/Startup.cs#L52-L58

I suppose the difference here that is not "incremental consent" and this is?

CC @jmprieur

**Comment by jmprieur** [comment]
Yes, @VictorioBerra. We could request the claims upfront (authorization filter), but this would not be enough. Nothing would guaranty that Azure AD would not ask for more claims / conditional access etc ..
So we prefer to try, and catch to challenge (in a web app, of course)
