### ISSUE TITLE
Can't authenticate with Azure AD on React Template

### ISSUE THREAD

**Issue by hbermani** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#234]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [x] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)

### Repro-ing the issue

Setup a new web app using Asp.net core with the default React template (with identity).  Follow the instructions on the Azure Portal to update Startup class and project.json to configure Azure AD authentication. 

Run the application, apply migrations and try to authenticate using Azure AD with redirect to https://Localhost:5001/signin-oidc. 

Error presented "Error loading external login information."

I searched the web and tried everything I can but I am stuck, please help :( 

**Expected behavior**

Use authenticates and login to web app.

**Actual behavior**

Error message "Error loading external login information." when attempting to register

**Possible Solution**

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 
None

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
> of ASP.NET Core, of MSAL.NET

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue? Yes
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview) Yes
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview) Yes
  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by TiagoBrenck** [comment]
Hi @hbermani could you please explain more about your scenario? 

The reason I ask is because when you mentioned to set "with identity" option for the template, you are choosing the topology where your users will be in a database and the authentication will be done against the users there. However, this tutorial is about using Microsoft Identity (AAD) to handle the authentication job, thus you wont have users on your database. I believe this sample might not be the best fit for your scenario.

**Comment by hbermani** [comment]
Tiago, thank you for getting back to me so promptly. 

Re. the scenario, what I pictured (and please bear with me as I am new to this), the ASP.Net React template uses identity service (understand that is Identity Server 4) to host local accounts in SQL server. What I need to do is have few select users that can authenticate locally using the username and password interface and access authorised controller, furthermore, the majority of users can authenticate with Azure AD and access the authorised controller as well. 

I hope I managed to explain this well, please let me know if I can provide any further information. 

Ps. I can confirm that authentication with Azure is working but the callback is not feeding the token into Identity Server (Don't know how to make that work)

**Comment by TiagoBrenck** [comment]
So, is your case a hybrid scenario where some users will be authenticated in AAD while few others will be under the SQL server?

**Comment by hbermani** [comment]
Exactly, yes.

**Comment by TiagoBrenck** [comment]
Would this be what you are looking for? https://stackoverflow.com/questions/54875422/hybrid-authentication-in-net-core-with-open-id-connect-and-local-database

**Comment by hbermani** [comment]
Oh Tiago, you are onto something here. 
There was a line I had to add onto the project.json that I have not seen in any of the documentation or code samples online that seems to have made a big difference.. 
    "CookieSchemeName": "Identity.External"

After I added that and the user signs in with Azure AD, a page appears that says you have successfully signed in into Azure AD and please provide an email address to register. (A great improvement). 

Now I am trying to login from the login button button but the page is stuck in processing login with few client side errors related to Cross-Origin-Read-Blocking.  I will investigate that as not come across that before.

**Comment by TiagoBrenck** [comment]
Im glad I could give you some guidance.

**Comment by hbermani** [comment]
You have indeed. I am just resolving the CORS issue. Once I figure that out I'll put here what the solution was. Being new to Github, can I give you kudos points or anything like that?

**Comment by TiagoBrenck** [comment]
I don't think we have point system here. I hope you find the solution. 
Have a good one.
