### ISSUE TITLE
Microsoft.Identity.Web: Should clear session auth cookie if cache is missing account

### ISSUE THREAD

**Issue by onovotny** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#240]
In the Microsoft.Identity.Web library, the system should automatically clear (`RejectPrincipal()`) the auth cookie if the corresponding account entry is missing from the token cache. This can happen if the cache expired, if it was a memory cache and the server bounced, etc.

The issue is that the system is now in an inconsistent state, where the user is considered logged-in, but any operations to call API's won't succeed because there's no token cache, no refresh token, etc.

I've worked around this here: https://github.com/dotnet-foundation/membership

In order to do so, I had to make some changes to `ITokenAquisition` and the MsalAbstractCacheProvider's GetCacheKey method.

`ITokenAcquisition` needed a method to check for a user's token cache:
https://github.com/dotnet-foundation/membership/blob/97b75e30e50aab76bfa5a21f1ab88bf31ae66da4/Microsoft.Identity.Web/TokenAcquisition.cs#L406-L426

In there, it takes the `CookieValidatePrincipalContext` to get the incoming ClaimsPrincpal as HtttpContext.User is not yet set at that point. It stores it in the HttpContext.Items via the `StoreCookieValidatePrincipalContext` extension method (used later by the GetCacheKey method so it can derive the appropriate key): 
https://github.com/dotnet-foundation/membership/blob/97b75e30e50aab76bfa5a21f1ab88bf31ae66da4/Microsoft.Identity.Web/TokenCacheProviders/MsalAbstractTokenCacheProvider.cs#L68-L69

Finally, the `CookieAuthenticationOptions` needs to be configured to check for and reject the incoming principal (this could/should be moved into the main IdentityPlatform AddMsal extension methods):
https://github.com/dotnet-foundation/membership/blob/97b75e30e50aab76bfa5a21f1ab88bf31ae66da4/Membership/Startup.cs#L110-L123

I can submit these changes as PR if you're in agreement with these changes.

**Comment by onovotny** [comment]
Strictly speaking, this is only necessary if there's any user-specific tokens in the cache. If the app is only using application credentials, this won't matter.

**Comment by TiagoBrenck** [comment]
@onovotny if we start forcing sign-outs for other middleware, like cookies, we would be stepping into a developer's custom settings for that middleware. These settings might/or might not be inline to how we think a user should be considered signed-in or out. 

What we can definitely consider doing is to raise an event when IAccount is null which a developer can use to carry out a custom action like clearing cookies, sessions, connections etc. or throwing an authorization challenge. 

Though I like the idea where Msal has a method that a developer can use to check if a valid token for a resource exists for a user.

I am hoping you have also gone though our class `AuthorizeForScopesAttribute` that handles this  memory cache and the server bounced scenario.

**Comment by onovotny** [comment]
In my case, I don't need scopes here since I'm not implementing an API. This is a web request. The core issue is that without a valid IAccount in the cache, any user-based token requests will fail. The only solution is to have the user login to the app again to get a new code. 

That's why I think forcing sign out isn't really a bad thing ... and should be automatic if there are any user scopes being requested via the code flow.

**Comment by TiagoBrenck** [comment]
Help me understand your scenario. Are you using MSAL just to cache IdTokens then?

**Comment by onovotny** [comment]
I'm not caching Id Tokens, but the code is priming the cache so that it can get access tokens as-needed to other API's. If the cache is missing, the app is in a broken/inconsistent state.

**Comment by TiagoBrenck** [comment]
Im completely aware of this inconsistent state. That is why we have the class `AuthorizeForScopesAttribute`. The logic there is to catch `MsalUiRequiredExceptionand` and try to "re sign-in" the user. Since the cookies/sessions/claims are all set for that user, they wont experience selecting an AAD account and typing login and password again, however the OpenIdConnect event `OnAuthorizationCodeReceived` will get triggered and the cache will get set.

I understood that in your scenario, you have access tokens without scopes, and `AuthorizeForScopesAttribute` for instance requires scope to operate. If you modify `AuthorizeForScopesAttribute` and remove all the code related to addiotional scopes, this inconsistent state will be solved without signing out the user.

I agree with you that your cookie approach is a good idea **if you want the user to have a sign-out experience**. What I am trying to say is that we have an approach without the sign-out experience. What I disagree is that we make this sign-out experience a rule. There are many ways to solve this inconsistent state, and Microsoft.Identity.Web shouldn`t impose flows to developers.

**Comment by onovotny** [comment]
If there's a cleaner way of getting a new code and setting the cache without the sign-in, then I agree that's better than forcing a sign out. In the end, my suggestion is that should be handled automatically so the state is never bad and things "just work." 

Auth is hard, and most developers just want a few lines to drop in and have things generally work.

**Comment by TiagoBrenck** [comment]
I have helped a developer that wanted to have this set globally. So he created a filter and registered in the Startup.cs. Here is a an example of a class that would work without scopes, in your case:

```csharp
public class MsalUiRequiredExceptionFilter : ExceptionFilterAttribute
    {
        public override void OnException(ExceptionContext context)
        {
            MsalUiRequiredException msalUiRequiredException = context.Exception as MsalUiRequiredException;
            if (msalUiRequiredException == null)
            {
                msalUiRequiredException = context.Exception?.InnerException as MsalUiRequiredException;
            }

            if (msalUiRequiredException != null)
            {
                if (CanBeSolvedByReSignInUser(msalUiRequiredException))
                {
                    var properties = BuildAuthenticationProperties(msalUiRequiredException, context.HttpContext);
                    context.Result = new ChallengeResult(properties);
                }
            }

            base.OnException(context);
        }

        private bool CanBeSolvedByReSignInUser(MsalUiRequiredException ex)
        {
            return ex.ErrorCode.ContainsAny(new[] { MsalError.UserNullError, MsalError.InvalidGrantError });
        }

        private AuthenticationProperties BuildAuthenticationProperties(MsalUiRequiredException ex, HttpContext context)
        {
            var properties = new AuthenticationProperties();

            // Set the scopes, including the scopes that ADAL.NET / MASL.NET need for the Token cache
            string[] buildInScopes =
                {OidcConstants.ScopeOpenId, OidcConstants.ScopeOfflineAccess, OidcConstants.ScopeProfile};
            properties.SetParameter<ICollection<string>>(OpenIdConnectParameterNames.Scope, buildInScopes);

            // Attempts to set the login_hint to avoid the logged-in user to be presented with an account selection dialog
            var loginHint = context.User.GetLoginHint();
            if (!string.IsNullOrWhiteSpace(loginHint))
            {
                properties.SetParameter(OpenIdConnectParameterNames.LoginHint, loginHint);

                var domainHint = context.User.GetDomainHint();
                properties.SetParameter(OpenIdConnectParameterNames.DomainHint, domainHint);
            }

            // Additional claims required (for instance MFA)
            if (!string.IsNullOrEmpty(ex.Claims))
            {
                properties.Items.Add(OidcConstants.AdditionalClaims, ex.Claims);
            }

            return properties;
        }
    }
```

**Comment by onovotny** [comment]
Where would that get hooked up? And should that be in the default wire-ups, in the spirit of "it just works?"

**Comment by onovotny** [comment]
The other thing is that exceptions are often caught deep down in the code and don't bubble up to the controller/MVC layer. Something that forces this check at the beginning of an incoming request proactively may be more effective?

**Comment by TiagoBrenck** [comment]
You may be looking at this configuration in the `Startup.cs` then: 

*(this code snippet uses dotnet core 3, if you are using version 2.x, the equivalent of AddControllersWithViews would be AddMvc)*

```
services.AddControllersWithViews(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
                options.Filters.Add(new AuthorizeFilter(policy));
                options.Filters.Add(new MsalUiRequiredExceptionFilter());
            });
```

**Comment by onovotny** [comment]
Right...but that assumes that the exception is not caught otherwise, which isn't a valid assumption. I have try/catches in my controllers and they catch all exceptions to do something useful as a last resort. 

I think something like this needs to be global/preemptive at the start of a request, not as a result of an exception when you try to use it.

**Comment by TiagoBrenck** [comment]
I agree, this approach wouldn't check this inconsistent state before every action. 

Maybe, to be more preemptive we might be looking at a custom `AuthorizationHandler<T>` and implement the `HandleRequirementAsync()` method. This method has the param `AuthorizationHandlerContext context` which gives us access to the httpContext.User. I am not quite sure if it allows dependency injection, so we would have `ITokenAcquisition` and run the custom validation that you created `HasTokenCacheForUser` against the current user in the context. 

One good investigation though would be if there is any big performance impact in being preemptive vs reactive only when the exception is thrown. That is a good topic to discuss.

**Comment by jmprieur** [comment]
Thanks @onovotny 

I did not know that: `HttpContext.GetCookieValidatePrincipalContext()?.Principal` contains the identity of the signed-in user. This is really good to know.

What I would propose is that on the signout we remove the cookie. Maybe here: https://github.com/dotnet-foundation/membership/blob/97b75e30e50aab76bfa5a21f1ab88bf31ae66da4/Microsoft.Identity.Web/TokenCacheProviders/MsalAbstractTokenCacheProvider.cs#L113, or in a method that calls it.

Would that be enought, @onovotny ?

We could also have an option to automatically signout the user when the user is no longer in the cache.

**Comment by sujayvsarma** [comment]
👆 fails in the scenario of organizational tenants where when the signin happened, you got a token. But between that and the token expiry, the user account was disabled (say the user left the organization). 

It is impractical to expect that a person that left an organization will not try to access organizational portals at a future point in time -- if only because they used a BYOD laptop and they had tabs open that attempt to refresh themselves when the underlying account is no longer accessible.

**Comment by jmprieur** [comment]
@sujayvsarma. This problem is being taken into account separately (by Azure AD)

**Comment by sujayvsarma** [comment]
@jmprieur  - I don't see it as being AzureAD's problem. Rather it is due to the decision of the middleware / library handling the auth token. If like @onovotny suggested, when the token expired if the user had to go through a manual sign in experience, this problem would not arise. Because then, they would get blocked right there when the Azure AD would ban them. No return to the app at all. 

But, since you are doing a "silent signin", you end up with an exception that takes **quite some effort** to code against and resolve.

**Comment by sujayvsarma** [comment]
There was a study somewhere that said that a huge number of corporate espionage problems where because ex-employees continued to have access to resources they should not. So this is a big & serious issue.

**Comment by JosephAspey** [comment]
Is there a solution to this yet?

**Comment by sujayvsarma** [comment]
Yes. Force a login everytime.

**Comment by jennyf19** [comment]
tracked in microsoft identity web repo: https://github.com/AzureAD/microsoft-identity-web/issues/13
