### ISSUE TITLE
Microsoft.Identity.Web: No user scopes leads to error

### ISSUE THREAD

**Issue by onovotny** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#241]
If you want to use .AddMsal(), there's no way to do so without any user scopes. It might be needed for Application flows.

If you use `new string[0]` for the scopes parameter, it'll throw in the OnAuthorizationCodeReceived callback since options.Scope will be null:
`await tokenAcquisition.AddAccountToCacheFromAuthorizationCodeAsync(context, options.Scope).ConfigureAwait(false);`

**Comment by jmprieur** [comment]
This is an external issue tracked in MSAL.NET: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/715

**Comment by jennyf19** [comment]
issue tracked in microsoft identity web repo: https://github.com/AzureAD/microsoft-identity-web/issues/14
