### ISSUE TITLE
401 calling WVD Api

### ISSUE THREAD

**Issue by wjdavis5** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#245]
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Repro-ing the issue

**Repro steps**

In Startup.cs:
```
services.AddMicrosoftIdentityPlatformAuthentication(Configuration)
                .AddMsal(Configuration, new string[] { "https://mrs-Prod.ame.gbl/mrs-RDInfra-prod/user_impersonation" })
                .AddInMemoryTokenCaches();
```
In controller:
   ```
     public async Task<IActionResult> Test()
        {
            var token = await TokenAcquisition.GetAccessTokenOnBehalfOfUserAsync(new[] { "https://mrs-Prod.ame.gbl/mrs-RDInfra-prod/user_impersonation" });
            var httpClient = new HttpClient();
            httpClient.BaseAddress = new Uri("https://rdweb.wvd.microsoft.com/");
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            var result = await httpClient.GetAsync("api/hubdiscovery/eventhubdiscovery.aspx");
            result = await httpClient.GetAsync("api/feeddiscovery/webfeeddiscovery.aspx");
            return new OkObjectResult(result);
        }
```

**Expected behavior**
Excepted that the calls to the WVD API do not return a 401 with the passed in token.

**Actual behavior**
Calling the Test endpoint and setting through we can see that the WVD api is returning a 401. The application has been granted permissions by admin in azure to this particular api. If I copy / paste the bearer token out of the [official web app](https://rdweb.wvd.microsoft.com/webclient/index.html) the calls succeed.

**Possible Solution**
I haven't gotten a response from the WVD Techcommunity folks so Im throwing a hail marry and asking here too.

Aspnet Core 3.1 MVC App. 
VS 2019 lastest GA release

  ```
<ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.8.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.AzureAD.UI" Version="3.1.0" />
    <PackageReference Include="Microsoft.Azure.Management.Fluent" Version="1.29.1" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="3.1.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.ApplicationInsights" Version="2.12.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="3.1.0" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.7.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.0" />
  </ItemGroup>
```

### Any log messages given by the failure
Just plain old 401 unauth.

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> Windows 10 1909

### Versions
> of ASP.NET Core 3.1

**The application has been granted permissions by admin in azure to this particular api.**

**Comment by jmprieur** [comment]
@wjdavis5 
1) do you get a token ?
2) are you able to confirm that the scope is right (you might want to use https://jwt.ms
3) If you have a token with the right scope, then you'd want to see with the Web API owners.

**Comment by wjdavis5** [comment]
Thanks for responding, this has really been driving me nuts.
I have getting a token, I'll check the scopes in the token using the link you just shared when I get home tonight. This really seems to be an issue with only the WVD endpoints b/c if I change the scope to azure user impersonation, I can list vms etc. just fine.

**Comment by jmprieur** [comment]
@wjdavis5 : I just thought you might have to use 'https://mrs-Prod.ame.gbl/mrs-RDInfra-prod//user_impersonation'
(note the double /)
See https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-migration#scopes-for-a-web-api-accepting-v10-tokens and in particular https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-migration#warning-should-you-have-one-or-two-slashes-in-the-scope-corresponding-to-a-v10-web-api

**Comment by wjdavis5** [comment]
Adding the extra / resulted in an exception.

**Comment by jmprieur** [comment]
Thanks for verifying, @wjdavis5 
Do you have the right scopes in your token?

**Comment by wjdavis5** [comment]
Here is the snip of the token:

`{
  "typ": "JWT",
  "alg": "RS256",
  "x5t": "piVlloQDSMKxh1m2ygnotsurewhatsasecrethere",
  "kid": "piVlloQDSMKxh1m2ygnotsurewhatsasecrethere"
}.{
  "aud": "https://mrs-Prod.ame.gbl/mrs-RDInfra-prod",
  "iss": "https://sts.windows.net/0105c271-1a0c-4114-9883-notsurewhatsasecrethere/",
  "iat": 1578158349,
  "nbf": 1578158349,
  "exp": 1578162249,
  "acr": "1",
  "aio": "AVQAq/8NAAAA8EHs2r8Oitid0KxXnjG83Dgj+sAxZI0Af3k5TFmPMf2/oGrAx93ETi787arS6PQHccVNr9notsurewhatsasecrethere",
  "amr": [
    "pwd",
    "mfa"
  ],`

**Comment by wjdavis5** [comment]
Is it b/c I have MFA enabled?

**Comment by wjdavis5** [comment]
Omg I just figured it out by comparing the token I got from the msft rdweb application:

From the RDWeb App:
"aud": "https://mrs-prod.ame.gbl/mrs-RDInfra-prod",

From my App:
"aud": "https://mrs-Prod.ame.gbl/mrs-RDInfra-prod",

....
Yes I was using an uppercase P in - mrs-Prod. And the msft app was using a lowercase p in mrs-prod.

I'm flabbergasted, angry and excited all at the same time.

**Comment by jmprieur** [comment]
Thanks for the update, @wjdavis5 
I let you close the issue :)
