### ISSUE TITLE
Authorize's LoginPath?

### ISSUE THREAD

**Issue by JasonKleban** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#246]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [x] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)

How do we override the AuthorizeAttribute unauthorized behavior?  I've tried these two ways, documented various places, but it doesn't seem to change the behavior of immediately redirecting to, in my case, https://login.microsoftonline.com/.  I want it to go to my page first because I have to handle the case when the page is in an iframe and I need to launch a popup instead.

```
services.ConfigureApplicationCookie(options => options.LoginPath = "/Account");
```

```
services.PostConfigure<CookieAuthenticationOptions>(
    IdentityConstants.ApplicationScheme,
    options => options.LoginPath = "/Account");
```

And here's some advise that doesn't apply to Core:  https://stackoverflow.com/a/35228379/162273

**Comment by jmprieur** [comment]
@JasonKleban did you try to override the OpenIdConnect event `OnRedirectToIdentityProvider`? 
Something like what is done here: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/6b150dc8b9d6c4b1b173385422e66edb9f367e8d/Microsoft.Identity.Web/WebAppServiceCollectionExtensions.cs#L72

**Comment by JasonKleban** [comment]
Thanks for the response.  Judging by its name, `OnRedirectToIdentityProvider` sounds like something that still needs to happen once I DO need to redirect to AzureAD.  I didn't see an obvious way to redirect to a custom in-app route instead anyway.  I'd expect some event like `OnUnauthorized` or something, perhaps.  Are we talking about the same thing?

**Comment by jmprieur** [comment]
What about using `OnAuthenticationFailed` ?

https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/6b150dc8b9d6c4b1b173385422e66edb9f367e8d/Microsoft.Identity.Web/Resource/OpenIdConnectMiddlewareDiagnostics.cs#L101

**Comment by TiagoBrenck** [comment]
@JasonKleban, the sample might not be related to your problem but we intercepted the event `OnAuthenticationFailed` and redirected to a custom page here: 
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/2-WebApp-graph-user/2-3-Multi-Tenant/Startup.cs#L98
