### ISSUE TITLE
Microsoft.Identity.Web should be netstandard2.1 rather than netcoreapp3.0 ideally 

### ISSUE THREAD

**Issue by jmprieur** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#248]
See request: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/242#issuecomment-569228606

**Comment by jmprieur** [comment]
This does not seem possible for the moment as MSAL.NET does not have a netstandard2.1 dependency. @bgavrilMS what do you think?

**Comment by bgavrilMS** [comment]
From MSAL perspective, you can do whatever you like with extension libraries. MSAL supports netstandrd 1.3, so extension library can target everything **above** netstandard 1.3 (i.e. netstandard2.1 etc.). 

However, this may not be what you want. If your only framework in ASP.NET Core, why do you want to support NetStandard? What is the benefit?

**Comment by jennyf19** [comment]
moved to microsoft identity web repo: https://github.com/AzureAD/microsoft-identity-web/issues/9
