### ISSUE TITLE
Microsoft.Identity.Web - Implement C# 8.0 nullable standard

### ISSUE THREAD

**Issue by sujayvsarma** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#249]
Even if the project is not C# 8.0, consider implementing the `nullable` standard by suffixing `?` to all parameters and returns that may be `NULL`. 

This will be a breaking changing internal to the library & to consuming code. Therefore, consider publishing the changes only during a major cycle.

**Comment by jmprieur** [comment]
@sujayvsarma can you be more specific about which parameters you'd want to be null?

**Comment by sujayvsarma** [comment]
Not that *I* would want to make null, but it creates a distinction between what the code would consider to maybe null or will never be null. 

For example, in `Microsoft.Identity.Web` > `TokenAcquisition.cs`, line 165, you are checking if the parameter `scopes` is null. If the `GetAccessTokenOnBehalfOfUserAsync` expects to receive `scopes`  as null sometime, it would define its signature as:

```
public async Task<string> GetAccessTokenOnBehalfOfUserAsync(
            IEnumerable<string>? scopes,
            string tenant = null)
```

Note the `?` at the end of the `IEnumerable<string>`. That says to the calling developer that scopes could be passed in as NULL. Otherwise it tells them that scopes cannot be NULL there. 

Simply add this to your `Microsoft.Identity.Web.csproj` and watch Visual Studio make those suggestions for you: 

```
<LangVersion>8.0</LangVersion>
<Nullable>enable</Nullable>
```

Fixing those suggestions is a breaking change.

**Comment by sujayvsarma** [comment]
Fyi, I have managed to implement these suggestions and managed to remove & clean up some code as well. If you're interested, I'll hook up a PR or send you the zip somewhere ?

**Comment by jmprieur** [comment]
Sure, @sujayvsarma, feel free to propose a PR.

**Comment by jennyf19** [comment]
issue tracked in microsoft identity web repo: https://github.com/AzureAD/microsoft-identity-web/issues/15
