### ISSUE TITLE
BUG - Azure RM token Scope URI should be changed, especially for Organizations multi-tenant logins

### ISSUE THREAD

**Issue by sujayvsarma** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#251]
When getting the access token after signing in with the "organizations" endpoint, the Scope URI for AzureRM token should be changed.

For `<tenantid>` logins, the Scope URI is `https://management.azure.com` as defined in `ArmOperationService.ArmResource` constant.

But for `organizations` logins, the Scope URI should be `https://management.core.windows.net`. Otherwise you get an invalid scope exception when you try to call ARM API.

In fact, `https://management.azure.com` works only for specific tenant logins. But `https://management.core.windows.net` works for ALL types of logins.

Repro:
1. Open the **3-WebApp-multi-APIs** sample, configure it for a multi-tenant application login.

2. In `appsettings.json`, set `TenantId` to a specific tenant. Run the application and login. Verify that the `/Home/Tenants` page lists your tenant(s).

3. Stop the application, change `TenantId` to "organizations". Now run the application. It may log you in again and prompt for consent -- do so. Even go into the Azure blade for Enterprise applications & grant Admin consent. Now hit the `/Home/Tenants` URL. You will see an invalid scope exception for `https://management.azure.com/user_impersonation`. 

4. Go into HomeController, Line# 59, change this line:

```
await tokenAcquisition.GetAccessTokenOnBehalfOfUserAsync(new[] { $"{ArmApiOperationService.ArmResource}user_impersonation" });
```

to read:

```
await tokenAcquisition.GetAccessTokenOnBehalfOfUserAsync(new[] { $"https://management.core.windows.net/user_impersonation" });
```

(notice the change in the URL)

5. Now run the application and go to the `/Home/Tenants` page. It will work fine.

**Comment by jmprieur** [comment]
@TiagoBrenck : can you please fix this one?
cc: @kalyankrishna1

**Comment by TiagoBrenck** [comment]
Sure, I will investigate it further since it seems to be a bug in ARM instead.
