### ISSUE TITLE
Microsoft.Identity.Web - Production-readiness & Issues

### ISSUE THREAD

**Issue by sujayvsarma** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#254]
First of all, kudos to every developer that worked on writing these samples and the Microsoft.Identity.Web codebase. You have done a great job at trying to navigate the maze that is ADAL + MSAL and tried to make things as easy as possible. 

BUT... 

Since you are talking about making Microsoft.Identity.Web "production grade" by making it available as a NuGet package, I don't think it is ready, not by a country mile. Here are some of the problems inherent in the codebase:

**1. Library cannot handle multi-tenant + multi-api scenario**
So, the "Multi-tenant" samples and code on their own work quite well. And the "Multi-API" samples and their code work on their own quite well. BUT, if you want to do multi-tenant + multi-API in one app, that does not work at all. Quite a lot of work arounds and ifs and buts need to be added to make all of that work.

Simple repro -- use the "3-WebApp-multi-APIs" project, try to target a multi-tenant app and authorize it using the "organizations" endpoint. You will get errors all over the place.

**2. `AuthorizeForScopesAttribute` does really kick in unless you have the code in a `try-catch` block and some of it is just plain meaningless.**
So when you have an attribute like this, you expect it to just work. Right? Some how it magically authorizes and you get a token in a Context object or something. Like how the AspNet/Core attribute `AuthorizeAttribute` works -- you just put `[Authorize]` on a controller or an action and the AspNet pipeline takes care of doing all the dirty work. 

But with the `AuthorizeForScopesAttribute`, you have to still write the `GetToken…` code. 

Now, here is the interesting & weird bit: the `OnException` function in the `AuthorizeForScopesAttribute` class does not trigger unless you have that `GetToken…` code in a `try-catch` block! Why??

All in all, I think this codebase has a lot of work to be done before it becomes ready as a production-worthy library. Until then, sure, it serves as a great sample, and lets you work with some individual scenarios.

**Comment by jennyf19** [comment]
issue moved to microsoft identity web repo: https://github.com/AzureAD/microsoft-identity-web/issues/7
