### ISSUE TITLE
CORS Issue in Authenticating asp.net core web app

### ISSUE THREAD

**Issue by nehaagrawal** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#255]
I have followed this document https://docs.microsoft.com/bs-latn-ba/azure/active-directory/develop/quickstart-v2-aspnet-core-webapp for implementing authentication in my asp.net core web app. I am getting below error. Above documenr doesn't say anything about setting CORS so I am wondering what could be the issue? 

    Access to XMLHttpRequest at 'https://login.microsoftonline.com/someid/oauth2/v2.0/authorize?client_id=someid&redirect_uri=someurl%3A9001%2Fsignin-oidc&response_type=id_token&scope=openid%20profile&response_mode=form_post&nonce=637145391895792520.ZGY1ZjY4MGYtMDdhZi00Y2Y5LTk5YjQtYTkyYjlmNDgxMjljOWE5Y2E2ZWEtYTZkNy00OGRiLWJiOTUtNTAxNmYwMzM1ODRm&state=CfDJ8K_0dkmtbvdKk3yIe6PLUU3Hvx4GJu_ybqj5XM-jtASL7HaSA32X8NrV0z7XiPVJEjqkDz4rGJHQ9Xab6cZpiZWByVQR_iGD1-zcJaqg0UvxkONLfKtqCMxbmdDiLDIaW3lXMVzDoKEUCPvYcoDNB9Ui2A1gNMXEvPX3Pwi_ZqsQlf8c2xz9cDot1WALDThzMvHYJSCyMlaw8JBMuAwlDdgW8RVaKwVb_XeMJxQVJl7_BT5gX1v2d2lzS2A4nPyk2MjHO_0BBtoh3rMItnb7YWlaJYa93l_utKw30q11TtWC07sELilt4vo1Vr5UjChX7K46eUEhBI45x6MF7nhaECy8SHDyYauTqzpb09w9Ybw0oymH9njPogAVDmMw4heaIPuvt_80gegqjluf_ow5czfVpqJa2aHMZwbdKH3Tzk4E5HPut0Jn4Ncjfy-tbgno7wd6bKdmnhHgVKZrdPmQuq0&x-client-SKU=ID_NET461&x-client-ver=5.3.0.0' (redirected from 'someurl') from origin 'someurl' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by TiagoBrenck** [comment]
CORS doesn't need to be set in this case indeed. Sometimes, this CORS error message misleads to the actual problem. Could you share the `AzureAd` of your `appsettings.json` please? (You can mask the clientId and tenant if you like so)

**Comment by jmprieur** [comment]
Closing as Tiago's question was not answered.
Feel free to reopen @nehaagrawal
