### ISSUE TITLE
2.1 - Call MsGraph - launchSettings - applicationUrl - default wrong port

### ISSUE THREAD

**Issue by boachim** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#258]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [x] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**
I downloaded and configured the quickstart solution.
We have identified that, by default, the launchSettings.json has a non-default applicationURL.
This should be: https://localhost:44321.

**Comment by jennyf19** [comment]
@TiagoBrenck we found this issue when working w/the css engineers in Lisbon. Can you take a look please? if you need more info, let us know.

**Comment by TiagoBrenck** [comment]
@jennyf19 could you elaborate more the repro steps?

**Comment by jmprieur** [comment]
@TiagoBrenck : when trying to run the sample, the launched URL was not the same as the port defined by the application.

The SSL Port is 44321
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/66fadc936081c08403d28ed403db50fe14c1930f/2-WebApp-graph-user/2-1-Call-MSGraph/Properties/launchSettings.json#L7

whereas the app is launched from https://localhost:44366
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/66fadc936081c08403d28ed403db50fe14c1930f/2-WebApp-graph-user/2-1-Call-MSGraph/Properties/launchSettings.json#L17
