### ISSUE TITLE
Example 1-5-B2C fails to start with .Net Core 3.1.1

### ISSUE THREAD

**Issue by stvb** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#260]
### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [X] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

Upgrade the project to use .net Core 3.1, and Microsoft.AspNetCore.Authentication.AzureADB2C.UI version 3.1.1

When starting the app, the following exception is raised:
Could not load file or assembly 'Microsoft.AspNetCore.Razor.Runtime, Version=3.1.1.0

Adding a reference to Microsoft.AspNetCore.Razor.Runtime, Version 3.1.1.0 does not seem to help.

### Versions
> .Net Core 3.1
> Microsoft.AspNetCore.Authentication.AzureADB2C.UI 3.1.1

**Comment by stvb** [comment]
No, but i just tried adding that reference explicitly and didn't help either. 

But, i just tried Microsoft.AspNetCore.Authentication.AzureADB2C.UI 3.1.0 and that works. So the breaking change is in the 3.1.1 change of Microsoft.AspNetCore.Authentication.AzureADB2C.UI

**Comment by jmprieur** [comment]
@jennyf19 FYI.

**Comment by jmprieur** [comment]
Closing as this is external (AzureAD.UI and AzureADB2C.UI depend on a non public NuGet package).
The new implementation (https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/jennyf/b2cwebapi) does not use them, but uses directly the OIDC middleware.
