### ISSUE TITLE
[Microsoft.Identity.Web] Microsoft.Identity.Web should leverage the ASP.NET Core IHttpClientFactory

### ISSUE THREAD

**Issue by jmprieur** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#267]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Microsoft.Identity.Web should leverage the ASP.NET Core IHttpClientFactory

**Comment by jennyf19** [comment]
moved to microsoft identity web repo: https://github.com/AzureAD/microsoft-identity-web/issues/6
