### ISSUE TITLE
The App token cache serialization key should contain the tenantId

### ISSUE THREAD

**Issue by jmprieur** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#268]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
The App token cache serialization key should contain the tenantId. Today it only contains the AppId

**Comment by kalyankrishna1** [comment]
@TiagoBrenck I'll check this once with the MT sample (enhance it with a client credential scenario). The token for Graph should be obtained and cached for each tenant separately.

**Comment by jmprieur** [comment]
@kalyankrishna1 : this should not be necessary at all given that application of different ClientId won't share the cache unless they are part of the same family of client IDs

Proposing to close this issue
cc: @TiagoBrenck @jennyf19
