### ISSUE TITLE
MsalException thrown when no Authority is set for ConfidentialClientApplication

### ISSUE THREAD

**Issue by twentytwokhz** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#27]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>When trying to authenticate via an app that is not multitenant, and which in my case restricts the users that can sign in to only one tenant (which I specified already as TenantId in the appsettings.json) an **MsalException** is thrown.

### Any log messages given by the failure
>AADSTS50194: Application '[GUID]' is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.
Trace ID: 4a7a6b33-61b6-45fa-a3db-eb7cc3660f00
Correlation ID: d5b01030-e720-4331-ad42-45602ca6a74c
Timestamp: 2018-12-08 12:53:39Z

### Expected/desired behavior
>This should work without any hickups since the appsettings.json file was configured correctly and the code seems to be correct. 

### OS and Version?
> Windows 10

### Versions
>Branch aspnetcore2-2-signInAndCallGraph

### Mention any other details that might be useful
Looking closer into the code, it seems that the **ConfidentialClientApplication** instance created in TokenAcquisition.cs line 117 does not take into account the possibility that the **Authority** parameter might be different than the [common] value. If taken into consideration (using appsettings.json Instance+TenantId value) the error will not appear.

**Comment by jmprieur** [comment]
Thanks @twentytwokhz for discovering this regression, and for analyzing the root cause.
I've proposed a PR. Do you want to check that this fixes the issue? (it works for me).

I still observe an issue with guest accounts, which I'll investigate ASAP (might not be before Monday, though)

**Comment by twentytwokhz** [comment]
@jmprieur awesome! will take a look. Thanks for the quick reply 👍
