### ISSUE TITLE
Handle signout in Blazor (dot net core 3.1), going to an allow anonymous page containing sign in link.

### ISSUE THREAD

**Issue by multco-malan** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#270]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [x] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**
ConfigureServices contains this code
`        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDistributedMemoryCache();
            services.AddHttpClient();

            services.Configure<CookiePolicyOptions>(options =>
            {
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            services.AddOptions();

            services.AddMicrosoftIdentityPlatformAuthentication(Configuration)
                    .AddMsal(Configuration, new string[] { scopes })
                    .AddInMemoryTokenCaches();

            services.Configure<CookieAuthenticationOptions>(AzureADDefaults.CookieScheme, o => o.AccessDeniedPath = "/General/HeyAccessDenied");

            services.AddMSGraphService(Configuration);
            services.AddTextMessagingService(Configuration);

            services.AddControllersWithViews(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
                options.Filters.Add(new AuthorizeFilter(policy));
            });

            // from https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-app-configuration
            services.Configure<OpenIdConnectOptions>(AzureADDefaults.OpenIdScheme, options =>
            {
                options.Events.OnSignedOutCallbackRedirect = async context =>
                {
                    context.Response.Redirect("/Public/Index");
                    context.HandleResponse();
                };

                Configuration.GetSection("AzureAd").Bind(options);
                var existingOnAuthorizationCodeReceivedHandler = options.Events.OnAuthorizationCodeReceived;
                options.Events.OnAuthorizationCodeReceived = async context =>
                {
                    await existingOnAuthorizationCodeReceivedHandler(context);
                    await OnAuthorizationCodeReceived(context);
                };
            });

            services.AddAuthorization(options =>
            {
                options.AddPolicy(Policies.Admin, policy => policy.RequireClaim(ClaimTypes.Role, ActiveDirectoryGroupName_ADMIN));
                options.AddPolicy(Policies.Manager, policy => policy.RequireClaim(ClaimTypes.Role, ActiveDirectoryGroupName_MANAGER));
                options.AddPolicy(Policies.Nobody, policy => policy.RequireClaim(ClaimTypes.Role, "NOBODY"));
            });

            services.AddRazorPages()
                .AddRazorPagesOptions(o => {
                    o.Conventions.AllowAnonymousToFolder("/Public");
                    o.Conventions.AuthorizeFolder("/Admin", Policies.Admin);
                    o.Conventions.AuthorizeFolder("/Manage", Policies.Manager);
                    o.Conventions.AuthorizeFolder("/Nobody", Policies.Nobody);
                });
            services.AddServerSideBlazor();

            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
            services.AddDbContext<SmsTextingContext>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("SmsTextingContext")));

            var DoNotPerformEFMigrations = Environment.GetEnvironmentVariable("DoNotPerformEFMigrations");
            _logger.LogInformation("DoNotPerformEFMigrations = " + DoNotPerformEFMigrations);

            ApplyEFMigrations(services);

            services.AddSingleton<WeatherForecastService>();
        }
`

I've allowed anonymous access to folder "/Public" 
/Public contains Index.razor
`@page "/Public/Index"

<h3>Public Index</h3>

@code {

}
`

Configure looks like this:
`        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            //if (env.IsDevelopment())
            if (env.IsDevelopment() || env.IsEnvironment("DEV"))
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseCookiePolicy();

            app.UseRouting();
            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapBlazorHub();
                endpoints.MapFallbackToPage("/_Host");
            });
        }`

**Expected behavior**

I added OnSignedOutCallbackRedirect in order to control where the user lands upon logging out from the application.

Because I've allowed Anonymous to the folder i'm expecting the user to see my /Public/Index.razor page.

I can't override the AzureAD/Account controller any longer because it is now "baked" in.

It seems that upon signing out it trys to get to /Public/Index.razor
but I get right back to the which account do you want to use.
![AzureADIssue](https://user-images.githubusercontent.com/29547881/72945531-f4064e80-3d30-11ea-88c4-0ef4999de314.PNG)

**Actual behavior**

**Possible Solution**

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
> of ASP.NET Core, of MSAL.NET

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue?
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)
  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@multco-malan we are working on unbacking AzureAD/Account controller.
PR is https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/pull/272

**Comment by jennyf19** [comment]
@jmprieur what's our status on this one?

**Comment by jmprieur** [comment]
This was done a long time ago.
Closing the issue. this works now

thanks for the heads-up, @jennyf19
