### ISSUE TITLE
AddMsal does not work with scopes for different resources (AADSTS28000 error)

### ISSUE THREAD

**Issue by rggammon** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#271]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [X] Other (please describe)

Issue is with Microsoft.Identity.Web

### Repro-ing the issue

**Repro steps**

AddMsal with scopes corresponding to different resources -

            services.AddMicrosoftIdentityPlatformAuthentication(Configuration)
                .AddMsal(Configuration, new string[] {
                    "https://management.core.windows.net/user_impersonation",
                    "00000007-0000-0000-c000-000000000000/user_impersonation" // CDS
                })

**Expected behavior**
Login works

**Actual behavior**
MsalServiceException: AADSTS28000: Provided value for the input parameter scope is not valid because it contains more than one resource. Scope 00000007-0000-0000-c000-000000000000/user_impersonation https://management.core.windows.net/user_impersonation offline_access openid profile is not valid. Trace ID: 41f469b8-47ac-4fa5-a625-957a7eab3700 Correlation ID: a7b67e8b-6d15-4914-bb6a-06cc02f9fc14 Timestamp: 2020-01-23 05:50:57Z

**Possible Solution**
AddMsal could take an array of arrays, one array per resource. Then, when getting tokens by call, make one token call per resource - I think using the same code would work here.

**Comment by TiagoBrenck** [comment]
Hello @rggammon this is actually expected and by design at the moment. Different resources could have different policies (like conditional access and MFA) and it would require a separate login experience for each resource, what is not UX friendly. 

@jmprieur @bgavrilMS is there any future plan regarding this topic?

**Comment by rggammon** [comment]
Ok - fyi, I get the appropriate consent screen across both resources, so it may be possible to do this with one login/consent, but I can understand if this is not something AddMsal supports.
