### ISSUE TITLE
InvalidOperationException: Either provide the 'ScopeKeySection' or the 'Scopes' to the 'AuthorizeForScopes'

### ISSUE THREAD

**Issue by TiagoBrenck** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#273]
> Please provide us with the following information:
> ---------------------------------------------------------------

`AuthorizeForScopesAttribute` is registered as a singleton, hence if you get it hit once by using the **ScopeKeySection** argument, the second time a `MsalUiRequiredException` is thrown you would have **ScopeKeySection** and **Scopes** populated (due to the singleton architecture) and the validation below will fail

```c#
if (!string.IsNullOrWhiteSpace(ScopeKeySection) && Scopes != null && Scopes.Length > 0)
{
      throw new InvalidOperationException($"Either provide the '{nameof(ScopeKeySection)}' or the '{nameof(Scopes)}' to the 'AuthorizeForScopes'.");
}
```

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [x] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [x] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [x] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [x] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [x] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [x] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [x] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

1. Setup sample 4.1
1. Run it and open two browsers in incognito
1. Log in with different accounts in both browsers
1. Stop the application in Visual Studio, and run again
1. In one of the browsers, click on **TodoList** menu item
1. In the other one, click on **TodoList** and observe the exception being thrown.

**Expected behavior**

Microsoft.Identity.Web should be capable in handling `MsalUiRequiredException` multiple times, coming from different requests. 

**Actual behavior**

An `InvalidOperationException` is thrown on the second time, even though the method is decorated with `AuthorizeForScopesAttribute` passing only the **ScopeKeySection** as parameter:

```c#
[AuthorizeForScopes(ScopeKeySection = "TodoList:TodoListScope")]
public async Task<ActionResult> Index()
{
      return View(await _todoListService.GetAsync());
}
```

**Comment by jennyf19** [comment]
cc: @jmprieur

**Comment by jmprieur** [comment]
@TiagoBrenck : why is it statically defined? it's an attribute instance? I don't get it. I looked at the doc for the exception filters, it does not say it's static?

**Comment by TiagoBrenck** [comment]
@jmprieur I don't know why it is statically defined. If you follow the steps mentioned above you will be able to reproduce the bug.

**Comment by jmprieur** [comment]
what happens is that Scopes is assigned (as an optimization) from the value of the resource, which means that next time we throw an error.
A fix would be to assigned the value of the resource into a different variable (which would not change Scopes).

This has actually good if we want to dynamically read the config file.

**Comment by TiagoBrenck** [comment]
Nice suggestion @jmprieur . I have opened a PR: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/pull/280

Honestly, I am still confused how come the `Scopes` kept assigned.

**Comment by jennyf19** [comment]
@TiagoBrenck it's because we're setting the Scopes value to whatever is in `configuration.GetValue<string>(ScopeKeySection)`, then later checking if there is a value in both: `                    if (!string.IsNullOrWhiteSpace(ScopeKeySection) && Scopes != null && Scopes.Length > 0)`, which there is, so then the InvalidException is thrown, even though the two scopes are the same.
