### ISSUE TITLE
[Tutorial] Example with web app calling web api in Core 3.1 using B2C

### ISSUE THREAD

**Issue by GedillurBjorn** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#274]
Hi,
I am looking for an example of asp.net core web app calling a asp.net core web api both using AAD B2C, I an fairly new to code in genera and did not find a way to adapt the code found with core 2.2 to 3.1. 
Thanks!

**Comment by jmprieur** [comment]
We are working on iut, @GedillurBjorn 
There is a PR here: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/pull/282

**Comment by jennyf19** [comment]
@GedillurBjorn The sample you are looking for is now available [here](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C). Closing this issue, but please reopen, or create another if you have any further issues.
