### ISSUE TITLE
Example for Blazor server side app 

### ISSUE THREAD

**Issue by sowsan** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#277]
Any examples for the blazor server-side app for the same scenario would be very helpful,

https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.1&tabs=visual-studio

**Comment by jmprieur** [comment]
@sowsan : this is on the backlog

**Comment by sowsan** [comment]
Thank you!
