### ISSUE TITLE
[Microsoft.Identity.Web?] No account or login hint was passed to the AcquireTokenSilent call - in authorization filter

### ISSUE THREAD

**Issue by fboucsc** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#281]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [x] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

I have an authorization filter which calls the Graph api to check access based on some MemberOf attribute of the logged in user
      `  [Authorize(Policy ="Admin")]` - this policy calls : 
 ```
public async Task<List<string>> GetUserMemberOf(bool onBehalfOfLogin = false)
        {
            var Scopes = new[] { Constants.ScopeUserRead, Constants.ScopeUserReadAll };
            string accessToken = await _tokenAcquisition.GetAccessTokenOnBehalfOfUserAsync(Scopes);
```
This is the controller method which calls it: 
```
 [AuthorizeForScopes(Scopes = new[] { Constants.ScopeUserRead , Constants.ScopeUserReadAll})]
        [Authorize(Policy ="Admin")]
        public IActionResult Index()
        {
            return View();
        }
```

to get the error: log in, then clear the in-memory tokens (restart app) or by changing the date on the tokens (distributed). Any calls to GetAccessTokenOnBehalfOfUserAsync which are outside of a controller will fail (ViewComponent, Authorization Filter) 

additionally, if graph is called in _Layout.CSHTML  (through the same auth filter) - it throws the same error:
```
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
@if ((await AuthorizationService.AuthorizeAsync(User, "Admin")).Succeeded)
{
    <a>Menu item only suitable for admins</a>
}

```
**Expected behavior**

 ItokenAcquisition finds user token or logs user in 

**Actual behavior**

the application throws  "MsalUiRequiredException: No account or login hint was passed to the AcquireTokenSilent call." when the cache/session resets (I've tried this with distributed sql cache as well as InMemoryToken) or the session expires.

I understand that "AuthorizeForScopes" would normally catch this exception but in this case (due to the order of authorize filter??) - it doesn't.

I've encountered a similar issue using "ITokenAcquisition" in a ViewComponent, since they don't support filters (AuthorizeForScopes) - and I wasn't able to implement a "ChallengeResult" since it returns a IActionResult and not a IViewComponentResult

**Possible Solution**

Injecting the auth service in the controller and using it like so : 
  ```
  
    [AuthorizeForScopes(Scopes = new[] { Constants.ScopeUserRead })]
        public async Task<IActionResult> Index()
        {
            var x = await _authService.AuthorizeAsync(User, "Admin");
            if (x.Succeeded) { 
                return View();
            }
            else
                return Forbid();
        }
```
Is a temporary workaround, but this does not solve the issue of ViewComponents throwing this error. 

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10
### Versions
> of ASP.NET Core, of MSAL.NET
ASP.Net Core 3.1 MSAL 4.8.1
### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue?
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)
  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by aelhadi** [comment]
Any news about this issue? 
Thanks

**Comment by TiagoBrenck** [comment]
Hi,
Have you tested applying the `AuthorizeForScopes` on top of GetUserMemberOf?

```c#
[AuthorizeForScopes(Scopes = new[] { Constants.ScopeUserRead, Constants.ScopeUserReadAll })]
public async Task<List<string>> GetUserMemberOf(bool onBehalfOfLogin = false)
       {
           var Scopes = new[] { Constants.ScopeUserRead, Constants.ScopeUserReadAll };
           string accessToken = await _tokenAcquisition.GetAccessTokenOnBehalfOfUserAsync(Scopes);
```

**Comment by fboucsc** [comment]
hey, 
I've tried that, since "GetUserMemberOf" isn't a controller action the filter doesn't seem to handle the exception. I usually use this method inside a controller action so its no problem for that use case. However I also used it to build a custom authorization rule (authorization filter) 

![image](https://user-images.githubusercontent.com/60673449/76243570-e8061b80-620e-11ea-862f-c0c879659ed4.png)

the "Admin" policy does some azure calls and that's where I get the failure.

**Comment by TiagoBrenck** [comment]
I understand your point. Indeed `AuthorizeForScopes` seems to be tied to controller actions and we have to improve it. I will open an internal discussion with the engineering team and I will post any updates here.

**Comment by isaacrlevin** [comment]
@TiagoBrenck here is a Blazor Sample that doesn't work after you stop the debugging session. All debugging sessions after the initial have the OP error 
https://github.com/isaacrlevin/BlazorGraphTest

**Comment by franva** [comment]
hi, hit the same issue. do we have any update?

**Comment by TiagoBrenck** [comment]
@franva is your app also in Blazor? We currently doesnt have a solution for this problem on Blazor apps, but the task is on the backlog.

**Comment by franva** [comment]
@TiagoBrenck  nope, I'm using WebAPI for the restful api + React.js app.

I solved this issue by adding the "AuthorizeForScopes". 

:)

**Comment by TiagoBrenck** [comment]
Yes, that is the current solution for this issue. I am glad it worked.

**Comment by frankkilcommins** [comment]
Any update timelines regarding this? Am hitting a similar issue with ViewComponents

**Comment by rharbaugh** [comment]
@frankkilcommins That's the context that I'm experiencing the issue in as well. It's happening on our web servers whenever a deployment hits, which reinforces my suspicions. Clearing browser cookies and allowing a proper MSAL re-auth fixes it.

@TiagoBrenck The situation where browser cookies exist, but the in-memory cache does not, evades null references until `GetAccessTokenOnBehalfOfUserFromCacheAsync` fails on a null `account`.

**Comment by TiagoBrenck** [comment]
@frankkilcommins and @rharbaugh We currently dont have a solution for this problem when using Razor app, or your AcquireToken method is happening in a ViewComponent or an Ajax call. 

If those are not your scenarios, then the current solution is to decorate your ActionResult with:

```csharp
[AuthorizeForScopes(Scopes = new[] { "TheScopeThatYouArePassingOnAcquireTokenMethod" })]
```

@rharbaugh the analysis that you did about why this error is happening is correct. When you stop the application, you lose your in-memory cache while your cookies are still alive. So, when you restart the application, you skip the authorization call necessary to bootstrap the token cache, thus your IAccount will be null. The `AuthorizeForScopes` attribute captures *MsalUIException* and sends an authorization challenge, that will result in bootstrapping the token cache.

**Comment by dengel223** [comment]
@TiagoBrenck For those of us that are using Blazor, where can we subscribe to get notified when this issue is resolved or the task on the Backlog has been completed and available?

**Comment by dengel223** [comment]
I am able to use a Distributed SQL Server Cache in Blazor which stores the token in a SQL table. This seems to work when the application is restarted, the call to GetAccessToken using the _tokenAcquisition DI uses the SQL table to find the token.  However, I noticed when the token expires, the SQL Cache removes the token entry in SQL and the next time GetAccessToken is called, we are back to the same 'No Account or Login Hint' error.  So refreshing tokens needs to be researched.

Here is some info on using distributed SQL server caching:
![image](https://user-images.githubusercontent.com/43100041/81830622-4c44a480-950a-11ea-86ea-7ce041994047.png)

**Comment by wmgdev** [comment]
I've been experimenting with calling Graph from a Blazor Server app. It seems to work, I ran into the problem when you lose the in-memory cache while your cookies are still alive, the auth calls are skipped and you don't bootstrap the token cache, which throws the _MsalUIException_ . Can't use the AuthorizeForScopes attribute, because we don't have a 'controller' in Blazor

I came up with a clunky fudge to catch the MsalUIException on the Blazor page and redirect to a 'normal' controller in same app, decorated with the AuthorizeForScopes attribute, which populated the token cache then redirected back to the Blazor page.

Full Repo [BlazorGraphApi](https://github.com/wmgdev/BlazorGraphApi)

I'd be interested to know if there is a better way to do it, it would be nice if an unpopulated token cache could be handled lower down in the code rather than using the AuthorizeForScopes attribute

**Comment by isaacrlevin** [comment]
ping @jasonjoh

**Comment by wmgdev** [comment]
> I've been experimenting with calling Graph from a Blazor Server app. It seems to work, I ran into the problem when you lose the in-memory cache while your cookies are still alive, the auth calls are skipped and you don't bootstrap the token cache, which throws the _MsalUIException_ . Can't use the AuthorizeForScopes attribute, because we don't have a 'controller' in Blazor
> 
> I came up with a clunky fudge to catch the MsalUIException on the Blazor page and redirect to a 'normal' controller in same app, decorated with the AuthorizeForScopes attribute, which populated the token cache then redirected back to the Blazor page.
> 
> Full Repo [BlazorGraphApi](https://github.com/wmgdev/BlazorGraphApi)
> 
> I'd be interested to know if there is a better way to do it, it would be nice if an unpopulated token cache could be handled lower down in the code rather than using the AuthorizeForScopes attribute

I've updated [BlazorGraphApi](https://github.com/wmgdev/BlazorGraphApi) and put AuthorizeForScopes attribute on __Host.cshtml PageModel

This does away with the extra controller and makes things a bit cleaner

**Comment by kenchilada** [comment]
> 
> 
> > I've been experimenting with calling Graph from a Blazor Server app. It seems to work, I ran into the problem when you lose the in-memory cache while your cookies are still alive, the auth calls are skipped and you don't bootstrap the token cache, which throws the _MsalUIException_ . Can't use the AuthorizeForScopes attribute, because we don't have a 'controller' in Blazor
> > I came up with a clunky fudge to catch the MsalUIException on the Blazor page and redirect to a 'normal' controller in same app, decorated with the AuthorizeForScopes attribute, which populated the token cache then redirected back to the Blazor page.
> > Full Repo [BlazorGraphApi](https://github.com/wmgdev/BlazorGraphApi)
> > I'd be interested to know if there is a better way to do it, it would be nice if an unpopulated token cache could be handled lower down in the code rather than using the AuthorizeForScopes attribute
> 
> I've updated [BlazorGraphApi](https://github.com/wmgdev/BlazorGraphApi) and put AuthorizeForScopes attribute on __Host.cshtml PageModel
> 
> This does away with the extra controller and makes things a bit cleaner

Thank you so much for publishing this to Github for everyone.  This is brilliant, I love you.  I've been trying to solve this all day and I can finally stop crying.

For the sake of others, I needed to handle scopes for **multiple** resources (Graph, PowerBi, Azure Storage, etc).  I subclassed `AuthorizeForScopesAttribute` and populated `Scopes` to include ALL of my scopes and used that attribute on `_Host`.  Then in `_Host` I needed to change `OnGetAsync()` to have a separate ` await _tokenAcquisition.GetAccessTokenForUserAsync()` call for **EACH** separate resource.  If you do not do the latter you will get an MSAL error about requesting an access token for multiple resources.

**Comment by jland13** [comment]
I'm having an issue with this exception as well and feel I have ran out of options.  I feel my situation is unique in that I'm using a helper function that is called from the Home controller, and I pass the ITokenAcquisition and WebOptions to the helper's constructor.  

The weird thing is it seems to work fine when I run the app in Firefox, but in Chrome it works only when I login for the first time to my app, and subsequent attempts to access the app while logged in trigger this exception/error and I need to clear cookies/tokens for it to work once more.  

 I am working on an application for a government agency for a school project which is built off of ASP.NET Core using code from the second example of accessing the Graph API using a school/work login,. 

I have tried switching from using session cache but am still getting the issue despite the method of caching I used.  I have also tried adding the AuthorizeForScopes to the calling Home controller (where [Authorize] usually goes), as well as to the helper class (which seems like it doesn't work for when reading above), neither are working.  

Thanks for any advice you can give on this issue.

**Comment by jmprieur** [comment]
@jland13 would it be a SameSite issue?

**Comment by TiagoBrenck** [comment]
@jland13 Have you tried adding the `AuthorizeForScopes` on top of the action result instead?

**Comment by jland13** [comment]
Sure, here are the relavant pats of the code, everything else should be the same as in the example, that is using the Services/Infrastructure, appsettings, etc.

`// In Startup.cs
  
public void ConfigureServices(IServiceCollection services)
{
	// Authentication/Authorization
	services.Configure<CookiePolicyOptions>(options =>
	{
		// This lambda determines whether user consent for non-essential cookies is needed for a given request.
		options.CheckConsentNeeded = context => true;
		options.MinimumSameSitePolicy = SameSiteMode.None;
		// Handling SameSite cookie according to https://docs.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-3.1
		options.HandleSameSiteCookieCompatibility();
	});

	services.AddOptions();

	services.AddSignIn(Configuration);

	// Token acquisition service based on MSAL.NET
	// and chosen token cache implementation
	services.AddWebAppCallsProtectedWebApi(Configuration, new string[] { Constants.ScopeUserRead })
			.AddInMemoryTokenCaches();

	// Add Graph
	services.AddGraphService(Configuration);

	services.AddControllersWithViews(options =>
	{
		var policy = new AuthorizationPolicyBuilder()
			.RequireAuthenticatedUser()
			.Build();
		options.Filters.Add(new AuthorizeFilter(policy));
	}).AddMicrosoftIdentityUI();

	services.AddRazorPages();
 
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
	if (env.IsDevelopment())
	{
		app.UseDeveloperExceptionPage();
	}
	else
	{
		app.UseExceptionHandler("/Home/Error");
		// The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
		app.UseHsts();
	}

	app.UseHttpsRedirection();
	app.UseStaticFiles();
	app.UseCookiePolicy();

	app.UseRouting();
	app.UseAuthentication();
	app.UseAuthorization();

	app.UseEndpoints(endpoints =>
	{
		endpoints.MapControllerRoute(
			name: "default",
			pattern: "{controller=Home}/{action=Index}/{id?}");
		endpoints.MapRazorPages();
	});
}

 
// In HomeController.cs    

readonly ITokenAcquisition _tokenAcquisition;
readonly IOptions<Services.WebOptions> _webOptions; // Not using Service.WebOptions since passing to helper
 
public HomeController(ILogger<HomeController> logger, ITokenAcquisition tokenAcquisition, IOptions<Services.WebOptions> webOptions)
{
	_logger = logger;
	_tokenAcquisition = tokenAcquisition;
	_webOptions = webOptions; // Not using .Value since passing to helper
}
 
 public async Task<IActionResult> Index()
 {
	...
	// User information
	GraphApi nGraphApi = new GraphApi(_tokenAcquisition, _webOptions); // Calling helper 
	string eName = nGraphApi.GetProfileName().Result; // Extracting name to use for a database helper
	...
}		


// GraphApi.cs helper

public class GraphApi
{
	readonly ITokenAcquisition _tokenAcquisition;
	readonly WebOptions _webOptions;

	public GraphApi(ITokenAcquisition tokenAcquisition, IOptions<WebOptions> webOptions)
	{
		_tokenAcquisition = tokenAcquisition;
		_webOptions = webOptions.Value;
	}

    [AuthorizeForScopes(Scopes = new[] { Infrastructure.Constants.ScopeUserRead })] // Not working?
	public async Task<string> GetProfileName()
	{
		// Initialize the GraphServiceClient. 
		Graph::GraphServiceClient graphClient = GetGraphServiceClient(new[] { Constants.ScopeUserRead });

		var me = await graphClient.Me.Request().GetAsync();
		string name = me.DisplayName;
		return name;
	}

	private Graph::GraphServiceClient GetGraphServiceClient(string[] scopes)
	{
		return GraphServiceClientFactory.GetAuthenticatedGraphClient(async () =>
		{
//            string result = await _tokenAcquisition.GetAccessTokenOnBehalfOfUserAsync(scopes); // Couldn't get this to work
			string result = await _tokenAcquisition.GetAccessTokenForUserAsync(scopes);
			return result;
		}, _webOptions.GraphApiUrl);
	}
}	`

**Comment by TiagoBrenck** [comment]
So, the attribute on top of `GetProfileName()` will definitely not work.
I ve heard from someone in another topic, that he added a try/catch in their helper method, and just throwing the `MsalUiRequiredException` made the attribute to be handled properly by the `AuthorizeForScopes` on top of the action result. Could you try that and see it solves your problem?

**Comment by jland13** [comment]
I had this in the GetProfileName() of GraphApi.cs but didn't include it as it didn't seem relevant other than for debugging, should I just switch the exception to `MsalUiRequiredException`?

`try
{
    var me = await graphClient.Me.Request().GetAsync();
    string name = me.DisplayName;
    return name;
}
catch (Microsoft.Graph.ServiceException e)
{
    System.Diagnostics.Debug.WriteLine("\n=================\n");
    System.Diagnostics.Debug.WriteLine(e);
    System.Diagnostics.Debug.WriteLine("\n=================\n");
}`

**Comment by TiagoBrenck** [comment]
You dont need to switch, since Graph may also throw exceptions. I was talking about adding this for test:

```c#
    try
    {
        var me = await graphClient.Me.Request().GetAsync();
        string name = me.DisplayName;
        return name;
    }
    catch (Microsoft.Graph.ServiceException e)
    {
        System.Diagnostics.Debug.WriteLine("\n=================\n");
        System.Diagnostics.Debug.WriteLine(e);
        System.Diagnostics.Debug.WriteLine("\n=================\n");
    }
    catch(MsalUiRequiredException ex) 
    {
        throw ex;
    }
    return null;
```

Would this make the attribute on `Index()` to catch it?

**Comment by jland13** [comment]
Okay I tried that and it didn't work, still getting the exception/user_null error.

**Comment by Rishab1988** [comment]
I am new to learning MSAL, I encountered the similar log " No account or login hint was passed to the AcquireTokenSilent call" in the sample app, can somebody help me to understand how this exception was handled and a user re-authentication was succeeded while my app simply gives and error and shuts.

**Comment by jmsv** [comment]
> @TiagoBrenck nope, I'm using WebAPI for the restful api + React.js app.
> 
> I solved this issue by adding the "AuthorizeForScopes".

I'm currently trying to set up the same architecture but adding `AuthorizeForScopes` didn't work for me - do you have a working set up I could look at?

**Comment by TiagoBrenck** [comment]
@jmsv here is where we use it: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/2-WebApp-graph-user/2-1-Call-MSGraph/Controllers/HomeController.cs#L34

You could decorate the controller as well.

**Comment by jmsv** [comment]
@TiagoBrenck if I understand correctly, that example handles the views for logging in? I'm trying to handle that part in a React app and pass the bearer token to the API - are there any examples of this?

**Comment by TiagoBrenck** [comment]
Oh I see. Yes, `AuthorizeForScopes` is just for MVC.
@jmprieur do we have a solution for React+.Core Web API?

**Comment by jland13** [comment]
Since Identity Web has been updated, is there any update to this?  My Home controller is getting really messy and I would like to be able to move my requests to a helper function before the end of my project.  Thanks!

**Comment by TiagoBrenck** [comment]
@jmprieur @jennyf19 @pmaytak could you help him?

**Comment by AlexA-1976** [comment]
Is there any fix for a controller action that is attempting to read user profile from AzureAD that is using .NET Core 2.2?

**Comment by KalyanChanumolu-MSFT** [comment]
> Is there any fix for a controller action that is attempting to read user profile from AzureAD that is using .NET Core 2.2? Where do I get AuthorizeForScopes?

Support for .NET Core 2.2 ended on December 23, 2019. Timelines are [here](https://dotnet.microsoft.com/platform/support/policy/dotnet-core)

You should consider upgrading to .NET Core 3.1

**Comment by TiagoBrenck** [comment]
@AlexA-1976 in case you can`t update your .NET Core version at all, unfortunately the only solution would be using Microsoft.Identity.Web project before becoming a NuGet package and before using Core 3.1.

The Git revision at this stage is: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/d043e49e

Be aware that at that time, some methods had a different name. I recommend checking the samples at that time to be your reference.

**Comment by jmprieur** [comment]
@fboucsc @aelhadi @isaacrlevin @franva @frankkilcommins @rharbaugh @dengel223  @wmgdev 
@kenchilada  @JaimeLanders @jmsv @AlexA-1976 @KalyanChanumolu-MSFT 

Microsoft.Identity.Web now provides solutions for MVC, Razor and Blazor. Please see https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access#in-blazor-server

Proposing to close this issue. Feel free to reopen if this still does not work for you

**Comment by andrenpt** [comment]
I dont think the **AuthorizeForScopes** Attribute it-s a good solution to this problem.

What happens in my application its really odd if I have no cookies it all works as expected but as soon as I have the **.AspNetCore.Cookies** already there it always fails with that error message "_Microsoft.Identity.Web.TokenAcquisition: Information: No account or login hint was passed to the AcquireTokenSilent call._"

The AuthorizeForScopes Atribute just Captures the Exception and redirects to the Challenge result but in reality the Exception shouldnt really  happen in the first place...

Thanks

**Comment by OnAzureCloud9** [comment]
@andrenpt also facing the same issue. The `AuthorizeForScopes` cannot handle an AJAX call to a controller action decorated with `AuthorizeForScopes` because it redirects and you get a CORS rejection. I'm currently investigating my own work around for this issue but it would be great for the library to be able to handle AJAX calls appropriately. I suppose this would mean returning a redirect URL and a 401 so the AJAX response can process and redirect the browser.

**Comment by binhnguyen1984** [comment]
> @jmsv here is where we use it: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/2-WebApp-graph-user/2-1-Call-MSGraph/Controllers/HomeController.cs#L34
> 
> You could decorate the controller as well.

Why do we need the scopes for AuthorizeForScopes if what it all does is to trigger the authentication flow? I try to remove the scopes and it is still working.

**Comment by jmprieur** [comment]
@binhnguyen1984 : it does not trigger the authentication flow ([`Authorize]` does). It processes the missing claims or missing consent to scopes exceptions. See https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access

**Comment by binhnguyen1984** [comment]
@jmprieur : I see that AuthorizeForScopes adds the missing scopes in case the client requires more permissions. But it also creates a new ChallengeResult (even in case there are no additional scopes required) and this triggers the authentication flow. The attribute [Authorize] does not trigger the authentication flow in case the user was already authenticated (with cookies) and AuthorizeForScopes addresses exactly this issue.

**Comment by jmprieur** [comment]
@binhnguyen1984 : Authorize does it a priori. AuthorizeForScopes does it a posteriori, for instance if there is no token in the cache whereas there is a session cookie (happens with the In memory cache when you restart the app), or if the service (Azure AD) asks for more scopes or requires more consent. The case you see is probably the first one, but in production you probably want to use another [token cache serialization](https://github.com/AzureAD/microsoft-identity-web/wiki/token-cache-serialization)

What can we do to make this article clearer? [https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access](https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access)

**Comment by filipgoris** [comment]
> What can we do to make this article clearer? https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access

This article solved the issue for me (in Blazor).
Nothing to add, seems pretty clear to me. Thx!

**Comment by newbiedev123** [comment]
Hi,

Is there a solution for this issue in the helper class(or any other class than the Controller action)?

I am facing same issue(getting "No account or login hint....") in my ASP.Net Core MVC project. 

My code follows an n-tier architecture and the code for calling the Downstream API is **not** in the Presentation Layer.

When I try the solution above in my MVC controller, it works fine. But when I move the code to a different layer it gives me the error when I stop and restart debugging. Then I have to clear the cache to debug my code again.

` public async Task<List<Something>> GetListAsync()
        {
            var apiResult = "";

            try
            {

                using var response = await _downstreamWebApi.CallWebApiForUserAsync("DownstreamApi").ConfigureAwait(false);

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    apiResult = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
                }
                else
                {
                    var error = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
                    throw new HttpRequestException($"Invalid status code in the HttpResponseMessage: {response.StatusCode}: {error}");
                }

            }
            catch (MsalUiRequiredException ex)
            {
                throw ex;
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
}`

I also tried adding the scope(below) to the top of the above method. But still not working.
[AuthorizeForScopes(ScopeKeySection = "DownstreamApi:Scopes")]


But as I mentioned above it all works fine when I add it to Controller action, like the below.

` [AuthorizeForScopes(ScopeKeySection = "DownstreamApi:Scopes")]
        public async Task<IActionResult> Index()
        {
            var apiResult = "";

            try
            {
                using var response = await _downstreamWebApi.CallWebApiForUserAsync("DownstreamApi").ConfigureAwait(false);
                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    apiResult = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
                }
                else
                {
                    var error = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
                    throw new HttpRequestException($"Invalid status code in the HttpResponseMessage: {response.StatusCode}: {error}");
                }

            }
            catch (MsalUiRequiredException ex)
            {
                throw ex;
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
}`

Is there a work around to get it to work from a different layer?

Thanks in advance

**Comment by jmprieur** [comment]
@newbiedev123 : 
- no, there is no interface. Do you have a scenario where you'd need one?
- You can also call .AddMicrosoftIdentityConsentHandler() on services.
  
  See https://github.com/AzureAD/microsoft-identity-web/blob/bba91c4298411e780c9f082e8e3843eacd8e543c/src/Microsoft.Identity.Web/MicrosoftIdentityCircuitHandler.cs#L50

**Comment by newbiedev123** [comment]
@jmprieur thanks for your reply.

- This was purely to unit test the method which uses it.
- I added the .AddMicrosoftIdentityConsentHandler() on services, but I am getting an error.

![image](https://user-images.githubusercontent.com/81688354/117934105-3672e680-b2fa-11eb-9c40-31f7c2d46120.png)

```
services.AddMicrosoftIdentityConsentHandler();

            var initialScopes = configuration.GetValue<string>("DownstreamApi:Scopes")?.Split(' ');

            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(configuration.GetSection("AzureAd"))
                .EnableTokenAcquisitionToCallDownstreamApi(initialScopes)
                .AddDownstreamWebApi("DownstreamApi", configuration.GetSection("DownstreamApi"))
                .AddInMemoryTokenCaches();

```

**Comment by jmprieur** [comment]
@newbiedev123 
you need to add the line after AddAuthentication etc ... not before!

**Comment by newbiedev123** [comment]
@jmprieur 
I tried adding it on top of AddAuthentication, but still having same issue.
       
          ```
 var initialScopes = configuration.GetValue<string>("DownstreamApi:Scopes")?.Split(' ');

            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(configuration.GetSection("AzureAd"))
                .EnableTokenAcquisitionToCallDownstreamApi(initialScopes)
                .AddDownstreamWebApi("DownstreamApi", configuration.GetSection("DownstreamApi"))
                .AddInMemoryTokenCaches();

            services.AddMicrosoftIdentityConsentHandler();

            services.AddMvc(options =>
                {
                    var policy = new AuthorizationPolicyBuilder()
                        .RequireAuthenticatedUser()
                        .Build();

                    options.Filters.Add(new AuthorizeFilter(policy));
                })
                .AddMicrosoftIdentityUI()
                .SetCompatibilityVersion(CompatibilityVersion.Version_3_0);

```

**Comment by jmprieur** [comment]
Thanks @newbiedev123 
Could you please try after .AddMvc ?
Maybe you'd also want to try AddRazor?

**Comment by newbiedev123** [comment]
@jmprieur 
Thanks for the prompt reply.

I believe you meant AddRazorPages().
I tried it, but still the same error.
           ```
 var initialScopes = configuration.GetValue<string>("DownstreamApi:Scopes")?.Split(' ');

            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(configuration.GetSection("AzureAd"))
                .EnableTokenAcquisitionToCallDownstreamApi(initialScopes)
                .AddDownstreamWebApi("DownstreamApi", configuration.GetSection("DownstreamApi"))
                .AddInMemoryTokenCaches();

            services.AddMicrosoftIdentityConsentHandler();

            services.AddMvc(options =>
                {
                    var policy = new AuthorizationPolicyBuilder()
                        .RequireAuthenticatedUser()
                        .Build();

                    options.Filters.Add(new AuthorizeFilter(policy));
                }).SetCompatibilityVersion(CompatibilityVersion.Version_3_0);

            services.AddRazorPages()
                .AddMicrosoftIdentityUI();

            services.AddMicrosoftIdentityConsentHandler();

            services.Configure<CookiePolicyOptions>(options =>
            {
                
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            services.AddCors(options =>
            {
                options.AddPolicy(
                    "Default",
                    builder =>
                    {
                        builder
                            .WithOrigins(configuration["CorsOrigin"])
                            .AllowAnyHeader()
                            .AllowAnyMethod()
                            .AllowCredentials();
                    }
                );
            });
```

**Comment by newbiedev123** [comment]
@jmprieur , so is there no other solution than adding the Blazor middleware?

**Comment by jmprieur** [comment]
@newbiedev123 not for the moment, it seems
do you mind to create a new github issue for this very specific problem?

Thanks

**Comment by newbiedev123** [comment]
@jmprieur will do, thanks.

**Comment by ataraxia89** [comment]
> 
> 
> @newbiedev123 : you can always use `MicrosoftIdentityConsentAndConditionalAccessHandler`. See https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access#in-blazor-server (this applies to other things than Blazor server)

Yeah, great, I tried to get a token and now the exception is handled, so how do I now get the token?? I still don't have what I want!!

**Comment by serge2112** [comment]
Is there any way to handle this issue or a work around for .Net Framework 4.8, Web Forms and Microsoft.Identity.Web.OWIN?
