### ISSUE TITLE
Cant find the AddDistributedSqlServerCache implementation

### ISSUE THREAD

**Issue by sowsan** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#283]
Following the instructions here to setup token cache provider for SQL. But I am not seeing an implementaiton of SQL Token Cache Provider mentioned in the Microsoft.Identity.Web

https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/Microsoft.Identity.Web/TokenCacheProviders/Distributed

Instructions here says, https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/2-WebApp-graph-user/2-2-TokenCache

Its implemented in MSALAppSqlTokenCacheProvider.cs and MSALPerUserSqlTokenCacheProvider of the Microsoft.Identity.Web project

**Comment by jmprieur** [comment]
Thanks for the feedback, @sowsan 
You need to reference the `Microsoft.Extensions.Caching.SqlServer` NuGet package. I've just updated the README.md
