### ISSUE TITLE
[Blazor server app] HttpContext is null 

### ISSUE THREAD

**Issue by sowsan** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#285]
Using the Blazor Server app and the graph API calls are working fine on the first page. When I visit the second page the corresponding graph API calls are getting the exception and it is coming from the below call stack. For some reason, HttpContext is getting null. Any hints on what is going wrong?

{"Object reference not set to an instance of an object."}

at Microsoft.Identity.Web.TokenAcquisition.<**GetAccessTokenOnBehalfOfUserAsync**>d__10.MoveNext() in C:\Users\sowmyans\source\repos\active-directory-aspnetcore-webapp-openidconnect-v2\Microsoft.Identity.Web\**TokenAcquisition.cs:line 176**

![image](https://user-images.githubusercontent.com/11544153/74158941-eeda4800-4be8-11ea-8efc-6fa16f2fc5f3.png)

**Comment by jmprieur** [comment]
Can you please share some repro steps, @sowsan ?

**Comment by sowsan** [comment]
Using the sample available here : https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/2-WebApp-graph-user/2-1-Call-MSGraph with an ASP.NET core Blazor Server side app.

1. On the landing page (index.razor) , Getting the users information using Graph API. It also show the directReport of the user. 
2. Upon click on one of the direct Reports listed it will redirect the user to a second page (ICView.razor) by passing the userId in the query string. Once Graph API tries to get the users information in this page I am getting the HttpContext as null.

**Comment by TiagoBrenck** [comment]
I was helping another developer to use Microsoft.Identity.Web in a Blazor app, and apparently it wont be possible due to Blazor's architecture. Please check https://github.com/dotnet/aspnetcore/issues/18761

**Comment by sowsan** [comment]
Thanks @TiagoBrenck . Seems that the issue is more on not tracking the exception. In my case, the httpContext is coming as null. Is there any correlation?

**Comment by TiagoBrenck** [comment]
Have you tried one of these answers? https://stackoverflow.com/questions/53817373/how-do-i-access-httpcontext-in-server-side-blazor

**Comment by sowsan** [comment]
I am getting the HttpContext on the first page and once I redirect the user to the second page is I am noticing its not available in GetAccessTokenOnBehalfOfUserAsync method. Do I need to customize the Microsoft.Identity.Web project to access the HttpContext passed by the web app using the method mentioned in the stackoverflow?.

**Comment by TiagoBrenck** [comment]
Honestly I don't have a working solution at the moment. Since Blazor has a different architecture than the MVC projects, it is understandable that the current Microsoft.Identity.Web project has issues with it.

We might create a Blazor sample in the future, but for now, it definitely needs customization in Microsoft.Identity.Web.

**Comment by sowsan** [comment]
Thank you, @TiagoBrenck

**Comment by mjnorman** [comment]
@sowsan I'm interested in your example if you have a simple repro.  I have been trying to accomplish somewhat the same in that I would like to use implicit flow to log the user in and be able to utilize Graph to fetch info.  I'm using the latest Microsoft.Idendity.Web from that same sample repo, and I am not even able to get it working from the first page (also getting a null reference, but I can't seem to find what is null).  Would you be willing to share your Startup config and any non PII config?

**Comment by jmprieur** [comment]
Transfering to Microsoft.Identity.Web

**Comment by jmprieur** [comment]
This is now fixed @sowsan @TiagoBrenck @njnorman
See https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access#in-blazor-server
