### ISSUE TITLE
[Microsoft.Identity.Web] There should be an option to have TokenAcquisitionbe a singleton 

### ISSUE THREAD

**Issue by jmprieur** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#287]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Why?

Today, TokenAcquisition is a scoped by request. See https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/ab84785cf757c2d3244090a90d563528ee4be616/Microsoft.Identity.Web/ServiceCollectionExtensions.cs#L38

There are scenarios, like using the Graph SDK, which require it to be a sigleton. This is a request from the Graph SDK team (Darrel).

### What?

Either make it a singleton all the time. I know it works, I tried it, but is there a performance hit?

Or provide an option, probably part of AddProtectedWebApiCallsWebApis and AddWebAppCallsWebApis, to let the developer specify to instanciate a TokenAcquisition service per request or a singleton.

**Comment by TiagoBrenck** [comment]
Did you try it with multiple users? I am trying to find where I read in the docs that ideally you want to have `ITokenAcquisition` scoped per http session, but I haven't found it yet. However I can see that our `TokenAcquisition` receives `IHttpContextAccessor` in the DI. I wonder if the singleton architecture would make all the subsequent calls use the same context and cause a big mess.

**Comment by TiagoBrenck** [comment]
Found it: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/High-availability#one-confidential-client-per-session

**Comment by jmprieur** [comment]
@bgavrilMS : is it our authoritative recommendation?

**Comment by jennyf19** [comment]
Now tracked in Microsoft-Identity-Web repo: https://github.com/AzureAD/microsoft-identity-web/issues/1
