### ISSUE TITLE
[Microsoft.Identity.Web] All Add... methods should propose an override with Action<MicrosoftIdentityOptions>

### ISSUE THREAD

**Issue by jmprieur** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#288]
Why?
Today all Microsoft.Identity.Web public API named Add.XXX propose an override with a config file section name. Some to propose an override with an Action<>

What?
Ensure that both overrides exists, to let use plug-in their configuration the way they want

Context:
recommended by Chris Ross/ASP.NET Core

**Comment by jennyf19** [comment]
Now tracked in microsoft identity web repo: https://github.com/AzureAD/microsoft-identity-web/issues/2
