### ISSUE TITLE
[Microsoft.Identity.Web] Microsoft.Identity.Web should use the ILogger rather than Console.Writeline

### ISSUE THREAD

**Issue by jmprieur** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#289]
***Why?***

Microsoft.Identity.Web's code uses Console.Writeline, whereas ASP.NET Core provides a ILogger interface which can be injected (by DI), and offers great logging, including for apps that would be deployed in App services

***What?***
- Inject ILogger in the constructor of the classes using Console.WriteLine
- Use ILogger instead of Console.Writeline

**Comment by jennyf19** [comment]
now tracked in microsoft identity web repo: https://github.com/AzureAD/microsoft-identity-web/issues/3
