### ISSUE TITLE
[Microsoft.Identity.Web] Identity.Web.UI should use Razor pages, not MVC

### ISSUE THREAD

**Issue by jmprieur** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#290]
***Why?***

Microsoft.Identity.Web.UI (in removeUI branch) currently uses MVC. The advise of the ASP.NET Core team is to change it to use Blazor pages because Razor pages have an extensibility model can be overridden by copy / paste in the user project, therefore replacing the pages which are provided by the library

***What?***
The advise of the ASP.NET Core team is to change MVC pages to Razor pages

**Comment by jennyf19** [comment]
now tracked in microsoft identity web repo: https://github.com/AzureAD/microsoft-identity-web/issues/4
