### ISSUE TITLE
[Microsoft.Identity.Web] SameSite browser sniffing code should be extensible

### ISSUE THREAD

**Issue by jmprieur** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#291]
Why? 
The number of browsers hit by SameSite keeps growing

What?
- Provide a way to let app developers add their favorite browser. Add some extensibility here.
- Possibly have a community project to propose the last known good browsers? 

recommendation from the ASP.NET Core team.

**Comment by TiagoBrenck** [comment]
@jmprieur it has extension options. *CookiePolicyOptionsExtensions.cs*:
```c#
        public static CookiePolicyOptions HandleSameSiteCookieCompatibility(this CookiePolicyOptions options, Func<string, bool> disallowsSameSiteNone)
        {
            options.MinimumSameSitePolicy = SameSiteMode.Unspecified;
            options.OnAppendCookie = cookieContext =>
                CheckSameSite(cookieContext.Context, cookieContext.CookieOptions, disallowsSameSiteNone);
            options.OnDeleteCookie = cookieContext =>
                CheckSameSite(cookieContext.Context, cookieContext.CookieOptions, disallowsSameSiteNone);
            return options;
        }
```

There is an overload that accepts a func, which would be the way developers can have custom browser sniffing code.

**Comment by jennyf19** [comment]
now tracked in microsoft identity web repo
