### ISSUE TITLE
[Microsoft.Identity.Web] Investigate if AuthorizeForScopes could be used Policy instead of an exception filter

### ISSUE THREAD

**Issue by jmprieur** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#292]
**Why?**
Policies work independently of ASP.NET, or even Http. They work with SignalR..
The recommendation of the ASP.NET Core team is to not embed rules in a filters
Policies can be parametrized. 

**What?**
AuthorizeForScopes might be be a Policy 
(or not, this might not work, in which case Barry wants to know)

**Resources**
=> GitHub.com/blowdart=>old workshop.

**Comment by TiagoBrenck** [comment]
I actually did some research and tests on this during the refactor, and it seems to be possible.

**Comment by jennyf19** [comment]
issue tracked in microsoft identity web repo: https://github.com/AzureAD/microsoft-identity-web/issues/17
