### ISSUE TITLE
Infinite loop when signing-in with a guest account in a single tenant application

### ISSUE THREAD

**Issue by jmprieur** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#30]
### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1. Change the appsetttings.json to set tenantId to a GUID (to have a tenanted authority). **This only reproes with a single tenant app**
2. sign-in to the app with a guest user
3. try to call Contact

### Any log messages given by the failure
There is an infinite loop

### Expected/desired behavior
you can see the information about the signed-in user

### OS and Version?
Chrome

### Mention any other details that might be useful

When calling the controller, the cache is empty. This is because the cache is keyed by the MSAL.id, and the computation of the MSAL.id is not right in the case of a guest user (tid and iod are the guest ones, not the home tenant information).

**Comment by jmprieur** [comment]
For the moment, fixed the issue with special processing for guest users
however.
GetMsalAccountId does not retrieve the right value for guest users in sigle tenant apps. Getting the home tenant id and home oid would require one more call to the STS.

**Comment by antonGritsenko** [comment]
Looks like it returns, see referenced issue above
