### ISSUE TITLE
AzureADOptions.ClientID must be a Guid

### ISSUE THREAD

**Issue by keithdv** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#305]
This isn't an issue or feature I think I am just struggling with how to use Microsoft.Identity.Web to both protect a WebAPI and get a bearer token to make a webapi call.

I set a non-guid client id like "api://myapi" as the AzureADOptions.ClientID in appsettings.json because that is the audience of the token coming in because the requested scope is "api://myapi/AScope". Works great to protect the WebApi. 

Then I try to using the Microsoft.Identity.Web library to call another api On-Behalf-Of using the example "3-WebApp-multi-APIs". I get an exception "ClientID must be a guid". Digging in when TokenAcquisition uses Microsoft.Client.Identity.ConfidentialClientApplicationBuilder it is what raises a  failure that the clientID must be a Guid. Putting libraries together JwtBearerOptions.Audience is set to AadOptions.ClientId in Microsoft.AspNetCore.Authentication.AzureAD.UI.JwtBearerOptionsConfiguration. 

I can tweak the code easy enough but I want to understand why it is assumed Audience and ClientID are a match? Does this need a fix or am I missing something???

Thanks in advance for your help!!

**Comment by jmprieur** [comment]
Hello @keithdv 
Did you checkout this sample: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API

It's a Web app calling a Web API.
(and a B2C Web app calling a B2C Web API)

Note that we changed Microsoft.Identity.Web recently and merged new code today.

**Comment by keithdv** [comment]
First, hats off for some wonderfully documented samples!
I still don't see a solution. The demo is a protected WebClient calling a protected WebApi. I'm adding another layer implementing a protected WebClient calling a protected WebApi calling a protected WebApi. I'm getting stuck calling the second WebApi. Am I missing a sample that shows this? 

I do think that if I do not set "Application ID URI" in Azure AD (App Registration=>Expose An API) and just use the clientid guid everywhere I wouldn't have this issue. But, I find descriptive URIs to be much better when debugging and demonstrating. Right now I'm trying to show using On-Behalf-Of to propagate the user identity thru the api gateway.

**Comment by jmprieur** [comment]
@keithdv : thanks for explaining. I think you'd want to have a look at the service of this sample: https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph
