### ISSUE TITLE
Why "need admin approval" is required for sample 

### ISSUE THREAD

**Issue by hejingkan2005** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#309]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [x] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**
- In "active-directory-aspnetcore-webapp-openidconnect-v2/4-WebApp-your-API/4-1-MyOrg/", run configure.ps1 to update  "TodoListScope": "api://6ca29601-4dfb-475c-bcad-fd77726500c4/access_as_user",
- Startup TodoListClient and TodoListservice project, and find it requires "admin consent" unexpectedly. From my understanding, if we should allow "user consent" instead of admin

**Expected behavior**
User consent instead of "admin consent"

**Actual behavior**
"Admin consent" popup, and I get no admin permission for tenant "microsoft.com"

**Possible Solution**

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> Windows 10

### Versions
> ASP.NET Core 3.1, of MSAL.NET

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue? yes
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview) => yes
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview) => yes
  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by hejingkan2005** [comment]
Here is what I get when starting TodoListClient:
![image](https://user-images.githubusercontent.com/14071136/75298469-8c7e7a00-586d-11ea-86db-ca5eff81713b.png)

From my understanding, we should not user content instead of admin

**Comment by TiagoBrenck** [comment]
@hejingkan2005, what you are facing is a Microsoft tenant restriction. We recommend MSFT employees to create their own test tenant, and use it instead.

**Comment by hejingkan2005** [comment]
@TiagoBrenck, thank you for your quick reply. I'm working on DevRel team, and currently my team is working on a new web API service for Microsoft account only access. So I'm expecting to use this sample to secure web API as an example. If Microsoft tenant is restricted to consent on user, do you get any other recommendation for it? Should I ask for MSFT domain admin to grant admin permission? It is not applicable to create another tenant since the user would be Microsoft employee

**Comment by TiagoBrenck** [comment]
Question answered in an internal thread
