### ISSUE TITLE
service.AddSignIn(configuration)  no overload for method AddSignIn take 1 arguments

### ISSUE THREAD

**Issue by chineseneolight** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#310]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

**Expected behavior**

**Actual behavior**

**Possible Solution**

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
> of ASP.NET Core, of MSAL.NET

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue?
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)
  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by chineseneolight** [comment]
And services.AddSignIn(configuration, null, false)  requires a receiver type of authenticationBuilder, I do not know how it works for this:              
services.AddSignIn(configuration);
                services.AddWebAppCallsProtectedWebApi(graphScopes)
                .AddInMemoryTokenCaches();

**Comment by jmprieur** [comment]
@chineseneolight : this is because the method is an extension method ?

**Comment by TiagoBrenck** [comment]
@chineseneolight for the `authenticationBuilder` question, the approach is, i.e:

```c#
services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddSignIn("AzureAd", Configuration, options => Configuration.Bind("AzureAd", options));
```

**Comment by OsirisTerje** [comment]
It would be nice if the [instructions](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal#option-2-create-the-sample-from-the-command-line) was updated to reflect this change.

**Comment by dpomBF** [comment]
Agreed. It took me a while to figure that out.

**Comment by jmprieur** [comment]
Thanks @OsirisTerje 
Fixed.

**Comment by dpomBF** [comment]
@jmprieur and here 
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-1-MyOrg#option-2-create-the-sample-from-the-command-line

**Comment by henriquebelotto** [comment]
Hello,

I have a similar issue with this "option" in my startup class.
Can you help me?

I have added the following code, from the[ B2C example](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-5-B2C)>

`            // Configuration to sign-in users with Azure AD B2C
            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddSignIn("AzureAdB2C", Configuration, options => Configuration.Bind("AzureAdB2C", options));
                //.AddSignIn("AzureAdB2C", Configuration, options => Configuration.Bind("AzureAdB2C", options));

            services.AddControllersWithViews()
                .AddMicrosoftIdentityUI();

            //Configuring appsettings section AzureAdB2C, into IOptions
            services.AddOptions();
            services.Configure<OpenIdConnectOptions>(Configuration.GetSection("AzureAdB2C"));`

However, I'm getting this error. I have added the Microsoft.Identity.Web to my project as a DLL that I got from this example, since there isn't any Nuget package for this.

In the example, it works fine when I run, but not in my project and I couldn't figure out what to do.

Thank you

![image](https://user-images.githubusercontent.com/38217514/78723851-34ba4080-78fa-11ea-8d8d-9b2bdac3262e.png)

**Comment by TiagoBrenck** [comment]
Do you have this Nuget package imported? 
```
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
```

**Comment by henriquebelotto** [comment]
Hello

Yes, I do have it.

These are some of the packages that the Startup class is using
```
using Microsoft.Extensions.Options;
using Microsoft.Identity.Web;
using Microsoft.Identity.Web.UI;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
```

What I'm wondering if the fact that I manually got the DLL from the Microsoft Identity Web and Web.UI from this folder "src\Microsoft.Identity.Web.UI\bin\Debug\netcoreapp3.1", when I ran this project, and added as reference to my project, if it somehow something got lost on the way...

**Comment by henriquebelotto** [comment]
I have the following errors related to this code.

![image](https://user-images.githubusercontent.com/38217514/78789704-80f99500-797b-11ea-996e-c8c7a9d9fb62.png)

Also, this one
![image](https://user-images.githubusercontent.com/38217514/78789749-94a4fb80-797b-11ea-9ea3-9fbcad271b39.png)

**Comment by TiagoBrenck** [comment]
If you copy and paste the 2 Identity.Web projects to your solution folder, and add them as existing projects, can you clan&build them?
