### ISSUE TITLE
Incorrect redirect URL?

### ISSUE THREAD

**Issue by kramffud** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#313]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [X] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

Follow tutorial steps as given, adding "https://localhost:44316/signin/B2C_1_sign_up_in" to the B2C SUSI User Flow Redirect URIs.

**Expected behavior**

User is presented w/ the std SUSI dialog.

**Actual behavior**

404 page not find

**Possible Solution**

Add "https://localhost:44316/signin-oidc" to the B2C SUSI User Flow Redirect URIs.

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Win 10

### Versions
> of ASP.NET Core, of MSAL.NET
ASP.NET Core

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue?
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)

Caught the alt URI address w/ Fiddler
  
### Mention any other details that might be useful

May apply to other User Flows as well.  I will be working w/ them shortly.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by TiagoBrenck** [comment]
Thanks @kramffud. I have opened a PR to fix the steps.

**Comment by kramffud** [comment]
Thank you Tiago.  I promise I won’t pester you.  But if you might permit me a moment of your time, I think I speak for others similarly confused about this Reply/Redirect URI.

I admit some degree of B2C ignorance.  But I will say that I tried it years ago and abandoned it.  Now I’ve got it working, but only after reading so many site pages, I need glasses.

My current project is an insurance agent’s portal.  We want a “Get a Quote” button on the main page.  We love that we can gather Joe Public’s name, address, etc via the B2C Sign Up form.

But when the site visitor click’s OK, we want them redirected from the main page to the Quote information forms pages.  Try as I might, I can only get B2C to authenticate the visitor, add them to the B2C AD and then – no matter what I put in the Reply URI – they are returned to the main page that requested the authentication.  Then they would have to click something else to begin the Quote data gathering process which decreases the user experience.

I have worked around that by having the “Get a Quote” button send them to the Quote Form page where I have a conditional check on User.Identity.IsAuthenticated.  If they’re not, I redirect them to the MicrosoftIdentity.Account.SignIn Action, they do their stuff and B2C then sends them back to that originating Quote Form page where they’re now IsAuthenticated and we can proceed with the process.

So, as near as I can tell, the “Reply URI” really doesn’t do what it claims to on the Azure B2C portal page, but rather provides the endpoint for authentication.  After that, no matter what “Reply/Redirect” URIs are applied (w/o signin-oidc, I just get a 404 or worse yet, and endless loop), the user is returned to the page that requested the authentication.

And why would anybody want multiple “Reply” URIs?  So confusing.

Anywho, thanks again.

Mark

**Comment by kramffud** [comment]
And I should probably mention, the experience I described is all with URIs that have a “localhost:<ssl port>” prefix.  Haven’t worked up the courage to deploy to the Web App yet.

Mark

From: Mark Duff
Sent: Monday, March 9, 2020 11:41 PM
To: Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2 <reply@reply.github.com>; Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2 <active-directory-aspnetcore-webapp-openidconnect-v2@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2] Incorrect redirect URL? (#313)

Thank you Tiago.  I promise I won’t pester you.  But if you might permit me a moment of your time, I think I speak for others similarly confused about this Reply/Redirect URI.

I admit some degree of B2C ignorance.  But I will say that I tried it years ago and abandoned it.  Now I’ve got it working, but only after reading so many site pages, I need glasses.

My current project is an insurance agent’s portal.  We want a “Get a Quote” button on the main page.  We love that we can gather Joe Public’s name, address, etc via the B2C Sign Up form.

But when the site visitor click’s OK, we want them redirected from the main page to the Quote information forms pages.  Try as I might, I can only get B2C to authenticate the visitor, add them to the B2C AD and then – no matter what I put in the Reply URI – they are returned to the main page that requested the authentication.  Then they would have to click something else to begin the Quote data gathering process which decreases the user experience.

I have worked around that by having the “Get a Quote” button send them to the Quote Form page where I have a conditional check on User.Identity.IsAuthenticated.  If they’re not, I redirect them to the MicrosoftIdentity.Account.SignIn Action, they do their stuff and B2C then sends them back to that originating Quote Form page where they’re now IsAuthenticated and we can proceed with the process.

So, as near as I can tell, the “Reply URI” really doesn’t do what it claims to on the Azure B2C portal page, but rather provides the endpoint for authentication.  After that, no matter what “Reply/Redirect” URIs are applied (w/o signin-oidc, I just get a 404 or worse yet, and endless loop), the user is returned to the page that requested the authentication.

And why would anybody want multiple “Reply” URIs?  So confusing.

Anywho, thanks again.

Mark

**Comment by TiagoBrenck** [comment]
@kramffud I am sorry to hear that. We understand that authentication is a complex topic so don't blame your reading skills haha.

The multiple reply urls on Azure Portal App Registration, is useful for customers that develop SaaS for instance. In your case, would this code snippet be the solution that you are looking for?

```c#
services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
    .AddSignIn("AzureAdB2C", Configuration, options =>
    {
        Configuration.Bind("AzureAdB2C", options);
        options.Events.OnTokenValidated = async context =>
        {
            context.Properties.RedirectUri = "https://YourQuoteUrl";
            await Task.FromResult(0);
        };
    });
```

**Comment by kramffud** [comment]
THE CLOUDS PARTED, THE SUN SHINED AND THE ANGLES SANG…

OMG YES!  Where has THAT been my whole B2C lifetime?

I ransacked the literal gigabytes of tutorials I’ve slaved through – not a whisper of that directive!

THANK YOU SO MUCH!!!

Mark

**Comment by kramffud** [comment]
…and you MUST understand the source of confusion.  The portal’s App Registration Authentication blade sure seems like it’s asking for the destination after authentication – not the destination for authentication…

[cid:image001.png@01D5F6E0.B5918DE0]

From: Mark Duff
Sent: Tuesday, March 10, 2020 1:27 PM
To: Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2 <reply@reply.github.com>; Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2 <active-directory-aspnetcore-webapp-openidconnect-v2@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2] Incorrect redirect URL? (#313)

THE CLOUDS PARTED, THE SUN SHINED AND THE ANGLES SANG…

OMG YES!  Where has THAT been my whole B2C lifetime?

I ransacked the literal gigabytes of tutorials I’ve slaved through – not a whisper of that directive!

THANK YOU SO MUCH!!!

Mark

**Comment by TiagoBrenck** [comment]
That refers to the OpenIdConnect protocol redirect uri. In case you would like to learn more about it, https://openid.net/specs/openid-connect-core-1_0.html

I am glad I could help. Have a good one.
