### ISSUE TITLE
AuthorizeForScopesAttribute.cs ArgumentNull Exception when token cache is reset

### ISSUE THREAD

**Issue by jak-hammond** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#314]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [x] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [x] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**
1) Configure authentication on the application and use the `InMemoryTokenCaches()` to handle the authentication tokens
2) Globally register the `AuthorizeForScopesAttribute`
3) Start debugging the application, complete a single authentication flow and then stop the application
4) Restart the application and navigate to an authenticated view, the cookie will still exist so the `HttpContext.User.Identity.IsAuthenticated` will return true, but when trying to acquire a token (in my case I was making a Graph API call and using the `ITokenAcquisition.GetAccessTokenForUserAsync()` method) it will fail with an argument null exception that originates inside the scopes filter

**Expected behavior**
Crash would not occur and filter would continue to function.

**Actual behavior**
Application crashes with ArgumentNullException around line 126 of `AuthorizeForScopeAttribute.cs` on the:
```
properties.SetParameter<ICollection<string>>(OpenIdConnectParameterNames.Scope,
scopes.Union(additionalBuiltInScopes).ToList());
```

**Possible Solution**
I was able fix this simply by instantiating an array if `scopes` was null but I am not sure of the wider impact this might have so the above erroneous code would become:
```
properties.SetParameter<ICollection<string>>(OpenIdConnectParameterNames.Scope,
(scopes ?? new string[0] { }).Union(additionalBuiltInScopes).ToList());
```

**Additional context/ Error codes / Screenshots**
The issue itself, from my understanding of the code, seems to come from line 85 of the `AuthorizeForScopeAttribute.cs` class where by the private class level variable `Scopes` has not been instantiated and `incrementalScopes` is then set to this null value before being passed into the `BuildAuthenticationPropertiesForIncrementalConsent` method.

I have seen, whilst researching this #240 there was a bug/feature logged asking that the cookie be removed from the HttpContext if a matching token could not be found in the cache. I assume this a drawback of the memory cache being cleared (I assume) between each debug session but for local testing it is easier to use this than a persistent instance.

Initially I used the middleware suggested in there for my solution but it could not handle incremental consent needed when I was requesting `User.Read.All` scopes which led me to discover you guys had already written an almost identical middleware that did all I needed but in the solution to the referenced issue, he seemed to be using hardcoded scope requests so this did not occur there.

### OS and Version?
macOS Catalina

### Versions
.NET Core 3.1
MSAL.NET - Not sure, I cloned the Identity.Web and Identity.Web.UI repos locally to investigate this so whatever the master branch is using as of 4th March 2020

**Comment by TiagoBrenck** [comment]
@jak-hammond Could you also share how you are using the `AuthorizeForScopes` decorator?
And what do you mean by globally register the attribute? This is not required in our samples.

**Comment by jak-hammond** [comment]
@TiagoBrenck Sure thing, I'll throw the snippet of my startup code below.

```
services.AddControllers();
services.AddRazorPages()
    .AddRazorPagesOptions(opts => 
    {
        // Authorize all Razor pages within the given folder
        opts.Conventions.AuthorizeFolder("/Authorized");
    })
    .AddMvcOptions(opts => 
    {
        // Global exception filter registered
        opts.Filters.Add(new AuthorizeForScopesAttribute());
        // Authorize Web API routes
        var policy = new AuthorizationPolicyBuilder()
            .RequireAuthenticatedUser()
            .Build();
        opts.Filters.Add(new AuthorizeFilter(policy));
    })
    .AddRazorRuntimeCompilation();

**Comment by TiagoBrenck** [comment]
So, in the samples, you will notice that we use it on top of the action result that will consume `AcquireTokenSilent` method, passing scopes (or appsettings key section that's value is the scope):

```c#
[AuthorizeForScopes(ScopeKeySection = "TodoList:TodoListScope")]
or
[AuthorizeForScopes(Scopes = new string[] { "User.Read" })]
```

If you want to have it globally registered, you must pass a scope as well.

**Comment by jak-hammond** [comment]
Okay, that makes a bit more sense for the null value I was seeing then. In relation to #240 and this filter being a form indirect workaround for it then, would you suggest just registering a global with a scope of least privilege like `User.Read`. I know it's a little off topic, but if I can solve both these issues with this one filter it would be the last hurdle in implementing all this :)

**Comment by TiagoBrenck** [comment]
Well, it depends on your scenario. If your application is only using one scope (lets say `User.Read`), then you are safe to use it on your global filter registration. If not, then you will face a bug that every time `MsalUIException` is thrown for a scope other than `User.Read`, your app will get stuck in an infinite loop.

About issue #240, we are still discussing it internally. The suggested approach of clearing the cookies, has some UX impacts. Also `MsalUIException` is not only related to token cache. You may get it if AAD requests you any conditional access (multi-factor authentication for instance) before refreshing an access token.

**Comment by jak-hammond** [comment]
Ah yes, I've seen that infinite loop a few times, okay, this at least gives me something to work with, I'll probably stick to method filters for now then and remove the global registration since the app itself isn't too big at the moment.

Thanks for the clarification on this :)
