### ISSUE TITLE
Review READMEs to reflect Microsoft.Identity.Web refactoring

### ISSUE THREAD

**Issue by TiagoBrenck** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#316]
With the refactoring on Microsoft.Identity.Web, we are not using **AzureAd.UI** methods anymore, and the samples got changed. However the READMEs are still referencing the old code or **AzureAd,UI**.

Some points to check:

 - Check if the code snippet is using 
```
services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddSignIn("AzureAd", Configuration, options => Configuration.Bind("AzureAd", options));
```
- Talk about `.AddMicrosoftIdentityUI()` or if they keep using **AzureAd.UI** mention the need to configure `AzureAdOptions`
- Some READMEs explain the `AccountController.cs` linking to **AzureAd.UI** code. We might want to also mention MicrosoftIdentityUI.

**Comment by jmprieur** [comment]
This should be done, now, @TiagoBrenck 
feel free to reopen if you disagree

cc: @jennyf19 @pmaytak
