### ISSUE TITLE
Please add an example of how to test

### ISSUE THREAD

**Issue by jamiemccrindle** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#318]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [x] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [x] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [x] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [x] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [x] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [x] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [x] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [x] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [x] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [x] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [x] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [x] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

N/A

**Expected behavior**

N/A

**Actual behavior**

N/A

**Possible Solution**

Add test cases e.g. using WebApplicationFactory

**Additional context/ Error codes / Screenshots**

N/A

### Any log messages given by the failure

N/A

### OS and Version?

N/A

### Versions

N/A

### Attempting to troubleshooting yourself:

I tried to use the examples here: https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1#mock-authentication but Azure AD auth fails before the Test handler can run.
  
### Mention any other details that might be useful

You guys are awesome. Thanks so much for the examples.

**Comment by TiagoBrenck** [comment]
Hi @jamiemccrindle, we are planning in creating a chapter to talk about unit test in this tutorial. In the mean time, you have [these tests from MSAL library](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/tree/master/tests) as a reference.

**Comment by derisen** [comment]
This is quite belated and possibly not relevant anymore but for anyone interested please follow the [tutorial series here](https://learn.microsoft.com/en-us/azure/active-directory/develop/test-automate-integration-testing).

Closing.
