### ISSUE TITLE
Implementation for React

### ISSUE THREAD

**Issue by spotnick** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#319]
Hi guys,

I really love using this solution with my ASP .Net Core projects. I´m planning to do a redesign of my application with C# as backend and React as frontend. Is there anything similar or a planned implementation for React?

Thanks a lot!

**Comment by derisen** [comment]
Hi @spotnick,

Yes, there'll be a .Net core backend single-page-app sample (possibly angular or react) very soon. You can keep an eye on [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/sample-v2-code) or search for `azure-samples/active-directory-javascript` in future.

**Comment by spotnick** [comment]
Thanks a lot!
