### ISSUE TITLE
Getting access token fails with "code already redeemed" exception, though code hasn't been used yet

### ISSUE THREAD

**Issue by Akos-T** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#325]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [x] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**
I cloned the repo and tried to make this sample work: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-1-MyOrg
For this I included the latest Microsoft.Identity.Web and Microsoft.Identity.Web.UI projects from: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/Microsoft.Identity.Web
And also changed the values in the appsettings.json (TenantId, ClientId, etc.)

**Expected behavior**
At startup I log in to get the authorization code and then the code is used to get an access token.

**Actual behavior**
On localhost:44321/signin-oidc page I see an exception saying the authorization code was already redeemed, even though i haven't used that auth code anywhere else before.
![image](https://user-images.githubusercontent.com/766068/76774863-ca076080-67a4-11ea-86c2-22b9ea47eb13.png)

**Additional context/ Error codes / Screenshots**
If I put a break point on Microsoft.Identity.Web/TokenAcquisition.cs line 133:
```
var result = await _application
                    .AcquireTokenByAuthorizationCode(scopes.Except(_scopesRequestedByMsal), context.ProtocolMessage.Code)
                    .ExecuteAsync()
                    .ConfigureAwait(false);
```
And I redeem the auth code to an access token manually from Postman, it works flawlessly. If I let the code run (without the Postman step) then I get the exception that the auth code was already redeemed.
I spent days on this and cannot seem to find the problem and/or the solution.

### OS and Version?
> Windows 10

### Versions
ASP.NET Core 3.1, MSAL.NET 4.9.0

Thank you for your help!

All the best,
Akos

**Comment by TiagoBrenck** [comment]
Hi @Akos-T, are you running the sample as is (just updating the config file)? Or do you have extra customization?

Another question is, how did you register the application on Azure Portal? Manually or via Powershell?

Thanks

**Comment by Akos-T** [comment]
Hi @TiagoBrenck,

Please ignore, we can close this issue. After posting (of course when else) I discovered that the Scope in the settings was incorrect. Nonetheless, the error message was terrible at telling me what is the problem, but that's not the samples repo's fault.

For future reference, if anyone sees the "code already redeemed" error, that not necessarily means that the code was actually used before. In this case it was because the scope was incorrect.

Anyhow, thank you for your time!

**Comment by TiagoBrenck** [comment]
@Akos-T  This is indeed very weird. Would you mind telling what scope were you using?
I will try to reproduce it here and send the results to the team responsible for the error messages. They might have a bug.

**Comment by Akos-T** [comment]
Sure. I was trying to use an Azure FHIR API.
Depending on the Active Directory App and the Azure FHIR API setup:
<ins>The correct scope:</ins> https://azurehealthcareapis.com/user_impersonation
<ins>The one I tried incorrectly:</ins> https://the-name-of-your-fhir-api.azurehealthcareapis.com/user_impersonation

p.s.: Sorry for the delay
