### ISSUE TITLE
Sentence duplicate in the README.MD

### ISSUE THREAD

**Issue by anniex325** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#326]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [x] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**
In README-incremental-instructions.md under 4-1-MyOrg, the sentences:
_in Admin consent display name type Access TodoListService-aspnetcore-webapi as a user
in Admin consent description type Accesses the TodoListService-aspnetcore-webapi Web API as a user_
_in User consent display name type Access TodoListService-aspnetcore-webapi as a user
in User consent description type Accesses the TodoListService-aspnetcore-webapi Web API as a user_

**Possible Solution**

in Admin consent display name type Access TodoListService-aspnetcore-webapi as **an admin** in Admin consent description type Accesses the TodoListService-aspnetcore-webapi Web API as **an admin**
_in User consent display name type Access TodoListService-aspnetcore-webapi as **an** user
in User consent description type Accesses the TodoListService-aspnetcore-webapi Web API as **an** user

**Additional context/ Error codes / Screenshots**

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10
### Versions
> of ASP.NET Core, of MSAL.NET
ASP.NET Core 3.1

  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@anniex325, actually the message is the same, it's just that it's addressed either to the user, or to an admin.
It would be better to say
- " the app can access the web api on your behalf" (in the case of the user consent)
- " the app can access the web api on behalf users in the tenant" (in the case of the admin consent)

**Comment by v-michaelmi** [comment]
Issue resolved with [commit 391863](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/commit/3918633c09c8f90275901939ad3844ab65a5ebb7)

Closing.
