### ISSUE TITLE
Graph api from Web api : "No account or login hint was passed to the AcquireTokenSilent call."

### ISSUE THREAD

**Issue by cedrox** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#328]
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ x] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue
I try to mix 2 samples in order to call graph API from Web API but : 

- When I try to import code from the service, I have "No account or login hint was passed to the AcquireTokenSilent call."

Add the graph api call from 
https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph/TodoListService/Controllers/TodoListController.cs

into the controller of the sample. 
Configure the app to access to Graph API 
Change startup to get TokenCacheInMemory

**Actual behavior**
When call GetAccessTokenOnBehalfOfUserFromCacheAsync, method application.GetAccountAsync return no account...

### OS and Version?
Windows 10

### Versions
> of ASP.NET Core, of MSAL.NET

**Comment by cedrox** [comment]
If we can have the same sample as https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph but for webapp and openidconnect, it will be great !

**Comment by TiagoBrenck** [comment]
Did you also include `AddProtectedApiCallsWebApis` on the WebAPI startup class?

**Comment by cedrox** [comment]
Hello @TiagoBrenck 
I try to replace line as shown bellow with no success :
![image](https://user-images.githubusercontent.com/10764310/78340513-867b6780-7596-11ea-9583-d01d932b0c28.png)

Same error

**Comment by cedrox** [comment]
Also I update the Microsoft.Identity.Web with 
  <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="6.5.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="6.5.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.5.0" />

**Comment by cedrox** [comment]
I am now facing error MsalUiRequiredException > ConsentRequired

**Comment by cedrox** [comment]
I try to connect the native client on the TodoListService-aspnetcore-webapi and it was working. 
Here are the changes that I did in the manifest of the Web Api Service :
- Add AppId in knownClientApplications
- Change  signInAudience from AzureADMyOrg to AzureADandPersonalMicrosoftAccount 
Maybe there are some other changes that I did not log. Do you think this is consistent ?

**Comment by TiagoBrenck** [comment]
Sorry @cedrox I am confused here and I didnt get your point.

Just to make sure that we are on the same page, if you want a Web API calling another Web API downstread (using on behalf of flow), the code and app registration steps for this scenario can be found here: https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph.

Could you go through this sample please?

**Comment by cedrox** [comment]
Thanks for your answer Tiago, 
I just highlighted few updates I had to do in order to have the sample [active-directory-aspnetcore-webapp-openidconnect-v2/4-WebApp-your-API/4-1-MyOrg](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-1-MyOrg) working... 
Thanks
