### ISSUE TITLE
WebApp Example Does Not Open or Load - Good Example PLEASE

### ISSUE THREAD

**Issue by clockwiseq** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#334]
Please add an 'x' for the scenario(s) where you found an issue

1. Web app that calls Microsoft Graph
   1. [X] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)

### Repro-ing the issue
Clone/Download Code and attempt to follow instructions on this page:
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/2-WebApp-graph-user/2-1-Call-MSGraph

**Repro steps**
Same as above

**Expected behavior**
WebApp-OpenIDConnect-DotNet project does not load individually nor in the solution (in VS2019 it says "(unloaded)".

**Actual behavior**
Doesn't load

**Possible Solution**
No clue

**Additional context/ Error codes / Screenshots**

I hate to just complain, but good gracious, can someone please just create a simple example of using the GraphServiceClient that actually has a code example that loads/builds/runs and documentation that supports that example?  That's all us .NET developers need/want and it's tiresome to have to constantly scour the entire internet just to find an example of how anything in the new .NET world works.

### Any log messages given by the failure
None

### OS and Version?
Windows 10 Professional

### Versions
3.1

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue?
Yes, it doesn't work

- did you go through the documentation:
Yes, it doesn't work

**Comment by dxm38** [comment]
Is it possible you have moved the folder with the solution you want to run to a different location than the other folders or have it in a particularly long file path?

**Comment by clockwiseq** [comment]
The file path is definitely long.  I will move to a shorter location and try again.



Thanks,
Keith

**Comment by TiagoBrenck** [comment]
Did you just download that specific project? Or did you clone the whole repo?
I ask that because currently, this sample is using a helper project (Microsoft.Identity.Web, and .UI) which is located in the root of the repo. They are required to get the sample built.

**Comment by jmprieur** [comment]
@clockwiseq : our samples have Continuous integration (See the build badge which builds the whole repo: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#tutorial---enable-your-web-apps-to-sign-in-users-and-call-apis-with-the-microsoft-identity-platform-for-developers)

You probably want to copy the folder for the repo close to the root of your hard drive, and rename this folder if this is too long. This definitively load.

Something that also happened to me in the past is trying to open the solution from the zip file ... but I suppose that's not what happens here.

Proposing to close this issue as I think we gave you insights
Feel free to reopen if you disagree.
