### ISSUE TITLE
Error while building app

### ISSUE THREAD

**Issue by Prashant1119** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#339]
MSB3713	The file "obj\Debug\netcoreapp3.1\WebApp-OpenIDConnect-DotNet.MvcApplicationPartsAssemblyInfo.cs" could not be created. Could not find a part of the path 'C:\Users\jjadhap5\Downloads\active-directory-aspnetcore-webapp-openidconnect-v2-master (1)\active-directory-aspnetcore-webapp-openidconnect-v2-master\1-WebApp-OIDC\1-1-MyOrg\obj\Debug\netcoreapp3.1\WebApp-OpenIDConnect-DotNet.MvcApplicationPartsAssemblyInfo.cs'.	WebApp-OpenIDConnect-DotNet	C:\Program Files\dotnet\sdk\3.1.201\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.MvcApplicationPartsDiscovery.targets	65

**Comment by jmprieur** [comment]
@Prashant1119 
I suspect that you've been hiting the long names issue on Windows (the paths have a limited length)

you might want to move the content of `C:\Users\jjadhap5\Downloads\active-directory-aspnetcore-webapp-openidconnect-v2-master (1)\active-directory-aspnetcore-webapp-openidconnect-v2-master` to a location closer to the root of your hard drive

for instance "C:\Users\jjadhap5\Downloads\webapp"

**Comment by Prashant1119** [comment]
@jmprieur  oh well its working great thank you so much!!!!!
