### ISSUE TITLE
trying to just display the name of the user only to store it in my model class

### ISSUE THREAD

**Issue by jsjanows1** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#349]
I've successfully implemented this code to get all the user information.  I really just want to be able to use this code to just pull the user name / email and store it into a model class.  How can I do this?  I'm new to this ASP.Net framework as well as this API but the things I've tried don't seem to work? I'm not passing to a view, I want to pass information to another class.  Please advise :

https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/2-WebApp-graph-user/2-1-Call-MSGraph

**Comment by jmprieur** [comment]
@jsjanows1 : did you try this sample: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-1-MyOrg

**Comment by jmprieur** [comment]
Closing, as I believed I've answered
feel free to reopen
