### ISSUE TITLE
signin-oidc returning 404 for 4-WebApp-your-API/4-2-B2C example

### ISSUE THREAD

**Issue by AndrewDGrant** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#350]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ X] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

Setup the app in B2C in our tenancy with reply URL https://localhost:44316/signin-oidc

appsettings set to 

 "AzureAdB2C": {
    "Instance": "https://myapp.b2clogin.com",
    "ClientId": "XXXXXXXXXXXXXXXX",
    "Domain": "myapp.onmicrosoft.com",
    "SignUpSignInPolicyId": "b2c_1_signup",
    "ResetPasswordPolicyId": "b2c_1_reset",
    "EditProfilePolicyId": "b2c_1_edit_profile"
  },

**Expected behavior**
Expect to see the microsoft login page

**Actual behavior**
blank page with 404

**Possible Solution**

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET https://localhost:5000/  
info: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[7]
      OpenIdConnect was not authenticated. Failure message: Not authenticated
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed.
info: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[12]
      AuthenticationScheme: OpenIdConnect was challenged.
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
MacOS Moave

### Versions
> of ASP.NET Core, of MSAL.NET
.NET Core 3.1 MS Identity0.1.3
### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue?
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)
  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@AndrewDGrant how do you launch your app? dotnet run?
 Did you have a look at the launchsettings.json in the properties folder? do you navigate to the right URL in your browser?

**Comment by AndrewDGrant** [comment]
> @AndrewDGrant how do you launch your app? dotnet run?
> 
>  Did you have a look at the launchsettings.json in the properties folder? do you navigate to the right URL in your browser?
> 
> 

@jmprieur Yes I launch with dotnet run via rider. I did look at and modify the launchsettings.json file in the project. My B2C tenancy and app work fine with the 1-WebApp-OIDC example btw.

**Comment by TiagoBrenck** [comment]
It looks like you have a reply url mismatch? 
In the error message is saying that your are using port 5000, but your registration in for 44316.

Could you double check that?

**Comment by AndrewDGrant** [comment]
> It looks like you have a reply url mismatch? 
> 
> In the error message is saying that your are using port 5000, but your registration in for 44316.
> 
> 
> 
> Could you double check that?
> 
> 

@TiagoBrenk There are two .NET Core apps in this example, the front end listens on port 5000, the backend on port 44316. Do I need to register both with the app in B2C or just the front end or just the backend?

**Comment by TiagoBrenck** [comment]
Just the front end actually, and the reply url should end with `/signin-oidc`

**Comment by AndrewDGrant** [comment]
> Just the front end actually, and the reply url should end with `/signin-oidc`

Thanks Tiago, that did the trick. Could you change the README.md file instructions to match the port in the launchSettings.json for the client. They don't actually match either but were closer to the server port than client port or if you prefer, I can modify and create a pull request.

**Comment by AndrewDGrant** [comment]
Client web app is working fine, thanks for your help. I am now getting a 403 forbidden on the WebApi when I try to display the todo list. One difference from the README.md, I have the TodoListScope set to the scope path from the azure portal i.e. https://<appname>.onmicrosoft.com/<app id>/user_impersonation rather than app://<appid>/user_impersonation. Using a client secret from my B2C app page.

**Comment by jmprieur** [comment]
You need to use the scopes that are provided in the portal. The portal displays the fully qualified scopes. That's the one you need to use, @AndrewDGrant

**Comment by AndrewDGrant** [comment]
My issue was caused by the following line on the server side todo list controller:

[Authorize(Policy = "ReadScope")]

The instructions have the todo list scope set to user_impersonation. If I change the ReadScope policy from read to user_impersonation in the Configure services function it works. 

options.AddPolicy("ReadScope",
                    policy => policy.Requirements.Add(new ScopesRequirement("user_impersonation")));

What is the correct way to resolve this issue? Thanks.

**Comment by TiagoBrenck** [comment]
@AndrewDGrant the sample is pre-configured to run out of the box, so the values like ClientId, Domain, Secret, Policies and TodoListScope, are accordingly to the app registered on our B2C playground (Fabrikam).

If you want to create your own client app and web api, you must update the config values accordingly to your configurations. So, when you register your web api app, you will have to create a scope (on Expose an API blade) and you can give it the name that you wants (it could be read, user_impersonation, access_as_user, w/e you want to name it), however you must pay attention to update the pre-configured sample to match the values and name that you registered.

So, there is no right or wrong name for scope. If you want to name your scope "read", then the policy requirements will already match the value, but if you name it "user_impersonation" also change the value on the policy requirement.

Does that clarify a bit more the sample?

**Comment by AndrewDGrant** [comment]
@TiagoBrenck it does clarify the sample yes. The problem, I think, is the documentation is confusing and incomplete. The user_impersonation scope name was something I got from the README-incremental-instructions.md. Scopes aren't mentioned at all in the main README.md file.
