### ISSUE TITLE
Azure AD use Access Token with Custom API not working

### ISSUE THREAD

**Issue by damienbod** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#354]
I am trying to login using Azure AD and use Azure AD to authorize my access token in an ASP.NET Core API project which users the user access token. 

UI APP => ASP.NET Core
API => ASP.NET Core

The login UI app works without problem. I use Code Flow with PKCE and I receive my tokens back.

Problem: I receive an access_token with the following format:

```
PAQABAAAAAAAm-06blBE1TpVMil8KPQ41- ...
```

How can I validate this in a WEB API ASP.NET Core application. None of the examples work or use a token which is not a JWT Bearer token. I need to use this token to access the API. Can I configure this to return a JWT token?  I need an user access token with an email and cannot use the CC flow. 

If not, how can I set this to authenticate using Azure AD?  

Here's the API exception:

```
Bearer was not authenticated. Failure message: No SecurityTokenValidator available for token: PAQABAAAAAAAm-06blBE1TpVMil8KPQ41-qsp2pwsugTW3v99OhL7D7EKXg9dxWYBwlmXNuAuSPjcaRvgHJPJcipwXPw3D5jxyu8g_NK7
```

Greetings Damien

**Comment by damienbod** [comment]
Some extra info:

When I request the access token using

```
https://login.microsoftonline.com/{tenantId}/v2.0
```

with the id_token token flow, then I get a JWT Bearer access token back which can be used. But I would like to use best practice and the Code Flow with PKCE.

**Comment by TiagoBrenck** [comment]
Is your UI App also registered in AzureAD?

**Comment by damienbod** [comment]
@TiagoBrenck yes,

```
services.AddAuthentication(options =>
{
	options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
	options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
})
.AddCookie()
.AddOpenIdConnect(options =>
{
   options.ClientId = "clientId";
   options.ClientSecret = "secret";
   options.RemoteAuthenticationTimeout = TimeSpan.FromSeconds(30);
   options.Authority =   "https://login.microsoftonline.com/{tenent}"; 
   options.ResponseType = "code";
   options.UsePkce = true;
   options.SaveTokens = true;
   options.Scope.Add("profile");
   options.Scope.Add("email");
   options.Scope.Add("offline_access");

   options.SaveTokens = true;
   options.GetClaimsFromUserInfoEndpoint = true;
   options.ClaimActions.MapUniqueJsonKey("preferred_username", "preferred_username");
   options.ClaimActions.MapUniqueJsonKey("gender", "gender");
   options.ClaimActions.MapUniqueJsonKey("email", "email");
   options.TokenValidationParameters = new TokenValidationParameters
   {
	   ValidateIssuer = false, 
	   NameClaimType = "email",
   };
   options.Prompt = "login"; // login, consent
});
```

**Comment by TiagoBrenck** [comment]
Ok, and do you have token encryption on the web api configuration on AzureAD?
I want to understand why your token is not JWT.

**Comment by damienbod** [comment]
@TiagoBrenck thanks for your help. Here's my manifest from the Azure AD App registration:

```
{
	"id": "376d480c-e18a-4d73-8ec8-34bd927f4099",
	"acceptMappedClaims": null,
	"accessTokenAcceptedVersion": 2,
	"addIns": [],
	"allowPublicClient": null,
	"appId": "ce820eb5-fbfb-4c83-bdad-8cd0e9e02ccd",
	"appRoles": [],
	"oauth2AllowUrlPathMatching": false,
	"createdDateTime": "2020-05-26T17:59:22Z",
	"groupMembershipClaims": "None",
	"identifierUris": [
		"api://ce820eb5-fbfb-4c83-bdad-8cd0e9e02ccd"
	],
	"informationalUrls": {
		"termsOfService": null,
		"support": null,
		"privacy": null,
		"marketing": null
	},
	"keyCredentials": [],
	"knownClientApplications": [],
	"logoUrl": null,
	"logoutUrl": "https://localhost:44307/signout-callback-oidc",
	"name": "GeberitDemo",
	"oauth2AllowIdTokenImplicitFlow": true,
	"oauth2AllowImplicitFlow": true,
	"oauth2Permissions": [],
	"oauth2RequirePostResponse": false,
	"optionalClaims": {
		"idToken": [
			{
				"name": "email",
				"source": null,
				"essential": false,
				"additionalProperties": []
			}
		],
		"accessToken": [
			{
				"name": "email",
				"source": null,
				"essential": false,
				"additionalProperties": []
			}
		],
		"saml2Token": []
	},
	"orgRestrictions": [],
	"parentalControlSettings": {
		"countriesBlockedForMinors": [],
		"legalAgeGroupRule": "Allow"
	},
	"passwordCredentials": [
		{
			"customKeyIdentifier": null,
			"endDate": "2299-12-30T23:00:00Z",
			"keyId": "0391c164-3e26-4a3b-a1a9-cb3fd894661d",
			"startDate": "2020-05-26T18:06:12.705Z",
			"value": null,
			"createdOn": "2020-05-26T18:06:12.7766605Z",
			"hint": "8~Q",
			"displayName": "demo"
		}
	],
	"preAuthorizedApplications": [],
	"publisherDomain": "damienbodhotmail.onmicrosoft.com",
	"replyUrlsWithType": [
		{
			"url": "http://localhost:4200/",
			"type": "Web"
		},
		{
			"url": "https://localhost:4200",
			"type": "InstalledClient"
		},
		{
			"url": "https://localhost:44347",
			"type": "Spa"
		},
		{
			"url": "https://localhost:44307/signin-oidc",
			"type": "Web"
		}
	],
	"requiredResourceAccess": [
		{
			"resourceAppId": "00000003-0000-0000-c000-000000000000",
			"resourceAccess": [
				{
					"id": "64a6cdd6-aab1-4aaf-94b8-3cc8405e90d0",
					"type": "Scope"
				},
				{
					"id": "7427e0e9-2fba-42fe-b0c0-848c9e6a8182",
					"type": "Scope"
				},
				{
					"id": "37f7f235-527c-4136-accd-4a02d197296e",
					"type": "Scope"
				},
				{
					"id": "14dad69e-099b-42c9-810b-d002981feec1",
					"type": "Scope"
				},
				{
					"id": "e1fe6dd8-ba31-4d61-89e7-88639da4683d",
					"type": "Scope"
				}
			]
		}
	],
	"samlMetadataUrl": null,
	"signInUrl": null,
	"signInAudience": "AzureADMultipleOrgs",
	"tags": [],
	"tokenEncryptionKeyId": null,
	"verifiedPublisher": {
		"displayName": null,
		"verifiedPublisherId": null,
		"addedDateTime": null
	}
}
```

**Comment by TiagoBrenck** [comment]
@jmprieur @kalyankrishna1 could you help me identify why the token received is not JWT?

**Comment by TiagoBrenck** [comment]
@damienbod apparently you are missing the configuration for `OnAuthorizationCodeReceived`. The token that you are getting is actually the authorization code, that needs to be exchanged to an access token with another call. I would recommend checking the sample, https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-1-MyOrg, for that. And highly recommend using Microsoft.Identity.Web.

Let us know if you need more help

**Comment by damienbod** [comment]
Thanks for your feedback. I have tried the Azure AD with 2 certified clients, which work with all OIDC servers... Strange that this does not work with Azure. I believe I do not need the 'OnAuthorizationCodeReceived' unless Azure does something non conform.  I'll try this example and I have already tried using the `Microsoft.Identity.Web` but it was doing a implicit flow request which is no longer best practice.

Greetings Damien

**Comment by TiagoBrenck** [comment]
So, *Microsoft.Identity.Web* doesnt control which flow to use. The flow is a reflection of you app registration on Azure Portal. 

From your manifest, I could check this `"oauth2AllowImplicitFlow": true,`, so there is the implicit flow configured. If you dont want implicit flow, and indeed is not secure, please update this property (which can also be done in the UI).

**Comment by damienbod** [comment]
@TiagoBrenck Thanks for your help, I have everything works now. The example put me on the right path. Thanks

My main proble was that do not configure the scope on the App Registration `api://{clientId}/access_as_user`

Then the `Microsoft.Identity.Web` uses the `code id_token` flow, I used the 1st example fromt he same repo which uses the Implcit Flow. `code id_token`  is fine for me. 

The Code Flow with PKCE does not work like before, so this is still open, but I don't need this. I have 2 clients for the same API, the ASP.NET Core client with the backend will use the hybrid flow, and the SPA app will use the 'id_token token' flow because of the Code Flow with PKCe not working.

All my .NET Core APPs will now use  `Microsoft.Identity.Web` 

So for me everything is working, thanks for your help. I think it would be good to get the Code flow with PKCE working as more and more SPAs use this, but for now I can stick with the Implicit Flow for SPAs.

Greetings Damien

**Comment by TiagoBrenck** [comment]
There is this sample that shows PKCE on SPA: https://github.com/Azure-Samples/ms-identity-javascript-v2
