### ISSUE TITLE
Exception error when configure OpenIdConnectOptions and add Events 

### ISSUE THREAD

**Issue by alilouchka** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#356]
I am trying to add some events in OpenIdConnectOptions in ASP Core app : 
after adding  some events in options : 

` services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
            {
                Configuration.Bind("AzureAdB2C", options);
                options.Events = new OpenIdConnectEvents
                {
                    OnSignedOutCallbackRedirect = async context =>
                    {
                        context.Response.Redirect("/Home");
                        context.HandleResponse();
                        await Task.CompletedTask;
                    }
                };
            });
`

I am getting the exception "{"No account or login hint was passed to the AcquireTokenSilent call."}" when i try to get an access token. 

But if I let only the Configuration without adding events options : 

`  services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
            {
                Configuration.Bind("AzureAdB2C", options);
            });`

the access token is received without problems! 

Do you have any solution for this problem please ?!! 

Thank you , 

Ali

**Comment by TiagoBrenck** [comment]
Hi @alilouchka 

When you sign-out, the MSAL token cache for that user is removed. Did you add any code in *Home/Index* that tries to acquire an access token? Also, did you decorate the action with `[AllowAnonymous]`?

**Comment by alilouchka** [comment]
> Hi @alilouchka
> 
> When you sign-out, the MSAL token cache for that user is removed. Did you add any code in _Home/Index_ that tries to acquire an access token? Also, did you decorate the action with `[AllowAnonymous]`?

Hi @TiagoBrenck 

No I am not using any code to acquire an access token in my Home controller. and I am not using the [Authorize] decorator in it.
I am getting the error 'No account or login hint was passed to the AcquireTokenSilent call.' after restarting my app or after a while. 

I used the same configuration that are in Startup of the project active-directory-aspnetcore-webapp-openidconnect-v2/4-WebApp-your-API/4-2-B2C/ 

I thought that adding     services.AddDistributedMemoryCache(); will solve the problem but it didn't.

**Comment by TiagoBrenck** [comment]
`services.AddDistributedMemoryCache();` is definitely needed to configure the token cache provider.   

Then, take a look at TodoListController, on top of *Index* we decorate it with `[AuthorizeForScopes(ScopeKeySection = "TodoList:TodoListScope")]`

You might want to add this on top of the action result (or controller) that you are acquiring a token silently. This attribute will handle `MsalUIRequiredException` by sending an authorization request, so it can bootstrap the token cache again.

Let me know if you need more guidance.

**Comment by alilouchka** [comment]
Hi @TiagoBrenck 

Thank you, yes we have to add 
`[AuthorizeForScopes(ScopeKeySection = "TodoList:TodoListScope")]` in the client controller. 

I had to edit my startup too in order to add some events, and this is how my ConfigureServices  looks now : 


` 



            services.AddDistributedMemoryCache();
            services.AddOptions();
            services.AddSignIn(Configuration, "AzureAdB2C");

            // This is required to be instantiated before the OpenIdConnectOptions starts getting configured.
            // By default, the claims mapping will map claim names in the old format to accommodate older SAML applications.
            // 'http://schemas.microsoft.com/ws/2008/06/identity/claims/role' instead of 'roles'
            // This flag ensures that the ClaimsIdentity claims collection will be built from the claims in the token
            // JwtSecurityTokenHandler.DefaultMapInboundClaims = false;

            // Token acquisition service based on MSAL.NET
            // and chosen token cache implementation
            services.AddWebAppCallsProtectedWebApi(Configuration, new string[] { Configuration["Bim3DViewerApiScopes:bim3dviewer"] }, configSectionName: "AzureAdB2C")
                    .AddInMemoryTokenCaches();

            // Add APIs
            services.AddBimViewerService(Configuration);

            services.AddControllersWithViews()
                  .AddMicrosoftIdentityUI();
            services.AddRazorPages();
            //Configuring appsettings section AzureAdB2C, into IOptions
            services.AddOptions();
            services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
            {
                Configuration.Bind("AzureAdB2C", options);
                options.Events.OnSignedOutCallbackRedirect = async context =>
                    {
                        context.Response.Redirect("/Home");
                        context.HandleResponse();
                        await Task.CompletedTask;
                    };
            });
        `
