### ISSUE TITLE
"GetAccessTokenForUser" fails when most recent token was not obtained through the signin policy

### ISSUE THREAD

**Issue by jackheywood** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#357]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [x] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

I've implemented authentication between a Client and Web API build in ASP.NET Core using using the [Azure AD B2C code as an example](https://github.com/jackheywood/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C).

I have three custom policies used by B2C, `B2C_1A_signin`, `B2C_1A_PasswordReset` and `B2C_1A_ProfileEit` which are set correctly in `appsettings.json`.

All of these are configured to return exactly the same claims in the JWT once the User Journey has been completed, the only differences being the timestamps and the value of the `tfp` claim, which is set to the value of the policy a user has returned to the website from (e.g. `B2C_1A_ProfileEdit`).

**Expected behavior**
I expect that any calls to my Web API from the Client will be able to silently acquire an access token using `tokenAcquisition.GetAccessTokenForUserAsync` no matter what `tfp` value is present in the cached access token.

**Actual behavior**
`tokenAcquisition.GetAccessTokenForUserAsync` only works as expected when the `tfp` value of my access token is the same as my `SignUpSignInPolicyId`, in this case `B2C_1A_signin`.

If the most recent access token has not been acquired from the `SignUpSignInPolicy`, the `GetAccessTokenForUserAsync` call fails with the error message:

```
MsalUiRequiredException: No account or login hint was passed to the AcquireTokenSilent call.
```

In other words, if I log into the application normally I can make as many API requests as I like until I try to edit my profile, at which point all of the attempts to access the API fail because the `tfp` claim of my access token is no longer `B2C_1A_signin`.

**Additional context/ Error codes / Screenshots**

I've noticed that if I upload my non-signin custom policies and hardcode the default `tfp` claim values to `B2C_1A_signin` then the error stops occurring and everything works fine, i.e. changing

```
<OutputClaim ClaimTypeReferenceId="trustFrameworkPolicy" Required="true" DefaultValue="{policy}" />
```

to

```
<OutputClaim ClaimTypeReferenceId="trustFrameworkPolicy" Required="true" DefaultValue="B2C_1A_signin" />
```

This seems like a terribly messy work around.

Am I missing some configuration step that's not allowing the `GetAccessTokenForUserAsync` method to obtain tokens from policies which aren't presenting as the default SignUpSignInPolicy, in which case the **documentation isn't very clear**, or is this a **genuine bug**?

### Any log messages given by the failure

Full stack trace:

```
MsalUiRequiredException: No account or login hint was passed to the AcquireTokenSilent call.
Microsoft.Identity.Client.AcquireTokenSilentParameterBuilder.Validate()
Microsoft.Identity.Client.AbstractAcquireTokenParameterBuilder<T>.ValidateAndCalculateApiId()
Microsoft.Identity.Client.AbstractClientAppBaseAcquireTokenParameterBuilder<T>.ExecuteAsync(CancellationToken cancellationToken)
Microsoft.Identity.Client.AbstractAcquireTokenParameterBuilder<T>.ExecuteAsync()
Microsoft.Identity.Web.TokenAcquisition.GetAccessTokenOnBehalfOfUserFromCacheAsync(IConfidentialClientApplication application, IAccount account, IEnumerable<string> scopes, string tenant)
Microsoft.Identity.Web.TokenAcquisition.GetAccessTokenOnBehalfOfUserFromCacheAsync(IConfidentialClientApplication application, ClaimsPrincipal claimsPrincipal, IEnumerable<string> scopes, string tenant)
Microsoft.Identity.Web.TokenAcquisition.GetAccessTokenForUserAsync(IEnumerable<string> scopes, string tenant)
Microsoft.Identity.Web.TokenAcquisition.GetAccessTokenForUserAsync(IEnumerable<string> scopes, string tenant)
ExternalWebApp.Helpers.ApiClient.<PrepareAuthenticatedClient>g__GetToken|4_0() in ApiClient.cs
```
where `PrepareAuthenticatedClient` is:

```
private void PrepareAuthenticatedClient()
{
    async Task<string> GetToken() =>
        await _tokenAcquisition.GetAccessTokenForUserAsync(new[] { _configuration["ApiScope"] });

    var accessToken = GetToken().Result;

    DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
}
```

### OS and Version?
Windows 10

### Versions
ASP.NET Core 3.1

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue?
Yes
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
   Yes
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)
   Yes
  
### Mention any other details that might be useful

Example working JWT:
```
{
  "typ": "JWT",
  "alg": "RS256",
  "kid": "abcdefghijklmnopqrstuvwxyz"
}.{
  "exp": 1590774225,
  "nbf": 1590770625,
  "ver": "1.0",
  "iss": "https://tenantname.b2clogin.com/example-id-1/v2.0/",
  "sub": "example-id-2",
  "aud": "example-id-3,
  "nonce": "defaultNonce",
  "iat": 1590770625,
  "auth_time": 1590770625,
  "oid": "example-id-2",
  "name": "Jack Heywood",
  "tid": "example0id-1",
  "tfp": "B2C_1A_signin"
}.[Signature]
```
Example broken JWT:
```
{
  "typ": "JWT",
  "alg": "RS256",
  "kid": "example-kid"
}.{
  "exp": 1590774180,
  "nbf": 1590770580,
  "ver": "1.0",
  "iss": "https://tenantname.b2clogin.com/example-id-1/v2.0/",
  "sub": "example-id-2",
  "aud": "example-id-3",
  "nonce": "defaultNonce",
  "iat": 1590770580,
  "auth_time": 1590770580,
  "oid": "example-id-2",
  "name": "Jack Heywood",
  "tid": "example-id-1,
  "tfp": "B2C_1A_ProfileEdit"
}.[Signature]
```

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by TiagoBrenck** [comment]
@jennyf19 @pmaytak could you take a look in that? 
Microsoft.Identity.Web might need to be adjusted.

**Comment by jennyf19** [comment]
thanks @TiagoBrenck we are working on fixing the b2c devex all up. have added the issue in identity web for tracking. 
cc: @jackheywood
