### ISSUE TITLE
When I try to call TodoListService I receive an error 401 Bearer error="invalid_token", error_description="The audience 'https://****/*** is invalid"

### ISSUE THREAD

**Issue by Steeve13011** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#358]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
1. [ ] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)

### Repro-ing the issue

**Repro steps**

I registred the TodoListService-aspnetcore-webapi with following permissions :
- Microsoft Graph
  - Email
  - offline_access
  - OpenID
- TodoListService-aspnetcore-webapi
  - access_as_user (like described in your documention)

In authentication step: 
  1) I registred 2 redirect URIs 
     https://localhost:44321/signin-oidc and https://localhost:44321
  2) Logout Url https://localhost:44321/signout-oidc.
  3) I chose the option _Accounts in this organizational directory only_ and checked _ID tokens_

In the visual studio configuration : 
For the TodoListClient projet I didn't change the code but I integrated my Azure Configuration in the appsettings.json file like this:
 "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "******.onmicrosoft.com",
    "TenantId": "****************",  // My tenant Organisation ID
    "ClientId": "**********************", // The application ID of TodoListService-aspnetcore-webapi
    "CallbackPath": "/signin-oidc",
    "SignedOutCallbackPath ": "/signout-callback-oidc",

    // To call an API
    "ClientSecret": "**************" The client secret of TodoListService-aspnetcore-webapi
  },
  "TodoList": {
    "TodoListScope": "https://MyOrganisation/The application ID of TodoListService-aspnetcore-webapi/access_as_user",
    "TodoListBaseAddress": "https://localhost:44351"

For the TodoListService projet I use the same configuration:
 "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "******.onmicrosoft.com",
    "TenantId": "****************",  // My tenant Organisation ID
    "ClientId": "**********************", // The application ID of TodoListService-aspnetcore-webapi

The authentication works well but in debug mode when I click on TodoList menu the function of controller Task<IEnumerable<Todo>> GetAsync() return the following response :
WWW-Authenticate: Bearer error="invalid_token", error_description="The audience 'https://********/**************' is invalid"

I followed this documentation (https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/4-WebApp-your-API/4-1-MyOrg/README.md) and I don't undestand why I have this error.

Thanks for your help.

### OS and Version?
> Windows 10

### Versions
> of ASP.NET Core 3.1, of MSAL.NET

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by TiagoBrenck** [comment]
Hi @Steeve13011 

This is because `Microsoft.Identity.Web` configuration for our web api, has a default audience validation, but it checks only for the pattern, `api://<you_app_id>`. I could notice that you registered your api with `https://<yourDomain>`.

There is nothing wrong in using the https pattern. So you basically have two options here:

1. Change the web api identifier uri to: `api://<your_app_id>` and leave the code as is.
2. Or leave the app registration as is, and add this to you web api startup.cs:

```c#
services.Configure<OpenIdConnectOptions>(options =>
{
    options.TokenValidationParameters.ValidAudience = "https://<your_audience>";
});
``` 

Let me know if you need more help.

**Comment by Steeve13011** [comment]
Hi @TiagoBrenck,

Thanks very much for your answer. 
In fact, I understood where the problem comes from. We have two azure portals. The first is an Azure AD V2 tenant and the second to an Azure AD B2C tenant. I tried your example with an Azure AD B2C thinking that it was only a complement to Azure AD V2. Your project works very well with an Azure AD V2, I tested it yesterday on the other tenant. The Azure AD V2 token must be kept for some elements of our infrastructure such as Azure Analysis Services but the flexibility of Azure AD B2C is interesting for the applications.
The scope of api Azure AD B2C uses this format **https://<myDomain>/<my_app_id>** and Azure AD V2 uses the format **api://<my_app_id>**.
 I am going to try to force the audience validation.

**Comment by jmprieur** [comment]
@Steeve13011 : did you have a look at using Microsoft.Identity.Web with B2C:

You have 2 test apps here (samples): https://github.com/AzureAD/microsoft-identity-web/tree/master/tests/B2CWebAppCallsWebApi

Also in this repo you have:
- How to sign-in to a Web app with B2C: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-5-B2C
- B2C Web app calling a B2C Web API: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C

**Comment by jmprieur** [comment]
@Steeve13011 : proposing to close this issue as I think we answered
Feel free to reopen if you disagree

**Comment by jmprieur** [comment]
@Steeve13011 : note that you can set the Audience property in the appconfig.json of your Web API.
See [What if the App ID URI of your application is not api://{ClientID}](https://github.com/AzureAD/microsoft-identity-web/wiki/web-apis#what-if-the-app-id-uri-of-your-application-is-not-apiclientid)

cc: @TiagoBrenck
