### ISSUE TITLE
Using Authorization code flow to signin users?

### ISSUE THREAD

**Issue by santhoshbomma** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#360]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [x] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

I see that the sample is using implicit grant flow

**Expected behavior**
As per [docs ](https://docs.microsoft.com/en-gb/azure/active-directory/develop/authentication-flows-app-scenarios#scenarios-and-supported-authentication-flows)here, should it use auth code flow?

**Actual behavior**
I would expect the sample use an authcode flow, as this is not a js app

**Possible Solution**

**Additional context/ Error codes / Screenshots**
![image](https://user-images.githubusercontent.com/25674017/84230637-48705780-aaa1-11ea-99b9-4a0fefe10bed.png)

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
> of ASP.NET Core, of MSAL.NET

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue?
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)
  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@santhoshbomma 
thanks for your feedback

Actually this sample does use the **auth code flow** and **not** the implicit flow. It's just that it also leverages the [ID Token](https://docs.microsoft.com/azure/active-directory/develop/id-tokens), which is improperly classified as part of implicit flow in the app registration portal.

I fixed the README.md you pointed to (1.2)

@kalyankrishna1 @TiagoBrenck @Shama-K
- Please fix the other ones: See https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/search?q=implicit&unscoped_q=implicit for all the references.
- Also the app creation scripts should require **oauth2AllowIdTokenImplicitFlow**, but NOT **oauth2AllowImplicitFlow**: Please fix the 1-1, 1-2, 1-3 and 1-4, and also the generator if needed.

**Comment by jennyf19** [comment]
@santhoshbomma looks like this was answered...feel free to reopen if needed.

**Comment by nikosft** [comment]
@jmprieur I believe you are wrong. Auth code grant requires client authentication and this sample is not configured with a client secret. The sample does implicit grant (which btw is considered insecure)

**Comment by jmprieur** [comment]
@nikosft : you don't need client credentials if you don't want to redeem the auth code. In the case of the chapters where you call a downstream web API you would need a client secret, but if you just sign-in users, you don't need any (first leg of the auth code flow)

**Comment by nikosft** [comment]
Dear @jmprieur 
I checked the provided sample and it  is doing implicit flow. If you see the request to the authorization server it says:

```
response_type=id_token
```
This is the the parameter used in [OpenID connect  authorization with implicit flow](https://openid.net/specs/openid-connect-core-1_0.html#ImplicitFlowAuth) which is [not secure](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics-19#section-2.1.2) and [not recommended](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow#prefer-the-auth-code-flow).
So if the ADB2C application is not configured with implicit flow it will fail.

An authorization code flow includes `response_type=code` (see also [OpenID connect specification](https://openid.net/specs/openid-connect-core-1_0.html#CodeFlowSteps)) So I believe that this issue should be re-opened (cc @jennyf19 ). In order to force OpenID connect with the authorization code flow, the ClientSecret must be provided and the code in Startup.CS should like something like this

```
services.AddMicrosoftIdentityWebAppAuthentication(Configuration)
                .EnableTokenAcquisitionToCallDownstreamApi()
                .AddInMemoryTokenCaches();
```

With respect  to your comment. The auth code **MUST** be exchanged with the token (see [specs](https://openid.net/specs/openid-connect-core-1_0.html#TokenRequest)). The auth code by itself is just a random string and no assumptions must be made about it. There is no "one legged auth code flow".
