### ISSUE TITLE
Check user on my database after Azure B2C sign in

### ISSUE THREAD

**Issue by camilastu** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#362]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [x] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

>----------------------------------------------------------------

I am trying to do a user check on my database after user signin on Azure B2C. I already try a few thing like:

1.  Use CallbackPath to call a controller and do the checks I want. Once I changed the CallbackPath after sign in I get in a infinite loop.
2. Use OnAuthorizationCodeReceived but for some reason it is not even building. I am getting "Cannot convert lambda expression to type 'string' because it is not a delegate type":
```
  services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddSignIn(Configuration, options =>
                {
                    Configuration.Bind("AzureAdB2C", options);
                    var existingHandler = options.Events.OnAuthorizationCodeReceived;
                    options.Events = new OpenIdConnectEvents
                    {
                        OnAuthorizationCodeReceived = async context =>
                        {
                            await existingHandler(context);
                           // Some checks or redirect
                        },
                    };
                });
```
Notice: to access any controller the user needs to be authorized, so the sign in is automatic there is no controller method to call sign in.

Any help or guidance would be greatly appreciated.

**Comment by TiagoBrenck** [comment]
I believe what you are looking for is something like this:

```c#
services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddSignIn(options =>
                {
                    Configuration.Bind("AzureAdB2C", options);
                    options.Events = new OpenIdConnectEvents
                    {
                        OnTokenValidated = async context =>
                        {
                            // Your code
                        },
                    };
                }, options => Configuration.Bind("AzureAdB2C", options));
```

The event OnTokenValidated will happen after OnAuthorizationCodeReceived , where MSAL gets the access token, so I think this event fits best your scenario. The building error is because you missed one argument.
