### ISSUE TITLE
Openid connect authentication behind Azure application proxy

### ISSUE THREAD

**Issue by PastelFish99** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#367]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [X] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

Hi, we have an on-prem .net core 2.1 app which is currently configured to use openid connect as per https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/aspnetcore2-2 and all is working fine. 
The application is configured on the azure application list and we are using the provided tenant-id and app-id.
an example of the app url is: https://orgappdomain/orgappname
and our azure ad team have configured the response urls as
https://orgappdomain/orgappname and
https://orgappdomain/orgappname/signin-oidc

the code in our startup file looks like this: 
services.AddAuthentication(AzureADDefaults.AuthenticationScheme)
               .AddAzureAD(options => Configuration.Bind("AzureAd", options));

            services.Configure<OpenIdConnectOptions>(AzureADDefaults.OpenIdScheme, options =>
            {
                options.Authority = options.Authority + "/v2.0/";                
                options.TokenValidationParameters.ValidateIssuer = false;
            }); 

The problem is that this works fine when logged in locally on the orgs network or via citrix.
Now the clients want to be able to access the app externally, so the Azure AD team created an Azure proxy app with url https://orgproxy/orgappname (external url) which has an internal url of the existing https://orgappdomain/orgappname, and when we try and access the site from externally, it does ask for our ms credentials, but then it tries to redirect to the https://orgappdomain/orgappname/signin-oidc url which it cant because that domain is not available outside the corporate network. I suspect this is the url we defined in the original Azure app as the response url for the AzureAD settings.

My question is how do we configure an app which has been configured on Azure AD and uses openid connect with a response url, to also work via a separate azure proxy app with a different url.   

Thanks for any assistance

**Expected behavior**
What we expect is when users are on the coprorate domain or citrix, the app is accessible and the users can login via their office credential. When the users login externally using the Azure proxy app url, they are still authenticated with their office credentials and the app is accessible.  

**Actual behavior**
When we access the url from external using the proxy app, it tries to redirect to the internal app /signin-oidc and fails

**Possible Solution**

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> Windows 10

### Versions
> ASP.NET Core 2.1

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue?
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)
  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by TiagoBrenck** [comment]
Would this doc help you? https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/application-proxy-add-on-premises-application

**Comment by PastelFish99** [comment]
Thanks Tiago, I'll check and provide feedback if it is a possible solution. cheers.

**Comment by jmprieur** [comment]
@PastelFish99 
Did you see https://github.com/AzureAD/microsoft-identity-web/wiki/Deploying-Web-apps-to-App-services-as-Linux-containers ?
Closing this issue as we think it's answered.
Feel free to reopen if you disagree

**Comment by PastelFish99** [comment]
Hi Jean-Marc,

Thanks for the link. I’ll check it out. I have been focusing on some other higher priority work so have not given much focus to this.

Regards
Adrian


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
