### ISSUE TITLE
[Scenario] Single sign on with Microsoft Identity Platform and store user info locally using Microsoft identity Framework

### ISSUE THREAD

**Issue by Blackleones** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#372]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [x] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [x] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Mention any other details that might be useful

It would be interesting to have a quick start (or sample code) where Identity Framework and Microsoft Identity Platform (Azure AD v2.0) are already connected. 

In this scenario:

 if the user is logging in for the first time using single-sign-on, then the web app will retrieve some user information (like email, profile photo, first name, and last name) and prompt them to the user so he can modify it.

If the user already has a local user identity, then he can associate it with his external identity (Facebook, Microsoft, etc)

What we could learn from this sample:

- interaction between Microsoft Identity Platform
- how can retrieve user information using Microsoft Graph during the first login
- how can associate a local user identity with an external user identity through single-sign-on

### Additional notes

I think it would be nice to have a sample that combines Microsoft Identity Platform with Microsoft Identity Framework. This sample, with the other one's, should contribute to cover all the possibilities scenarios.

### Version

Asp.Net Core: 3.1.x
Microsoft identity Platform (Microsoft.Identity.Web) - preview.

**Comment by TiagoBrenck** [comment]
@Blackleones from what you are describing, your needs fit Azure AD B2C. We have a sample for it in this repo. 
[Azure B2C website](https://azure.microsoft.com/services/active-directory/external-identities/b2c/)

**Comment by Blackleones** [comment]
@TiagoBrenck  thank you, I am going to read the Azure B2C docs.

I am trying to connect my project to my azure ad tenant. My project is like a blog website where everyone inside the same tenant can create a new thread. So, just to learn, I am trying to store each user locally and collect some user info (like photos, first name, and last name).

I've started with AzureAD sign in, then I've found Microsoft Identity Platform, and now, Azure B2C. To be honest, this is my third day where I am trying to understand all the "Microsoft Authentication" methods and I have to admit that I am lost.

I am having a hard time understanding which one to use and why. Like, why I should user Azure B2C? Why not Azure AD or Windows Identity Platform? they are looking the same. Each one let you sign in, select permissions and so on.. the only "difference" I've found is that Microsoft Identity Platform is the newest technology, and because of that I thought it was the solution for my request.

**Comment by TiagoBrenck** [comment]
Microsoft Identity Platform represents all the AAD/B2C etc technologies. You can relate it to a Microsoft technology to authenticate users in the cloud.

Azure AD used to be more focused on users from AAD tenants only, without adding extra identity providers (like Facebook, Google etc). They are working on this and at this stage is on preview mode. If you would like to try, access your Azure Portal > Azure Active Directory > External Identities.

Azure B2C already have the capability of working with multiple identity providers and collect extra attributes from users during sign-up. At some point, we might have a merge of AAD and B2C. 

This repo has samples for AAD and B2C. Check chapter one and you can play around and learn more about them.

**Comment by kalyankrishna1** [comment]
there is a detailed FAQ that should help -> https://docs.microsoft.com/en-us/azure/active-directory-b2c/faq?tabs=app-reg-ga
