### ISSUE TITLE
Signin callback error OpenIdConnectAuthenticationHandler: message.State is null or empty.

### ISSUE THREAD

**Issue by juanan** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#373]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [x] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

.Net core project that offers 2 login possibilities: local login with Identity server or external login with Microsoft Identity Web.

**Expected behavior**
Callback successfully executed.

**Actual behavior**
If the user clicks on external login, the Microsoft login form is successfully shown but after login in with my office account I get this error on my redirect callback:

---> System.Exception: OpenIdConnectAuthenticationHandler: message.State is null or empty.
--- End of inner exception stack trace ---
at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler1.HandleRequestAsync() at IdentityServer4.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync() at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT1.ProcessRequestAsync()

This is the info that Azure sends to my callback

![image](https://user-images.githubusercontent.com/17723190/86008087-a0530c00-ba18-11ea-96d4-91b541f6052c.png)

And this is my controller to challengue the external login

![image](https://user-images.githubusercontent.com/17723190/86008157-ae089180-ba18-11ea-9b98-866d200fa28c.png)

In my case, I don't have deployed my .Net Core project on Azure so the solution to disable App Service Authentication is not valid for me, I just created an app under App registrations to have a client id, redirect url...

I would apprecciate any help, I can not figure out why its failing.

### OS and Version?
Windows 10

### Versions

Using .Net Core 3.1
Microsoft Identity Web 0.1.5-preview

  
Many thanks.

**Comment by TiagoBrenck** [comment]
Do you have this `/account/azuread/login/callback` code in your project? We usually use `/signin-oidc` which is implemented by default.

What is the result using `/signin-oidc` for CallbackPath?

**Comment by juanan** [comment]
Hi @TiagoBrenck ,

I have done the test using /signin-oidc for CallbackPath with the same error.

I have attached a trace file to see if that can give you any clue.

Many thanks.

[trace.txt](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/files/4850007/trace.txt)

**Comment by juanan** [comment]
Attached a repro project with testing instructions (very simple).

[IdentityServers.zip](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/files/4851963/IdentityServers.zip)

**Comment by TiagoBrenck** [comment]
Sorry I couldn't reproduce the error, but I noticed something that is missing. OpenIdConnectOptions shouldn't be different than IdentityOptions. You missed some key configs I guess

Could you try this:

```c#
            services.AddSignIn(options =>
            {
                options.Instance = "https://login.microsoftonline.com/";
                options.ClientId = "65431e8a-28f5-45b2-ac17-68c78e3fb021";
                options.CallbackPath = "/signin-oidc";
                options.TenantId = "organizations";

            }, identityOption =>
            {
                identityOption.Instance = "https://login.microsoftonline.com/";
                identityOption.TenantId = "organizations";
                identityOption.ClientId = "65431e8a-28f5-45b2-ac17-68c78e3fb021";
                identityOption.CallbackPath = "/signin-oidc";
            });
```

**Comment by juanan** [comment]
Ok, I will try it but didnt you get any error using my repro solution

**Comment by TiagoBrenck** [comment]
I mean, I couldn't run the code. I would need to use localhost but your reply url wasn't matching

**Comment by juanan** [comment]
I tried with the same result, at the end I just made 

`services.AddSignIn(Configuration); `

to avoid problems but no luck.

My client has the reply url configured for localhost so you should not have problems to run my code

![image](https://user-images.githubusercontent.com/17723190/86209340-b1179500-bb72-11ea-988f-1932aed23895.png)

Did you see my log trace?

Don't know, could be that the error comes because the client (SPA) requests an access token using authorization code with PKCE and that generates a conflict when its merged with info coming from Microsoft Login?

**Comment by juanan** [comment]
Solved, my error was to mix the internal callback (/signin-oidc) with my custom one.
