### ISSUE TITLE
How to disable scope and roles claims validation of Oauth 2.0 Bearer tokens when using AddProtectedWebApi?

### ISSUE THREAD

**Issue by tbrophy** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#374]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [x] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

The Use Case involves a client that does not provide either scope or role claims in a Bearer token.

1. obtain a Bearer token from Azure AD without scope or role claim (we do this as shown in the code snippet under step number 1 below—this exactly reproduces the behavior of our client in Production today)
2. modify Startup.cs (as described below)
3. submit to service to check validation logic, e.g. `curl -k -H "Authorization: Bearer $(cat .token)" http://localhost:44351`

( Quick summary of the remaining report content below; _Is there a way to disable scope and roles claims declaratively in appsettings.json?_  If there is **_not_** a way to turn off scope and claims via appsettings.json, can you please suggest a programmatic alternative? 

Thanks in Advance!
mr.T )

**1.  obtain Bearer token**

```
curl -s --request POST \
  --url 'https://login.microsoftonline.com/${TENANT_ID}/oauth2/token' \
  --header 'content-type: application/x-www-form-urlencoded' \
  --data grant_type=client_credentials \
  --data client_id=${CLIENT_ID} \
  --data client_secret=${CLIENT_SECRET} \
  --data resource=${AUDIENCE_CLAIM} | jq -r '.access_token' \
  > .token
```

**2. modifications to Startup.cs** 

_( i.e. in an attempt to disable scope and role claim validation )_

Replacing (master branch) https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/d52951f3006c51a1470690b2a716d10c0f24705a/4-WebApp-your-API/4-1-MyOrg/TodoListService/Startup.cs#L34 with...

```
            services.AddProtectedWebApi(options =>
            {
                Configuration.Bind("AzureAd", options);
                options.Events = new JwtBearerEvents();
                options.Events.OnTokenValidated = context =>
                {
                    return Task.CompletedTask;
                };
            }, options =>
            {
                Configuration.Bind("AzureAd", options);
            });
```

**3. submit to service to check validation logic**

```
curl -k -H "Authorization: Bearer $(cat .token)" http://localhost:44351
```

**Expected behavior**

The token validation passes (it does) **_AND_** no scope or role claims are processed.

**Actual behavior**

We see the same "Neither scope or roles claim was found in the bearer token" error output in the console as when using the master branch version of Startup.cs (perma-link above) without the modification on L34 described above in step number 2;

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:44351/  
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[2]
      Successfully validated the token.
fail: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[3]
      Exception occurred while processing message.
System.UnauthorizedAccessException: Neither scope or roles claim was found in the bearer token.
   at Microsoft.Identity.Web.WebApiAuthenticationBuilderExtensions.<>c__DisplayClass1_1.<<AddProtectedWebApi>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.UnauthorizedAccessException: Neither scope or roles claim was found in the bearer token.
   at Microsoft.Identity.Web.WebApiAuthenticationBuilderExtensions.<>c__DisplayClass1_1.<<AddProtectedWebApi>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 1006.9329ms 500 text/plain
```

**Possible Solution**

Turning off scope and role claims declaratively in appsettings.json? 

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure

Add any other context about the problem here, such as logs.

( Log messages are quoted above. )

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> macOS (Mojave)

### Versions

> of ASP.NET Core, of MSAL.NET

```
$ >dotnet --version
3.1.201
```

Dependencies in the .csproj file...

```
  <ItemGroup>
    <PackageReference Include="Microsoft.Identity.Web" Version="0.1.5-preview" />
    <PackageReference Include="System.Threading.Tasks" Version="4.3.0" />
  </ItemGroup>
```

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue?  **Yes**
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview) **Yes**
  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by TiagoBrenck** [comment]
@tbrophy how did you end up with an access token from AAD without scope?

**Comment by tbrophy** [comment]
@TiagoBrenck, _Thanks for your quick reply._

How do we get an access token without scope?  The entire shell script is quoted at the bottom of this reply, with hard-coded tenant id.  

The shell script was created based on; https://docs.microsoft.com/en-us/azure/active-directory/azuread-dev/v1-oauth2-client-creds-grant-flow

Not sure it will matter, but the version of Bash this script is being executed within is...

```
$ >bash --version
GNU bash, version 5.0.16(1)-release (x86_64-apple-darwin18.7.0)
```

_What error(s) did you get for the script?_

____

Also, in the interest of full disclosure, a day after opening **this** request for advice, I created an issue here; https://github.com/AzureAD/microsoft-identity-web/issues/281

____

### What does the token payload look like?

Using the shell script quoted below, we get the following payload keys;
  
- aud
- iss
- iat
- nbf
- exp
- aio
- appid
- appidacr
- idp
- tid
- uti
- ver

When our production client calls us, their payload includes the following additional keys (that we ignore);
  
- oid
- rh
- sub

____

### source_token.sh

```
#!/usr/bin/env bash

set -e
set -o pipefail


usage="$(basename "$0") [-h] [-aud URI] -- generate RS256 encrypted token from Azure Active Directory"

if [ "$#" -lt 2 ] && [ "$1" != "-h" ]; then
  printf "exiting: missing argument value for '-aud', see usage note...\n" >&2
  printf "$usage\n" >&2
  exit 1
fi

if [[ -z "${CLIENT_ID}" ]]; then
  printf "exiting: missing CLIENT_ID environment variable...\n" >&2
  printf "The id for a client is defined on the Overview page for an AAD App registration.\n\n" >&2
  printf "$usage\n" >&2
  exit 1
fi 

if [[ -z "${CLIENT_SECRET}" ]]; then
  printf "exiting: missing CLIENT_SECRET environment variable...\n" >&2
  printf "The secret for a client is displayed only once after creating it on 'Certificate & secrets' pane of an AAD App registration.\n\n" >&2
  printf "$usage\n" >&2
  exit 1
fi

AUDIENCE_CLAIM=""
PARAMS=""

while (( "$#" )); do
  case "$1" in
    -aud|--flag-with-argument)
      AUDIENCE_CLAIM=$2
      if [ -z "$AUDIENCE_CLAIM" ]
      then
        printf "exiting: missing argument for '-aud', usage...\n" >&2
        printf "$usage\n" >&2
        exit 1
      fi 
      shift 2
      ;;
    -h) printf "$usage\n"
       exit
       ;;
    --) # end argument parsing
      shift
      break
      ;;
    -*|--*=) # unsupported flags
      printf "Error: Unsupported flag $1\n" >&2
      exit 1
      ;;
    *) # preserve positional arguments
      PARAMS="$PARAMS $1"
      shift
      ;;
  esac
done
# set positional arguments in their proper place
eval set -- "$PARAMS"


printf "Writing RS256 encrypted token from AAD with 'aud' claim value of '${AUDIENCE_CLAIM}'..."

curl -s --request POST \
  --url 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/token' \
  --header 'content-type: application/x-www-form-urlencoded' \
  --data grant_type=client_credentials \
  --data client_id=${CLIENT_ID} \
  --data client_secret=${CLIENT_SECRET} \
  --data resource=${AUDIENCE_CLAIM} | jq -r '.access_token' \
  > .token

echo "in file: './.token'."
```

**Comment by TiagoBrenck** [comment]
Ok, I managed to get it working now. We have a few considerations in your scenario:

You are using the v1 endpoint, and we highly recommend using the v2.0 endpoint (which will give you roles):

```sh
curl -s --request POST \
  --url 'https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/token' \
  --header 'content-type: application/x-www-form-urlencoded' \
  --data grant_type=client_credentials \
  --data client_id='{client_id}' \
  --data client_secret="{secret}" \
  --data scope="api://{WebApi_ClientId}/.default"  \
  > .token

echo "in file: './.token'."
```

Please, [refer to this sample](https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/tree/master/2-Call-OwnApi) for the client credential flow. You would like to add the role in your WebApi manifest, then go to your daemon app registration > API Permissions > set the WebAPI role that you created > Click on Grant Admin Consent. These steps are mentioned in the sample that I linked.

Please, try this approach first, which is more secure on your web api side.

**Comment by tbrophy** [comment]
@TiagoBrenck, _Thanks for confirmation on the correct sample to use_—was just starting to work with it this afternoon.  Stepping-back in the git commit timeline to the earliest support of netcore3.1, I have seen that it demands roles and scopes for; https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/tree/master/2-Call-OwnApi/TodoList-WebApi

Perhaps we may have to go really old-school with our service and somehow roll our own adapter for https://www.nuget.org/packages/System.IdentityModel.Tokens.Jwt/ or the like?

Finally, I'm not just being stubborn.  Though we could choose to use the v2.0 endpoint all day long for our own testing, our client's Principal Software Eng Lead has told me in no uncertain terms as recently as today 'it is not on their roadmap'.  In other words, our client is owned by a different internal team.  Because their service (i.e. our client) is mission critical—one step away from Azure Front Door—with many, many, many visitors monthly, they are not going to prioritize moving to v2.

**Comment by TiagoBrenck** [comment]
@jmprieur is it possible for Microsoft.identity.Web to not validate scopes or roles?

**Comment by jmprieur** [comment]
@TiagoBrenck
Assuming you mean here: https://github.com/AzureAD/microsoft-identity-web/blob/aa72fadd98181a01ce0da4aee4206e0bbc6d9fba/src/Microsoft.Identity.Web/WebApiAuthenticationBuilderExtensions.cs#L139-L148, I would think yes, as roles and scopes should be validated in the controllers with the [ValidateAppRole](https://github.com/AzureAD/microsoft-identity-web/blob/aa72fadd98181a01ce0da4aee4206e0bbc6d9fba/src/Microsoft.Identity.Web/Resource/RolesRequiredHttpContextExtensions.cs#L28) and [VerifyUserHasAnyAcceptedScope](https://github.com/AzureAD/microsoft-identity-web/blob/aa72fadd98181a01ce0da4aee4206e0bbc6d9fba/src/Microsoft.Identity.Web/Resource/ScopesRequiredHttpContextExtensions.cs#L32)

@kalyankrishna1 what was the reason why you introduced the validation straight on token validated ?
cc: @jennyf19 @pmaytak

**Comment by kalyankrishna1** [comment]
Folks that check exists to satisfy an [important security posture ](https://docs.microsoft.com/azure/active-directory/develop/reference-breaking-changes#app-only-tokens-for-single-tenant-applications-are-only-issued-if-the-client-app-exists-in-the-resource-tenant)that we fixed last year. That's reason #1
We can introduce a flag to skip this check, but its not advisable to walk around security checks. 
fyi, in AAD v2, its no longer possible to obtain ATs that would not have either a role or scope.

**Comment by jmprieur** [comment]
Thanks @kalyankrishna1 
Do you mean tokens emitted by AAD v2.0 ?
or v2.0 tokens?

**Comment by udlose** [comment]
@jmprieur can you describe the difference?

**Comment by tbrophy** [comment]
@kalyankrishna1 Is there a process for having a 'disable role and scope checking ' flag formally considered?

As an aside, our client is in the same tenant.  We check the audience and client id in the token from the client as the next-best alternative to having been provided no role or scope passed to us.

**Comment by jmprieur** [comment]
@udlose : The Azure AD v2.0 endpoint (Microsoft identity platform endpoint), like the Azure AD v1.0 endpoint emit access tokens which version is the version that the Web API expects (accepted access token version in the application manifest)

**Comment by jmprieur** [comment]
@udlose 
Something you could do is override options.Events.OnTokenValidated:
See https://github.com/AzureAD/microsoft-identity-web/wiki/customization

**Comment by tbrophy** [comment]
@jmprieur and @udlose, Can one of you help me out here?  I am missing something.  Is the recommendation to override options.Events.OnTokenValidated for the purpose of skipping role and scope claim validation or to support v1.0 tokens, or something else?  

If the modification is for the purpose of skipping role and scope claim validation, is the code snippet under "2. modifications to Startup.cs' in my first post opening this thread an incorrect way to prove that this approach will not work?  That is, it will now work in light of the following, which runs unconditionally?  

https://github.com/AzureAD/microsoft-identity-web/blob/aa72fadd98181a01ce0da4aee4206e0bbc6d9fba/src/Microsoft.Identity.Web/WebApiAuthenticationBuilderExtensions.cs#L139-L148

**Comment by udlose** [comment]
> Thanks @kalyankrishna1
> Do you mean tokens emitted by AAD v2.0 ?
> or v2.0 tokens?

@jmprieur I was asking if you could explain the difference between the 2 types of tokens you mention above

**Comment by jmprieur** [comment]
@udlose : please see https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens and https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens

**Comment by jmprieur** [comment]
@tbrophy : it should not run unconditionally if you override the `OnTokenValidated` event.

**Comment by tbrophy** [comment]
@jmprieur, Thanks.  Using the snippet at https://github.com/AzureAD/microsoft-identity-web/wiki/customization as guidance, I was able to override the default claims checking.

**Comment by jmprieur** [comment]
@tbrophy : thanks for the update. Do we want to close this issue?
