### ISSUE TITLE
Single sign-on working with 1-1-MyOrg Sample, but not with 1-5-B2C. Please help.

### ISSUE THREAD

**Issue by rajeev16mca2k5** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#375]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [x] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

I tried 1-1-MyOrg sample, deployed on different domains. Single sign-on works fine.
But When I try 1-5-B2C sample, deployed on different domains. Single sign-on feature doesn't work.

In Single sign-on configuration under Session behavior for sign-in user flow, I have selected Tenant.

Does Single sign-on works with 1-5-B2C sample works for others? Is it bug in 1-5-B2C Sample OR I am missing some configuration on azure portal?

**Working -** https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-1-MyOrg
**Not Working -** https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-5-B2C

**Expected behavior**

Single sign-on functionality

**Actual behavior**

Single sign-on doesn't work, asking for credentials again.

**Possible Solution**

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10

### Versions
> of ASP.NET Core, of MSAL.NET
ASP.NET Core 3.1, Microsoft.Identity.Web 0.1.5 Preview

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue?
Yes
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
Yes
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)
Yes
  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jennyf19** [comment]
@rajeev16mca2k5 have you tried running the b2c sample as-is? it is preconfigured. 

What are you expecting for single sign-on?

**Comment by mossywell** [comment]
Problem confirmed.
If 1-5-B2C is run against the Fabrikam, it works.
The bug is in the instructions which omit "allow Implict Flow" via the Legacy App Registration option. I would also recommend making it clear that this sample uses Implict Flow and not Authorization Code flow.

**Comment by jmprieur** [comment]
@mossywell : it does not use implicit flow. It just asks for an IDToken, which turns out to be presented, in the app registration (and wrongly) in the part about implicit flow

**Comment by mossywell** [comment]
@jmprieur : Interesting. So, the option "allow Implicit Flow" (which returns an access token if using oAuth2) should say "allow ID token"? I also just read this: https://docs.microsoft.com/en-us/azure/active-directory/azuread-dev/v1-protocols-openid-connect-code "The response_type parameter must include id_token". So, Microsoft's OIDC implementation requires id_token even though the OIDC standard doesn't - I didn't know that. Either way, I do think the instructions should say to Enable "Allow implicit flow". :-)

**Comment by TiagoBrenck** [comment]
Hi @mossywell could you point me to this instruction that you are getting confused?
I checked that our sample 1-5 has a link to the registration steps, which says:

 - Under Implicit grant, select both the Access tokens and ID tokens check boxes.

This "Under Implicit grant" is referencing the Azure Portal UI. The IdToken checkbox is under the title Implicit grant.

**Comment by mossywell** [comment]
I have searched the instructions page https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-5-B2C for the word "implicit" and cannot find it.

**Comment by TiagoBrenck** [comment]
@mossywell the readme on sample 5-1 itself doesn't have the steps to create the application, but a link to the steps. You will find it in [this text](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-5-B2C#step-2-get-your-own-azure-ad-b2c-tenant) (the ** would be the link):

```
If you don't have an Azure AD B2C tenant yet, you'll need to create an Azure AD B2C tenant by following the **Tutorial: Create an Azure Active Directory B2C tenant**.
```
