### ISSUE TITLE
No account or login hint was passed to the AcquireTokenSilent call

### ISSUE THREAD

**Issue by freemstr** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#376]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [x] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [x] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [x] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [x] Other (please describe)

## Configuration
I realize that this is an aspnet core thread however [the relevant project for MVC is archived](https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect)

I am running an API using Core 3.1 in production but the client in question is legacy MVC application on .NET 4.8
Essentially its 4-WebApp-your-API/4-1-MyOrg scenario but with different (both supported) framework on each side

### Repro-ing the issue
Configure MVC (.NET 4.8) application to access an API with Azure AD authentication
First run is successful, subsequent runs result in MSAL cache being empty

**Expected behavior**
User is authenticated, cache is re-populated 

**Actual behavior**
Cache is empty, user is forced to perform signout to re-signin and trigger authentication

**Possible Solution**
My somewhat working solution for MVC 5 is System.Web.Mvc.IExceptionFilter implementation 
similar to AuthorizeForScopesAttribute for Core
with redirect to an action which is then meant to refresh sign in and trigger OnAuthorizationCodeReceived 

However, this being Azure AD, 
If I use HttpContext.GetOwinContext().Authentication.SignOut user is signed out of Teams, OWA, SharePoint etc etc, which I would like to avoid.
If I only use HttpContext.GetOwinContext().Authentication.Challenge - the problem is NOT solved and cache remains empty

Is there a supported way to re-request the token without global sign out if user is authenticated but the cache is empty?
I am looking for .NET Framework solution or something agnostic that would also work for Blazor and SPA implementations as was requested in other tickets

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
No account or login hint was passed to the AcquireTokenSilent call
app.GetAccountsAsync() returns empty collection
app.GetAccountAsync(code) returns null

### OS and Version?
Microsoft.Identity.Client 4.16.1
Microsoft.Owin.Security 4.1.0

### Versions
API: ASP.NET Core 3.1 
Front End Client: ASP.NET 4.8 MVC 5

### Mention any other details that might be useful
Seems relevant, however fixes in Core package will not directly solve my issue at hand
https://github.com/AzureAD/microsoft-identity-web/issues/11
https://github.com/AzureAD/microsoft-identity-web/issues/13
Also seems to be related to
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/115
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/137
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/216
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/281
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/314
> ---------------------------------------------------------------

Thank you.

**Comment by jmprieur** [comment]
@freemstr 
We just released Microsoft.Identity.Web 0.2.0 which refactored the the token cache key
If you provide all the necessary scopes in the AddMicrosoftWebAppCallsWebApi, you should not have this issue

Do you have a repro?

**Comment by freemstr** [comment]
@jmprieur 
Thank you
I will have to look at code changes and see if there is anything useful for me.
API is secured and is operating as intended.
However, the code in question is **.NET Framework** project not using Microsoft.Identity.Web nuget targeted at Core
The original relevant Azure-Samples project for MVC is [archived](https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect)
I will upload minimum repro as soon as I can

My scopes:
AuthenticationConfig.Scope contains custom scope for the API access (like api://bbbb0b00-000b-00b0-00bb-0b00000b000b/DEV-API)
```
app.UseCookieAuthentication(new CookieAuthenticationOptions()
            {
                AuthenticationType = CookieAuthenticationDefaults.AuthenticationType,
                CookieSameSite = Microsoft.Owin.SameSiteMode.None,
                CookieManager = new SameSiteCookieManager(new SystemWebChunkingCookieManager()),
                CookieSecure = CookieSecureOption.Always,
                SlidingExpiration = true
            });

string scopes = "openid profile "+ AuthenticationConfig.Scope ;

new OpenIdConnectAuthenticationOptions
{
   ResponseType = OpenIdConnectResponseType.CodeIdToken,
   ResponseMode = OpenIdConnectResponseMode.FormPost,
   Scope = scopes,
   Notifications = new OpenIdConnectAuthenticationNotifications
                    {
                        AuthorizationCodeReceived = async (context) => {
                            var claimsPrincipal = new ClaimsPrincipal(context.AuthenticationTicket.Identity);
                            IConfidentialClientApplication clientApp = MsalAppBuilder.BuildConfidentialClientApplication(
                                claimsPrincipal,
                                out MSALPerUserMemoryTokenCache tokenStore
                            );
                            var result = await clientApp.AcquireTokenByAuthorizationCode(new string[]{AuthenticationConfig.Scope}, context.Code).ExecuteAsync();
                            context.HandleCodeRedemption(result.AccessToken, result.IdToken);
                        }
                    },
                    CookieManager = new SameSiteCookieManager(new SystemWebChunkingCookieManager())
}
```
The issue is that here GetAccountsAsync returns null after restart of the application
and AuthorizationCodeReceived is not called on subsequent application restarts

```

        public override ActionResult Index(string id = null)
        {
             IConfidentialClientApplication app = MsalAppBuilder.BuildConfidentialClientApplication(
                ClaimsPrincipal.Current,
                out MSALPerUserMemoryTokenCache tokenStore);
                var acct = app.GetAccountsAsync().Result.FirstOrDefault()
        }
```

Like you said in one of the other tickets User is perceived as Authenticated by MVC but the cache stored in memory does not exist on the application start

**Comment by TiagoBrenck** [comment]
The scenario of empty cache and AuthorizationCodeReceived not being called after restarting the application is an expected stage. The `AuthorizeForScopesAttribute` takes care of it, filtering `MsalUiRequiredException` and throwing an authentication challenge. Since there are valid auth cookies in the user s browser, they wont be asked to type their password again. This solution does **not** involve signing them out.

Currently, Microsoft.Identity.Web isn't compatible with .NET MVC Framework, so you will need to create your own "AuthorizeForScopes" sort of thing, and again, just throwing an authentication challenge with the same AuthScheme name that you have configured in the startup is enough. Do not sign them out.

About Blazor, its architecture is a bit different than .NET Core web apps. The `.razor` pages doesnt have all the middleware pipeline executions as your are used to in the web/api apps, which prevents the `AuthorizeForScopesAttribute` to work as intended. In one of our threads about Blazor, a user suggested adding the `AuthorizeForScopesAttribute` in `_Host` file, and making it extends from `PageModel`. [You can find the thread here](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/281#issuecomment-630190753). We haven't officialized this solution though, but it could be a starting point for your investigations.

**Comment by freemstr** [comment]
@TiagoBrenck @jmprieur 

I will look at the code changes for 0.2 and see what I can infer that is usable for legacy applications.

This issue seems to also still be open https://github.com/AzureAD/microsoft-identity-web/issues/13
but ideas provided by @jennyf19 seem promising

I understand that Microsoft.Identity.Web isn't compatible with .NET MVC Framework and appreciate all the work that went into it.
It working quite flawlessly in my Core projects but this is not one of them.
If you happen to know of a better place to ask about legacy .NET framework issues with MSAL/AAD other than 
/Azure-Samples repo, please let me know what that place would be.

Thank you for prompt responses and detailed explanations.

**Comment by TiagoBrenck** [comment]
Thanks for the detailed solution @freemstr 

We are waiting for [.NET 5](https://devblogs.microsoft.com/dotnet/introducing-net-5/) to be released, so we would have one single platform that would handle Net Core and Net Standard.

**Comment by freemstr** [comment]
Hope it helps the remaining few people working with Framework projects
I have my doubts about release of 5.0 bridging difference in `AuthenticationProperties `(for example) so I expect my solution to stay there until the entire app is upgraded.

Thanks again

**Comment by gsmith140** [comment]
@TiagoBrenck I am having the same issue in .Net framework. Is the cache being empty on application restart due to the specific cache implementation, or will it always be an issue in .Net framework regardless of cache implementation?

@freemstr Would it be possible to share a code sample of your AuthorizeForScopesAttribute class?

**Comment by freemstr** [comment]
@gsmith140 
This is (over)simplified version for .NET Framework
```
public sealed class AuthorizeForScopesAttribute : HandleErrorAttribute
{

public override void OnException(ExceptionContext context)
{
        MsalUiRequiredException msalUiRequiredException = context?.Exception as MsalUiRequiredException;

        if (msalUiRequiredException != null && msalUiRequiredException.ErrorCode.ContainsAny(new[] { MsalError.UserNullError, MsalError.InvalidGrantError }))
        {
            var properties = new AuthenticationProperties();
//configure these AuthenticationProperties according to            
//https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow
properties.Dictionary.Add(OpenIdConnectParameterNames.Scope, _ YOUR SCOPES _ );
            context.ExceptionHandled = true;
            context.HttpContext.GetOwinContext().Authentication.Challenge(properties, 
OpenIdConnectAuthenticationDefaults.AuthenticationType);
        }
    base.OnException(context);
}

}
```

**Comment by jmprieur** [comment]
@gsmith140 : I'm surprised you used the implicit grant settings and not the auth code flow settings?
ASP.NET does not use implicit flow

cc: @jennyf19 FYI (and the support of the attribute in .NET Framework)

**Comment by freemstr** [comment]
@jmprieur
Please elaborate on "does not use"

What is your suggestion to improve this?

**Comment by jmprieur** [comment]
@freemstr : It uses the Authorization code flow. See https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow

**Comment by gsmith140** [comment]
> @gsmith140 : I'm surprised you used the implicit grant settings and not the auth code flow settings?
> ASP.NET does not use implicit flow

I'm confused by your comment. I don't believe I am using implicit grant. On startup I am getting an auth code and that process works fine. It's subsequent calls to AcquireTokenSilent that always fail. I'm still not clear on whether or not this even works in .Net framework.

**Comment by jmprieur** [comment]
This is because the comment in the code you proposed is:

```CSharp
//configure these AuthenticationProperties according to            
//https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow
```

I think that this would work. you might also want to add the claims.

@jennyf19 another good candidate to expose in ASP.NET (FW) applications

**Comment by gsmith140** [comment]
Ahh, I think you meant to tag @freemstr in that comment as it is his proposed code. Apologies for the confusion.
