### ISSUE TITLE
Still getting No account or login hint was passed to the AcquireTokenSilent using latest microsoft.identity.web

### ISSUE THREAD

**Issue by maarten1055** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#382]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [x] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

**Expected behavior**

Getting an access token from cache using the code from the example:

`private async Task PrepareAuthenticatedClient()
        {
            string accessToken = accessToken = await this.tokenAcquisition.GetAccessTokenForUserAsync(new[] { this.scope });
            Debug.WriteLine($"access token-{accessToken}");
            this.httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            this.httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }`
 in startup:
`services.AddMicrosoftWebAppAuthentication(Configuration)
                .AddMicrosoftWebAppCallsWebApi(Configuration, new string[] { Configuration["API:Scope"] })
               .AddInMemoryTokenCaches();`
**Actual behavior**
Exception in title.

**Possible Solution**

**Additional context/ Error codes / Screenshots**

Logging in works but after some time I get this error. I don't get an error when I run it from Visual Studio, only live.

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
> of ASP.NET Core, of MSAL.NET

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue?
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)
  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by TiagoBrenck** [comment]
Did you deploy it on Azure? If not, where did you deploy it?
Another question is, did you add any code customization (other than setting your clientId, tenantId etc)?

**Comment by maarten1055** [comment]
No, we deploy it to an on-premise IIS server.
No, at least not in the authorization flow to call our API.

I don't know if it matters but it has always worked until the separation of microsoft.identity.web.

**Comment by TiagoBrenck** [comment]
Is your `ActionResult`, or `Controller`, decorated with the attribute: `[AuthorizeForScopes(Scopes = new[] { "Your-WebApi-Scope" })]` ?

**Comment by maarten1055** [comment]
Sorry, I should've specified this. My API is MVC but the webapp that calls it are razor pages, so no `Controller `or `ActionResult`.
Unless handler methods count as `ActionResult`, but I doubt it?

**Comment by TiagoBrenck** [comment]
@maarten1055, `Microsoft.Identity.Web` is about to release a version that makes this, ``No account or login hint...`` problem to be handle quiet easily for MVC and Blazor apps.

Would you mind [tracking this issue](https://github.com/AzureAD/microsoft-identity-web/issues/360) so you can get notified when they release the new version?

**Comment by maarten1055** [comment]
Will do, I'll update if it solves my issue when it's released . 

Thanks!

**Comment by jmprieur** [comment]
@maarten1055 @TiagoBrenck 
Did you read: this is documented in https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access ?

**Comment by maarten1055** [comment]
So I tried the new version and the info @jmprieur provided but no luck.

Since the new version I do get a new error: `An MsalUiRequiredException was thrown due to a challenge for the user. This has occurred in a Blazor page. You need to use ConsentHandler.HandleException(ex) to challenge the user`
Which is weird because I'm not using Blazor but Razor Pages.

**Comment by jmprieur** [comment]
@maarten1055 : 
Did you add the attribute on the Razor page as show here? https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access#in-razor-pages ?

**Comment by maarten1055** [comment]
I did, but checking this made me recheck everything again and I noticed that this new exception also mentions the graph API I call. 
I thought it wouldn't matter at first because It's a separate flow. But apparently it does interfere with each other because it seems to work when I disable graph.

**Comment by jmprieur** [comment]
Thanks @maarten1055 for the update.
I'm not clear if you think there is an issue in MIcrosoft.Identity.Web / the sample? or in your code?

**Comment by maarten1055** [comment]
I'm pretty sure it's in my code. So this can probably be closed?

Thanks for the help anyways!

**Comment by jmprieur** [comment]
Thanks for the update @maarten1055. 
Closing this issue
