### ISSUE TITLE
4-2 B2C: How to diagnose 401 errors?

### ISSUE THREAD

**Issue by RhomGit** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#386]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [x] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

1. download the 4-2 B2C sample and open in Visual Studio
2. unload the TodoListClient
3. update appsettings.json with my own value
4. publish the TodoListService to Azure

**Expected behavior**
Browsing to https://myapp.azurewebsites.net/api/ToDoList would present me with the B2C sign-in page.

**Actual behavior**
HTTP ERROR 401

Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/2.0 GET https://localhost:44332/api/TodoList  
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService: Information: Authorization failed.
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler: Information: AuthenticationScheme: Bearer was challenged.

### Versions
.NET Core 3.1
Microsoft.Identity.Web v0.2.1-preview

### Attempting to troubleshooting yourself:
I was following the instructions at:
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C
Note: the line "services.AddAuthentication()" doesn't work, you need to add a scheme here like you do in the actual code sample. I suggest updating this document.
My web 1-5 B2C app signs in fine when using my B2C params.

  
### Mention any other details that might be useful
Just curious if this actually works for anyone? Am I doing something wrong? I don't actually know how to diagnose this issue, I am way out of my depth.

**Comment by jmprieur** [comment]
@RhomGit : I'm a bit confused. It seems the doc is up to date here :https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C#step-2-modified-the-generated-code ?
where is it obsolete?

To understand the 401, the best is to change this line 

https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/dc1cd5e79c978aeac86d54ec7c8c800da3c3b8a8/4-WebApp-your-API/4-2-B2C/Client/appsettings.json#L28

to use "Debug" instead of "Warning"

and then look on the console application for the errors, this should tell you want the problem is.

If this is not enough, please provide repro steps (or your app coordinates that you can email me at Jean-Marc.Prieur at microsoft dot com)

**Comment by RhomGit** [comment]
Thanks for your response. With regard to the doc:
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C#modify-the-startupcs-file-to-validate-bearer-access-tokens-received-by-the-web-api

   services.AddAuthentication()
           .AddMicrosoftWebApi(options =>

Which I believe should read:
            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                    .AddMicrosoftWebApi(options =>

I copy/pasted from the doc and then ran into issues, namely:
_InvalidOperationException: No authenticationScheme was specified, and there was no DefaultChallengeScheme found. The default schemes can be set using either AddAuthentication(string defaultScheme) or AddAuthentication(Action<AuthenticationOptions> configureOptions)._

**Comment by RhomGit** [comment]
IIS is reporting this when trying to open the url:
_info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2.0 GET https://localhost:44332/api/TodoList  
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed.
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[12]
      AuthenticationScheme: Bearer was challenged.
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 14.5141ms 401_ 

In my appsettings.json:
    "ClientId": matches my API's App Registration in Azure.
    "Instance": "https://myb2ctenant.b2clogin.com",
    "Domain": "myB2CTenant.onmicrosoft.com",
and my policies seem correct also.

I am an amateur when it comes to this so I am probably making a rookie mistake but I just can't figure it out. I would have thought that I would be presented with my sign-in window when trying to access the TodoList?

If this doesn't help explain the issue appropriately I can email you directly.

Thanks

**Comment by jmprieur** [comment]
Could you please subscribe to the events diagnostics? (set to true the last parameter of AddMicrosoftWebApp)

**Comment by TiagoBrenck** [comment]
@RhomGit you unloaded the Client app and publish the API.
API doesnt have landing page, so you wont be able to access it via the url: `https://localhost:44332/api/TodoList` or its published version.

To test it, you need to make a GET request with a **bearer token** in the header. This is not possible to do by just browsing the URL. [This link explaining access tokens](https://docs.microsoft.com/en-us/azure/active-directory-b2c/access-tokens) might be helpful

**Comment by RhomGit** [comment]
Ok, that makes sense. I have been trying to use it the same way my old B2C API was working using Azure App Service to fetch the token:
![image](https://user-images.githubusercontent.com/25700833/89007540-83716780-d33b-11ea-80d3-87ee139b5bd7.png)

Requesting the url redirects me to my sign in flow, and then redirects back but I am getting a 401.
I have also used MSAL (4.16.1) PCA to obtain a token and was trying to pass that to the API which also isn't working.

Its not your problem, I will keep trying to figure out what I am doing wrong, thanks.

**Comment by jmprieur** [comment]
Oh, if you use the authentication in our samples, you should disable Azure App Service authentication (for the moment they are conflicting with each other. See https://github.com/AzureAD/microsoft-identity-web/issues/8

**Comment by RhomGit** [comment]
Ok, that's kind of a big deal considering all of our tokens (desktop, web, mobile) are currently acquired via MSAL and Easy Auth.
I didn't even know there was a difference in tokens, damn I wasted alot of time on this.

**Comment by jmprieur** [comment]
You are right @RhomGit 
would you have suggestions on how we could surface this better?

**Comment by RhomGit** [comment]
Is it possible to catch the invalid token/bearer at point of auth in microsoft.identity.web and report an additional diagnostic line? Documentation is good (might stop some developers earlier) but easily missed, some sort of information at point of failure would be very beneficial in my opinion:

e.g.
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService: Information: Authorization failed.
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler: Information: AuthenticationScheme: Bearer was challenged.
**Microsoft.Identity.Web: Information: X-MS-TOKEN-AAD-ID-TOKEN not supported, get a real bearer token.**

Perhaps update this existing 4-2 section to point at your new article explaining that EasyAuth doesn't work.
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C#modify-the-startupcs-file-to-validate-bearer-access-tokens-received-by-the-web-api
Side note: also please update the "services.AddAuthentication()" to include the JwtBearerAuthenticationScheme
![image](https://user-images.githubusercontent.com/25700833/89088391-967f4880-d3ca-11ea-8434-1366f63bf2de.png)

 And maybe even a comment in your API sample:
![image](https://user-images.githubusercontent.com/25700833/89088502-5a98b300-d3cb-11ea-9993-4d56288714ee.png)

**Comment by RhomGit** [comment]
Thanks for your fast response time by the way, Your team is great and one of the reasons I switched to this library when looking for a solution.

For anyone who stumbles across this thread, I found this link helps to explain the token issue a little more (and provides a possible workaround):
http://jsandersblog.azurewebsites.net/2020/01/17/easy-auth-using-x-ms-token-aad-access-token-as-a-bearer-token/

**Comment by jmprieur** [comment]
Thanks for reporting the docs issue, @RhomGit and for your feedback. I fixed the README.md

the issue with the workaround is that the token is only active for 1h, and won't be refreshed. But I guess that's ok.
