### ISSUE TITLE
Authorization Code Flow does not work possibly because ResponseType has been overridden by CodeIdToken in Microsoft.Identity.Web

### ISSUE THREAD

**Issue by rajeev16mca2k5** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#387]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [x] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

Since we want to use Authorization Code Flow (Not Implicit flow), De-selecting the Implicit flow check-boxes stops the sample from working.

It looks like Microsoft.Identity.Web makes use of Implicit flow (ResponseType=CodeIdToken), not Authorization Code Flow (ResponseType=Code). Even when we specify to use ResponseType=Code in MicrosoftIdentityOptions.

**Repro steps**

1. Open Azure Portal and go to registered application.
2. Select Authentication tab and go to Implicit grant section.
3. UnCheck "Access tokens" and "ID tokens" checkboxes.

**Expected behavior**

Microsoft.Identity.Web should make use of Authorization Code Flow, when specified in MicrosoftIdentityOptions and not default to Implicit flow.

Added this block of code to use Authorization Code Flow, but still it makes use of Implicit flow.
services.Configure<MicrosoftIdentityOptions>(options => {
	options.ResponseType = OpenIdConnectResponseType.Code;  // "code";
	options.UsePkce = false;
});

**Actual behavior**

Microsoft.Identity.Web still makes use of Implicit flow, instead of Authorization Code Flow. 

**Possible Solution**

It looks like Microsoft.Identity.Web is overriding ResponseType to CodeIdToken always.

Changing Microsoft.Identity.Web sources fixes the issue for me.

- WebAppCallsWebApiAuthenticationBuilderExtensions.cs

    Commented out Line No. 122, Method Name - AddMicrosoftWebAppCallsWebApi
    // options.ResponseType = OpenIdConnectResponseType.CodeIdToken;

- AzureADB2COpenIDConnectEventHandlers.cs
    Commented out Line No. 35, Method Name - OnRedirectToIdentityProvider
    // context.ProtocolMessage.ResponseType = OpenIdConnectResponseType.CodeIdToken;

so after commenting out the above lines, ResponseType specified in MicrosoftIdentityOptions is honored. 

Please verify the changes. We would prefer not to have to patch and maintain these 2 source files ourselves.

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10

### Versions
> of ASP.NET Core, of MSAL.NET
ASP.Net Core 3.1
Microsoft.Identity.Client 4.16.1
Microsoft.Identity.Web 0.2.0-preview

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue?
yes
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
yes
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)
yes
  
### Mention any other details that might be useful
We have submitted support request to Microsoft on 14th Jul 2020 regarding this issue.
We have had several sessions and email exchanges with a support engineer, who requested us to submit this issue on github.

We would prefer not to have to patch and maintain these 2 source files ourselves.
We would like confirmation that these fixes are correct and will be incorporated in the future release of Microsoft.Identity.Web NuGet package.

We have spent more than a few weeks to diagnose this problem and would appreciate a quick response.

[Sources.zip](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/files/5022499/Sources.zip)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@rajeev16mca2k5 
CodeIdToken is not implicity flow. The portal incorrectly states that IDToken is in implicity flow, but it's not. you would have implicit flow only if you checked "Implicit flow access token", which we don't advise.

If you want to override what Microsoft.Identity.Web does, you can use the following code:


```CSharp
           services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                    .AddMicrosoftIdentityWebApp(Configuration, "AzureAdB2C");

            services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
            {
                var previousOptions = options.Events.OnRedirectToIdentityProvider;
                options.Events.OnRedirectToIdentityProvider = async context =>
                {
                    await previousOptions(context);
                    context.ProtocolMessage.ResponseType = Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectResponseType.IdToken;
                };
            });
```
