### ISSUE TITLE
5-WebApp-AuthZ/5-2-Groups: AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application

### ISSUE THREAD

**Issue by PingPongSet** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#396]
I created my app following the instructions on the link below:
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/5-WebApp-AuthZ/5-2-Groups

I got the error below when I tried to log into my app hosted on Azure,

> AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application

The url at the time of error is shown below:
> https://login.microsoftonline.com/xxx/oauth2/authorize?response_type=code id_token&redirect_uri=https://xxx.azurewebsites.net/.auth/login/aad/callback&client_id=xx&scope=openid profile email&response_mode=form_post&nonce=xx&state=redir=%2F

Please note the `redirect_uri=https://xxx.azurewebsites.net/.auth/login/aad/callback` above, which requires setting it to Reply url on App Registration. This is completely different from the tutorials above.

I found a strange solution/hack from this github project below, which is to disable my app's 'Authentication / Authorization'
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/337#issuecomment-617402116

**Which solution** is the correct one? Because will disabling AA works for features configured in Token Configuration under App Registration?

Please note that it works locally without disabling it. 

Another issue is that when AA is disabled following the suggestion above, after users log out, it **CANNOT** redirect back to my app, it stops on `https://login.microsoftonline.com`, with message below:

> You've signed out of your account
> It's a good idea to close all browser windows.

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [x] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

1. Login to my AppService web app
2. Get the error reported above

**Expected behavior**
I should be abled to login.

**Actual behavior**

Get the error reported above

**Possible Solution**

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
> of ASP.NET Core, of MSAL.NET

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue?
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)
  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by TiagoBrenck** [comment]
Hello,

Our samples are configured to run locally, using the `https://localhost:44321/signin-oidc` reply URI. If you want to deploy your application (or the sample), the reply URI must be updated as well, according to your AppService. For i.e, `https://xxx.azurewebsites.net/signin-oidc`. For more guidance about this topic, check [our deployment steps sample](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/6-Deploy-to-Azure)

**Comment by PingPongSet** [comment]
Hi @TiagoBrenck,

Before I opened the issue, I did follow the steps on the link below. But I got the same error.
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/5-WebApp-AuthZ/5-2-Groups#how-to-deploy-this-sample-to-azure

I also got error when I tried to import Profile downloaded from App Service, which means I was not able to set the setting below:

> make sure Enable Organizational Authentication is NOT selected

I think the document for the sample is very good. 

I will try the new link you provided and come back with update.

**Comment by PingPongSet** [comment]
Hi @TiagoBrenck,

Thank you for comments.

I have checked the link you provided, which lacks settings for App Registration including Token Configuration, Permission, secret, settings on appsettings.json file and others. 

However, the link I am using is below, which includes settings mentioned above.
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/5-WebApp-AuthZ/5-2-Groups

The issue is that I am getting the exception mentioned on my OP. 

Any idea?

**Comment by TiagoBrenck** [comment]
Could you share your `Startup.cs` code section where you are using Microsoft.Identity.Web methods and configuring the authentication?

**Comment by PingPongSet** [comment]
Hi @TiagoBrenck,

Please find `Startup.cs` code file below:
```

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.AzureAD.UI;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.AspNetCore.Mvc.Authorization;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Identity.Web;
using Microsoft.Identity.Web.TokenCacheProviders.InMemory;
using Microsoft.Identity.Web.UI;

namespace Web
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.Unspecified;
                // Handling SameSite cookie according to https://docs.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-3.1
                options.HandleSameSiteCookieCompatibility();
            });

            // Sign-in users with the Microsoft identity platform
            services.AddMicrosoftWebAppAuthentication(Configuration)
                .AddMicrosoftWebAppCallsWebApi(Configuration, new string[] { "User.Read", "Directory.Read.All" })
                .AddInMemoryTokenCaches();

            services.AddMSGraphService(Configuration);    // Adds the IMSGraphService as an available service for this app.

            services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options => {
                // The following code instructs the ASP.NET Core middleware to use the data in the "groups" claim in the [Authorize] attribute and for User.IsInRole()
                // See https://docs.microsoft.com/en-us/aspnet/core/security/authorization/roles for more info.
                options.TokenValidationParameters.RoleClaimType = "groups";
            });


            services.AddControllersWithViews(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
                options.Filters.Add(new AuthorizeFilter(policy));
            }).AddMicrosoftIdentityUI();
            services.AddRazorPages();

            services.AddScoped<IAuthorisationService, AuthorisationService>();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }
            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseCookiePolicy();

            app.UseRouting();

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
                endpoints.MapRazorPages();
            });
        }
    }
}
```

Please find `appsettings.json` file below:

```
{

  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "xxx.onmicrosoft.com",
    "TenantId": "xxxx-xxx-xxx-xxx-xxx",
    "ClientId": "xxxx-xxx-xxx-xxx-xxx",
    "CallbackPath": "/signin-oidc",
    "SignedOutCallbackPath ": "/signout-callback-oidc",
    "ClientSecret": "Q.xxxxx..-x"

  },
  "ConnectionStrings": {
    "Connection": "xxxxx"
  },
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "GraphApiUrl": "https://graph.microsoft.com/beta"
}

```

Please note that I followed the steps on the link below, as I mentioned on my OP.
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/5-WebApp-AuthZ/5-2-Groups

**Comment by TiagoBrenck** [comment]
The `Startup.cs` looks fine.

I couldnt find the the instruction in the readme that tells you to enable App Service Authentication. Would you mind sending the link of the header where it is written?

Also, what version of Microsoft.Identity.Web are you using? On the discussion that you linked, [Jean-Marc replied about Microsoft.Identity.Web dealing with App Service Authentication](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/337#issuecomment-617660360)

**Comment by PingPongSet** [comment]
Hi @TiagoBrenck

Please find the packages below that are being used.

```
 <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.AzureAD.UI" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="3.1.0-preview1.19506.1" />
    <PackageReference Include="Microsoft.Graph" Version="3.10.0" />
    <PackageReference Include="Microsoft.Identity.Web" Version="0.2.3-preview" />
    <PackageReference Include="Microsoft.Identity.Web.UI" Version="0.2.3-preview" />
  </ItemGroup>
```

I used the link below.
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/5-WebApp-AuthZ/5-2-Groups

I cannot see the instruction that enable App Service Authentication from the link above. 

Can you see it?

**Comment by TiagoBrenck** [comment]
Sorry @PingPongSet I got confused about what is the problem here, so could you bear with me?
Which of these is your scenario:

1- You need to deploy the sample 5-2, *enabling* the App Service Authentication option, but it is not working?
2- You need to deploy the sample 5-2, *disabling* the App Service Authentication option, but it is not working?
3- You don`t know rather you should *enable or disable* App Service Authentication option, when deploying the sample 5-2?
4- None of these

**Comment by PingPongSet** [comment]
I want both authenication and authorisation working on both Azure and locally.

I tried enabling AppService Authentication option plus following the steps on the document, but it is not working on Azure. Instead, I have to disable AppService Authentication option to make it work.

I want to know is this the correct configuration?

**Comment by TiagoBrenck** [comment]
Yes, this is the correct configuration. Our samples documentation does not suggest you to turn that option on.

**Comment by TiagoBrenck** [comment]
Im closing this for now. Let us know if you need more guidance.
