### ISSUE TITLE
[FeatureRequest] Implement CallsMicrosoftGraph in Startup.cs

### ISSUE THREAD

**Issue by jennyf19** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#397]
See this [issue in Microsoft Identity Web](https://github.com/AzureAD/microsoft-identity-web/issues/427) for details, but let's update the samples to use the new API in [0.3.0-preview](https://aka.ms/ms-id-web/0.3.0-preview). Here's an [example](https://github.com/AzureAD/microsoft-identity-web/blob/master/tests/WebAppCallsMicrosoftGraph/Startup.cs#L33).

**Comment by jmprieur** [comment]
@kalyankrishna1 FYI

**Comment by pmaytak** [comment]
Additional converted sample as an example: [1](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/f94cf7f25b63ae3defa697c24663b35016676ae0/2.%20Web%20API%20now%20calls%20Microsoft%20Graph/TodoListService/Startup.cs#L27), [2](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/f94cf7f25b63ae3defa697c24663b35016676ae0/2.%20Web%20API%20now%20calls%20Microsoft%20Graph/TodoListService/appsettings.json#L15), [3](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph/TodoListService/Controllers/TodoListController.cs).
