### ISSUE TITLE
[Feature Request] Implement AddDownstreamWebApi 

### ISSUE THREAD

**Issue by jennyf19** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#398]
See this [issue in Microsoft Identity Web](https://github.com/AzureAD/microsoft-identity-web/issues/403) for details, but let's update the samples to use the new API in [0.3.0-preview](https://aka.ms/ms-id-web/0.3.0-preview). Here's an [example](https://github.com/AzureAD/microsoft-identity-web/blob/master/tests/WebAppCallsWebApiCallsGraph/Client/Startup.cs#L47) and the [controller](https://github.com/AzureAD/microsoft-identity-web/blob/master/tests/WebAppCallsWebApiCallsGraph/Client/Controllers/TodoListController.cs#L22)

**Comment by jmprieur** [comment]
@kalyankrishna1 FYI
