### ISSUE TITLE
How to get '.TokenAuthCookies'  cookie from this sample code - [3-WebApp-multi-APIs]

### ISSUE THREAD

**Issue by dglumesh** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#403]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [x] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

**Expected behavior**
get '.TokenAuthCookies' cookie for authentication api requests. It can help to getting tenant token array like this one using in background https://docs.microsoft.com/en-us/rest/api/resources/tenants/list. Its getting '.TokenAuthCookies' cookie when initially login. Please refer the above link to get better understand. Look for the network from developer options on browser. It will show when they got this cookie. They use that cookie to authentication 'https://token.docs.microsoft.com/accesstokens ' this api request to get tenant wise token array.

**Actual behavior**
Current application didn't get any tokenauth cookie for authentication. Currently its get '.AspNetCore.Cookies' cookie.

**Possible Solution**
(Add cookie options to startup class) I don't have clear understand on this. Please advise me on this.

**Additional context/ Error codes / Screenshots**
Current Cookies
![InkedCurrentCookies_LI](https://user-images.githubusercontent.com/19363980/91520720-9dd73a80-e913-11ea-8297-3459ad6e1aef.jpg)

Expected cookie

![InkedExpectedCookie_LI](https://user-images.githubusercontent.com/19363980/91520751-b2b3ce00-e913-11ea-86db-8dc41af7f2b0.jpg)

### OS and Version?
> Windows 10.

### Versions
> of ASP.NET Core 3.1, of MSAL.NET

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue? Yes
- did you go through the documentation: Yes
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview) I'm working on this one.
  
### Mention any other details that might be useful
Clearly I need to know how should I get '.TokenAuthCookies' from this sample code. Hopefully understand the situation. I'm working with this situation since two weeks now. I didn't get any help for that. Much appreciate any help for this. Thanks! 
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@hspin FYI

**Comment by jmprieur** [comment]
@dglumesh : 
Please look at:
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/b355c94177caa58d4e8c59a07a13429dc3788395/3-WebApp-multi-APIs/Controllers/HomeController.cs#L55-L70, 

It does what you want (without having to use a token auth cookies which is proprietary to docs.microsoft.doc, and which you should probably not use.

**Comment by dglumesh** [comment]
@jmprieur  Thank you for letting me know regarding this. I was wondering how should they access tenant list before getting tenant list by api request. i will follow with this. Thanks again 👍

**Comment by jmprieur** [comment]
@dglumesh : proposing to close this issue. Feel free to reopen if that does not work for you

**Comment by dglumesh** [comment]
Done! Thanks. @jmprieur
