### ISSUE TITLE
Issuer validation for Guest AzureAd Users

### ISSUE THREAD

**Issue by mitirazvan** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#407]
Hello
We have a multi tenant application defined in our AzureAd organization and in our client application we have implemented a custom logic to validate the issuer property for the AzureAD users. We can add tenant ids for the allowed organization and everything works ok.
The problem appears when we try to login with an User that belongs to different Organization that is not added as allowed in our system but the user is added as a Guest user in one of the allowed Organization.

Is there a way to check or to get the list of Organizations where that User is added as Guest?
Are there any other ways to validate and complete the login process for that Guest User even if its issuer is not part of our allowed Organizations/Issuers?
We would like to avoid adding extra allowed Organizations only for few guest users.
Our client application is an Asp.Net Core Web application and we are using OpenIdConnect protocol to connect with AzureAd.

**Comment by jmprieur** [comment]
You could get the list of tenants a user belongs to using ARM (Azure Resource Manager).
See https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/3-WebApp-multi-APIs/Services/ARM

But you would get the information from the claims in the User (if using Microsoft.Identity.Web), as you'll get both the home tenant ID, and the guest tenant ID (See https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web/Constants/ClaimConstants.cs)

**Comment by jennyf19** [comment]
closing as answered @mitirazvan
