### ISSUE TITLE
aspnetcore2-2: Section "About The code" refers to nonexistent file

### ISSUE THREAD

**Issue by InPermutation** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#41]
In https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/aspnetcore2-2/README.md, there is an aside to

> (see the `AccountController.cs` file)

This file does not exist on this branch.

**Comment by InPermutation** [comment]
Relatedly, `Views/Shared/_LoginPartial.cshtml` also refers to `asp-controller="Account"` in two places.

**Comment by jmprieur** [comment]
It's now part of ASP.NET Core itself. I fixed the readme. thanks for the heads-up @InPermutation 
see the [AccountController.cs](https://github.com/aspnet/AspNetCore/blob/master/src/Azure/AzureAD/Authentication.AzureAD.UI/src/Areas/AzureAD/Controllers/AccountController.cs) file in the ASP.NET Core source tree)
