### ISSUE TITLE
Specify multiple sign-in policies for service

### ISSUE THREAD

**Issue by iamalexmang** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#415]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
   1. [ ] with a work and school account in your organization: [4-WebApp-your-API/4-1-MyOrg](../blob/master/4-WebApp-your-API/4-1-MyOrg)
   1. [x] with B2C users: [4-WebApp-your-API/4-2-B2C](../blob/master/4-WebApp-your-API/4-2-B2C)
   1. [ ] with any work and school account: [4-WebApp-your-API/4-3-AnyOrg](../blob/master/4-WebApp-your-API/4-3-AnyOrg)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

Is there a way to have more than a single policy specified for the service?
Specifically, in one of my scenarios, I have multiple web applications, each with their own authentication policy, all calling a single API.
As of right now, the policy the user is authenticated with must be specified in the **service** as well.

**Comment by TiagoBrenck** [comment]
Hi @iamalexmang 

Do you mean that you have for instance:
- b2c_1_susi
- b2c_2_susi

Then depending on some logic, you would call the policy 2 instead of 1?

**Comment by iamalexmang** [comment]
There are two scenarios:

  *    I either have a multi-tenant (multiple customers, each with their own application users, part of the same tenant) system. As such, I end up having application tenant 1 using their own front-end calling b2c_1_signin_customerA, b2c_1_signin_customerB, b2c_1_signin_customerC and so on. Each time a new customer is onboarded, we develop an app for them, a singin flow as per their own requirements and demands etc.
  *   In the other scenario, we end up writing a sign-up-invitation policy, a sign-in-ropc policy, a sign-in-only flow. Hence, as the API only accepts a single policy reference, users authenticated with other policies do not have a valid token to call the downstream API.

Alex

**Comment by TiagoBrenck** [comment]
Hi Alex, 

.NET Core supports multiple authentication schemes configured, given that they have distinct names. If I got your scenario correctly, I believe that you need to set multiple JWTBearer schemes, one for each client. Since I dont have this multiple customer, multi-tenant scenario on my end, do you mind testing this approach and let us know if it worked?

This is what we are trying to achieve: https://stackoverflow.com/questions/49694383/use-multiple-jwt-bearer-authentication

Example

appsettings:

```json
{
  "AzureAdB2C1": {
    "Instance": "https://fabrikamb2c.b2clogin.com",
    "ClientId": "90c0fe63-bcf2-44d5-8fb7-b8bbc0b29dc6",
    "Domain": "fabrikamb2c.onmicrosoft.com",
    "SignedOutCallbackPath": "/signout/B2C_1_susi_fabrikam",
    "SignUpSignInPolicyId": "b2c_1_susi_fabrikam",
    "ResetPasswordPolicyId": "b2c_1_reset_fabrikam",
    "EditProfilePolicyId": "b2c_1_edit_profile_fabrikam"
  },
  "AzureAdB2C2": {
    "Instance": "https://contosob2c.b2clogin.com",
    "ClientId": "90c0fe63-bcf2-44d5-8fb7-b8bbc0b29dc6",
    "Domain": "contosob2c.onmicrosoft.com",
    "SignedOutCallbackPath": "/signout/B2C_1_susi_contoso",
    "SignUpSignInPolicyId": "b2c_1_susi_contoso",
    "ResetPasswordPolicyId": "b2c_1_reset_contoso",
    "EditProfilePolicyId": "b2c_1_edit_profile_contoso"
  }

etc...
}
```

Startup.cs:

```c#
services.AddAuthentication("BearerClient1")
            .AddMicrosoftIdentityWebApi(options =>
            {
                Configuration.Bind("AzureAdB2C1", options);

                options.TokenValidationParameters.NameClaimType = "name";
            },
            options => { Configuration.Bind("AzureAdB2C1", options); });

services.AddAuthentication(BearerClient2)
            .AddMicrosoftIdentityWebApi(options =>
            {
                Configuration.Bind("AzureAdB2C2", options);

                options.TokenValidationParameters.NameClaimType = "name";
            },
            options => { Configuration.Bind("AzureAdB2C2", options); });
```

>Note: You might require more code changes to support the multiple JWT authentication setup, this example is just an initial step.

Let us know if this solves your problem.
Thanks

**Comment by iamalexmang** [comment]
Before testing it, let me confirm that the instance and tenant is the same. Would this pose a problem?
The sole difference is that each front end application uses its custom policy (with its own customizations applied - branding, experience etc.) but they all share the API.

Alex

**Comment by TiagoBrenck** [comment]
Oh, gotcha. So nevermind about the multiple JWTBearer configuration. Let me check with the engineering team.

You might have to have your own `AccountController` though, to handle Signout, Edit profile, etc. `Microsoft.Identity.Web.UI` provides those for you, but it expects only one policy for each flow.

@jmprieur @jennyf19 @pmaytak Would you know if his scenario is supported? He has one tenant, one instance but multiple user-flows for different clients (susi_custA, susi_custB etc).

**Comment by jennyf19** [comment]
@jmprieur fyi.

**Comment by iamalexmang** [comment]
All, in the same note we came across another (somewhat typical) scenario where APIs secured by B2C must be consumed by several clients of various types (desktop, web and mobile). Whilst some of these clients have for certain [API Gateways](https://microservices.io/patterns/apigateway.html) particularly designated for them and secured using scopes and OAuth authorizations, others are shared across these clients. 

The troublesome part is that these clients have authentication policies relevant to the client. For example, there's a custom authentication flow for mobile, a different one for desktop and a different one for web clients - not having the ability to specify multiple sign-in policies poses a potential blocker which currently seems to be overcome only by using multiple APIs which have the same purpose/responsibilities.

**Comment by jmprieur** [comment]
@iamalexmang : you could create several endpoints, with different authentication schemes, and these endpoints would really delegate to the same method on the controller (they would only take care of the auth)
https://github.com/AzureAD/microsoft-identity-web/wiki/web-apis#using-multiple-authentication-schemes

**Comment by iamalexmang** [comment]
May I please pick your mind on that, Jean Marc?

I am aware of the multiple authentication schemes approach, but in this case the authentication scheme is almost the same - the sole difference being the authority, or, put differently, the custom policy used for signing users in. What I don’t yet realize is how you would bind that to the various endpoints of the same project.

Would you have multiple application settings section?
If so, various extension methods from Microsoft Identity Platform will fail binding.
And then, how would you enforce the utilization of the various configurations for each controller?

Alex

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jmprieur** [comment]
@iamalexmang : yes you would have multiple AzureADB2Cx sections in the appsettings.json. And you'd have to register each (duplicate the lines). However, you would have only one AddAuthentication with a parameter (the default value). The others would not have a default value.

In the controller actions, you would use the scheme https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-3.1#selecting-the-scheme-with-the-authorize-attribute..

Happy to tell you more, but I'm not sure I fully understand the question?

**Comment by jmprieur** [comment]
Closing as I believe I answered
fee free to reopen if I didn't, @iamalexmang
