### ISSUE TITLE
Retrieve user groups in Startup.cs

### ISSUE THREAD

**Issue by sameer-kumar** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#421]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [x] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
   1. [ ] with a work and school account in your organization: [4-WebApp-your-API/4-1-MyOrg](../blob/master/4-WebApp-your-API/4-1-MyOrg)
   1. [ ] with B2C users: [4-WebApp-your-API/4-2-B2C](../blob/master/4-WebApp-your-API/4-2-B2C)
   1. [ ] with any work and school account: [4-WebApp-your-API/4-3-AnyOrg](../blob/master/4-WebApp-your-API/4-3-AnyOrg)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

I'm trying to modify the provided sample WebApp-OpenIDConnect-DotNet.sln to pull user group membership in Startup.cs class file so that I can add user groups as claims. My startup.cs file looks like a bit like this:

` services.AddMicrosoftIdentityWebAppAuthentication(Configuration, "AzureAD")
                .EnableTokenAcquisitionToCallDownstreamApi(initialScopes)
                .AddMicrosoftGraph(Configuration.GetSection("MSGraphApi"))
                .AddInMemoryTokenCaches();

services.Configure<MicrosoftIdentityOptions>(options =>
            {
                options.Events.OnTokenValidated = async (context) =>
                {
                    (context.Principal.Identity as ClaimsIdentity).AddClaim(new Claim("AddByMyWebApp", "ClaimValue"));
                };
             };`

**Expected behavior**

**Actual behavior**

**Possible Solution**

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
> of ASP.NET Core, of MSAL.NET
ASP.Net Core Version 3.1
Microsoft.Identity.Web Version="0.4.0-preview"
Microsoft.Identity.Web.UI Version="0.4.0-preview"
Microsoft.Identity.Web.MicrosoftGraph Version="0.4.0-preview"

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue? (Yes)
- did you go through the documentation: (Yes)
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)
  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Shama-K** [comment]
Is there any specific reason to add claims in Startup.cs? As you can get groups claim by [configuring group claims for applications with Azure Active Directory](https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-fed-group-claims#:~:text=Configure%20the%20Azure%20AD%20Application%20Registration%20for%20group,only%20the%20groups%20that%20are%20explicitl%20...%20).
Related sample can be found here: [5-WebApp-AuthZ/5-2-Groups](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/5-WebApp-AuthZ/5-2-Groups).

**Comment by sameer-kumar** [comment]
I've looked at that sample too and see this in Startup.cs

services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options => {

                // The following code instructs the ASP.NET Core middleware to use the data in the "groups" claim in the [Authorize] attribute and for User.IsInRole()
                // See https://docs.microsoft.com/en-us/aspnet/core/security/authorization/roles for more info.
                options.TokenValidationParameters.RoleClaimType = "groups";
            });

However, my use case is different. I want to retrieve groups which user is part of and then modify them a bit per my application logic and finally add those details into user claims. I am able to add dummy claim in token with the following code:

services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
{

    options.Events.OnTokenValidated = async (context) =>
    {
        // ToDo: read Graph here instead of hard coding claims
        (context.Principal.Identity as ClaimsIdentity).AddClaim(new Claim("AddByMyWebApp", "ClaimValue"));
    }
}

**Comment by Shama-K** [comment]
As mentioned earlier, You can retrieve groups claim by [configuring group claims for applications with Azure Active Directory](https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-fed-group-claims#:~:text=Configure%20the%20Azure%20AD%20Application%20Registration%20for%20group,only%20the%20groups%20that%20are%20explicitl%20...%20) in the app registration.
Can you try that and share if the issue is resolved or not?

**Comment by sameer-kumar** [comment]
Sorry, I guess I was not able to communicate properly. All the links you have shared shown ways to access group membership in ID token (automatically) or manually in Controller. What I need is a way to access GraphAPI from Startup.cs class so that I can pull details of current user and store them in token as Claims. For instance, I tried this code in Startup but without success:

```
services.Configure(OpenIdConnectDefaults.AuthenticationScheme, options =>
{
  options.Events.OnTokenValidated = async (context) =>
  {
    // ToDo: read Graph here instead of hard coding claims
    (context.Principal.Identity as ClaimsIdentity).AddClaim(new Claim("AddByMyWebApp", "ClaimValue"));
     var tokenAcquisition = context.HttpContext.RequestServices.GetRequiredService<ITokenAcquisition>();
     string accessToken = await tokenAcquisition.GetAccessTokenForUserAsync(initialScopes); //FAILS..
     
  }
}
```

**Comment by sameer-kumar** [comment]
I see there is an update to samples you linked on github. Let me try those, will keep you posted.

**Comment by sameer-kumar** [comment]
Your updated [sample](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/5-WebApp-AuthZ/5-2-Groups) works. I have some other questions but not related with the original post hence will start a new discussion assuming you don't want to twist this thread. Thanks!

**Comment by jennyf19** [comment]
@sameer-kumar can this be closed? thanks.

**Comment by vamsea2002** [comment]
X💓🥢

Thanks & Regards
Vamsi J

________________________________
