### ISSUE TITLE
Add steps how to setup Scopes and Permissions 

### ISSUE THREAD

**Issue by MarekLani** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#425]
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:
In the following readme.md file https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C please also include steps how to setup scope and permissions if one wants to use custom AD B2C apps to run the sample.

**Comment by v-michaelmi** [comment]
Steps are now included in the **Setup** instructions of the main `README` file.

Closing.
