### ISSUE TITLE
Call to an internal api fails

### ISSUE THREAD

**Issue by sameer-kumar** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#427]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [x] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [x] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
   1. [x] with a work and school account in your organization: [4-WebApp-your-API/4-1-MyOrg](../blob/master/4-WebApp-your-API/4-1-MyOrg)
   1. [ ] with B2C users: [4-WebApp-your-API/4-2-B2C](../blob/master/4-WebApp-your-API/4-2-B2C)
   1. [ ] with any work and school account: [4-WebApp-your-API/4-3-AnyOrg](../blob/master/4-WebApp-your-API/4-3-AnyOrg)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [x] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

I am trying to integrate the sample code provided in WebApp-OpenIDConnect-DotNet project which is part of 5-WebApp-AuthZ\5-2-Groups repository in my current app. However, my api calls stopped working after integration. Each api call from mvc controller now returns Sigin page with status code 200. 

**Expected behavior**

I expect the code should be able to call my internal apis without prompting to sign-in.

**Actual behavior**

Instead of Api response, I receive typical sign page html in json body.

**Possible Solution**

**Additional context/ Error codes / Screenshots**
This is what you can do to mimic my setup:
1. Add a new Api controller.

```CSharp
[Route("api/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {
        [HttpGet]
        public IEnumerable<int> Get()
        {
            return Enumerable.Range(1, 5).ToArray();
        }
    }
```
2. Add below line in Startup.cs > ConfigureServices()
`services.AddHttpClient();`

3. Add/update these lines in HomeController.cs

```CSharp
[Authorize]
    public class HomeController : Controller
    {
        private readonly IHttpClientFactory _clientFactory;

        public HomeController(IHttpClientFactory clientFactory)
        {
            _clientFactory = clientFactory;
        }

        public async Task<IActionResult> Index()
        {
            ViewData["User"] = HttpContext.User;
            // Calls method GetSessionGroupList to get groups from session.
            var groups = GraphHelper.GetUserGroupsFromSession(HttpContext.Session);
            if (groups?.Count > 0)
            {
                ViewData.Add("groupClaims", groups );
            }

            // Call internal api
            var apiUrl = new Uri(new Uri(this.Request.GetEncodedUrl()), "api/values");
            var request = new HttpRequestMessage(HttpMethod.Get, apiUrl);
            var httpClient = _clientFactory.CreateClient();
            httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            var response = await httpClient.SendAsync(request);
            if (response.IsSuccessStatusCode)
            {
                string str = await response.Content.ReadAsStringAsync();
            }
            else
            {
                //not success.
            }
            return View();
        }
}
```

### Any log messages given by the failure
This is what I get back in response content:

[response.txt](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/files/5404953/response.txt)

### OS and Version?
> Windows 10. 

### Versions
> ASP.NET Core 3.1

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue?
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)
  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@sameer-kumar if your API is protected, you necessarily need to provide an access token (even if you call it from your own application). I think that requesting a token which scope is your own clientID should work.

To do that, I would recommend you use the `IDownstreamWebApi` interface that you would inject by dependency injection. See https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-call-api?tabs=aspnetcore#option-2-call-a-downstream-web-api-with-the-helper-class for details

```CSharp
HttpResponseMessage responseMessage = await _downstreamApi.CallWebApiForUser(null,
  options => {
     options.BaseUrl = "/";
     options.RelativePath = "api/values";
     options.Scopes = "your-client-id";
   });

```

**Comment by sameer-kumar** [comment]
@jmprieur This is what I get from using the above code:

> **ArgumentException: API does not accept client id as a user-provided scope**

**Comment by jmprieur** [comment]
@sameer-kumar : ok. I had not realized this had changed, but this makes sense.

Given you have a Web API, you probably exposed scopes (See https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-app-registration#exposed-api) ? 
So, I suggest passing-in the scope associated with the endpoint: `api://clientId/access_as_user` for instance.

**Comment by sameer-kumar** [comment]
@jmprieur what do you mean when you say "_you probably exposed scopes_". Based on the mentioned article I have followed this [step](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-app-registration#exposing-delegated-permissions-scopes) in my AAD registration of app associated with web app. And when I run the app in VS with scope changed as `api://{clientId}/access_as_user` then I get this error: 

> **MsalUiRequiredException: No account or login hint was passed to the AcquireTokenSilent call.**

**Comment by jmprieur** [comment]
Did you use the `[AuthorizeForScopes]` attribute? : https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access

**Comment by sameer-kumar** [comment]
@jmprieur now, i'm getting different error. 
Can I use both [option1](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-app-configuration?tabs=aspnetcore#option-1-call-microsoft-graph) and [option2](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-app-configuration?tabs=aspnetcore#option-2-call-a-downstream-web-api-other-than-microsoft-graph) in same project?
This is my Startup.cs as: 

```
var initialScopes = new string[] { Constants.ScopeUserRead, Constants.ScopeGroupMemberRead };
services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
             .AddMicrosoftIdentityWebApp(
                options =>
                {
                    Configuration.Bind("AzureAd", options);
                    options.Events = new OpenIdConnectEvents();
                    options.Events.OnTokenValidated = async context =>
                    {
                        //Calls method to process groups overage claim.
                        var overageGroupClaims = await GraphHelper.GetSignedInUsersGroups(context);
                    };
                }, options => { Configuration.Bind("AzureAd", options); })
                    .EnableTokenAcquisitionToCallDownstreamApi(options => Configuration.Bind("AzureAd", options), initialScopes)
                    .AddMicrosoftGraph(Configuration.GetSection("GraphAPI"))
                    .AddDownstreamWebApi("MyApi", Configuration.GetSection("MyApiEndPoint"))
                    .AddInMemoryTokenCaches();
```

This is my MVC controller action method,

```
[AuthorizeForScopes(ScopeKeySection = "MyApiEndPoint:Scopes")]
public async Task<IActionResult> Index()
{
    var serviceName = "MyApi";
    var val1 = await _downstreamWebApi.CallWebApiForUserAsync<object, IEnumerable<int>>(
            serviceName, null, options => {
                options.RelativePath = "api/values";
                options.Scopes = "api://{Client_Id_WebApp}/access_as_user";
            });
}
```

Mvc controller action is called twice - Is this expected? 
Also, I don't think, my WebApi ValuesController is triggered at all.
The error thrown is:

> **JsonReaderException: '<' is an invalid start of a value. LineNumber: 2 | BytePositionInLine: 0.**

**Comment by sameer-kumar** [comment]
@jmprieur  I realized, its same error. But this time I was trying to cast html response into Json hence the above error. So back to where I started  :-(. 
Essentially I followed all the links you mentioned but no luck. Do you have access to a sample for my use case?

**Comment by sameer-kumar** [comment]
@jmprieur the response which I received back by calling downstream api looks like a sign-in form as html text. Instead I assume, it should pop-up a sign-in/consent window.

**Comment by jmprieur** [comment]
@sameer-kumar : what is your web API? isn't it a web app? 
It does not seem to be a proper web API?

**Comment by sameer-kumar** [comment]
Yes, my webapi is part of asp.net core mvc 3.1 project, if thats what you mean. I am simply updating this [sample](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/5-WebApp-AuthZ/5-2-Groups)

**Comment by jmprieur** [comment]
@sameer-kumar : did you read this article? https://github.com/AzureAD/microsoft-identity-web/wiki/Mixing-web-app-and-web-api-in-the-same-ASP.NET-core-app

Did you also expose a scope in your app registration?

Shouldn't your API controller inherit from APIController?

**Comment by sameer-kumar** [comment]
@jmprieur Thanks for the link. I have used the provided code in my app but no luck. Here how my Startup.cs looks like after the new code integration:

```
services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                    .AddMicrosoftIdentityWebApp(
                options =>
                {
                    Configuration.Bind("AzureAd", options);
                    options.Events = new OpenIdConnectEvents();
                    options.Events.OnTokenValidated = async context =>
                    {
                        //Calls method to process groups overage claim.
                        var overageGroupClaims = await GraphHelper.GetSignedInUsersGroups(context);
                    };
                }, options => { Configuration.Bind("AzureAd", options); })
                    .EnableTokenAcquisitionToCallDownstreamApi(options => Configuration.Bind("AzureAd", options), initialScopes)
                    .AddMicrosoftGraph(Configuration.GetSection("GraphAPI"))
                    .AddDownstreamWebApi("MyApi", Configuration.GetSection("MyApiEndPoint"))
                    .AddInMemoryTokenCaches();

            services
                .AddAuthentication()
                .AddMicrosoftIdentityWebApi(Configuration.GetSection("AzureAd"), JwtBearerDefaults.AuthenticationScheme)
                .EnableTokenAcquisitionToCallDownstreamApi();
```


Yes, I did exposed a scope in my app registration. 
This is how my webApi controller looks:

```
[Route("api/[controller]")]
[ApiController]
[Authorize]
public class ValuesController : ControllerBase{}
```

What am I missing here?

**Comment by sameer-kumar** [comment]
Phew! It was a struggle to pull it off. The thing which I was missing is authN scheme name from Api Controller:

`[Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]`

@jmprieur thanks again for helping me through this and all useful links.
And on to next challenge now...

**Comment by jmprieur** [comment]
Thanks for the update, @sameer-kumar. I'm happy you made it work.
