### ISSUE TITLE
Information on how to authenticate for Resource Owner Password grant type with AD

### ISSUE THREAD

**Issue by PingPongSet** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#43]
Is it possible to authenticate using Resource Owner Password grant type with AD?

If so, can anyone provide links or info?

**Comment by jmprieur** [comment]
It is, but we don't encourage it as there are limitations.
The conceptual doc is: http://aka.ms/msal-net-up
A sample is linked from the bottom of that page.

**Comment by jmprieur** [comment]
@PingPongSet closing the question as I answered.
Feel free to continue using this issue, I also monitor the closed issues
