### ISSUE TITLE
Login errors when having more than one tenant and multiple apps in single tenant mode.

### ISSUE THREAD

**Issue by gavin2n** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#436]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
   1. [ ] with a work and school account in your organization: [4-WebApp-your-API/4-1-MyOrg](../blob/master/4-WebApp-your-API/4-1-MyOrg)
   1. [ ] with B2C users: [4-WebApp-your-API/4-2-B2C](../blob/master/4-WebApp-your-API/4-2-B2C)
   1. [ ] with any work and school account: [4-WebApp-your-API/4-3-AnyOrg](../blob/master/4-WebApp-your-API/4-3-AnyOrg)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ x] Other (please describe)
### Repro-ing the issue

**Repro steps**

Have two Azure AD tenants tenant A and tenant B
and two applications app A and app B

each app is registered on its own tenant in single tenant mode. 

**Expected behavior**
The login page either automatically logs in using the correct account for the tenant or prompts for a new login

**Actual behavior**
If you are logged into only app A and try to access app B, you get  an error about your user not existing in tenant B. and it will not let you login,

if your are logged into both, it lets you chose but will error if you pick incorrectly. 

**Possible Solution**
Workaround use incognito mode each time you switch apps?
 have something like the google HD parameter? 
https://developers.google.com/identity/protocols/oauth2/openid-connect#hd-param

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 

### OS and Version?
Windows 10

### Versions
core 3.1

### Attempting to troubleshooting yourself:

no luck finding anything through searching, The domain setting looks useful, but that only appears to be used for azure B2C
  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@gavin2n 

This is because of the SSO. 

What you could do is, in your **startup.cs**, after the call to `.AddMicrosoftIdentityWebApp(Configuration.GetSection("AzureAd"))` etc ... to add the following:

```CSharp
  services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
  {
    options.Prompt = "select_account";
  });
```

This will override the prompt to force the login.

**Comment by gavin2n** [comment]
Thanks, that does at least give users a choice on which account to use to login.

but just to clarify, there is no way of telling https://login.microsoftonline.com/ to filter the shown accounts at all?

**Comment by jmprieur** [comment]
@gavin2n: There is, by using a tenanted authority
(tenantId = a tenant, instead of common or organizations)

What do you have in your appsettings.json for "Instance", possibly "Authority" (used in the case of Blazor wasm apps), "TenantId", and "Domain" (used for B2C)?

**Comment by gavin2n** [comment]
"Instance": "https://login.microsoftonline.com/",
    "TenantId": "481c5bef-6d6b-45e4-9bf5-0b562130e928",
    "Domain": "amigo.me"  (primary domain of the above tenant)

its a webapp and the app manifest is set to "signInAudience": "AzureADMyOrg",

**Comment by jmprieur** [comment]
Adding @hpsin

**Comment by hpsin** [comment]
You're correct, @gavin2n  - there's no way to filter out users at this time such that we only show users who can sign into the app successfully.  This has to do with a number of checks that are only done after the account is selected - we can't know ahead of time that user@fabrikam is not eligible to sign into Contoso for between 4 and 6 reasons, depending on the sign in request.  While we have some research ongoing to find better ways to accomplish this, at the moment we don't have a solution for you.  

Unfortunately, by-design.  #please-close (@gavin2n happy to discuss more, just closing to indicate no solution exists)

**Comment by gavin2n** [comment]
Thanks for clarifying.

From reading the docs I'm guessing that going forwards we should be using multiple Azure B2C instances rather than just multiple  azure AD tenants with single tenant apps
