### ISSUE TITLE
Access token timeout via Microsoft identity platform and ASP.NET Core

### ISSUE THREAD

**Issue by PingPongSet** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#438]
**Updated to the title and the body to make it clearer that It is about the timeout of access token (login session), not session state.**

What is the length of  Access token timeout by default via Azure AD and Microsoft Identity Platform in the code below, which is from the link below?

https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/5-WebApp-AuthZ/5-2-Groups/Startup.cs

```csharp
     public void ConfigureServices(IServiceCollection services)
            {
                var initialScopes = new string[] { Constants.ScopeUserRead, Constants.ScopeGroupMemberRead };
                services.Configure<CookiePolicyOptions>(options =>
                {
                    // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                    options.CheckConsentNeeded = context => true;
                    options.MinimumSameSitePolicy = SameSiteMode.Unspecified;
                    // Handling SameSite cookie according to https://docs.microsoft.com/en-us/aspnet/core/security/samesite
                    options.HandleSameSiteCookieCompatibility();
                });
    
                // Sign-in users with the Microsoft identity platform
                services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                        .AddMicrosoftIdentityWebApp(
                    options =>
                    {
                        Configuration.Bind("AzureAd", options);
                        options.Events = new OpenIdConnectEvents();
                        options.Events.OnTokenValidated = async context =>
                        {
                            //Calls method to process groups overage claim.
                            var overageGroupClaims = await GraphHelper.GetSignedInUsersGroups(context);
                        };
                    }, options => { Configuration.Bind("AzureAd", options); })
                        .EnableTokenAcquisitionToCallDownstreamApi(options => Configuration.Bind("AzureAd", options), initialScopes)
                        .AddMicrosoftGraph(Configuration.GetSection("GraphAPI"))
                        .AddInMemoryTokenCaches();
    
                // Adding authorization policies that enforce authorization using group values.
                services.AddAuthorization(options =>
                {
                options.AddPolicy("GroupAdmin",
                policy => policy.Requirements.Add(new GroupPolicyRequirement(Configuration["Groups:GroupAdmin"])));
                    options.AddPolicy("GroupMember",
                  policy => policy.Requirements.Add(new GroupPolicyRequirement(Configuration["Groups:GroupMember"])));
                });
                services.AddSingleton<IAuthorizationHandler, GroupPolicyHandler>();
    
                services.AddDistributedMemoryCache();
                services.AddSession(options =>
                {
                    options.IdleTimeout = TimeSpan.FromMinutes(1);
                    options.Cookie.HttpOnly = true;
                    options.Cookie.IsEssential = true;
                });
    
                services.AddControllersWithViews(options =>
                {
                    var policy = new AuthorizationPolicyBuilder()
                        .RequireAuthenticatedUser()
                        .Build();
                    options.Filters.Add(new AuthorizeFilter(policy));
                }).AddMicrosoftIdentityUI();
                services.AddRazorPages();
            }
```

I guess the links below have the answer. Can anyone please confirm this and provide answer ideally?

https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes
https://docs.microsoft.com/en-us/azure/active-directory/develop/configure-token-lifetimes

**Questions**
1 What is access token timeout by default from Azure AD?
2 How to set it if possible?

**Comment by Shama-K** [comment]
@PingPongSet, Thank you for taking time. I am afraid there was testing code for session timeout in [Startup.cs](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/4f196bbe09db88a480a140278583259d723d95cb/5-WebApp-AuthZ/5-2-Groups/Startup.cs#L71). I have updated the code, it will use default session timeout of ASP.NET Core. 
To understand session policies via Azure AD you can follow: [Configure authentication session management with Conditional Access](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/howto-conditional-access-session-lifetime)

**Comment by PingPongSet** [comment]
@Shama-K 
Thank you for your reply.

On the session timeout, do you mean it is one minute? But this is session state, not login session timeout. Please correct me if I am wrong.

            services.AddSession(options =>
            {
                options.IdleTimeout = TimeSpan.FromMinutes(1);
            });

**Comment by PingPongSet** [comment]
@Shama-K

I updated the OP to make it clearer that I am asking about access token timeout, not session state timeout. Sorry for the confusion.

**Comment by jmprieur** [comment]
@PingPongSet : do you mean the access token expiry?

**Comment by PingPongSet** [comment]
@jmprieur yes.

**Comment by jmprieur** [comment]
@PingPongSet : please see https://docs.microsoft.com/azure/active-directory/develop/configure-token-lifetimes

**Comment by jmprieur** [comment]
Closing as this is answered
