### ISSUE TITLE
Unable to grant access

### ISSUE THREAD

**Issue by PingPongSet** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#44]
I followed the instructions on link below

https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2

Use Option 1 of Step 2

When I run the app locally, I can select my azure account to login, however, I got the error below after that:

The url: https://login.microsoftonline.com/common/reprocess?ctx=xxxxx ....

Need admin approval
ADPdaSsoWebApp
ADPdaSsoWebApp needs permission to access resources in your organisation that only an admin can grant. Please ask an admin to grant permission to this app before you can use it.

Have an admin account? Sign in with that account

Return to the application without granting consent

Why do I need admin to grant access? Is there a way around?

**Comment by jmprieur** [comment]
This indicates that the admin of the tenant where you want to install the application has disabled the possibility for users to consent, therefore requiring an admin consent.

You probably want to create your own tenant (in the Azure Portal, new resource, Azure Active Directory).
