### ISSUE TITLE
Web API calls Microsoft Graph

### ISSUE THREAD

**Issue by ducalai** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#447]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue
1. [ ] Web app calling your own Web API
   1. [ ] with a work and school account in your organization: [4-WebApp-your-API/4-1-MyOrg](../blob/master/4-WebApp-your-API/4-1-MyOrg)
   1. [x] with B2C users: [4-WebApp-your-API/4-2-B2C](../blob/master/4-WebApp-your-API/4-2-B2C)
   1. [ ] with any work and school account: [4-WebApp-your-API/4-3-AnyOrg](../blob/master/4-WebApp-your-API/4-3-AnyOrg)

### Repro-ing the issue

**Repro steps**

Complete [4-WebApp-your-API/](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C) scenario. Then, try to make Web API call Microsoft Graph API as mentioned in the **Next steps** section, following [2. Web API now calls Microsoft Graph](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph) documentation.

**Expected behavior**
Get information from authenticated User coming from Graph API

**Actual behavior**
Error thrown:
---> MSAL.NetCore.4.22.0.0.MsalServiceException: 
      	ErrorCode: unsupported_grant_type
      Microsoft.Identity.Client.MsalServiceException: AADB2C90086: The supplied grant_type [urn:ietf:params:oauth:grant-type:jwt-bearer] is not supported.

**Possible Solution**

**Additional context/ Error codes / Screenshots**

### OS and Version?
> macOS Catalina

### Versions
> .NET5.0, Microsoft.Identity.Web 1.3.0
  
### Mention any other details that might be useful
I am probably messing up with the DefaultScope when configuring the client. But I cannot figure out how to set it correctly. Can you provide some example?
Thanks for your help

**Comment by Shama-K** [comment]
[2. Web API now calls Microsoft Graph](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph) adds delegated permissions of MS graph API in app registration. But in B2C, users can obtain tokens for Microsoft APIs using application permissions. The instructions in [Manage Azure AD B2C with Microsoft Graph](https://docs.microsoft.com/en-us/azure/active-directory-b2c/microsoft-graph-get-started?tabs=app-reg-ga) explain the application registration in detail.

**Comment by ducalai** [comment]
@Shama-K, thx for your reply. Would you say that:
- I need to make an extra application registration for a "service account" app which would use client_credentials and then inform my Web API to use it when calling for Graph API. How do I make the link between my Web API and that "management app" ?
- or can I edit Web API registration to make it act as "service account" to call Graph API ?

Regards

**Comment by Shama-K** [comment]
@ducalai, you need to update client app, as on-behalf-of flow is not currently supported in the Azure AD B2C.

**Comment by ducalai** [comment]
So, once the app registration has been updated with proper application permissions, the web client app must request a token from Azure AD and then call Graph API, without passing through Web API. Right?

**Comment by Shama-K** [comment]
yes right, you can use client credentials flow to acquire token.

**Comment by ducalai** [comment]
Thanks for your help. Is Azure AD B2C planning to support on-behalf-of flow soon? This is a limitation that has a large impact on architecture design.

**Comment by Shama-K** [comment]
Currently, we don't have a timeline for Azure AD B2C on-behalf-of flow support.

**Comment by nickgmicrosoft** [comment]
Shama is correct, there's no immediate timeline for OBO support. For client-credentials, note that it should be using AAD's client credentials service. This can be done from within the same Azure AD B2C tenant, just using AAD's endpoints (ie. login.microsoftonline.com without a policy parameter) instead of B2Cs. See [this](https://docs.microsoft.com/en-us/azure/active-directory-b2c/microsoft-graph-get-started?tabs=app-reg-ga) documentation.
