### ISSUE TITLE
How to use JWTTokenValidation along with Microsoft.Identity.Web

### ISSUE THREAD

**Issue by brijesh-1111** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#448]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [x] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
   1. [ ] with a work and school account in your organization: [4-WebApp-your-API/4-1-MyOrg](../blob/master/4-WebApp-your-API/4-1-MyOrg)
   1. [ ] with B2C users: [4-WebApp-your-API/4-2-B2C](../blob/master/4-WebApp-your-API/4-2-B2C)
   1. [ ] with any work and school account: [4-WebApp-your-API/4-3-AnyOrg](../blob/master/4-WebApp-your-API/4-3-AnyOrg)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

`services.AddAuthentication(AzureADDefaults.AuthenticationScheme).AddAzureAD(options => Configuration.Bind("AzureAd", options)); `

returns `AuthenticationBuilder `which can further be utilized to join AddJwtBearer like below

` services.AddAuthentication(AzureADDefaults.AuthenticationScheme).AddAzureAD(options => this.configuration.Bind("AzureAd", options)).AddJwtBearer()`

While `services.AddMicrosoftIdentityWebAppAuthentication(Configuration);` returns `MicrosoftIdentityWebAppAuthenticationBuilderWithConfiguration`

Can you also document what is the best way to add AddJwtBeaer while we use Microsoft.Identity.Web by replacing the existing AddAzureAD?

We use AddJwtBearer to validate the token coming from a different application (like Microsoft Azure MarketPlace) where the user login is not required

**Expected behavior**
AddMicrosoftIdentityWebAppAuthentication either should return AuthenticationBuilder or there should be a way to further attached the JWTBearer validation in the pipeline

### OS and Version?
> Windows 10

### Versions
> of ASP.NET Core 5

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue?
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)
  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Shama-K** [comment]
We are looking at this scenario and will get back with an update.

**Comment by pmaytak** [comment]
@brijesh-1111 Does this wiki describe what you're looking for? [Mixing web app and web API in the same ASP.NET core app](https://github.com/AzureAD/microsoft-identity-web/wiki/Mixing-web-app-and-web-API-in-the-same-ASP.NET-core-app)

**Comment by brijesh-1111** [comment]
Yes, Indeed this is exactly, I was looking for - Thanks pmaytak. 

I have added these in my code (except AddMicrosoftGraph - which was not a requirement for my code). 
My solution has both Web App + Web API flavor (together) and both refer the Azure AD (one through Code flow vs another through Client Cred). 

Code flow was working with AddMicrosoftIdentityWebApp but I was not sure in the chain How can we add AddMicrosoftIdentityWebApi that request coming from Azure Marketplace Fulfilment API (coming with token) and I have to add logic to validate that through my client credential.
