### ISSUE TITLE
5-WebApp-AuthZ - What is the alternative of storing the groups in the Session 

### ISSUE THREAD

**Issue by brijesh-1111** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#450]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
   1. [ ] with a work and school account in your organization: [4-WebApp-your-API/4-1-MyOrg](../blob/master/4-WebApp-your-API/4-1-MyOrg)
   1. [ ] with B2C users: [4-WebApp-your-API/4-2-B2C](../blob/master/4-WebApp-your-API/4-2-B2C)
   1. [ ] with any work and school account: [4-WebApp-your-API/4-3-AnyOrg](../blob/master/4-WebApp-your-API/4-3-AnyOrg)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [x] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

I really like the entire solution and the way it structures. It helps a lot to understand each scenario very clearly and throughout. I appreciate the effort team is adding to maintain this repository. 
### Repro-ing the issue

**Repro steps**

I have two query regarding 5-WebApp-AuthZ part (5-2-Groups in perticular). 

**Query 1:** I login in and checked the claims for the Principal.Identity and I found that my login user is part of two groups and both are coming under the claims list. so, the question I have is why are we querying the AD Group again? can't we use those groups which already part of the claims coming after login? or that won't be sufficient?

**Query 2:** Suppose we like to store those groups then is there a better way than session? I mean like we have current user identity with role as claims, can't we have groups also like the same way as part of identity itself? so that, we don't require to have that in session? 

**Expected behavior**

Just want to understand the above two queries.  there is nothing wrong so-far I found with the solution. I just want to understand if we can have groups the same way we have roles (as part of current user principal identity)

### OS and Version?
> Windows 10 

### Versions
> ASP.NET Core 5

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Shama-K** [comment]
Please find the below response for your queries:
Query 1: If incoming token contains Group Overage claim then only we request groups from Microsoft Graph and store in session. If the token already has groups then it'll not retrieve the groups again. [The groups overage claim](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/5-WebApp-AuthZ/5-2-Groups#the-groups-overage-claim) section in Readme file explains this scenario. 
Query 2: With groups overage, the number of groups returned is large so we have stored them into session. If we add all the groups in claims collection then size of authentication cookie is increased and the browser can throw Bad request exception.
If you have number of groups lower than overage limit then you don't need to go through these steps.  
Let me know if you require more information.

**Comment by Shama-K** [comment]
Please find the below response for your queries:
For Query 1: If incoming token contains Group Overage claim then only we request groups from Microsoft Graph and store in session. If the token already has groups then it'll not retrieve the groups again. [The groups overage claim](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/5-WebApp-AuthZ/5-2-Groups#the-groups-overage-claim) section in Readme file explains this scenario. 
For Query 2: With groups overage, the number of groups returned is large so we have stored them into session. If we add all the groups in claims collection then size of authentication cookie is increased and the browser can throw Bad request exception.
If you have number of groups lower than overage limit then you don't need to go through these steps.  
Let me know if you require more information.

**Comment by jmprieur** [comment]
https://github.com/AzureAD/microsoft-identity-web/issues/846 might also be promissing

**Comment by brijesh-1111** [comment]
I understood it now. As you described, It makes sense to carefully consider whether to use the cookie or session while we have the larger set. 
extension methods to fetch the groups and role would be really a great value addition. 
Thanks.
