### ISSUE TITLE
NameClaimType = "name" ?

### ISSUE THREAD

**Issue by arqe** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#454]
Hi, 

why is the authentication scheme set to use TokenValidationParameters.NameClaimType = "name"; ?

It seems that it gets mapped to what is received from Azure AD B2C as "Display Name". Something that may change or be changed for whatever reason in the future. Is this on purpose?

![image](https://user-images.githubusercontent.com/16734197/105714948-47e7dc80-5f1d-11eb-82f8-d503bccecc36.png)

I find claims to identity mapping very confusing, is anywhere comprehensive documentation how is that managed when using Microsoft.Identity.Web? I can found many examples and tutorials. but no real documentation :(. 

Many thanks

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@jennyf19 : do you want to answer this one?

**Comment by jmprieur** [comment]
@arge 
you could use the name of any claim displaying information about the user (displayed in the web app). It's just that depending on the iDP this name is different. See https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens#claims-in-an-id_token for AAD and

**Comment by arqe** [comment]
@jmprieur 

Thank you - it took me some time to understand, but now I think I may got it. 

 `opions.tokenValidationParameters.NameClaimType = "name" `

**only** tells middleware what claim is to be mapped to ClaimsPrincipal.Identity.Name.  

In this case the claim of "name" type, regardless of what is default, or whether I call 
JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();

Is it correct? (Sorry for such a basic question, I am definitely still at the steep part of the learning curve.)

**Comment by jmprieur** [comment]
Yes this is correct, @arqe
You might also be interested in https://github.com/AzureAD/microsoft-identity-web/issues/911
