### ISSUE TITLE
[ASP.NET MVC] No Account or login hint after every debug

### ISSUE THREAD

**Issue by omarmallat** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#461]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [x] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [x] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [x] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
   1. [ ] with a work and school account in your organization: [4-WebApp-your-API/4-1-MyOrg](../blob/master/4-WebApp-your-API/4-1-MyOrg)
   1. [ ] with B2C users: [4-WebApp-your-API/4-2-B2C](../blob/master/4-WebApp-your-API/4-2-B2C)
   1. [ ] with any work and school account: [4-WebApp-your-API/4-3-AnyOrg](../blob/master/4-WebApp-your-API/4-3-AnyOrg)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

using MSALPerUserMemoryTokenCache to store cache, 
Start with Debugging in Visual Studio 2019

```
            return new GraphServiceClient(
                new DelegateAuthenticationProvider(
                    async (requestMessage) =>
                    {
                        var idClient = ConfidentialClientApplicationBuilder.Create(Models.AuthenticationConfig.ClientId)
                            .WithRedirectUri(Models.AuthenticationConfig.RedirectUri)
                            .WithClientSecret(Models.AuthenticationConfig.ClientId)
                            .Build();

                        var CacheToken = new Models.MSALPerUserMemoryTokenCache(idClient.UserTokenCache, ClaimsPrincipal.Current);

                        var accountId = ClaimsPrincipal.Current.GetMsalAccountId();
                        var account = await idClient.GetAccountAsync(accountId); //Return null
                        // By calling this here, the token can be refreshed
                        // if it's expired right before the Graph call is made
                        AuthenticationResult result=null;
                            result = await idClient.AcquireTokenSilent(Models.AuthenticationConfig.BasicSignInScopes.Split(' '), account)
                                .ExecuteAsync();

                        requestMessage.Headers.Authorization =
                            new AuthenticationHeaderValue("Bearer", result.AccessToken);

                    }));

```

**Expected behavior**
the following code is expected to return the account
`                        var account = await idClient.GetAccountAsync(accountId);
`

**Actual behavior**
The first time I start debugging, or if while starting the debug, it decided to go to Microsoft for authentication, then the below code returns an account as expected.

but if while start debugging, it does not go to Microsoft and decided to use the memory, the below code returns null.

`                        var account = await idClient.GetAccountAsync(accountId);`

**Possible Solution**

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> Windows 10. 

### Versions
> of ASP.NET Core, of MSAL.NET

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue?
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)
  
### Mention any other details that might be useful
To let my application work in such scenario, after I start debugging and get the error, 

1. I open Edge developer tools, 
2. go to Network tab, 
3. refresh and get the error again, 
4. right click and clear browser cache and cookies, 
5. refresh again (this time it redirect again to Microsoft for reauthenticate) so it works

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Shama-K** [comment]
@omarmallat, can you share why do you require this customization and also the steps with details?
In the samples, we don't explicitly acquire token and add to authorization header as that is handled when you add **AddMicrosoftGraph** extension method in [Startup.cs](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/8294c9d4504ec115b68552acc9e63c8d49c5d892/2-WebApp-graph-user/2-1-Call-MSGraph/Startup.cs#L31). Then you can use GraphServiceClient to call graph endpoint as done here [HomeController.cs](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/8294c9d4504ec115b68552acc9e63c8d49c5d892/2-WebApp-graph-user/2-1-Call-MSGraph/Controllers/HomeController.cs#L31).

**Comment by jmprieur** [comment]
@omarmallat 
This is expected as you are using an In memory token cache, and therefore you'll need to let the user resign-in  This is explained in https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access

You might want to use another token cache. See https://github.com/AzureAD/microsoft-identity-web/wiki/token-cache-serialization

**Comment by omarmallat** [comment]
Not sure if I posted the question in the right place, but I'm using **webforms** with **dotnet 4.8** (not .net core/ .net 5).
I modified my authentication to use _MSAL_ instead of _ADAL_ as per https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-migration and yes, I'm using In Memory Token Cache but it was working till few days ago!

I'm building the _GraphServiceClient_ as shown in the code above along with the _Microsoft.Graph_ package to get required info from Azure Active Directory..

When I start debugging, the _ClaimsPrincipal.Current_ is captured SOMEHOW, without being redirected to Microsoft for Authentication (Not aware of how this decision will be taken). 

But while building the _GraphServiceClient_, I will get the accounts from the memory related to the same _ClaimsPrincipal.Current_ which cannot be found!!

So why the Authentication finds it, and _GraphServiceClient_ cannot find it? 
### and why it was working till last week while I used the same code since few months?

**Comment by jmprieur** [comment]
@omarmallat 
- I think that the ClaimsPrincipal is stored in a cookie (session cookie)
- When you restart your app, the in memory token cache is lost, and therefore Microsoft Graph does not find it.

You might be interested in this sample, which uses the Microsoft.Identity.Web token caches, but in an ASP.NET (not core) sample: 
Sample | Platform | Description
------ | -------- | -----------
[ms-identity-aspnet-webapp-openidconnect](https://github.com/Azure-Samples/ms-identity-aspnet-webapp-openidconnect) | ASP.NET (net472) | Example of token cache serialization in an ASP.NET MVC application (using MSAL.NET). See in particular [MsalAppBuilder](https://github.com/Azure-Samples/ms-identity-aspnet-webapp-openidconnect/blob/master/WebApp/Utils/MsalAppBuilder.cs)

You might also want to read https://github.com/AzureAD/microsoft-identity-web/wiki/asp-net

**Comment by omarmallat** [comment]
It's clear now, but is there any reason why Owin use cookies, and [Token Cache Serialization](https://github.com/AzureAD/microsoft-identity-web/wiki/token-cache-serialization) does not propose cookies? they are discussing only memory, session and distributed.

While I figure out that it's better to go for another caching method, I found two ways to solve the current issue:

1. (work for debugging only) Enable script debugging that create a fresh browser while starting the debugging.
2. (work for both debugging and production) When no account found in Memory cache, I am signing out, to force getting new token using             `HttpContext.Current.GetOwinContext().Authentication.SignOut(CookieAuthenticationDefaults.AuthenticationType);`

**Comment by jmprieur** [comment]
@omarmallat : the cookie is storing the identity of the signed in user (ID Token claims), whereas the token cache stores the access tokens and refresh tokens.

For debugging, indeed, you can use an "In Private" browsing

And yes, you can force the sign-out if you prefer not to challenge the user.

**Comment by omarmallat** [comment]
Actually I forced the sign-out because I did not find another way. How to challenge the user when using `ConfidentialClientApplicationBuilder`? this one does not have `AcquireTokeninteractive`

**Comment by jmprieur** [comment]
@omarmallat : just use `HttpContext.Current.GetOwinContext().Authentication.Challenge()`
