### ISSUE TITLE
Login for guest user

### ISSUE THREAD

**Issue by oleksii-mykhniak** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#464]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

All samples using standard Microsoft login UI and I don't understand how I can get an authorization token for a guest user?

I can create a guest user in Azure Ad by invitation like this:
```
curl --location --request POST 'https://graph.microsoft.com/v1.0//invitations' \
--header 'Authorization: Bearer eyJ....' \
--header 'Content-Type: application/json' \
--data-raw '{
  "invitedUserEmailAddress": "oleksii@test.com",
  "inviteRedirectUrl": "https://myapp.test.com"
}'
```
Bearer token for this call I generate by the next method:
```
curl --location --request POST 'https://login.microsoftonline.com/TenantId/oauth2/v2.0/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'client_id=ClientId' \
--data-urlencode 'scope=https://graph.microsoft.com/.default' \
--data-urlencode 'redirect_uri=/signin-oidc' \
--data-urlencode 'grant_type=client_credentials' \
--data-urlencode 'client_secret=ClientSecret'
```

**Comment by jmprieur** [comment]
@oleksii-mykhniak : I'm not sure I fully understand your question. It does not seem to be related to this sample, nor to the MSAL libraries?

### Daemon applications
I see that you used client credentials. Maybe you are asking for a daemon application sample? If that's the case, please look at https://github.com/azure-samples/active-directory-dotnetcore-daemon-v2

### Some information you might find useful in case you are asking how the guest user can login

**Guest only works with tenanted authority, not common/organizations**
If you invite a guest user to a tenant, then the tenantId that you configure in the appsettings.json of all these samples needs to be the tenant from where you sent the invite (or its domain name).

**Comment by oleksii-mykhniak** [comment]
Hi @jmprieur, 
I don't understand how a guest user can do authenticate, because it doesn't have a password and I can't manage that password in my web application.

**Comment by jmprieur** [comment]
@oleksii-mykhniak 
A guest user will receive an email, and will have to sign-in and set a password. Then they'll be able to authenticate.

**Comment by oleksii-mykhniak** [comment]
Does exist any auth flow when a web application could control a guest user password? Because I have the request to create a web application with my own sign-in/sign-up/reset password web page and then they are going to manage user access to different power bi reports by different Azure AD groups.

**Comment by jmprieur** [comment]
I don't think so, @oleksii-mykhniak. If a user is a guest user, they'll use their password in their own tenant. 
you'd want to check what the Microsoft Graph API allows to create users?  https://docs.microsoft.com/en-us/graph/api/user-post-users?view=graph-rest-1.0&tabs=http
