### ISSUE TITLE
published on server, but return error AADSTS50011 

### ISSUE THREAD

**Issue by tiagobernardes** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#465]
[ x] bug report -> please search issues before submitting
 [ ] feature request
 [ x] documentation issue or request
 [ ] regression (a behavior that used to work and stopped in a new release)

1. Web app that signs in users
   1. [ x] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-

**Repro steps**
I set up the example with my organization's data.
on azure i added the URL for localhost (for development) and also for my production server.
In localhost (development) I can authenticate myself but when I upload the code to the server the authentication does not happen, the error: "AADSTS50011: The reply URL specified in the request does not match the reply URLs configured"
Is there any way to find out which reply URL the authentication is returning?

**Additional context/ Error codes / Screenshots**

AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'xxxxx-xxxx-xxx-xxxxx'.

### OS and Version?
Linux ubuntu

### Versions
ASP.NET Core

**Comment by jmprieur** [comment]
@tiagobernardes 
when you deploy the web app, you need to add a redirect URI 
see https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/6-Deploy-to-Azure#update-the-redirect-urls

**Comment by tiagobernardes** [comment]
Yes, I did, exactly as it is in that example.
the defined url has a custom port (port 8085)
is there any limitation in this regard?

**Comment by jmprieur** [comment]
No this should work. does it have the path? "/signin-oidc" ?

**Comment by tiagobernardes** [comment]
I have this configuration:
![image](https://user-images.githubusercontent.com/15774469/109509042-656a1200-7a98-11eb-9f75-21878db2c90d.png)

**Comment by jmprieur** [comment]
Would you have a load balancer? or URI rewriters? 
you might be interested in https://github.com/AzureAD/microsoft-identity-web/wiki/Deploying-Web-apps-to-App-services-as-Linux-containers

**Comment by twofingerrightclick** [comment]
I have the similar problem. I can authenticate when running locally, but as soon as I try using the app registration in an Azure Web App service I get the redirect issue: 
![image](https://user-images.githubusercontent.com/11265760/121756477-053f2f00-cacf-11eb-9b60-5e2a2cdbe5fe.png)

My app registration redirects:
![image](https://user-images.githubusercontent.com/11265760/121756555-5c450400-cacf-11eb-8695-b397ac8bb8d3.png)

When I look at the header of the login when I get the redirect error I see that its trying to redirect to `https://***/.auth/login/aad/callback` , and if I add that uri to the redirect list it, I no longer get the redirect error, but instead get back to my azure app and it throws a server error.

I also observe that in creating an app registration from the app service (so not creating the registration before hand and then adding it to the web app service, but using the tool in the web app service) it will automatically only add the one redirect uri to the registration's redirect uri's : `https://***/.auth/login/aad/callback` . So why is my azure web app service wanting that to be the redirect, but the examples in this repo all say to use `/signin-oidc`? I am trying to figured out what paradigms currently exist for AAD auth, as there appears to be many in use  and sounds like there is a new "EasyAuth" now coming into play as well...

**I am wondering if the default `Issuer URL`** in "name of app service" -> Authentication-> (click edit on the current provider)->Edit identity provider  is the problem as this is the only difference between the localhost instance of the demo site and the Azure Web app service instance.... Here is what I get:

![image](https://user-images.githubusercontent.com/11265760/121757137-636d1180-cad1-11eb-8c8e-fa33ab092f4a.png)
