### ISSUE TITLE
2-1-Call-MSGraph login is broken for me:  Exception: Correlation failed

### ISSUE THREAD

**Issue by Breee** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#466]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [x] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
   1. [ ] with a work and school account in your organization: [4-WebApp-your-API/4-1-MyOrg](../blob/master/4-WebApp-your-API/4-1-MyOrg)
   1. [ ] with B2C users: [4-WebApp-your-API/4-2-B2C](../blob/master/4-WebApp-your-API/4-2-B2C)
   1. [ ] with any work and school account: [4-WebApp-your-API/4-3-AnyOrg](../blob/master/4-WebApp-your-API/4-3-AnyOrg)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

1. Clone this repo, 
1. go to 2-WebApp-graph-user/2-1-Call-MSGraph
1. Configure your OIDC application by changing appsettings.json
1. start the application
1. go to the website 
1. login with your Microsoft account 

**Actual behavior**
After logging in, the redirect to `/signin-oidc` happens and an exception is thrown. 
It also seems that no cookie is set

```
Exception: Correlation failed.
Unknown location

Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()
```

```
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:8080
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: U:\repos\microsoft-identity-platform-aspnetcore-webapp-tutorial\2-WebApp-graph-user\2-1-Call-MSGraph
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:8080/  
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
info: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[7]
      OpenIdConnect was not authenticated. Failure message: Not authenticated
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed.
info: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[12]
      AuthenticationScheme: OpenIdConnect was challenged.
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 1044.783ms 302 
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://localhost:8080/signin-oidc application/x-www-form-urlencoded 1403
warn: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[15]
      '.AspNetCore.Correlation.OpenIdConnect.RCnq1EyRVaYzGg3LoxUh24R5ZwtpQrFIYnVlZU_7wKg' cookie not found.
info: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[4]
      Error from RemoteAuthentication: Correlation failed..
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: Correlation failed.
   --- End of inner exception stack trace ---
```

### OS and Version?
Windows 10

### Versions
dotnet core 3.1

**Comment by jmprieur** [comment]
@Breee wasn't the redirect URI you registered in the app registration portal an https URI?

**Comment by Breee** [comment]
Hm nope, it's a http url. (http works for localhost URLs, while it is required for everything else i think)

**Comment by Breee** [comment]
Update: 

in firefox it works,
in chrome it does not. 

can you confirm that?

**Comment by rlasker-b2w** [comment]
I get this exact same error but using [1-WebApp-OIDC/1-1-MyOrg](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/1-WebApp-OIDC/1-1-MyOrg)

All I do is Register the app in Azure, open the solution, replace the Client ID, Tenant ID and Domain ... then when I run the app and log into Microsoft when the request is redirected to /signin-oidc I get Exception: Correlation failed

**Stack Trace:**
at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

In event viewer I also see this .Net Runtime Warning
'.AspNetCore.Correlation.OpenIdConnect.###################################' cookie not found.

**Comment by jmprieur** [comment]
You might want to clear the cookies?

**Comment by Breee** [comment]
It's a chromium issue, in Firefox it works^^ 
Try to set your CookieOptions  to `options.SameSite = SameSiteMode.Unspecified;` and see if this resolves the issue. 

For me this does resolve it. 

```
 services.Configure<CookiePolicyOptions>(options => {
                options.MinimumSameSitePolicy = SameSiteMode.Unspecified;
                options.OnAppendCookie = cookieContext =>
                    SetSameSite(cookieContext.Context, cookieContext.CookieOptions);
                options.OnDeleteCookie = cookieContext =>
                    SetSameSite(cookieContext.Context, cookieContext.CookieOptions);
            });
``` 

```
        private void SetSameSite(HttpContext httpContext, CookieOptions options) {
            if (options.SameSite == SameSiteMode.None) {
                    options.SameSite = SameSiteMode.Unspecified;
            }
        }
```

**Comment by rlasker-b2w** [comment]
@Breee ... thank you. Your solution worked for me. Do you know why this is an issue in Chromium?

**Comment by Breee** [comment]
@rlasker-b2w Hmm look into this: 

https://github.com/dotnet/aspnetcore/issues/14996
https://docs.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-3.1
