### ISSUE TITLE
4-2-B2C - TodoListClient launch settings have wrong launching ports compared to documentation

### ISSUE THREAD

**Issue by jcanquelain** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#473]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [X] Web app calling your own Web API
   1. [ ] with a work and school account in your organization: [4-WebApp-your-API/4-1-MyOrg](../blob/master/4-WebApp-your-API/4-1-MyOrg)
   1. [X] with B2C users: [4-WebApp-your-API/4-2-B2C](../blob/master/4-WebApp-your-API/4-2-B2C)
   1. [ ] with any work and school account: [4-WebApp-your-API/4-3-AnyOrg](../blob/master/4-WebApp-your-API/4-3-AnyOrg)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

- Configure the sample following the README (https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C#setup)
  - On the step 6 of "Registrer the client app" (https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C#register-the-client-app-todolistclient-aspnetcore-webapi), the README states to configure https://localhost:44321/signin-oidc as "Redirect URIs" on the app registration
  - Finish the configuration steps.
- Follow the steps to run the sample with visual studio (https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C#run-the-sample-using-visual-studio)

**Expected behavior**
- The browser should redirect to my AD B2C user flow to signin and then redirect to https://localhost:44321/signin-oidc upon login

**Actual behavior**
- The browser opens a page with an error 404 on https://localhost:44321/

**Possible Solution**
- I fixed the issue by changing client ports to 44321 in `TodoListClient/Properties/launchSettings.json`

**Additional context/ Error codes / Screenshots**
N/A

### Any log messages given by the failure
N/A

### OS and Version?
Windows 10 Enterprise (build 19042.867)
Browser : Chrome (89.0.4389.90)

### Versions
ASP.Net Core : 5.0.102
  
### Mention any other details that might be useful
The following is not directly related to the issue, but might help to enhance documentation.

I think the README could be clarified on following steps of "Setup" parts:
- **Create User Flows and Custom Policies** : give examples of values to use in user flows creation form. Actual values can then be referenced in the parts "Configure the service app" and "Configure the client app"
- **Add External Identity Providers** : this step is not mandatory for the sample (AD B2C with local account is sufficient for the purpose of the sample IMHO), it adds confusion and let think an external provider is mandatory, which is not the case.
- **Register the service app**: in the steps 7 and 8 (expose API and add scope), the format of the API URI (containing client ID) and the name of the scope are really different from the value in sample code (https://fabrikamb2c.onmicrosoft.com/tasks/read).  Would be better to name the scope `https://{tenantName}.onmicrosoft.com/tasks/read` for the sake of clarity.
- **Configure the service app** and **Configure the client app** could be enhanced by giving actual values of policies and scope configured in previous steps of the setup. Maybe give an example with multiple scopes ?
- **Running the sample** : give the URLs where the webapp and the API can be reached upon launch.

BTW, appart from these suggestions, thank you for these sample and the provided code, which help a lot to bootstrap an application :)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Shama-K** [comment]
@jcanquelain, Thank you for the suggestions. 
For **Create User Flows and Custom Policies**: we have provided the official docs where the examples are given.
**Add External Identity Providers**: We have included the option so that user is aware of this scenario in B2C. We don't have a separate sample for this.
I have created a Pull Request to make steps more clear.

**Comment by jmprieur** [comment]
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/pull/474
