### ISSUE TITLE
restricting a personal account login to a specific user how-to

### ISSUE THREAD

**Issue by ne0rrmatrix** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#476]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [x] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [x] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
   1. [ ] with a work and school account in your organization: [4-WebApp-your-API/4-1-MyOrg](../blob/master/4-WebApp-your-API/4-1-MyOrg)
   1. [ ] with B2C users: [4-WebApp-your-API/4-2-B2C](../blob/master/4-WebApp-your-API/4-2-B2C)
   1. [ ] with any work and school account: [4-WebApp-your-API/4-3-AnyOrg](../blob/master/4-WebApp-your-API/4-3-AnyOrg)
1. Web app restricting users
   1. [] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

Create a web form and then a pdf. login a user and let them upload a file to onedrive. 
**Expected behavior**

Only a single user that is specified can authenticate and login.
**Actual behavior**

Any user with a personal microsoft account can login and access.
**Possible Solution**

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Ubuntu 20.10 
### Versions
> of ASP.NET Core, of MSAL.NET
DOTNET 5.0 MVC Web App
### Attempting to troubleshooting yourself:
Custom Identity with role based auth which i could not get to work with external ms login.
- did you go through the README.md in the folder where you found the issue?
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)
  
### Mention any other details that might be useful
I am completely new to developing with MVC and i am also working on my first program after taking months of online courses. I am sure there is any easy way to do this.  I have spent 40+ hours trying to figure this out on MS site with documentation and googling different ways of solving this. I am pretty sure this has an easy solution and i just lack the experience or knowledge to implement it. 
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@ne0rrmatrix 
I'm not sure I understand your scenario. There is a need for your web app or your web API to know the identity needs to use. 
Do you mean that when the user creates the PDF, they are in a certain context, with a certain identity? Which tool are they using then?

**Comment by ne0rrmatrix** [comment]
The scenario is they log in and upload a bunch of pdf's to their personal account. I just want to limit access to MVC controller to one specific user that logs in using Microsoft Identity. I have no idea how to do that.

**Comment by ne0rrmatrix** [comment]
If There is a different login flow that allows someone with a personal microsoft account to upload a file to onedrive that limits it to specific accounts logging into app i would appreciate any suggestions. I want just one individual to be able to login with the rights to upload files. I want to have others be able to fill out pdf's and save them locally. Then one user can have access to files and upload them.

**Comment by jmprieur** [comment]
- how do you want to describe/specify this user? by its login?
- did you try specifying "consumers" as the tenant? (to be sure you have only personal accounts)

**Comment by ne0rrmatrix** [comment]
I am open to suggestions. The easiest way to specifiy user would be just by email.

**Comment by jmprieur** [comment]
then you can probably specify a `login_hint`:

In the startup.cs, after the configuration of the web app by AddMicrosoftIdentityWebApp ...

```CSharp
 services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
            {
                var previousEvents = options.Events.OnRedirectToIdentityProvider;
                options.Events.OnRedirectToIdentityProvider = async context =>
                {
                    await previousEvents(context);
                    context.ProtocolMessage.LoginHint = "the user name";
                };
            });
```

**Comment by ne0rrmatrix** [comment]
I am looking at controlling which users access the site and limit access to a preapproved list of users. And i want to have access control. I also want to access microsoft graph and use onedrive. I was hoping to do this with microsoft identity web library but if i use it all users who have a personal microsoft account can log in. I want to limit logins to a specific list of users.

**Comment by jmprieur** [comment]
Ok I understand now.
you want to apply authorization. Please look at the following: 
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/5-WebApp-AuthZ

**Comment by ne0rrmatrix** [comment]
I am not hosting the app on azure. I have a host that i am using. Both of those options listed by jmprieur require me to host it in azure. I have a server on a vps that i am using. I am a learning to devolop apps and i can't budget in azure credits or spending a significant amount of money to test whether i can program the app. Sorry but i don't have the resources to do that atm.

**Comment by jmprieur** [comment]
@ne0rrmatrix : you can host your web app wherever you want, but use Azure Active Directory for the authentication / authorization, and this is free. Create a free tenant (https://docs.microsoft.com/azure/active-directory/develop/quickstart-create-new-tenant), and then invite the personal accounts you want.

I don't know what I can do better for you. Sorry as well ....

**Comment by ne0rrmatrix** [comment]
Yes i have a free azure account :) I guess i just have a lot of reading to do to understand how this all works. I had it working with one of the samples but i lack the understanding of how to limit authorization. I have azure active directory tenant on the free version.

**Comment by Shama-K** [comment]
You can invite the user in Azure AD by following [Add a new guest user](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/add-users-azure-active-directory#add-a-new-guest-user) document.
Here is the link to [Create a basic group and add members](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-groups-create-azure-portal).

**Comment by ne0rrmatrix** [comment]
> @ne0rrmatrix, you can invite the user in Azure AD by following [Add a new guest user](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/add-users-azure-active-directory#add-a-new-guest-user) document.
> Here is the link to [Create a basic group and add members](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-groups-create-azure-portal).
> For authorization using roles or groups, the chapters can be found here: [5-WebApp-AuthZ](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/5-WebApp-AuthZ).

That solved all of my problems thank you for advice. I have solved access problems for application. I have also reduced my workload and made things easier by adding azure as my user management tool.
