### ISSUE TITLE
Query MSGraph for current user in OnTokenValidated

### ISSUE THREAD

**Issue by dbman86** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#482]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [x] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
   1. [ ] with a work and school account in your organization: [4-WebApp-your-API/4-1-MyOrg](../blob/master/4-WebApp-your-API/4-1-MyOrg)
   1. [ x] with B2C users: [4-WebApp-your-API/4-2-B2C](../blob/master/4-WebApp-your-API/4-2-B2C)
   1. [ ] with any work and school account: [4-WebApp-your-API/4-3-AnyOrg](../blob/master/4-WebApp-your-API/4-3-AnyOrg)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

How can I query MSGraph for current user in OnTokenValidated?

Configuring Azure B2C like this:

```CSharp
        public void ConfigureServices(IServiceCollection services)
        {
            _services = services;

            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(Configuration, "Authentication:AzureAdB2C")
                .EnableTokenAcquisitionToCallDownstreamApi(new[] {Configuration["Authentication:AzureAdB2C:ApiScopes"]})
                .AddMicrosoftGraph(Configuration.GetSection("Authentication:DownstreamApi"))
                .AddInMemoryTokenCaches();

            services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
            {
                Configuration.Bind("Authentication:AzureAdB2C", options);

                https://github.com/AzureAD/microsoft-identity-web/wiki/customization#openidconnectoptions
                var existingOnTokenValidatedHandler = options.Events.OnTokenValidated;
                options.Events.OnTokenValidated = async context =>
                {
                    await existingOnTokenValidatedHandler(context);
                    // Your code to add extra claims that will be executed after the current event implementation.
                    await HandleOpenIdConnectTokenValidated(context);
                };
            });
        }

        private async Task HandleOpenIdConnectTokenValidated(TokenValidatedContext context)
        {
                var graphClient = context.HttpContext.RequestServices.GetService<GraphServiceClient>();
                // Checks if 'JwtSecurityTokenUsedToCallWebAPI' key already exists.
                // This key is required to acquire Access Token for Graph Service Client.
                if (!context.HttpContext.Items.ContainsKey("JwtSecurityTokenUsedToCallWebAPI"))
                {
                    // For Web App, access token is retrieved using account identifier. But at this point account identifier is null.
                    // So, SecurityToken is saved in 'JwtSecurityTokenUsedToCallWebAPI' key.
                    // The key is then used to get the Access Token on-behalf of user.
                    context.HttpContext.Items.Add("JwtSecurityTokenUsedToCallWebAPI", context.SecurityToken as JwtSecurityToken);
                }

            try
            {
                var blah = graphClient.Me.AppRoleAssignments.Request().GetAsync().Result;
            }
            catch (Exception e)
            {
            }

            await Task.FromResult(0);
        }
```

appsettings.json:

```JSon
{
  "Authentication": {
    "AzureAdB2C": {
      "Domain": "MyCompany.onmicrosoft.com",
      "Instance": "https://MyCompany.b2clogin.com",
      "ClientId": "xxxxxxx",
      "ClientSecret": "xxxxxxx",
      "SignUpSignInPolicyId": "B2C_1_SignIn",
      "ResetPasswordPolicyId": "B2C_1_ResetPassword",
      "EditProfilePolicyId": "B2C_1_EditProfile",
      "SignedOutCallbackPath": "/signout/B2C_1_susi",
      "ApiScopes": "https://MyCompany.onmicrosoft.com/MyService/read",
      "RedirectUri": "https://localhost:44355/signin-oidc",
    },
    "DownstreamApi": {
      /*
     'Scopes' contains space separated scopes of the Web API you want to call. This can be:
      - a scope for a V2 application (for instance api:b3682cc7-8b30-4bd2-aaba-080c6bf0fd31/access_as_user)
      - a scope corresponding to a V1 application (for instance <App ID URI>/.default, where  <App ID URI> is the
        App ID URI of a legacy v1 Web application
      Applications are registered in the https:portal.azure.com portal.
    */
      "BaseUrl": "https://graph.microsoft.com/beta",
      "Scopes": "user.read"
    }
  },
}
```

**Expected behavior**
I would get a list of app role assignments for current user

**Actual behavior**
exception:
Count = 1
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146233088
    HelpLink: null
    InnerException: {"Code: generalException\r\nMessage: An error occurred sending the request.\r\n"}
    InnerExceptions: Count = 1
    Message: "One or more errors occurred. (Code: generalException\r\nMessage: An error occurred sending the request.\r\n)"
    Source: "System.Private.CoreLib"
    StackTrace: "   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\r\n   at System.Threading.Tasks.Task`1.get_Result()\r\n   at Heska.CoreWeb.B2C.ManagementWebApplication.Startup.<HandleOpenIdConnectTokenValidated>d__12.MoveNext() in C:\\WorkSource\\Heska-ResultsMobileApp\\CoreWeb\\B2C\\ManagementWebApplication\\Startup.cs:line 242"
    TargetSite: {TResult GetResultCore(Boolean)}

Inner Exception:
The supplied grant_type [urn:ietf:params:oauth:grant-type:jwt-bearer] is not supported.

**Possible Solution**

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
> of ASP.NET Core, of MSAL.NET

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue?
YES
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)
 YES

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@dbman86 
You should have the app roles directly in the token without calling Microsoft Graph. See:

https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/012df8a0682948226a5916fc751dcdddc1c98558/5-WebApp-AuthZ/5-1-Roles/Startup.cs#L63

If you really need to call Microsoft Graph, see https://github.com/AzureAD/microsoft-identity-web/wiki/Customization#how-to-query-microsoft-graph-on-token-validated

**Comment by dbman86** [comment]
@jmprieur thank you for the response, I am using AD B2C.  I do not think that is the same app role - I am looking for app role assignments configured in enterprise application section (app registration -> overview -> click on "Managed application in local directory" -> users 
https://docs.microsoft.com/en-us/graph/api/user-list-approleassignments?view=graph-rest-1.0&tabs=http
if this works where exactly is this information in the result?

Otherwise - I already went through that example to query ms graph on OnTokenValidated, and I was not able to get it to work, I didn't include the inner exception:

AADB2C90086: The supplied grant_type [urn:ietf:params:oauth:grant-type:jwt-bearer] is not supported.
Correlation ID: 3dbeb09f-88e7-444e-927e-973801057144
Timestamp: 2021-04-13 10:42:16Z

I included all the code can you tell me what needs to change to do this?  thank you.

**Comment by jmprieur** [comment]
@dbman86 I understand from the error you have that you are building a web API, not a web app?
and that you want to call a downstream web API (Microsoft Graph) on behalf of the user for whom the API was called.
Unfortunately this is not supported by Azure AD B2C: see https://github.com/AzureAD/microsoft-identity-web/wiki/b2c-limitations

This should work, though, if you use an Azure AD authority (and not a B2C authority), and sign-in an AAD user to manage that tenant (I'm understanding that you are trying to manage the tenant, not use it in B2C scenarios?) 
for instance https://login.microsoftonline.com/tenant, where the tenant is you B2C tenant.

**Comment by dbman86** [comment]
@jmprieur thank you for the response.  this is a web app not a web api... (see in my original question I am using AddMicrosoftIdentityWebApp()), so is this possible? thank you

**Comment by jmprieur** [comment]
that's what I understood initially, @dbman86, but then I couldn't understand why this was using the On behalf of flow, until I realized you had probably copied this code from a web API, which was using a hack

Just remove the following code:

```CSharp
 if (!context.HttpContext.Items.ContainsKey("JwtSecurityTokenUsedToCallWebAPI"))
                {
                    // For Web App, access token is retrieved using account identifier. But at this point account identifier is null.
                    // So, SecurityToken is saved in 'JwtSecurityTokenUsedToCallWebAPI' key.
                    // The key is then used to get the Access Token on-behalf of user.
                    context.HttpContext.Items.Add("JwtSecurityTokenUsedToCallWebAPI", context.SecurityToken as JwtSecurityToken);
                }
```

This should just work.

**Comment by dbman86** [comment]
@jmprieur thanks - but  If I remove that then I get this exception:

IDW10502: An MsalUiRequiredException was thrown due to a challenge for the user. See https://aka.ms/ms-id-web/ca_incremental-consent. 

-> No account or login hint was passed to the AcquireTokenSilent call. 

Any other ideas?

**Comment by dbman86** [comment]
@jmprieur I get same exception if I try this:
`            var accessToken = await _tokenAcquisition.GetAccessTokenForUserAsync(scopes2);
`
?

**Comment by dbman86** [comment]
@jmprieur is this because of B2C?  I know some things are limited with B2C... thank you

**Comment by Shama-K** [comment]
@dbman86, Is your app registered in B2C with audience as "AzureADandPersonalMicrosoftAccount"? If yes, then below information could be of use:
For AzureAD B2C, users can obtain tokens for Microsoft APIs using application permissions. The instructions in [Register a Microsoft Graph application](https://docs.microsoft.com/en-us/azure/active-directory-b2c/microsoft-graph-get-started?tabs=app-reg-ga) explain the application registration in detail. 
Token can be acquired using client credentials flow. You can find more information here: [Manage Azure AD B2C with Microsoft Graph](https://docs.microsoft.com/en-us/azure/active-directory-b2c/microsoft-graph-operations).

**Comment by dbman86** [comment]
@Shama-K Thank you for reply but I don’t want to manage anything I just want to get more details of the logged in user. I would rather not use app based credentials it is quite slow. I want to do what’s in this article but it’s not working I am wondering if it’s because I’m using B2C instead of pure AD, https://github.com/AzureAD/microsoft-identity-web/wiki/Customization#how-to-query-microsoft-graph-on-token-validated

@jmprieur ?

**Comment by jmprieur** [comment]
@dbman86, then you cannot use Graph with B2C.
See [AAD B2C limitations](https://github.com/AzureAD/microsoft-identity-web/wiki/b2c-limitations)
