### ISSUE TITLE
Exception visiting https://localhost:44321/signin-oidc after sign on

### ISSUE THREAD

**Issue by PingPongSet** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#49]
I followed steps 1 - 3, but got exception when visiting` https://localhost:44321/signin-oidc `after sign on.

However, when I checked `Access tokens` option below,
 
Register your app
`Advanced settings | Implicit grant section`, check `Access tokens`

After setting above, `https://localhost:44321/signin-oidc` is then redirected to `https://localhost:44321/.` 

After this change, it works.

Is it missing the setting above?

**Comment by yespreddy** [comment]
I have even checked the check box **Access tokens** in **Advanced settings | Implicit grant** section,
still facing the redirection issue to **https://localhost:44321/signin-oidc** when I open the link from the Microsoft Word.
But normally, if I type the url in the browser window, its working fine.

**Comment by jmprieur** [comment]
@yespreddy  
Wouldn't you be using Adanced Threat Protection?
It includes a feature called Safe Links, which replaces the URLs in an incoming email with URLs (*.outlook.com) that allow Microsoft to scan the original link for anything suspicious and redirect the user only after it is cleared.

**Comment by jmprieur** [comment]
@yespreddy : what is your scenario? why would you navigate directly to https://localhost:44321/signin-oidc ? and not to https://localhost:44321

**Comment by jmprieur** [comment]
Closing as there was no answer
