### ISSUE TITLE
Web app that signs in users with a work and school account in your organization : SecurityTokenSignatureKeyNotFoundException: IDX10501

### ISSUE THREAD

**Issue by rjehl** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#490]
### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [X ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
   1. [ ] with a work and school account in your organization: [4-WebApp-your-API/4-1-MyOrg](../blob/master/4-WebApp-your-API/4-1-MyOrg)
   1. [ ] with B2C users: [4-WebApp-your-API/4-2-B2C](../blob/master/4-WebApp-your-API/4-2-B2C)
   1. [ ] with any work and school account: [4-WebApp-your-API/4-3-AnyOrg](../blob/master/4-WebApp-your-API/4-3-AnyOrg)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

Every time I launch the project, an error page occurs.

**Expected behavior**

Expect to connect with my organisation account before going further.

**Actual behavior**

The page opends and gives me a exception : 
SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match key:
kid: 'o977oxTx0hQN8yZrshJszVnuJmQ'.

**Additional context/ Error codes / Screenshots**

My ConfigureService :

```CSharp
 public void ConfigureServices(IServiceCollection services)
        {

            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(Configuration.GetSection("AzureAd"));
                /*
                .EnableTokenAcquisitionToCallDownstreamApi(new string[] { "user.read" })
                .AddInMemoryTokenCaches(); 
                */

            IdentityModelEventSource.ShowPII = true;

            services.AddControllersWithViews(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
                options.Filters.Add(new AuthorizeFilter(policy));
            });
           services.AddRazorPages()
                .AddMicrosoftIdentityUI();
            
        }
```

Response from : https://login.microsoftonline.com/<tenant name>/.well-known/openid-configuration?appid=<SAML App ID>

`{"keys":[{"kty":"RSA",
"use":"sig",
"kid":"o977oxTx0hQN8yZrshJszVnuJmQ",
"x5t":"o977oxTx0hQN8yZrshJszVnuJmQ",
"n":"...."}]}`

### Any log messages given by the failure

`An unhandled exception occurred while processing the request.
SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match key:
kid: 'o977oxTx0hQN8yZrshJszVnuJmQ'.
Exceptions caught:
''.
token: '{"alg":"RS256","typ":"JWT","kid":"o977oxTx0hQN8yZrshJszVnuJmQ"}.{"aud":"......","ver":"2.0"}'.

System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(string token, TokenValidationParameters validationParameters)
Exception: An error was encountered while handling the remote login.

Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()`

### OS and Version?
> Windows 10

### Versions
> of ASP.NET Core : 3.1

### Attempting to troubleshooting yourself:

- I read everything I could find
- Checked internet
- Tried to change OAuth version from V2.0 to 1.0 
- Tried with an OWIN connexion

### Mention any other details that might be useful

Thanks in advance, I'm totally clueless... Searched for 2 days what I missed in the tutorial.

**Comment by jmprieur** [comment]
@rjehl did you add the certificate to the app registration?

**Comment by rjehl** [comment]
Okay, I fell stupid... As the tutorial stated : 

> Note that unless the Web App calls a Web API, no certificate or secret is needed.

I did not do it. Is it mandatory ?

**Comment by jmprieur** [comment]
Sorry, @rjehl 
I missed that you had `.EnableTokenAcquisitionToCallDownstreamApi(new string[] { "user.read" })` commented out. so no, you don't need a client certificate if you don't enable token acquisition. This seems to be the certificate used to validate ID token signature? (as you don't get an access token)

Azure AD seems to say that you are receiving a token which was signed with a key that is not found in the IDP metadata. @brentschmaltz; do you have an idea?

I'm trying to narrow down the possibilities: Would you use App services authentication?

**Comment by rjehl** [comment]
@jmprieur

No problem, I should have simply removed that part, it's confusing.

I don't think we use App services authentication. My administrator did not find anything related to this on our Azure Ad Back Office.

**Comment by jmprieur** [comment]
@rjehl : thanks for the update.
Sorry for my lack of knowledge. I'd like to understand better in order to improve the FAQ/Troubleshooting section:
- what does it mean: "Administrator had enabled Single sign-on with SAML signing Certificate." Is it what is described here: https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/certificate-signing-options ?
- Is your app a SAML app? or is it because your tenant is connected to ADFS?

**Comment by rjehl** [comment]
@jmprieur 

Don't worry, I lack even more than you. I started working on this last week and I'm really clueless about a lot of things.

- Yes, It was there : 

![application-overview-page](https://user-images.githubusercontent.com/84378191/118828985-08734080-b8be-11eb-9093-07216c1e24b8.png)

I think that my manager tried to select SAML and adding information on the user in the token. Or it's by default in our organisation. I can not help you a lot more on this as I do not have any access and have to wait for my manager or administrator to get the informations (in which they are also clueless).

- Not really for the moment. My plan was to used Microsoft Graph as in here : https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/2-WebApp-graph-user
 in order to get information on the user for our webapp (connecting it to our EDM solution and get documents depending on what they are allowed). 
My manager wanted to do it without graph, just by checking if an user is allowed to use the web app in AzureAd and getting the information from the JWT token. 

Right now I'm struggling to do this.

Still it's possible that in the end, we will have to make it a SAML app. Think that will be another challenge...
