### ISSUE TITLE
App Registratrion (Preview) is missing

### ISSUE THREAD

**Issue by yoozek** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#51]
It was available some days ago, but now App Registration (Preview) is missing from AzureAD administration, how can I work around it?

**Comment by jmprieur** [comment]
@yoozek what region are you in? 
@lnalepa FYI

**Comment by yoozek** [comment]
@jmprieur 
**Country or region**
Poland
**Location**
EU Model Clause compliant datacenters

**Comment by jmprieur** [comment]
@yoozek : is the App Registration preview back?

**Comment by yoozek** [comment]
@jmprieur  no it's not, but I created normal app registration.
Could you tell me what's the difference between Enterprise applications and App registrations?
I didn't know how to change "groupMembershipClaims": "SecurityGroup" in enterprise app, so I created normal one with reply url set to https://localhost:44362/signin-oidc and specified TenantId in appsettings and it works :)

**Comment by jmprieur** [comment]
@yoozek 
Enterprise applications are for service principals, whereas the App registration is to create apps: Please see [AZURE Active Directory - What is the difference between a Service Principal and an Enterprise Application?](https://stackoverflow.com/questions/53109262/azure-active-directory-what-is-the-difference-between-a-service-principal-and/53109692#53109692)

You cannot change the groupMembershipClaims in enterprise apps.

Do you want to close this issue? or are you expecting something from us?

**Comment by yoozek** [comment]
@jmprieur thanks for explanation, everything is clear now. Thanks!
