### ISSUE TITLE
Is there a B2C sample with access token requests available ?

### ISSUE THREAD

**Issue by Lu-Fi** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#511]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [x] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
   1. [ ] with a work and school account in your organization: [4-WebApp-your-API/4-1-MyOrg](../blob/master/4-WebApp-your-API/4-1-MyOrg)
   1. [ ] with B2C users: [4-WebApp-your-API/4-2-B2C](../blob/master/4-WebApp-your-API/4-2-B2C)
   1. [ ] with any work and school account: [4-WebApp-your-API/4-3-AnyOrg](../blob/master/4-WebApp-your-API/4-3-AnyOrg)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Versions
ASP.NET Core 3.1

### Attempting to troubleshooting yourself:
I Tried the "1-WebApp-OIDC/1-5-B2C/" sample with https://docs.microsoft.com/de-de/azure/active-directory/develop/scenario-desktop-acquire-token?tabs=dotnet but since "GetAccountsAsync" is removed (https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1967), this won't work.

**Comment by jmprieur** [comment]
@Lu-Fi. 
I don't understand what you are trying to do. 

### this sample works

I just tried this sample again (we do test them each time we release Microsoft.Identity.Web anyway, so I was surprised if it didn't work).

```Shell
cd  1-WebApp-OIDC\1-5-B2C
dotnet run
```
and navigated to `https://localhost:44316` in a browser and I was able to sign-in as expected.

### Are you looking for a web API?

Would you be trying to call a web API? If that's the case, that's the sample you need:
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C

### Some comment
If you write you were trying to apply the desktop interactive logging to a web app, this won't work. GetAccountsAsync() is only removed from confidential client applications (web apps, web APIs, daemon apps) as it does not make sense there, but it's working for desktop applications

**Comment by Lu-Fi** [comment]
Sry for this misunderstanding.

I was searching for a solution where additional access tokens can be requestet after initial authentication.

**Comment by jmprieur** [comment]
I think the sample I provided will work, @Lu-Fi
