### ISSUE TITLE
How do I host this in AKS?

### ISSUE THREAD

**Issue by jrperron88** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#52]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I have this project working fine locally without any changes. However, I'm trying to host this application in an AKS cluster, and after logging in i'm getting an error. I've tried added any URLs i could think of to the redirect URL, but none are working.

### Any log messages given by the failure
>AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application

### Expected/desired behavior
> Login and redirect to home page as is done locally

### OS and Version?
> Windows 10 - Azure AKS

### Versions
>

### Mention any other details that might be useful
I was trying to use this to authenticate users into my application when hosted in AKS. Is there a better practice?
I'm not able to capture the request_url via network traffic. But it appears the base url is http and not https. I'm unable to add http urls to app reply urls
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@jrperron88 
In the list of pages for the app in the Azure portal, select **Authentication**. 
In the Redirect URIs, add a redirect URL of type Web and valued **<URL where you have deployed your app>**/signin-oidc

**Comment by jrperron88** [comment]
> @jrperron88
> did you update the app registration:
> 
> * In the list of pages for the app in the Azure portal, select **Authentication**.
> * In the Redirect URIs, add a redirect URL of type Web and valued **URL where you have deployed your app**/signin-oidc

I attempted to, but i'm not sure what URL to add. I have it hosted in an AKS cluster with the external endpoint here: http://104.43.128.214
I've tried using this url, but it doesn't accept non-https URLs.

**Comment by jmprieur** [comment]
@jrperron88 : I'm not familiar with AKS. isn't there a publicly visible URL ?
@danieldobalian  : would you know?

**Comment by jrperron88** [comment]
it looks like the reply url is http://104.43.128.214/signin-oidc. I'm thinking I need to add a security layer on my AKS cluster to utilize https before I can get this to work.
