### ISSUE TITLE
1-WebApp-OIDC/1-5-B2C: Cannot Edit Profile of a GitHub account

### ISSUE THREAD

**Issue by rgl** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#520]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [x] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
   1. [ ] with a work and school account in your organization: [4-WebApp-your-API/4-1-MyOrg](../blob/master/4-WebApp-your-API/4-1-MyOrg)
   1. [ ] with B2C users: [4-WebApp-your-API/4-2-B2C](../blob/master/4-WebApp-your-API/4-2-B2C)
   1. [ ] with any work and school account: [4-WebApp-your-API/4-3-AnyOrg](../blob/master/4-WebApp-your-API/4-3-AnyOrg)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

1. Clone the repo as described at https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/1-WebApp-OIDC/1-5-B2C/README.md
2. Run dotnet run
3. Please note that I didn't modify any settings. Since the example seems to work out-of-the-box (which is great!) I have explored the example that way.
3. Sign-in the example application with a GitHub account
4. Click the Edit Profile button
5. Observe that the GitHub account authentication method is not available (see the screenshots bellow)

**Expected behavior**

I expected to edit my profile using a GitHub account.

**Actual behavior**

When I login I can use these account types:

![image](https://user-images.githubusercontent.com/43356/126534634-2725aa5a-07b8-46f2-aef9-d4d4f20bdca3.png)

But when I click the application Edit Profile button, I can only login with these account types:

![image](https://user-images.githubusercontent.com/43356/126534723-4d34bc05-114e-46e7-956a-9127acafde62.png)

**Comment by jmprieur** [comment]
@aremo-ms could you please have a look?

Note that corresponding Microsoft.Identity.Web sample works fine: https://github.com/AzureAD/microsoft-identity-web/tree/master/tests/webapp-b2c (no need to re-sign-in)

**Comment by aremo-ms** [comment]
> @aremo-ms could you please have a look?
> 
> Note that corresponding Microsoft.Identity.Web sample works fine: https://github.com/AzureAD/microsoft-identity-web/tree/master/tests/webapp-b2c (no need to re-sign-in)

@jmprieur On it

**Comment by jmprieur** [comment]
Thanks  @aremo-ms

**Comment by aremo-ms** [comment]
Identity provider for GitHub was disabled inside "b2c_1_edit_profile" user flow and this caused the issue. 
I've re-enabled the provider and sample work as expected.
Please let us know if you have other concerns.
