### ISSUE TITLE
How to call a custom API

### ISSUE THREAD

**Issue by jrperron88** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#53]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>I'm looking to extend this behavior to call a web API i created and hosted in azure. You allude to how this can be done, but what i've done is not working. Could you provide a guide on how to do that? I've created a default web api that is protected to my organization. It has an exposed scope. I gave access for this application to call the API with a secret key. I tried updating the scope to be the same as the exposed api, but i'm getting errors that my scope is invalid. I expected after granting access to the API, i would get another accept permission dialog

### Any log messages given by the failure
>AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope user_impersonation openid offline_access profile is not valid. The scope format is invalid. Scope must be in a valid URI form <https://example/scope> or a valid Guid <guid/scope>.

### Expected/desired behavior
> Able to call a protected web api

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
Hello @jrperron88 
Thanks for your feedback

We are currently building a multi-phase tutorial (in the Tutorials branch, but I need to warn you that this is work in progress => not yet consistent), and one of the goals is to show that
Meanwhile, you might want to have a look at this sample. It's not a web app but the scopes will be the same: https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/1.%20Desktop%20app%20calls%20Web%20API

to answer your immediate question, the scope you pass should not be user_impersonation, but, if you created your Web API with the Azure portal probably api://ClientIDForYourAPI/access_as_user (See https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/1.%20Desktop%20app%20calls%20Web%20API#configure-the-todolistclient-c-project)

cc: @kalyankrishna1, @SaeedAkhter-MSFT  (+1 for the tutorial approach)

**Comment by jrperron88** [comment]
Thank you, that got me a little further. I'm running into an issue accessing the webAPI now that I have a token. I'm getting the following error. I think i'm missing something. The only thing I altered in the code was the endpoint and the scope variable:
HttpRequestException: Invalid status code in the HttpResponseMessage: StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent, Headers:
{
Server: Kestrel
WWW-Authenticate: Bearer error="invalid_token", error_description="The audience is invalid"
X-SourceFiles: =?UTF-8?B?QzpcSFJCXGFvcG9jd2ViYXBpXGFvcG9jd2ViYXBpXGFwaVx2YWx1ZXM=?=
X-Powered-By: ASP.NET
Date: Wed, 27 Feb 2019 16:23:11 GMT
Content-Length: 0
}.

**Comment by jmprieur** [comment]
@jrperron88 : Can you please describe the topology of your application?
Do I understand correctly that this is:

ASP.NET Core Web app ----->    your Web API

You got a token for your Web API (using the following scope: api://clientIdOfYourWebAPI/access_as_user) ?

What **audience** did you set in the Web API? They need to match with the scope.
See [WebAPI/Startup.cs#L56](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/master/1.%20Desktop%20app%20calls%20Web%20API/TodoListService/Startup.cs#L56)

To help debugging the Web App and Web API you could enable:

- the IdentityModelExtension PII: See [TodoListService/Startup.cs#L76](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/84694b59995e65a90920b5fde9951581f73b2877/1.%20Desktop%20app%20calls%20Web%20API/TodoListService/Startup.cs#L76)

```CSharp
// Since IdentityModel version 5.2.1 (or since Microsoft.AspNetCore.Authentication.JwtBearer version 2.2.0),
// PII hiding in log files is enabled by default for GDPR concerns.
// For debugging/development purposes, one can enable additional detail in exceptions by setting IdentityModelEventSource.ShowPII to true.
Microsoft.IdentityModel.Logging.IdentityModelEventSource.ShowPII = true;
```

- put breakpoints in the JwtBearerMiddlewareDiagnostics class (or the ODICMiddlewareDiagnostics class in the Web App)

```CSharp
// If you want to debug, or just understand the JwtBearer events, uncomment the following line of code
options.Events = JwtBearerMiddlewareDiagnostics.Subscribe(options.Events);
```

**Comment by jrperron88** [comment]
@jmprieur I was able to troubleshoot it enough to get it working. I was using the VS 2017 template for web API with Authentication. The Startup was using AAD authentication library. I switched it over to JWT and it works. Thank you for your help and this guide!
