### ISSUE TITLE
Missing Controller

### ISSUE THREAD

**Issue by karayakar** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#530]
active-directory-aspnetcore-webapp-openidconnect-v2/1-WebApp-OIDC/1-5-B2C/Controllers/

Project missing Account controller.
` <li class="navbar-btn">
            <form method="get" asp-area="MicrosoftIdentity" asp-controller="Account" asp-action="EditProfile">
                <button type="submit" class="btn btn-primary" style="margin-right:5px">Edit Profile</button>
            </form>
        </li>
        <li class="navbar-btn">
            <form method="get" asp-area="MicrosoftIdentity" asp-controller="Account" asp-action="SignOut">
                <button type="submit" class="btn btn-primary">Sign Out</button>
            </form>
        </li>`

**Comment by jmprieur** [comment]
@karayakar what problem are you seeing? what are your repro steps?
the account controller is in Microsoft.Identity.Web.UI: https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web.UI/Areas/MicrosoftIdentity/Controllers/AccountController.cs

**Comment by deruss** [comment]
Hello,

I am having the same issue, where EditProfile does not work properly on 1-5-B2C project configured against my own ADB2C tenant.

It looks like the initial authorize is being rejected, generating the following error:

    Message contains error: 'server_error', error_description: 'AADB2C: An exception has occurred. Correlation ID: 05f99e87-0735-4734-862b-6331519ccc78 Timestamp: 2021-10-03 22:16:05Z ', error_uri: 'error_uri is null'.

Clicking Edit Profile button again will trigger a fresh signin process and then shows the expected profile editing screens.

(clicking Edit Profile a third time will then produce the error again, etc).

To reproduce:

1. Follow the "Configure authentication in a sample web app by using Azure AD B2C" tutorial:
   - Tutorial: https://docs.microsoft.com/en-gb/azure/active-directory-b2c/configure-authentication-sample-web-app?tabs=visual-studio
   - Register web application in Azure B2C: https://docs.microsoft.com/en-gb/azure/active-directory-b2c/tutorial-register-applications?tabs=app-reg-ga
   - Setup Sign-up and sign-in user flow: https://docs.microsoft.com/en-gb/azure/active-directory-b2c/add-sign-up-and-sign-in-policy?pivots=b2c-user-flow

2. Then add the Profile Editing user flow:
   - Steps: https://docs.microsoft.com/en-gb/azure/active-directory-b2c/add-profile-editing-policy?pivots=b2c-user-flow
   - Add EditProfilePolicyId to appsettings.json

3. Run website. Signin with valid login.

4. Click Edit Profile.
   - This will generate the error.

5. Click Edit Profile again
   - This will trigger a new signin process.
   - The edit profile screen will appear, and perform as expected.

We are having this issue in our own product website, but as it's happening with the tutorial project is it more likely an issue with Azure B2C server than our code or configuration?
  
Thanks,
David.

**Comment by jmprieur** [comment]
I cannot repro this, @karayakar 
Please provide repro steps
