### ISSUE TITLE
[Bug] remove <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="3.0.0" />

### ISSUE THREAD

**Issue by jennyf19** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#534]
remove `<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="3.0.0" />` from all samples csproj, as it's already brought by Microsoft.Identity.Web

**Comment by v-michaelmi** [comment]
Removed with commit [a55623115bcfd126847e3a6f5b1adb1a9dee2598](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/commit/a55623115bcfd126847e3a6f5b1adb1a9dee2598)

Closing.
