### ISSUE TITLE
Calling web API with Azure B2C token returns 401 Unauthorized due to invalid signature

### ISSUE THREAD

**Issue by ataraxia89** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#544]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [x] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
   1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
   1. [x] Web app calling your own Web API
   1. [ ] with a work and school account in your organization: [4-WebApp-your-API/4-1-MyOrg](../blob/master/4-WebApp-your-API/4-1-MyOrg)
   1. [ ] with B2C users: [4-WebApp-your-API/4-2-B2C](../blob/master/4-WebApp-your-API/4-2-B2C)
   1. [ ] with any work and school account: [4-WebApp-your-API/4-3-AnyOrg](../blob/master/4-WebApp-your-API/4-3-AnyOrg)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

- Create a web app which utilizes Azure B2C authentication as per this example >> https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC
- Replace this:

```
// Configuration to sign-in users with Azure AD B2C
services.AddMicrosoftIdentityWebAppAuthentication(Configuration, Constants.AzureAdB2C);
            
services.AddControllersWithViews()
    .AddMicrosoftIdentityUI();

services.AddRazorPages();

//Configuring appsettings section AzureAdB2C, into IOptions
services.AddOptions();
services.Configure<OpenIdConnectOptions>(Configuration.GetSection("AzureAdB2C"));
```

- with this:

```
services.AddRazorPages();

services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApp(Configuration.GetSection(Constants.AzureAdB2C))
    .EnableTokenAcquisitionToCallDownstreamApi(new string[] { "https://myapp.net/api/query" })
    .AddInMemoryTokenCaches();

services
    .AddControllersWithViews()
    .AddMicrosoftIdentityUI();

services
    .AddServerSideBlazor()
    .AddMicrosoftIdentityConsentHandler();

services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
{
    options.ResponseType = "code";
    options.SaveTokens = true;
}).AddInMemoryTokenCaches();
```

- Create a web API which utilizes Azure B2C authentication as per this example >> https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C
- Replace the appsettings for the API (see [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/enable-authentication-web-application-options#use-a-custom-domain)) with:

```
"AzureAdB2C": {
    "Instance": "https://login.myapp.net/",
    "ClientId": "api-application-client-id",
    "Domain": "b2c-tenant-id",
    "SignUpSignInPolicyId": "B2C_1_SignUpIn",
    "SignedOutCallbackPath": "/signout/B2C_1_SignUpIn"
  }
```

**Expected behavior**
I have published my web API to an Azure App Service, and am running the web app locally. I am redirected to my B2C login flow from the local web app, sign in and am then able to request an access token using the below:

```
private readonly ITokenAcquisition _tokenAcquisition;

public AuthTokensService(ITokenAcquisition tokenAcquisition)
{
    _tokenAcquisition = tokenAcquisition;
}

/// <inheritdoc />
public async Task<string> GetToken()
{
    return await _tokenAcquisition.GetAccessTokenForUserAsync(new[] { "https://myapp.net/api/query" });
}
```

This token should then be available to set as an authorization header to request my API and the API should validate that token and call upon the requested endpoint.

**Actual behavior**
Whilst this works when both the web app and the web API are running locally, when the API is running in an Azure App Service I always get a `401 Unauthorized` response because the signature is invalid.

**Possible Solution**
I've tried:
- Swapping out all custom domain values for `myapp.onmicrosoft.com` and `myapp.b2clogin.com` where relevant
- Publishing the web app so that both instances are running in Azure
- Running the web API in release configuration on my local machine with live connection to my app's database (this worked with no issues)
- Including `TenantId` in both the web app and web API's configuration settings
- Setting `https://login.myapp.net/[tenant-id]/B2C_1_SignUpIn/oauth2/2.0/` specifically as the authority
- Setting the web app's ID as the client ID in both the web app and the web API's appsettings
- Setting the web API's ID as the client ID in both the web app and the web API's appsettings

None of these worked.

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
The response's `WwwAuthenticate` header value is `Bearer error="invalid_token", error_description="The signature is invalid"`

### Versions
> .NET version: ASP.NET 5
> Microsoft.Identity.Web/WebUI Nuget Version: 1.18.0
  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by v-michaelmi** [comment]
Hey @ataraxia89 

Do you know the `accessTokenAcceptedVersion` settings in the Manifests of your application?

You can read more about it [here](https://learn.microsoft.com/en-us/azure/active-directory/develop/access-tokens)

When see issues like these it's usually because of a value mismatch. If you need to support consumers outside of **AzureAD**.

**Comment by v-michaelmi** [comment]
Marking this issue as closed.

Please re-open if this issue still persists.
