### ISSUE TITLE
Singin with 1-5-B2C example returns unexpected error after cookies are deleted

### ISSUE THREAD

**Issue by HWouters** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#545]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [x] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
   1. [ ] with a work and school account in your organization: [4-WebApp-your-API/4-1-MyOrg](../blob/master/4-WebApp-your-API/4-1-MyOrg)
   1. [ ] with B2C users: [4-WebApp-your-API/4-2-B2C](../blob/master/4-WebApp-your-API/4-2-B2C)
   1. [ ] with any work and school account: [4-WebApp-your-API/4-3-AnyOrg](../blob/master/4-WebApp-your-API/4-3-AnyOrg)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**
- Run 1-5-B2C example
- Sign in
- Remove .AspNetCore.Cookies cookie
- Refresh page
- Sign in again

**Expected behavior**
Application signs in again silently, because the session on the b2c server is still there.

**Actual behavior**
Redirected to /MicrosoftIdentity/Account/Error. 

**Additional context/ Error codes / Screenshots**
### Any log messages given by the failure
error: server_error,
error_description: AADB2C: An exception has occurred.

### OS and Version?
> Chrome browser

### Versions
> ASP.NET Core 3.1 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jennyf19** [comment]
@HWouters I'm not able to repro this. Do you have code you can share or a repo you can point me to?

**Comment by HWouters** [comment]
@jennyf19, no I don't have any other code, I'm using this sample project.

**Comment by jennyf19** [comment]
@aremo-ms i wasn't able to repro this, do you have time to try it out? if it repros, lmk.

**Comment by aremo-ms** [comment]
> @aremo-ms i wasn't able to repro this, do you have time to try it out? if it repros, lmk.

@jennyf19 I will take a look and update soon

**Comment by aremo-ms** [comment]
> > @aremo-ms i wasn't able to repro this, do you have time to try it out? if it repros, lmk.
> 
> @jennyf19 I will take a look and update soon

@jennyf19 @HWouters 
I couldn't reproduce it as well - see the screen recording

https://user-images.githubusercontent.com/85962119/140000810-dd222b33-bba2-42fb-92cb-5602cbdab691.mp4

**Comment by jennyf19** [comment]
thanks for the follow-up @HWouters
