### ISSUE TITLE
Unable to hit common endpoint with  .net core web app

### ISSUE THREAD

**Issue by ssarin3194** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#548]
Hi all, 

I have posted a stackoverflow question. I have some concerns on when the /common endpoint will be hit. When I hit the url..

asmfeedbackamestage.azurewebsites.net .. only after attempting to sign in- will it hit the common endpoint?

Also, the redirectURL of my AAD app is ""/.auth/login/aad/callback"" so not sure what that means here,

https://stackoverflow.microsoft.com/questions/279006

**Comment by kalyankrishna1** [comment]
closed as its an app svc issue
