### ISSUE TITLE
Experiences with setup 4-1-MyOrg and deployment to Azure

### ISSUE THREAD

**Issue by tacklers** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#550]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
   1. [x ] with a work and school account in your organization: [4-WebApp-your-API/4-1-MyOrg](../blob/master/4-WebApp-your-API/4-1-MyOrg)
   1. [ ] with B2C users: [4-WebApp-your-API/4-2-B2C](../blob/master/4-WebApp-your-API/4-2-B2C)
   1. [ ] with any work and school account: [4-WebApp-your-API/4-3-AnyOrg](../blob/master/4-WebApp-your-API/4-3-AnyOrg)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

**Expected behavior**

**Actual behavior**

**Possible Solution**

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
> of ASP.NET Core, of MSAL.NET

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue?
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)
  
### Mention any other details that might be useful
1. Extensive help text and lots of aspects to configure. It would be helped by bundling all the scripting at the end. If you're a novice you need to do it manually before launching powershell.
2. We had various attempts at publishing 4-1-MyOrg direct to Azure before realising that tucked way at the end of the help the 'deployment' section explained how to do that exactly. 
3. Our direct to Azure publish attempts involved various package updating, we got it on the web but could not get over hard socket errors. Now sorted using the download publish scripts.
4. In the direct and publish profile routes from VS2019 various dependencies are highlighted for authentication, storage and secrets. No mention is made in the documentation as to whether these should be ignored. In the direct publish we did configure secrets to a keyvault and eventually got past that stage. Guess this should be done in production. 
5. The documentation reads that the Service when published should open a browser to the URL to the project to be successful. This failed, went back over the documentation line by line and it still failed. Decided to press on with the client and when that worked everything did.
6. Eventually a message appeared that on signin the reply URL specified in the request did not match reply URLS configured for the application. This was the clue to configure another redirect URI in the client as client URL/signin-oidc. This then worked and we later found this reference in another document higher in the help stack. Shown in attached table.
7.  To try to make sense of all the references that need to be in place the below table was assembled. This really helped understand what the relationships were and would help in your documentation as would a diagram of the traffic routing.
8. Very confusing was the instruction   1. Find the key `TodoListBaseAddress` and replace the existing value with the base address of `TodoListService-aspnetcore-webapi` (by default `https://localhost:44351`).  What is the 'base address'? Worked it out in the end.
9. Also instructions setup 'access_as_a_user' the code template reads 'access_as_user' so another stall. 
10. Our plan was to get this in place and replace the service API with a Power-Apps sample Dataverse API. Not sure where to start engineering the connections yet.
[king-config.pdf](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/files/7443023/king-config.pdf)

All great at the end of the day. We couldn't have done it without this! Cheers, Richard
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jennyf19** [comment]
Thanks for all the feedback here @tacklers, much appreciated.

We can proceed in a couple of different ways...you can open smaller issues for each of the points above for easier tracking on our side or you can provide a PR/PRs which address any of the issues you want to address personally.

@aremo-ms thoughts on how to tackle some of these?

**Comment by aremo-ms** [comment]
> Thanks for all the feedback here @tacklers, much appreciated.
> 
> We can proceed in a couple of different ways...you can open smaller issues for each of the points above for easier tracking on our side or you can provide a PR/PRs which address any of the issues you want to address personally.
> 
> @aremo-ms thoughts on how to tackle some of these?

I will check it tomorrow first thing and answer, @jmprieur

**Comment by aremo-ms** [comment]
@jennyf19 
As I see there were mainly readme misunderstandings. Agree - this is confusing and disordered.
I will work on regenerating new readme file with all improvements in it and submit a PR for review

**Comment by jennyf19** [comment]
thanks @aremo-ms. It's hard to keep so many readme's updated with new content. Appreciate you taking this on so quicky.

**Comment by aremo-ms** [comment]
> thanks @aremo-ms. It's hard to keep so many readme's updated with new content. Appreciate you taking this on so quicky.

We are working on updating our CodeGenerator tool, so hoping to make it easier soon.

**Comment by aremo-ms** [comment]
The instructions were updated and are in main branch. Feel free to re-open with any question
