### ISSUE TITLE
Unable to sing-In with 4-3-AnyOrg

### ISSUE THREAD

**Issue by robidas** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#554]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [X ] Web app calling your own Web API
   1. [ ] with a work and school account in your organization: [4-WebApp-your-API/4-1-MyOrg](../blob/master/4-WebApp-your-API/4-1-MyOrg)
   1. [ ] with B2C users: [4-WebApp-your-API/4-2-B2C](../blob/master/4-WebApp-your-API/4-2-B2C)
   1. [X ] with any work and school account: [4-WebApp-your-API/4-3-AnyOrg](../blob/master/4-WebApp-your-API/4-3-AnyOrg)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**
Follow the steps as described in https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-3-AnyOrg

Everything was performed exactly as described. Began Testing the Application. After clicking the "Consent as Admin" button and responding to the prompts with my admin account robster@ridtestad.onmicrosoft.com, I received the first prompt for consent, and then was prompted for user id a second time (as expected). I used the same admin account. I did not receive the second prompt for consent, but was instead redirected back the the client application. I clicked the sign-in button and immediately got an exception (see below in **Actual behavior**)

See **Repro steps** above.

**Expected behavior**

Correctly sign-in without throwing an exception. 

**Actual behavior**

OpenIdConnectProtocolException: Message contains error: 'invalid_client', error_description: 'AADSTS650053: The application 'WebApp-MultiTenant-ToDoListClient-v2' asked for scope 'ScopeDefault' that doesn't exist on the resource '00000003-0000-0000-c000-000000000000'. Contact the app vendor.

**Possible Solution**

The "ScopeDefault" scope that was put in as per "Configure the client app" step number 7, however it just felt wrong. My suggestion would be to update step number 7 with a scope that doesn't cause the app to throw an exception. 

**Additional context/ Error codes / Screenshots**
All my code changes were made in the appsettings config files. 

Here is my client application settings file:
{
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "ridtestad.onmicrosoft.com",
    "TenantId": "common",
    "ClientId": "e2eeef6b-cba5-4570-a99e-688bfa1ed585",
    "ClientSecret": "*******",
    "CallbackPath": "/signin-oidc",
    "SignedOutCallbackPath": "/signout-callback-oidc"
  },
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "TodoList": {
    "TodoListAppId": "f86713f8-c30a-4cf9-8743-f0913483d2ae",
    "TodoListScope": "ScopeDefault",
    "TodoListBaseAddress": "https://localhost:44351",
    "AdminConsentRedirectApi": "https://localhost:44351/api/Home"
  },
  "RedirectUri": "https://localhost:44321/",
  "AllowedHosts": "*"
}

Here is my service application settings file:
{
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "ridtestad.onmicrosoft.com",
    "TenantId": "common",
    "ClientId": "f86713f8-c30a-4cf9-8743-f0913483d2ae",
    "ClientSecret": "********************************",
    "GraphAPI": "https://graph.microsoft.com/v1.0"
  },
  "https_port": 44351,
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*"
}

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 

fail: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[12]
      Message contains error: 'invalid_client', error_description: 'AADSTS650053: The application 'WebApp-MultiTenant-ToDoListClient-v2' asked for scope 'ScopeDefault' that doesn't exist on the resource '00000003-0000-0000-c000-000000000000'. Contact the app vendor.
      Trace ID: 9ee61155-54f0-4400-8868-c2e583c83600
      Correlation ID: aad2ea17-b5c6-400c-a1a8-0ace5da4366e
      Timestamp: 2021-11-21 02:46:04Z', error_uri: 'error_uri is null'.
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.Exception: An error was encountered while handling the remote login.
 ---> Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException: Message contains error: 'invalid_client', error_description: 'AADSTS650053: The application 'WebApp-MultiTenant-ToDoListClient-v2' asked for scope 'ScopeDefault' that doesn't exist on the resource '00000003-0000-0000-c000-000000000000'. Contact the app vendor.
Trace ID: 9ee61155-54f0-4400-8868-c2e583c83600
Correlation ID: aad2ea17-b5c6-400c-a1a8-0ace5da4366e
Timestamp: 2021-11-21 02:46:04Z', error_uri: 'error_uri is null'.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10 Pro Version 21H1 (OS Build 19043.1348)

### Versions
> of ASP.NET Core, of MSAL.NET
dotnet core version 5.0.403
I don't know how to look up the version number for MSAL.NET

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue? Yes
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview) yes
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview) yes
  
### Mention any other details that might be useful
I used visual studio code and the dotnet command line to build and run the applications. I registered the apps online through the azure portal instead of the powershell script

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by aremo-ms** [comment]
Hello @robidas, thank you for your feedback
Could you tell me if you setup app registration with PowerShell script or manually?

**Comment by robidas** [comment]
manually

________________________________

**Comment by aremo-ms** [comment]
@robidas 
I've found a possible reason for your issue, seems like out README is incorrect:
Please do next 2 things:

1. Inside your client's appsettings.json, set "TodoListScope" : "api://<your todo list service app client id>/.default"
instead of "ScopeDefault" as specified inside README

2. Make sure you have Admin Consent inside your Service's App Registration for User.Read.All permission (README omitted it)

Let me know if it helped. I will go ahead and update our README for meanwhile
