### ISSUE TITLE
1-5-B2C README.md has broken link

### ISSUE THREAD

**Issue by KSchlobohm** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#557]
### This issue is for a: (mark with an `x`)
* [ ] bug report -> please search issues before submitting
* [ ] feature request
* [x] documentation issue or request
* [ ] regression (a behavior that used to work and stopped in a new release)

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [x] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
   1. [ ] with a work and school account in your organization: [4-WebApp-your-API/4-1-MyOrg](../blob/master/4-WebApp-your-API/4-1-MyOrg)
   1. [ ] with B2C users: [4-WebApp-your-API/4-2-B2C](../blob/master/4-WebApp-your-API/4-2-B2C)
   1. [ ] with any work and school account: [4-WebApp-your-API/4-3-AnyOrg](../blob/master/4-WebApp-your-API/4-3-AnyOrg)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

The link is broken
```md
Learn how to:

- Enable your [Web App to call a Web API on behalf of the signed-in user](../../2-WebApp-graph-user/README-incremental-instructions.md)
```

**Expected behavior**
* links to https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C

**Actual behavior**
* page not found

**Comment by aremo-ms** [comment]
Hi @KSchlobohm
thank you for your feedback. I've updated the link, you can see it in  [this PR](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/pull/558)

Let me know any other issue, if not, I'll close the issue once the PR is approved

Best Regards
Alex

**Comment by KSchlobohm** [comment]
@aremo-ms it was a minor nit but i noticed in the README's there are sections that say "Never expires". 2-WebApp-graph-user/2-1-Call-MSGraph/README-incremental-instructions.md is one of these examples.

```md
1. In the **Client secrets** section, click on **New client secret**:
   - Type a key description (for instance `app secret`),
   - Select one of the available key durations (**In 1 year**, **In 2 years**, or **Never Expires**) as per your security concerns.
```
The "Never expires" option is not a valid selection for client secrets.

**Comment by aremo-ms** [comment]
> @aremo-ms it was a minor nit but i noticed in the README's there are sections that say "Never expires". 2-WebApp-graph-user/2-1-Call-MSGraph/README-incremental-instructions.md is one of these examples.
> 
> ```lisp
> 1. In the **Client secrets** section, click on **New client secret**:
>    - Type a key description (for instance `app secret`),
>    - Select one of the available key durations (**In 1 year**, **In 2 years**, or **Never Expires**) as per your security concerns.
> ```
> 
> The "Never expires" option is not a valid selection for client secrets.

@KSchlobohm thanks again
I'm actively updating all readme files and I saw that. I will fix it when I get there.
Thanks again
Feel free to close the issue if you have no other concerns

Sincerely
Alex

**Comment by aremo-ms** [comment]
I will close the issue. Feel free to open new in case of problems
