### ISSUE TITLE
Correlation failed - on 20 minute delay of signing in.

### ISSUE THREAD

**Issue by jeanmarclaiml** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#572]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [x] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
   1. [ ] with a work and school account in your organization: [4-WebApp-your-API/4-1-MyOrg](../blob/master/4-WebApp-your-API/4-1-MyOrg)
   1. [ ] with B2C users: [4-WebApp-your-API/4-2-B2C](../blob/master/4-WebApp-your-API/4-2-B2C)
   1. [ ] with any work and school account: [4-WebApp-your-API/4-3-AnyOrg](../blob/master/4-WebApp-your-API/4-3-AnyOrg)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

1. Using the Visual Studio solution found in active-directory-aspnetcore-webapp-openidconnect-v2\1-WebApp-OIDC\1-5-B2C
1. Ensure you have an existing B2C instance, with an application registration with a redirect URI website of https://localhost/signin-oidc.
2. Update appsettings.json to configure the project to use your B2C instance.
3. Run the project. 
3. Press Sign Up/In button on the local page once it has loaded.
4. Observe that you are transferred to a Microsoft Azure B2C login page.
4. Wait 20 minutes before signing in.
5. Observe that you are transferred back to the solution 
5. Observe error received ""Correlation failed."
6. Press Sign Up/In button again.
7. Observe that you don't get redirected to Microsoft Azure B2C, and you are already logged in.

**Expected behavior**
If the issue is that it has timed out, then I would expect a message to say it has timed out and not to be already logged in.
Documentation as to how to handle this situation.
Documentation on how to increase the timeout.

**Actual behavior**
An error "Correlation Failed" is displayed. Pressing Sign In/Up has the effect of logging you in without having to sign in again. The status code of the error is 302.

**Possible Solution**
The demo solution to capture the correlation failed error. But some sort of explanation as to what is going on, whether this error should be ignored (because it seems you are then logged in) and how to recover from the error.

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
Correlation failed.

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> Windows 10

### Versions
> of ASP.NET Core, of MSAL.NET

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue? yes
- did you go through the documentation: yes
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)
  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@jeanmarclaiml I think it's a behavior of the b2c service.
@nickgmicrosoft FYI and to reply

**Comment by jeanmarclaiml** [comment]
> @jeanmarclaiml I think it's a behavior of the b2c service. @nickgmicrosoft FYI and to reply

Many thanks for your reply. You do get a remote failure (you can trap it if you add a OnRemoteFailure event handler like this


            // Configuration to sign-in users with Azure AD B2C
            // + add event handler to be able to pass the login hint 
            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(options =>
                {
                    Configuration.Bind("AzureAdB2C", options);
                    options.Events ??= new OpenIdConnectEvents();
                    options.Events.OnRedirectToIdentityProvider += OnRedirectToIdentityProviderFunc;
                    options.Events.OnAuthenticationFailed += OnAuthenticationFailedFunc;
                    options.Events.OnAccessDenied += OnAccessDeniedFunc;
                    **options.Events.OnRemoteFailure += OnRemoteFailureFunc**;
                    options.Events.OnMessageReceived += OnMessageReceivedFunc;
                });

and add

        private async Task OnRemoteFailureFunc(RemoteFailureContext context)
        {
            await Task.CompletedTask.ConfigureAwait(false);
        }

with a breakpoint.

Can you please provide why this occurs and guidance on how to handle this? What should the code do? As it seems when you press sign in again, it signs you in without being transferred to b2c and having to put your credentials in.

**Comment by jmprieur** [comment]
@Tratcher do you have an idea?

**Comment by Tratcher** [comment]
Logins have a 15 minute timeout by default, and that's applied to the cookies. It's a compromise between how long someone needs to log in vs the buildup of abandon cookies on the client. You can change it if you need to.
https://github.com/dotnet/aspnetcore/blob/7f97f3ca84290c15ddfa40ed43e86b610399a4a4/src/Security/Authentication/Core/src/RemoteAuthenticationOptions.cs#L114-L117

**Comment by jeanmarclaiml** [comment]
@Tratcher many thanks for your answer. What I would like to know and if it can be addressed in the sample, is how to handle that situation, if it times out in b2c (its a remote error). How would you advise to handle it. Should you trap "correlation error" and display something like "sorry, you took too long to log in. Please try again?", which would be fine however, when clicking on sign in again, you find out your already logged in, as you dont need to authenticate with b2c again, and the claims are there - e.g. the site displays "Hello <name>". So I don't know what is the recommended why to handle that. Is there a way to know that this will happen (e.g. not having to log in again)? If so maybe I could somehow refresh the page for this error.

Its important because this is for a large commericial organisation, its not for a school project. Users will have a shopping basket and then be asked to log in via b2c and if we get this error, I'm very worried about the user experience. Please could you look into it?

**Comment by Tratcher** [comment]
That's not a decision I can make for you, you need to decide what you want the user experience to be and then we can help get you there.  Some of your options:
- Raise the timeout and see how often it comes up in practice. You may not need to address it if it's 1/10000.
- Return a nice error page with a retry link.
- Return to a neutral anonymous page like the home page.
- Retrying automatically, but be careful of infinite loops.

> when clicking on sign in again, you find out your already logged in, as you dont need to authenticate with b2c again, and the claims are there - e.g. the site displays "Hello ".

When you retry, if you're already signed in with the RDP it should automatically return to the app and complete the local login. I haven't tried this sample, where is the code that handles the error, displays Hello, etc?

**Comment by jeanmarclaiml** [comment]
@Tratcher many thanks for you advice. 

The issue is that you press sign in, go to b2c, you then get redirected back, with an error. you press sign in again, and you dont go to b2c but find your somehow logged in. The sample indicates your logged in by displaying "hello <name>". Its just an indication that your logged in. I refer you to the repo steps I documented above. I humbly thank you for you help.

**Comment by Tratcher** [comment]
@jmprieur can you have your folks to work through the sample's error handling with @jeanmarclaiml?  Let me know if you get stuck.

**Comment by jmprieur** [comment]
@kalyankrishna1 @aremo-ms can you please help?

**Comment by Tratcher** [comment]
Hmm, that nonce takes its timeout from somewhere else:
https://github.com/dotnet/aspnetcore/blob/ed1ac4285213158a85f69449dba448ef0c65fbf4/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectOptions.cs#L324
https://github.com/dotnet/aspnetcore/blob/ed1ac4285213158a85f69449dba448ef0c65fbf4/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectOptions.cs#L180

**Comment by JeanmarcLai** [comment]
@Tratcher thank you so much. I will try also increasing this timeout too.
Did you ever get to the bottom of why after you get this error, you find out you don't need to sign in after pressing the sign in button? You seem to then be signed in already? Thank you.

**Comment by jeanmarclaiml** [comment]
@Tratcher 
note, I added 

```
            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(options =>
                {
                    Configuration.Bind("AzureAdB2C", options);
                    options.Events ??= new OpenIdConnectEvents();
                    options.Events.OnRedirectToIdentityProvider += OnRedirectToIdentityProviderFunc;
                    options.Events.OnAuthenticationFailed += OnAuthenticationFailedFunc;
                    options.Events.OnAccessDenied += OnAccessDeniedFunc;
                    options.Events.OnRemoteFailure += OnRemoteFailureFunc;
                    options.Events.OnMessageReceived += OnMessageReceivedFunc;
                    options.RemoteAuthenticationTimeout = TimeSpan.FromHours(12);    // FOR CORRELATION FAILED
                    options.ProtocolValidator.NonceLifetime = TimeSpan.FromHours(12); // FOR NONCE TIMEOUT FAILED
                });
```
I updated the options.ProtocolValidator.NonceLifetime to a large value for testing see above, but I noticed that the Nonce Lifetime gets overwritten/reset back to 15 minutes, as I got the error:

{"IDX21324: The 'nonce' has expired: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'. Time from 'nonce': '02/07/2022 10:52:38', Current Time: '02/07/2022 12:32:51'. NonceLifetime is: '00:15:00'."}

The only way I got the NonceLifetime updated was to set it in the OnRedirectToIdentityProviderFunc event handler.

```
        private async Task OnRedirectToIdentityProviderFunc(RedirectContext context)
        {
            context.Options.ProtocolValidator.NonceLifetime = TimeSpan.FromHours(12);
            await Task.CompletedTask.ConfigureAwait(false);
        }
```

**Comment by jeanmarclaiml** [comment]
@Tratcher @jmprieur @kalyankrishna1 @aremo-ms

so increasing both these time outs does work, I can increase it to say 1 hour..

Please can you help on finding out why once you get the error, when clicking the sign in button, you don't have to enter your credientials (again) and find out your logged in? Many thanks

**Comment by jeanmarclaiml** [comment]
@Tratcher @jmprieur @kalyankrishna1 @aremo-ms

I found a similar issue that was raised here:

https://codersatellite.com/question-with-identifier-49067562

if anyone has any ideas as to implement the answer from the Microsoft Support team in this example? Any help would be appreciated. Thank you.

**Comment by v-michaelmi** [comment]
Hello @jeanmarclaiml,

Unfortunately I would need to know a bit more about your application before I can give a hard diagnosis on your issue but after looking at the code here I'm noticing there's a call to `UseCookiePolicy` in the `ApplicationBuilder` in `Startup.cs`.

The original line should read `app.UsingCookiePolicy`.

This will be removed with [PR 591](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/pull/591)

I can reproduce with the code that uses that method but I have not seen this issue when that line is removed. Would you need to setup a policy with this method and if not does its removal resolve your issue?

**Comment by v-michaelmi** [comment]
No response.

Closing.

**Comment by jeanmarclaiml** [comment]
Hello @v-michaelmi 

I've very sorry that I have not responded sooner. I appreciate your time and I apologise for not responding.

I have tried your suggestion of the app.UseCookiePolicy(). This has not resulted in any change to the behaviour.

I summary, the issue is that if you don't sign in before the timeout as set in startup.cs: 

```
public void ConfigureServices(IServiceCollection services)
        {
            ...
            services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(options =>
                {
                    ...
                    options.RemoteAuthenticationTimeout = TimeSpan.FromMinutes(1);
                    options.ProtocolValidator.NonceLifetime = TimeSpan.FromMinutes(1);
                    ...
                });
```

then you enter your correct credentials, you get a correlation error, which is fine, as this can be caught in the client UI, and this is due to the timeout. So then the user will attempt to log in again (by pressing the sign in/up button), and then what happens is that **it doesnt go to b2c but you find out your then logged in successfully.**

The issue in **bold** above.

I'm not sure whether this is that much of an issue, perhaps it because the client sets its timeout and b2c being sso, may have lots of different clients so if this is the expected behaviour then that is fine. I just need confirmation that it is from Microsoft.

I have a demo site which I will email Alaa Husseiny - rather not post that here on a public forum. You can try it yourself there - 1. just signup then once you have an account, log out.
2. then sign in again, wait 2 min before you hit enter
3. get correlation error
4. try to sign in again
5. you are not redirected to b2c and are logged in.

as mentioned perhaps this is ok, as you did enter the correct credentials prior to the error.

**Comment by v-michaelmi** [comment]
Reopening this issue.

Currently corresponding with customer.

**Comment by gdoron** [comment]
@v-michaelmi @kalyankrishna1 where is the issue standing? seems like you took it offline a bit.

**Comment by kalyankrishna1** [comment]
This is expected behavior, timeouts in stateless systems would lead to correlation failures
SSO behavior is expected, if the user just signed in with AAD

**Comment by ajbeaven** [comment]
This feels like a pretty big security concern that should be patched? 

I'm experiencing the same behaviour where upon receiving a correlation failure due to the nonce timeout, issuing a subsequent request to the login page immediately logs the user in without requiring they renter their credentials. The app reports a non-authenticated state post-correlation failure. The user walks away from their public terminal and the next person to come along clicks the login button and gains access to the previous user's account.

**Comment by jmprieur** [comment]
Did you try to set the Prompt option to 'login'. This would force the login

**Comment by ajbeaven** [comment]
Thanks, that did the trick!

**Comment by lakeman** [comment]
> I updated the options.ProtocolValidator.NonceLifetime to a large value for testing see above, but I noticed that the Nonce Lifetime gets overwritten/reset back to 15 minutes, as I got the error:
> 
> {"IDX21324: The 'nonce' has expired: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'. Time from 'nonce': '02/07/2022 10:52:38', Current Time: '02/07/2022 12:32:51'. NonceLifetime is: '00:15:00'."}

I believe that `IOptionsMonitor<OpenIdConnectOptions>.Get("[Scheme]").ProtocolValidator.NonceLifetime`  is the timeout value that is used at runtime. 

I see that an attempt is made to copy the entire `ProtocolValidator` instance from `MicrosoftIdentityOptions` to `OpenIdConnectOptions`, via an instance of `MergedOptions`;

https://github.com/AzureAD/microsoft-identity-web/blob/3266eb2dd6d401b05036d22770809f9fa114d9ed/src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs#L468

However, for some unknown reason, this copying is not occurring in my application. Leaving the default `NonceLifetime` of 15 minutes. But I'm not certain why this is happening.

I worked around the problem by setting the lifetime explicitly in a custom `IConfigureNamedOptions<OpenIdConnectOptions>` service.
