### ISSUE TITLE
Upgrade to .NET 6 LTS

### ISSUE THREAD

**Issue by sshquack** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#574]
All the code samples are using [netcoreapp3.1](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/search?q=netcoreapp3.1&type=code) They all fail on macOS with M1 Arm64 because .NET 3 does not work on ARM 64. Only .NET 6 is supported on macOS with Arm64 architecture. Please upgrade all the samples to .NET 6 LTS.

Running every single sample on this repo leads to this error:
```
4-2-B2C/TodoListService/bin/Debug/netcoreapp3.1/TodoListService.dll
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '3.1.0' (arm64) was not found.
  - The following frameworks were found:
      6.0.1 at [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=3.1.0&arch=arm64&rid=osx.12-arm64

Process finished with exit code 150.
```

**Comment by jmprieur** [comment]
I think this is work in progress.
@kalyankrishna1 @aremo-ms ?

**Comment by aremo-ms** [comment]
> I think this is work in progress. @kalyankrishna1 @aremo-ms ?

YES!

**Comment by sshquack** [comment]
I found a confusing duplicate sample for b2c [here](https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi) that is running on .netframework4.8. Newbies stumble across these old samples and assume b2c is broken. I have even created an issue there https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi/issues/120 Please fix these as well.

**Comment by aremo-ms** [comment]
@sshquack  can you please test the PR on your side?

**Comment by sshquack** [comment]
@aremo-ms Ran the sample on macOS + Apple silicon + .NET 6 and it finally works out of the box. Thanks!

Please remove this other stale [b2c repo](https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi) because for some reason it keeps showing up higher on Google search than this repo. I've had few team mates running into this. Everyone should be using this repo for all AAD samples!

**Comment by jmprieur** [comment]
> I found a confusing duplicate sample for b2c [here](https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi) that is running on .netframework4.8. Newbies stumble across these old samples and assume b2c is broken. I have even created an issue there [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#120](https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi/issues/120) Please fix these as well.

There is a little difference though. This sample is ASP.NET Core. the other one is ASP.NET ...

**Comment by aremo-ms** [comment]
I've closed issue on (this)[https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi] repo because it is supposed to be .Net Framework

**Comment by aremo-ms** [comment]
I guess we can sign off here as well
