### ISSUE TITLE
3-WebApp-multi-APIs Sample Broken - site doesn't load when targetting: .net 6.0 framework

### ISSUE THREAD

**Issue by Mson888** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#580]
> 3-WebApp-multi-APIs no longer works after changing from .net core 3.1 to .net framework 6.0 target runtime
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [X ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:
3-WebApp-multi-APIs no longer works after changing from .net core 3.1 to .net framework 6.0 target runtime

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [X]  [2-3 Multi-tenant](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/2-WebApp-graph-user/2-3-Multi-Tenant)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [X] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
   1. [ ] with a work and school account in your organization: [4-WebApp-your-API/4-1-MyOrg](../blob/master/4-WebApp-your-API/4-1-MyOrg)
   1. [ ] with B2C users: [4-WebApp-your-API/4-2-B2C](../blob/master/4-WebApp-your-API/4-2-B2C)
   1. [ ] with any work and school account: [4-WebApp-your-API/4-3-AnyOrg](../blob/master/4-WebApp-your-API/4-3-AnyOrg)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**
1. Clone repository
2. install min. requirements
3. Follow steps to set up the app, populate config etc.
4. Build (on VS2022) and deploy (F5)
5. Try to log in as a valid user

**Expected behavior**
Site loads. tabs work.

**Actual behavior**
Site doesn't load.  Unable to find index.cshtml

Internal Server Error
InvalidOperationException: The view 'Index' was not found. The following locations were searched:
/Views/Home/Index.cshtml
/Views/Shared/Index.cshtml
/Pages/Shared/Index.cshtml
Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable<string> originalLocations)

**Possible Solution**
- revert back to .netcore3.1 
ie. 
back to    <TargetFramework>netcoreapp3.1</TargetFramework>
from     <TargetFramework>net6.0</TargetFramework>
doing this - confirmed that the site loads once again.

- If using .net 6.0 - unsure -> Ensure the route registration works or .cshtml are always deployed?

**Additional context/ Error codes / Screenshots**

![image](https://user-images.githubusercontent.com/48302641/154867603-19b308b0-2d4c-4163-b43e-cdee8570d699.png)

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 
N/A

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windwos 10

### Versions
> of ASP.NET Core, of MSAL.NET
not sure - the project says .net core but the targeting framework is .net framework x64 runtime as of the change 
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/commit/2607df1338a9f7c06fe228c87644b8b456ca708b

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue?  Yes.
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview). Yes Read it - don't think the issue is there (since I auth'ed in properly)
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)
  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jerry1100** [comment]
It works when I start the app via `dotnet run` instead of F5. Not sure why though.

**Comment by v-michaelmi** [comment]
Similar issue was encountered in sample `2-3` and should be resolved with [PR 593](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/pull/593).

It seems the issue here is routing in the `Startup.cs` file. 

[PR 594](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/pull/594) should resolve this. Tested this code with `VS 2022` and `dotnet CLI` without issue.

**Comment by v-michaelmi** [comment]
Issue resolved with [commit 2607](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/commit/2607df1338a9f7c06fe228c87644b8b456ca708b)

Closing.
