### ISSUE TITLE
How change the Redirect URL in the Project

### ISSUE THREAD

**Issue by algab87** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#6]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>When I try change in the project the URL redirect in Application Registration Portal. I Receive Error don't match the URL Redirect.

### Any log messages given by the failure
>The text of the message is the next= "Message: AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: '...'."

### Expected/desired behavior
>I have My project but I need integrate this with Microsoft Authentication.

### OS and Version?
> Windows 10

### Versions
>Enterprise

### Mention any other details that might be useful

> I was working with Visual Studio 2017 and  .Net Core 2.0
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@algab87 : did you try to also change the `CallbackPath` in 
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/appsettings.json#L7 ?

**Comment by algab87** [comment]
![image](https://user-images.githubusercontent.com/39596420/43272766-0860cb16-90b8-11e8-8fd9-906f3f9c9e29.png)

I configured in the Application Registration Portal as the last Image.
In the appSettign.Json the next code>
{
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "qualified.domain.name",
    "TenantId": "22222222-2222-2222-2222-222222222222",
    "ClientId": "9ea57f0a-97ac-4541-a48e-a0f5cd388783",
    "CallbackPath": "http://localhost:3110/Home/About"
  },
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Warning"
    }
  }
}

But I Receive the next response:
![image](https://user-images.githubusercontent.com/39596420/43272982-83f2c072-90b8-11e8-9f69-acbd950ec8a6.png)

**Comment by algab87** [comment]
When we have a different Welcome Page Like the next picture:
![image](https://user-images.githubusercontent.com/39596420/43472399-97c3d3d4-94aa-11e8-8583-ea49d7668f44.png)
You need configure the default Route of the project and change the URL Pack.
![image](https://user-images.githubusercontent.com/39596420/43472526-e240921c-94aa-11e8-9f99-39f9a1288d57.png)
The Sing in Microsoft Button need to redirect to your controller that display you Welcome Page.
To redirect after the login, you need setup the URL in the App Developer like the main example.
You could Set up the redirect in the 
Solution:  Go to AccountController and find SingIn Method and modify this line.

> Url.Action(nameof(LoginController.SingIn), "Login");
}In this line you could change the controller and Method to redirect
