### ISSUE TITLE
Capturing FirstName from AAD Login in asp.net core 2.2 web apps

### ISSUE THREAD

**Issue by melzoghbi** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#62]
I am developing .net core 2.2 application. I would like to get the user's first name in the _LoginPartial.cshtml in RAZOR web app. I am able to get the user's surname and email but not the first name. Is there away to get this?

This is what i have in my login partial view:

```
Claim nameClaim = User.Claims.FirstOrDefault<Claim>(claim => string.Compare(claim.Type, "name", StringComparison.Ordinal) == 0);
    string userName = (nameClaim != null) && !string.IsNullOrEmpty(nameClaim.Value) ? nameClaim.Value : ((User != null) && (User.Identity != null) ? User.Identity.Name : string.Empty);
```

Also i tried this:

@User.FindFirst(System.Security.Claims.ClaimTypes.GivenName).Value

The given name claim returns the email address the same as name and email properties!!

What would be the ideal way to get the **first name** by extending the identity model in asp.net?

**Comment by jmprieur** [comment]
@melzoghbi : 
If the first name is not in the Claims (you can inspect them with the debugger),  the best is probably to call Microsoft Graph to get all the information you want. Did you have a look at this branch [aspnetcore2-2-signInAndCallGraph](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/aspnetcore2-2-signInAndCallGraph) or that one [tutorials](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/tutorials) ?

**Comment by jmprieur** [comment]
@melzoghbi : you might want to configure optional claims in your application. See https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims#v20-optional-claims

**Comment by jmprieur** [comment]
closing the issue as it was answered.
