### ISSUE TITLE
Safari Login loop

### ISSUE THREAD

**Issue by RvdMerweJHB** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#66]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Follow all steps to register the app provided in Azure QuickStart.
> Try to login with safari and chrome from iphone results in a infinite loop. 

### Any log messages given by the failure
>None

### Expected/desired behavior
> Successful login

### OS and Version?
> IOS 12

### Versions
>12.1.4

### Mention any other details that might be useful
None of the supplied fixes work:
https://github.com/aspnet/AADIntegration/issues/52
https://hajekj.net/2018/08/31/beware-of-samesite-cookie-policy-in-asp-net-core-and-upcoming-ios-12/

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
Closing as it's external (not related to the sample)
