### ISSUE TITLE
OAuth2 Authorization code was already redeemed please retry with a new valid code or use an existing refresh token

### ISSUE THREAD

**Issue by kastroph** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#664]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [x] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [x] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [x] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [x] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
   1. [ ] with a work and school account in your organization: [4-WebApp-your-API/4-1-MyOrg](../blob/master/4-WebApp-your-API/4-1-MyOrg)
   1. [ ] with B2C users: [4-WebApp-your-API/4-2-B2C](../blob/master/4-WebApp-your-API/4-2-B2C)
   1. [ ] with any work and school account: [4-WebApp-your-API/4-3-AnyOrg](../blob/master/4-WebApp-your-API/4-3-AnyOrg)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

This only happens in production 

**Expected behavior**
Provide a valid authentication  response 

**Actual behavior**
Microsoft retunes Since updating to dot net 7 we keep seeing this error in production. This was working fine in dot net 6. 

"OAuth2 Authorization code was already redeemed please retry with a new valid code or use an existing refresh token"

**Possible Solution**

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows Server  
### Versions
> dot net 7.0.2

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue?
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)
  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by kastroph** [comment]
More information, the issue happnes after 23 hours in prduction. Recycling the IIS pool does not resolve the issue. However, if I do a full depoyment resloves the issue. Futhermore, it affects all users at the same time that are using the orgnastaions AD authicatiuion for the app.

**Comment by jmprieur** [comment]
@kastroph : I think this might be due to this issue:
https://github.com/AzureAD/microsoft-identity-web/issues/1995

See https://github.com/AzureAD/microsoft-identity-web/issues/1995#issuecomment-1367606908 and the following conversations, for the description of the problem and the workaround, until .NET 7 releases a patch.

**Comment by kastroph** [comment]
@jmprieur Thank you for your reply.

I was actually following https://github.com/AzureAD/microsoft-identity-web/issues/1995#issuecomment-1367606908. I tried the workaround but it has no effect on the issue, this is why I have raised a new issue as it might be something different and we are getting close to the next patch release date. 

This has been driving me nuts for the last two weeks trying to force Web Identity to work in production or fail in development so I can inspect the mode of failure

**Comment by jmprieur** [comment]
You mentioned that this is with .NET 7.1. Where did you get it? I'm only aware of .NET 7.0.2.
cc: @Tratcher

**Comment by kastroph** [comment]
Sorry @jmprieur I meant 7.0.2 (typo)
This is the Idenity packages we are uing 
![image](https://user-images.githubusercontent.com/68622811/213033357-770725a1-eb47-47d0-831c-7f1e4d91c021.png)

**Comment by jmprieur** [comment]
@kastroph: Do you mind trying with 2.0.8-preview? We've changed the way we were handling options. This might work better?

**Comment by kastroph** [comment]
@jmprieur Not at all, I have tested in devlopment and pushed it to production. I will moniter metrics for the next 72 hours and see if this resoves the issue.

**Comment by jmprieur** [comment]
Thanks @kastroph

**Comment by kastroph** [comment]
@jmprieur  After, about 36 hours in production. I'm starting to see OAuth2 Authorization code+ was+ already redeemed 
 please retry with a new valid code or use an existing refresh token. 

The push to production for 2.0.8-preview happened on 01/18/2023, 00:24 
the last successful sign-in using  Web Identity was on 01/19/2023, 11:47, 
errors were produced on 01/19/2023, 12:08.

**Comment by jmprieur** [comment]
@kastroph 
Closing as this is fixed with the .NET 7.0 SDK update of mid-february.

**Comment by TejendraPrasad** [comment]
@jmprieur, Just wanted to check is there fix available in .NET 6.0 SDK? as still .NET 6.0 is LTS until application gets migrated to .NET 7.0 OR direct .NET 8.0...
