### ISSUE TITLE
[Feature Request] Update 2-WebApp-graph-user/2-3-Multi-Tenant to Graph SDK 5

### ISSUE THREAD

**Issue by jmprieur** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#712]
**Is your feature request related to a problem? Please describe.**
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/2-WebApp-graph-user/2-3-Multi-Tenant is not yet migrated to MsGraph SDK 5

**Describe the solution you'd like**
Update the project to MsGraph SDK5 . Id.Web.GraphServiceClient

Also update 5.2 Roles.

**Comment by jennyf19** [comment]
I think this is old, no?
