### ISSUE TITLE
Why is the secret necessary in sample 2-1-Call-MSGraph?

### ISSUE THREAD

**Issue by bk147** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#725]
### Documentation related to sample 2-1-Call-MSGraph
Authentication (https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/2-WebApp-graph-user/2-1-Call-MSGraph/README.md)

### Please check all that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x ] documentation needs clarification
- [ ] error(s) in the example
- [ ] needs an example

### Description of the issue
Going through this sample, I don't get why the secret is necessary on the 'App Registration' created for the sample. As far as I understand, when running this sample - I'm logging in as a user and get a token as myself for accessing the /me info. Shouldn't this be enough - why do the sample need a secret too?

Also when supplying the secret and making sure that the sample works I can only see my 'user sign-in' in the logs for the app registration - there are no indication that the secret has been used (cannot see anything in the 'Service principal sign-ins' log!?) Shouldn't the usage of the secret be shown in this log or where can the secret usage been seen in the logs in Azure?

Thanks,
-Brian

**Comment by bk147** [comment]
Hi Jean-Marc,

Thanks for your reply - I'm not a developer, but an Azure Administrator, so I'm trying to understand how all of this works and to get some governance in place. I still don't entirely understand how the 'Confidential Client Applications' works, but hopefully some further reading solves this :-)

Regarding the logs - my expectation is that the application sometimes 'checks' the secret (at startup and other times). I trust that this happens by doing an authentication using the AppID/secret?! In my opinion this should result in a log entry in one of the sign-in logs in AzureAD - probably the 'Service principal sign-ins' log  (AADServicePrincipalSignInLogs).

Thanks,
-Brian

**Comment by bgavrilMS** [comment]
@bk147 - confidential client means there is a secure connection between the machine (the backend web server) and the identity provider (AAD). This secure connection is proved by holding a shared secret or, for better security, by using a certificate that is known to both AAD and the client. 

So the secret / certificate aspect is relevant to all types of apps: 

- web site 
- web api
- service to service 

In terms of audits, if you go to the "Sign-ins" page, you can filter by "Credential Type", which can be 
<img width="224" alt="image" src="https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/assets/12273384/d71f5899-a737-472c-bf87-cac8ee5f41c1">

Note that public client apps (mobile app, desktop apps) do not use secrets. 

Typically 1 Azure app corresponds to a single web site or web api or service to service, so filtering by the app ID should also help.
