### ISSUE TITLE
todo: interchange the steps in tutorial

### ISSUE THREAD

**Issue by jmprieur** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#76]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [w ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

As reported by @negoe, we need to change in all the README.md, the order of step2 with step 1, i.e. making this one first [Download/ Clone this sample code or build the application using a template](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-2-AnyOrg#step-2-download-clone-this-sample-code-or-build-the-application-using-a-template)”  and then [Register the sample with your Azure AD tenant](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-2-AnyOrg#step-1-register-the-sample-with-your-azure-ad-tenant) to avoid confusion for developers

**Comment by kalyankrishna1** [comment]
done
