### ISSUE TITLE
Port mismatch between documentation and configuration

### ISSUE THREAD

**Issue by HopperTech** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#8]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Configuring per the documentation causes a localhost debug run to fail during authentication

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful
The README.md under the section "Step 1: Register the sample with your Azure AD tenant" states port 5000. The actual configuration in Properties/launchSettings.json is using port 3110. 

I considered making the change and creating a PR, but didn't know which port number you would like to use. Let me know and I can make this change.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
Thanks for the feedback @HopperTech 
I guess since 5000 is the default port for Kestrel, this would be a good idea if I had not overridden the port in the launchSettings.json.
