### ISSUE TITLE
Alternative approach to soverign clouds

### ISSUE THREAD

**Issue by RedBlue1776** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#80]
Is it possible to detect if an account is sovereign, and then redirect the URL/host to a node that is running in the same environment?

E.g. If my global server is "GlobalRelyingParty.com", and I have something deployed in "GermanyRelyingParty.com", then I would 302 redirect (or something) to that instance.  Similar behavior would occur in the opposite direction for a global user who mistakenly uses the Germany(perhaps default) provider.

It seems to be similar to the discovery process used for LiveID -vs- AAD, where there is a background JSON lookup that occurs in the MSAL login flow

**Comment by jmprieur** [comment]
@RedBlue1776 this is something that will be available in the future (instance discovery)
cc: @negoe to elaborate.

**Comment by jmprieur** [comment]
@negoe : which product would that be related to? Not libraries?
(for sure not samples)
