### ISSUE TITLE
Instructions seem out-of-date against dotnet version 2.1

### ISSUE THREAD

**Issue by ceszare** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#9]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Execute the following command: `dotnet new mvc --auth SingleOrg --client-id <client_id>`

### Any log messages given by the failure
> No failure, but there is no Extensions\AzureAdAuthenticationBuilderExtensions.cs file.

### Expected/desired behavior
> There should be instructions that guide us through the installation with the latest framework

### OS and Version?
> macOS High Sierra (10.3.6)

### Versions
> .NET Core 2.1.401

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
See also https://github.com/aspnet/Docs/issues/7224

**Comment by jmprieur** [comment]
@ceszare thanks again for the heads-up.
I've gone ahead and updated both the code of the sample and the instructions in the README.md to accommodate for the changes in the ASP.NET template. If you are interested in a preview it's in the following branch [spnetcore2-2](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/aspnetcore2-2)

Leaving the issue open, until this is reviewed and the new branch becomes the active branch.
