### ISSUE TITLE
Unable to obtain configuration from: https://login.microsoftonline.com/common/dis

### ISSUE THREAD

**Issue by brubakerjeff** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#98]
Hi,

I'm working through the example and receive the following when running. I updated the TenantID, ClientID, and Domain to match the example tenant. I'm working behind a corporate http proxy , could this be related or should I look elsewhere? If so, is there a way to set proxy flags in this example

'One or more errors occurred. (IDX20803: Unable to obtain configuration from: 'https://login.microsoftonline.com/common/discovery/instance?authorization_endpoint=https://login.microsoftonline.com/common/oauth2/v2.0/authorize&api-version=1.1'.)'

the exception occurs on AadIssuerValidator: 74
 
>       IssuerMetadata issuerMetadata = configManager.GetConfigurationAsync().Result;

cross link https://stackoverflow.com/questions/56117385/azure-configurationmanager-getconfigurationasync-proxy-error?noredirect=1#comment98868348_56117385

**Comment by jmprieur** [comment]
@brentschmaltz @mafurman
Is there a way to set a proxy on Config manager? 
@brentschmaltz, I believe you are revisiting this code. Is it something we can take into account
cc: @MarkZuber @kalyankrishna1 @TiagoBrenck

**Comment by brentschmaltz** [comment]
@jmprieur I will be looking into this code in the next two weeks. This code requires that the address specified should return the metadata. Is the server required to call the proxy, then the proxy relay the request?
It would be easiest if the proxy was configured to allow this specific call through.

**Comment by kalyankrishna1** [comment]
@brubakerjeff , It would be much more easier if the domain "https://login.microsoftonline.com" is whitelisted by Proxy. It will also allow other apps integrating with AAD not change to accommodate the proxy. 
We can learn from your feedback and work to expose the HttpClient like we did for MSAL, but consider  
the whitelisting as a possible workaround.

**Comment by brentschmaltz** [comment]
@kalyankrishna1 please share with me what we did with MSAL. We are about 2 weeks out from shipping 5.5.0, if its a small item, we may be able to add it.

**Comment by kalyankrishna1** [comment]
@brentschmaltz , I was referring to something similar to [this](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-3-released#you-told-us-you-needed-more-configuration-for-applications)

**Comment by brentschmaltz** [comment]
Oh, we have support for specifying an HttpClient here https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/8b126a518875e3007655f75bbb842d4dffe0650f/src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs#L58, but we don't support HttpClientFactory.

**Comment by rishavghosh605** [comment]
I had the same issue of IDX20803 when creating a protected web api, after several trials found out my appsettings.json needed a fix.
My current appsetting.json
{
  "AzureAdB2C": {
    "Instance": "https://xxxxxxxxxxxxx.b2clogin.com/tfp",
    "ClientId": {Your AppID},
    "Domain": "xxxxxxxxxxxxxxxxxxx.onmicrosoft.com",
    "SignUpSignInPolicyId": "B2C_1_signupsignin1"
  },
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*"
}
 
And this is a screenshot of the Postman OAuth2.0 Authorization facility to access the app:
![image](https://user-images.githubusercontent.com/47952161/71392047-a4970a80-262c-11ea-9b3d-c4d72f2387c7.png)

Hope it helps 👍
